### ISSUE TITLE
Crash when closing settings

### ISSUE THREAD

**Issue by DavidSouthgate** [ish-app/ish#1005]
App crashes as soon as "Done" is tapped in settings. This occurs every time this button is pressed.

Build 78
Clean install
iOS 14.1

Crash Dump:
[iSH-2020-10-30-155615.ips.beta.txt](https://github.com/ish-app/ish/files/5466188/iSH-2020-10-30-155615.ips.beta.txt)

**Comment by tbodt** [comment]
A new AboutNavigationController is instantiated when I tap this button and I don't know why. This instance is immediately destroyed resulting in a double KVO unregister.

**Comment by lijhello** [comment]
How about write it with SwiftUI

**Comment by DavidSouthgate** [comment]
I think that’s a bad idea. Keeping compatibility with iOS11 is probably a higher priority than using a different technology that users wouldn’t notice.

**Comment by DavidSouthgate** [comment]
> How about write it in SwiftUI

That would drop iOS 11 compatibility. I think having iOS11 compatibility is a higher priority than using swiftui

**Comment by tbodt** [comment]
Fixed by #1004 somewhere
