### ISSUE TITLE
Feature Request - Better finger gesture support

### ISSUE THREAD

**Issue by StewAlexander-com** [ish-app/ish#1007]
Hi,

Would be nice if the finger gesturing for the arrow keys was more responsive 

Using the arrow keys to maneuver around the file system using ranger, and it's pretty difficult

**Comment by tbodt** [comment]
How exactly would you like it to behave?

**Comment by StewAlexander-com** [comment]
It would be nice if the cursor or highlight continues in the direction of the arrow, somewhat slowly until the finger press is released

Or even better have the cursor follow the finger press, like a mouse.

Right now it seems like the arrow just stops after  the next hop, rather than continuing at a controlled pace or following the finger

Maybe move the cursor faster than 1 hope a second, maybe 2 or slightly more than 2 place moves a second … that way it seems fluid and natural

Anyway it would make navigating /moving the cursor much much nicer, imho

**Comment by tbodt** [comment]
It currently stops for half a second and then repeats 10 times a second. I guess you want these numbers to be tweaked?

**Comment by StewAlexander-com** [comment]
Yeah I didn't hold long enough, hmm maybe just make the pause just a tad less

Once I held it long enough it worked well

Ha, well thanks!
