### ISSUE TITLE
Where is the package manager apk on the ish app from AppStore?

### ISSUE THREAD

**Issue by stc2001** [ish-app/ish#1010]
I cannot find it
![image](https://user-images.githubusercontent.com/46279716/97770305-fffb2880-1b6c-11eb-9ec5-737baa876727.png)

**Comment by saagarjha** [comment]
The version of iSH on the App Store has had package management functionality removed. The ability to run Linux programs, as well as import files, has not been changed.

**Comment by stc2001** [comment]
Is that because of the unstable performance of the package manager ,so that you remove it?

**Comment by Assfugil** [comment]
No, it is because apple is shit.

**Comment by StewAlexander-com** [comment]
Agree there

**Comment by StewAlexander-com** [comment]
You can download the apk.static binary into the temp directory
