### ISSUE TITLE
How to fix apk warning about it being old?

### ISSUE THREAD

**Issue by StewAlexander-com** [ish-app/ish#1011]
WARNING: This apk-tools is OLD! Some packages might not function properly.
OK: 160 MiB in 90 packages

**Comment by tbodt** [comment]
apk upgrade, probably

**Comment by StewAlexander-com** [comment]
I did, didn't stop the errors!!

**Comment by tbodt** [comment]
`apk fix apk-tools`?

**Comment by StewAlexander-com** [comment]
Well it reinstalled the apk-tools package, I'll report back with any findings
