### ISSUE TITLE
iSH Failure to build in Xcode

### ISSUE THREAD

**Issue by emkey1** [ish-app/ish#1012]
I've forked iSH and am trying to build a clone of my repository.  I'm doing this on a Mac running macOS 10.15.7 and have read the README.md and followed the instructions there.  When I try to build the project in code I get a bunch of errors.

Apologies in advance as it's probably something obvious that I've missed.  Here is a screenshot showing some of the errors.

<img width="1286" alt="Screen Shot 2020-10-31 at 10 32 53 AM" src="https://user-images.githubusercontent.com/18100932/97781885-99720c80-1b64-11eb-86cc-af9528a83ac4.png">

When I drill down into the errors I often/always see the following...

ld: warning: ignoring file /Users/mke/Library/Developer/Xcode/DerivedData/iSH-focsdfgcxxkibubiyufveaclvfum/Build/Products/Debug-iphonesimulator/libarchive.a, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64

I'm not sure if that is relevant.  

Here's some additional text from one of the build errors.

"_archive_write_new", referenced from:
      _fakefs_export in fakefs.o
  "_archive_write_add_filter_gzip", referenced from:
      _fakefs_export in fakefs.o
  "_archive_write_open_filename", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_set_pathname", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_set_ino64", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_set_uid", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_set_gid", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_set_size", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_set_symlink", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_linkify", referenced from:
      _fakefs_export in fakefs.o
  "_archive_write_set_format_pax_restricted", referenced from:
      _fakefs_export in fakefs.o
  "_archive_write_header", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_linkresolver_new", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_size", referenced from:
      _fakefs_export in fakefs.o
  "_archive_filter_bytes", referenced from:
      _fakefs_import in fakefs.o
  "_archive_write_data", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_free", referenced from:
      _fakefs_export in fakefs.o
  "_archive_read_new", referenced from:
      _fakefs_import in fakefs.o
  "_archive_read_support_format_tar", referenced from:
      _fakefs_import in fakefs.o
  "_archive_entry_uid", referenced from:
      _fakefs_import in fakefs.o
  "_archive_entry_pathname", referenced from:
      _fakefs_import in fakefs.o
  "_archive_entry_symlink", referenced from:
      _fakefs_import in fakefs.o
  "_archive_read_open_filename", referenced from:
      _fakefs_import in fakefs.o
  "_archive_entry_linkresolver_free", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_filetype", referenced from:
      _fakefs_import in fakefs.o
  "_archive_read_data_into_fd", referenced from:
      _fakefs_import in fakefs.o
  "_archive_write_free", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_mode", referenced from:
      _fakefs_import in fakefs.o
  "_archive_read_next_header", referenced from:
      _fakefs_import in fakefs.o
  "_archive_errno", referenced from:
      _fakefs_import in fakefs.o
      _fakefs_export in fakefs.o
  "_archive_write_close", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_set_rdev", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_gid", referenced from:
      _fakefs_import in fakefs.o
  "_archive_error_string", referenced from:
      _fakefs_import in fakefs.o
      _fakefs_export in fakefs.o
  "_archive_entry_linkresolver_set_strategy", referenced from:
      _fakefs_export in fakefs.o
  "_archive_entry_set_mode", referenced from:
      _fakefs_export in fakefs.o
  "_archive_read_free", referenced from:
      _fakefs_import in fakefs.o
  "_archive_entry_new", referenced from:
      _fakefs_export in fakefs.o
  "_archive_read_support_filter_gzip", referenced from:
      _fakefs_import in fakefs.o
  "_archive_entry_hardlink", referenced from:
      _fakefs_import in fakefs.o
  "_archive_entry_rdev", referenced from:
      _fakefs_import in fakefs.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by saagarjha** [comment]
Did you clone submodules? `git submodule update --init`.

**Comment by emkey1** [comment]
I did indeed.

**Comment by tbodt** [comment]
Might also try Project > Clean Build Folder.

**Comment by emkey1** [comment]
> Might also try Project > Clean Build Folder.

I've tried that as well.

Maybe I forked at a bad time and things were broken?

**Comment by tbodt** [comment]
Maybe if you forked a while ago, but things are working on my machine now...

**Comment by emkey1** [comment]
I believe I did it yesterday.  Maybe I should delete my fork and fork again?

**Comment by emkey1** [comment]
It seems like this might be the key issue?  

ignoring file /Users/mke/Library/Developer/Xcode/DerivedData/iSH-focsdfgcxxkibubiyufveaclvfum/Build/Products/Debug-iphonesimulator/libarchive.a, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64

If I remove that file it always gets regenerated when I initiate the build and it always gets ignored as well which seems odd.

**Comment by emkey1** [comment]
I figured out how to merge the changes to the main repo to my fork and updated my fork.  Essentially no change so at this point it's almost certainly something on my laptop that is screwed up.

I did have both brew and portage installed at one point but have completely remove portage.  I'm thinking something might be lingering there that is causing issues.

I'll keep digging as I have time.  Any advice would be greatly appreciated but is not expected.

Thank you.

**Comment by emkey1** [comment]
Hmm, adding

EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64

to ish.xcconfig gets me down to one error but I suspect that is because it is now failing earlier.  Here is the error.

-----
Sanity check compile stderr:

-----
Running test binary command: /Users/mke/Library/Developer/Xcode/DerivedData/iSH-ddruqnzrbvsdzicfrywnpewjxfwq/Build/Products/Debug-iphonesimulator/meson/meson-private/sanitycheckc.exe
C compiler for the build machine: env -u SDKROOT -u IPHONEOS_DEPLOYMENT_TARGET xcrun clang (clang 12.0.0 "Apple clang version 12.0.0 (clang-1200.0.32.21)")
C linker for the build machine: env -u SDKROOT -u IPHONEOS_DEPLOYMENT_TARGET xcrun clang ld64 609
None of 'AR_FOR_BUILD' are defined in the environment, not changing global flags.
None of 'CFLAGS' are defined in the environment, not changing global flags.
None of 'LDFLAGS' are defined in the environment, not changing global flags.
None of 'CPPFLAGS' are defined in the environment, not changing global flags.
None of 'CC_LD' are defined in the environment, not changing global flags.

../../../../../../../../../Documents/GitHub/ish/meson.build:1:0: ERROR: Unable to determine dynamic linker

**Comment by emkey1** [comment]
I updated meson from 0.55.3 to 0.56.0, no change.

**Comment by saagarjha** [comment]
We just put in a bunch of build system changes, could you try building this again with a recent Xcode and seeing if it works for you?

**Comment by emkey1** [comment]
Build is now a success.  Thank you!
