### ISSUE TITLE
Running git signal 4

### ISSUE THREAD

**Issue by oflebbe** [ish-app/ish#1019]
When running git (for instance `git clone https://go.googlesource.com/go` ) One gets 

```
...
remote: Total 443866 (delta 329937), reused 443853 (delta 329937)
Receiving objects: 100% (443866/443866), 333.78 MiB | 457.00 KiB/s, done.
error: index-pack died of signal 4
fatal: index-pack failed
```

Looking at dmesg:
oPhone:~# dmesg
```
oPhone:~# dmesg
51 stub syscall 375
50 stub syscall 375
54 stub syscall 375
57 illegal instruction at 0xf7f8ec20: f4 8b 44 24 08 c7
 44 24
```

Instruction 0xf4 is HLT ?!?!
Syscall 375 is membarrier (maybe HLT is a safeguard for failed membarrier ?)

**Comment by oflebbe** [comment]
Maybe we should return ENOSYS for membarrier , rather EPERM (-1) ?

**Comment by oflebbe** [comment]
Will try to sketch an implementation of this special stub.

**Comment by tbodt** [comment]
This could be the emulator not respecting memory ordering. What device model/year do you have?

**Comment by oflebbe** [comment]
iPhone Xr

**Comment by oflebbe** [comment]
Do we have multiprocessing enabled?

**Comment by tbodt** [comment]
Yes, git index-pack is multithreaded. You can try disabling this as a workaround: `git config --global pack.threads 1`

**Comment by oflebbe** [comment]
Oh I get it now. The arm64 ASM gadget may violate memory consistency of i386...

**Comment by oflebbe** [comment]
Ok: Check. Disabling threads in index-pack indeed works.

And I see that musl's pthread_create calls membarrier()  without checking it's return code. Makes no sense to implement it as a dummy returning ENOSYS.

Regarding HLT instruction, I see that musl emits hlt for several inconsistencies, one of them is pthread_join(). Maybe ish doesn't implement threads in a way musl expects?

**Comment by oflebbe** [comment]
#858 seems to trigger exactly the same code path.

**Comment by oflebbe** [comment]
Given we have two totally unrelated processes triggering exactly the same code, I think memory ordering issues are unlikely.

**Comment by tbodt** [comment]
The race would be in the internal malloc locking code.

If anyone can reproduce this on x86, that would disprove the theory. If so I would appreciate an rr trace.

**Comment by oflebbe** [comment]
Cannot repro on x86 (as docker container). 
Self-compiled git from current master sometimes dying with signal 11. 
Race now looks much more convincing to me, too.

**Comment by oflebbe** [comment]
Just learned the Apple M1 seems to have a specific register to emulate the stronger memory consistency needed by rosetta emulation. 

https://www.reddit.com/r/hardware/comments/i0mido/apple_silicon_has_a_runtime_toggle_for_tso_to/

Would be interesting to see if this bug is not triggered by running an ish on an M1 mac with TSO switched to "on"

**Comment by saagarjha** [comment]
See #874.

**Comment by 62f** [comment]
illegal instruction at 0xf7f8ec20: f4 8b 44 24 08 c7 44 24
Device: iPhone7+
Command issued: ^C while apk in zsh as non-root user \h:\w\$ in /media/usb(mount -t ios foo)
```^Czsh: illegal hardware instruction  apk list gcc perl-crypt-passwdmd5 ldc2 gdmd gcc-gdc gd ldc```
Yes, ldc2 is a nonexistent apk.

```meson setup``` was also ^Z suspended in the background.

**Comment by tbodt** [comment]
This might be fixed in latest testflight.

**Comment by oflebbe** [comment]
Looks like the initial issue (checkout of large source tree with git)  is fixed 👍 👍 👍 . Thank you. I lost hope.
