### ISSUE TITLE
support arm executable

### ISSUE THREAD

**Issue by NobodyXu** [ish-app/ish#1023]
It will be great if ish support native arm executable by running them on the arm CPU directly without using emulation.

alpine already support arm platform and has lots of application like `java`, `python` needs to run on the native platform to 
provides better performance.
Running JVM and interpreter inside emulation is certainly a bad idea since they are computation heavy and not running as
native would have a heavy penalty on performance that cannot be removed by other means.

If you can relax ish to run arm directly without emulation, it would be better for these softwares.

Edit:

I tried to use [sdk](https://sdkman.io/) to install java and it took like 5 mins, which I think A12 can do much better.

**Comment by tbodt** [comment]
The constraint here is the iOS sandbox not allowing executing unsigned code, not the architecture being emulated.

**Comment by NobodyXu** [comment]
Thx for replying.

iOS sandbox is sure somewhat annoying.

**Comment by tbodt** [comment]
Even if it were possible to run arbitrary unsigned code, it would still need to be recompiled and run slower than native code to handle MMU emulation.

**Comment by NobodyXu** [comment]
OK, I get it.

Looks like it's something iSH had to suffer from.

**Comment by Assfugil** [comment]
You can execute unsigned code in sandbox while being debugged.

**Comment by NobodyXu** [comment]
If running arm native code installed from `apk` is impossible, can be distribute additional software, like jvm, python3, numpy and R
along with ish itself to improve execution speed?

**Comment by Assfugil** [comment]
it will increase the app size. The app is > 5 MB right now. Also this isn't flexible. So no.

**Comment by tbodt** [comment]
This is harder than you think it is: most software would have to be specifically ported to iOS to work like this. There's a different app for that, called a-Shell.

**Comment by NobodyXu** [comment]
I see, thank you for taking your time to reply.

I will install a-Shell after my iOS is upgraded to 14.

**Comment by NobodyXu** [comment]
I see, thank you for taking your time to reply.

I will install a-Shell after my iOS is upgraded to 14.
