### ISSUE TITLE
iOS JIT Support

### ISSUE THREAD

**Issue by hazcod** [ish-app/ish#1026]
https://9to5mac.com/2020/11/06/ios-14-2-brings-jit-compilation-support-which-enables-emulation-apps-at-full-performance/

**Comment by tbodt** [comment]
Duplicate of #129

I think this headline is misleading. I'm of the opinion that this is probably a bug, and if so it will stop working before too long.

**Comment by saagarjha** [comment]
(Plus, this would require a rewrite of iSH to take advantage of, so it's not immediately helpful.)
