### ISSUE TITLE
Command line tool does not compile with gcc on aarch64

### ISSUE THREAD

**Issue by asdfugil** [ish-app/ish#1027]
OS: Debian GNU/Linux 10 (buster) aarch64 
Kernel: 3.18.71-14176914

**Expected result**
It compiles

**Actual result**
It doesn't compile

**Logs**
[build.log](https://github.com/ish-app/ish/files/5504692/build.log)

**Comment by tbodt** [comment]
Clang is more likely to work.

**Comment by asdfugil** [comment]
error when compiling with clang
```

root@localhost:~/ish# meson build && cd build && ninja                                          The Meson build system                                                                          Version: 0.56.0                                                                                 Source dir: /root/ish                                                                           Build dir: /root/ish/build                                                                      Build type: native build                                                                        Project name: ish                                                                               Project version: undefined                                                                      C compiler for the host machine: cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")                     C linker for the host machine: cc ld.bfd 2.31.1                                                 Host machine cpu family: aarch64                                                                Host machine cpu: aarch64                                                                       Run-time dependency threads found: YES                                                          Library rt found: YES                                                                           Library m found: YES                                                                            Library sqlite3 found: YES                                                                      Program clang found: YES (/usr/bin/clang)                                                       Program check-cc.sh found: YES (/root/ish/vdso/check-cc.sh)                                     Program tools/staticdefine.sh found: YES (/root/ish/tools/staticdefine.sh)                      Library unicorn found: NO                                                                       Found pkg-config: /usr/bin/pkg-config (0.29)                                                    Run-time dependency libarchive found: YES 3.3.3                                                 Program tests/e2e/e2e.bash found: YES (/root/ish/tests/e2e/e2e.bash)                            Build targets in project: 8                                                                                                                                                                     Found ninja-1.8.2 at /usr/bin/ninja                                                             [34/88] Compiling C object float80_test.p/emu_float80-test.c.o                                  ../emu/float80-test.c:8:32: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]                                                                                              #pragma GCC diagnostic ignored "-Wliteral-range"                                                                               ^~~~~~~~~~~~~~~~~                                               [62/88] Compiling C object libish.a.p/fs_tty.c.o                                                ../fs/tty.c: In function 'tty_input':                                                           ../fs/tty.c:269:10: warning: comparison is always true due to limited range of data type [-Wtype-limits]                                                                                              ((0 <= ch && ch < ' ') || ch == '\x7f') && \                                                        ^~                                                                                    ../fs/tty.c:338:21: note: in expansion of macro 'SHOULD_ECHOCTL'                                                 if (SHOULD_ECHOCTL(ch)) {                                                                           ^~~~~~~~~~~~~~                                                             [73/88] Compiling C object libish.a.p/jit_gadgets-aarch64_entry.S.o                             FAILED: libish.a.p/jit_gadgets-aarch64_entry.S.o                                                cc -Ilibish.a.p -I. -I.. -Ivdso -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu11 -g -DLOG_HANDLER_DPRINTF=1 -DENGINE_JIT=1 -Wno-switch -fPIC -MD -MQ libish.a.p/jit_gadgets-aarch64_entry.S.o -MF libish.a.p/jit_gadgets-aarch64_entry.S.o.d -o libish.a.p/jit_gadgets-aarch64_entry.S.o -c ../jit/gadgets-aarch64/entry.S                        ../jit/gadgets-aarch64/entry.S: Assembler messages:                                             ../jit/gadgets-aarch64/entry.S:14: Error: operand 1 must be an integer or stack pointer register -- `add _ip,x0,184'                                                                            ../jit/gadgets-aarch64/entry.S:16: Error: operand 1 must be an integer or stack pointer register -- `add _tlb,x2,16'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr eax,[_cpu,24]'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr ebx,[_cpu,36]'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr ecx,[_cpu,28]'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr edx,[_cpu,32]'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr esi,[_cpu,48]'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr edi,[_cpu,52]'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr ebp,[_cpu,44]'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr esp,[_cpu,40]'                                                                            ../jit/gadgets-aarch64/entry.S:18: Error: 64-bit integer or SP register expected at operand 2 -- `ldr x8,[_ip,0*8]!'                                                                            ../jit/gadgets-aarch64/entry.S:18: Error: operand 1 must be an integer or stack pointer register -- `add _ip,_ip,8'                                                                             ../jit/gadgets-aarch64/entry.S:22: Error: operand 1 must be an integer or stack pointer register -- `cmp _ip,0'                                                                                 ../jit/gadgets-aarch64/entry.S:24: Error: operand 2 must be an integer or stack pointer register -- `sub x8,_ip,184'                                                                            ../jit/gadgets-aarch64/entry.S:25: Error: 64-bit integer or SP register expected at operand 2 -- `str x8,[_cpu,480]'                                                                            ../jit/gadgets-aarch64/entry.S:26: Error: 64-bit integer or SP register expected at operand 2 -- `ldr x8,[_ip,0*8]!'                                                                            ../jit/gadgets-aarch64/entry.S:26: Error: operand 1 must be an integer or stack pointer register -- `add _ip,_ip,8'                                                                             ../jit/gadgets-aarch64/entry.S:31: Error: operand 1 must be an integer register -- `mvn _tmp,wzr'                                                                                               ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str eax,[_cpu,24]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str ebx,[_cpu,36]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str ecx,[_cpu,28]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str edx,[_cpu,32]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str edi,[_cpu,52]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str esi,[_cpu,48]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str ebp,[_cpu,44]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str esp,[_cpu,40]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str eip,[_cpu,56]'                                                                            ../jit/gadgets-aarch64/entry.S:48: Error: operand 1 must be an integer register -- `ldr _tmp,[_ip]'                                                                                             ../jit/gadgets-aarch64/entry.S:49: Error: 64-bit integer or SP register expected at operand 2 -- `ldr eip,[_ip,8]'                                                                              ../jit/gadgets-aarch64/entry.S:53: Error: 64-bit integer or SP register expected at operand 2 -- `ldr eip,[_ip]'                                                                                [78/88] Compiling C object libish.a.p/jit_gen.c.o                                               ninja: build stopped: subcommand failed.
```

**Comment by saagarjha** [comment]
Can you format this more nicely, please?

**Comment by tbodt** [comment]
This still seems to be compiling with gcc. The way to use clang is to delete the build directory and `CC=clang meson build`.

**Comment by asdfugil** [comment]
compiles but segfaults
```
root@localhost:~/ish# CC=clang meson build
The Meson build system
Version: 0.56.0
Source dir: /root/ish
Build dir: /root/ish/build
Build type: native build
Project name: ish
Project version: undefined
Using 'CC' from environment with value: 'clang'
C compiler for the host machine: clang (clang 7.0.1-8 "clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)")
C linker for the host machine: clang ld.bfd 2.31.1
Using 'CC' from environment with value: 'clang'
Host machine cpu family: aarch64
Host machine cpu: aarch64
Run-time dependency threads found: YES
Library rt found: YES
Library m found: YES
Library sqlite3 found: YES
Program clang found: YES (/usr/bin/clang)
Program check-cc.sh found: YES (/root/ish/vdso/check-cc.sh)
Program tools/staticdefine.sh found: YES (/root/ish/tools/staticdefine.sh)
Library unicorn found: NO
Found pkg-config: /usr/bin/pkg-config (0.29)
Run-time dependency libarchive found: YES 3.3.3
Program tests/e2e/e2e.bash found: YES (/root/ish/tests/e2e/e2e.bash)
Build targets in project: 8

Found ninja-1.8.2 at /usr/bin/ninja
root@localhost:~/ish# cd build
root@localhost:~/ish/build# ninja
[80/88] Linking target float80_test
/usr/bin/ld: float80_test.p/emu_float80.c.o(.debug_info+0x37): R_AARCH64_ABS64 used with TLS symbol f80_rounding_mode
[87/88] Linking target ish
/usr/bin/ld: libish.a(kernel_task.c.o)(.debug_info+0x1d0): R_AARCH64_ABS64 used with TLS symbol current
/usr/bin/ld: libish.a(kernel_log.c.o)(.debug_info+0x4c): R_AARCH64_ABS64 used with TLS symbol vprintk.buf
/usr/bin/ld: libish.a(kernel_log.c.o)(.debug_info+0x62): R_AARCH64_ABS64 used with TLS symbol vprintk.buf_size
/usr/bin/ld: libish.a(util_sync.c.o)(.debug_info+0x37): R_AARCH64_ABS64 used with TLS symbol should_unwind
/usr/bin/ld: libish.a(util_sync.c.o)(.debug_info+0x54): R_AARCH64_ABS64 used with TLS symbol unwind_buf
/usr/bin/ld: libish.a(emu_float80.c.o)(.debug_info+0x37): R_AARCH64_ABS64 used with TLS symbol f80_rounding_mode
[88/88] Linking target tools/fakefsify
/usr/bin/ld: libish.a(kernel_task.c.o)(.debug_info+0x1d0): R_AARCH64_ABS64 used with TLS symbol current
/usr/bin/ld: libish.a(kernel_log.c.o)(.debug_info+0x4c): R_AARCH64_ABS64 used with TLS symbol vprintk.buf
/usr/bin/ld: libish.a(kernel_log.c.o)(.debug_info+0x62): R_AARCH64_ABS64 used with TLS symbol vprintk.buf_size
/usr/bin/ld: libish.a(util_sync.c.o)(.debug_info+0x37): R_AARCH64_ABS64 used with TLS symbol should_unwind
/usr/bin/ld: libish.a(util_sync.c.o)(.debug_info+0x54): R_AARCH64_ABS64 used with TLS symbol unwind_buf
/usr/bin/ld: libish.a(emu_float80.c.o)(.debug_info+0x37): R_AARCH64_ABS64 used with TLS symbol f80_rounding_mode
root@localhost:~/ish/build# ./ish
Segmentation fault
```

**Comment by 62f** [comment]
```root@localhost:~ /ish# meson build && cd build && ninja                                          The Meson build system                                                                          Version: 0.56.0                                                                                 Source dir: /root/ish                                                                           Build dir: /root/ish/build                                                                      Build type: native build                                                                        Project name: ish                                                                               Project version: undefined                                                                      C compiler for the host machine: cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")                     C linker for the host machine: cc ld.bfd 2.31.1                                                 Host machine cpu family: aarch64                                                                Host machine cpu: aarch64                                                                       Run-time dependency threads found: YES                                                          Library rt found: YES                                                                           Library m found: YES                                                                            Library sqlite3 found: YES                                                                      Program clang found: YES (/usr/bin/clang)                                                       Program check-cc.sh found: YES (/root/ish/vdso/check-cc.sh)                                     Program tools/staticdefine.sh found: YES (/root/ish/tools/staticdefine.sh)                      Library unicorn found: NO                                                                       Found pkg-config: /usr/bin/pkg-config (0.29)                                                    Run-time dependency libarchive found: YES 3.3.3                                                 Program tests/e2e/e2e.bash found: YES (/root/ish/tests/e2e/e2e.bash)                            Build targets in project: 8                                                                                                                                                                     Found ninja-1.8.2 at /usr/bin/ninja                                                             [34/88] Compiling C object float80_test.p/emu_float80-test.c.o                                  ../emu/float80-test.c:8:32: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]                                                                                              #pragma GCC diagnostic ignored "-Wliteral-range"                                                                               ^~~~~~~~~~~~~~~~~                                               [62/88] Compiling C object libish.a.p/fs_tty.c.o                                                ../fs/tty.c: In function 'tty_input':                                                           ../fs/tty.c:269:10: warning: comparison is always true due to limited range of data type [-Wtype-limits]                                                                                              ((0 <= ch && ch < ' ') || ch == '\x7f') && \                                                        ^~                                                                                    ../fs/tty.c:338:21: note: in expansion of macro 'SHOULD_ECHOCTL'                                                 if (SHOULD_ECHOCTL(ch)) {                                                                           ^~~~~~~~~~~~~~                                                             [73/88] Compiling C object libish.a.p/jit_gadgets-aarch64_entry.S.o                             FAILED: libish.a.p/jit_gadgets-aarch64_entry.S.o                                                cc -Ilibish.a.p -I. -I.. -Ivdso -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu11 -g -DLOG_HANDLER_DPRINTF=1 -DENGINE_JIT=1 -Wno-switch -fPIC -MD -MQ libish.a.p/jit_gadgets-aarch64_entry.S.o -MF libish.a.p/jit_gadgets-aarch64_entry.S.o.d -o libish.a.p/jit_gadgets-aarch64_entry.S.o -c ../jit/gadgets-aarch64/entry.S                        ../jit/gadgets-aarch64/entry.S: Assembler messages:                                             ../jit/gadgets-aarch64/entry.S:14: Error: operand 1 must be an integer or stack pointer register -- `add _ip,x0,184'                                                                            ../jit/gadgets-aarch64/entry.S:16: Error: operand 1 must be an integer or stack pointer register -- `add _tlb,x2,16'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr eax,[_cpu,24]'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr ebx,[_cpu,36]'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr ecx,[_cpu,28]'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr edx,[_cpu,32]'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr esi,[_cpu,48]'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr edi,[_cpu,52]'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr ebp,[_cpu,44]'                                                                            ../jit/gadgets-aarch64/entry.S:17: Error: 64-bit integer or SP register expected at operand 2 -- `ldr esp,[_cpu,40]'                                                                            ../jit/gadgets-aarch64/entry.S:18: Error: 64-bit integer or SP register expected at operand 2 -- `ldr x8,[_ip,0*8]!'                                                                            ../jit/gadgets-aarch64/entry.S:18: Error: operand 1 must be an integer or stack pointer register -- `add _ip,_ip,8'                                                                             ../jit/gadgets-aarch64/entry.S:22: Error: operand 1 must be an integer or stack pointer register -- `cmp _ip,0'                                                                                 ../jit/gadgets-aarch64/entry.S:24: Error: operand 2 must be an integer or stack pointer register -- `sub x8,_ip,184'                                                                            ../jit/gadgets-aarch64/entry.S:25: Error: 64-bit integer or SP register expected at operand 2 -- `str x8,[_cpu,480]'                                                                            ../jit/gadgets-aarch64/entry.S:26: Error: 64-bit integer or SP register expected at operand 2 -- `ldr x8,[_ip,0*8]!'                                                                            ../jit/gadgets-aarch64/entry.S:26: Error: operand 1 must be an integer or stack pointer register -- `add _ip,_ip,8'                                                                             ../jit/gadgets-aarch64/entry.S:31: Error: operand 1 must be an integer register -- `mvn _tmp,wzr'                                                                                               ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str eax,[_cpu,24]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str ebx,[_cpu,36]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str ecx,[_cpu,28]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str edx,[_cpu,32]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str edi,[_cpu,52]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str esi,[_cpu,48]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str ebp,[_cpu,44]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str esp,[_cpu,40]'                                                                            ../jit/gadgets-aarch64/entry.S:36: Error: 64-bit integer or SP register expected at operand 2 -- `str eip,[_cpu,56]'                                                                            ../jit/gadgets-aarch64/entry.S:48: Error: operand 1 must be an integer register -- `ldr _tmp,[_ip]'                                                                                             ../jit/gadgets-aarch64/entry.S:49: Error: 64-bit integer or SP register expected at operand 2 -- `ldr eip,[_ip,8]'                                                                              ../jit/gadgets-aarch64/entry.S:53: Error: 64-bit integer or SP register expected at operand 2 -- `ldr eip,[_ip]'                                                                                [78/88] Compiling C object libish.a.p/jit_gen.c.o                                               ninja: build stopped: subcommand failed.
```

**Comment by saagarjha** [comment]
Please use code formatting, thanks
