### ISSUE TITLE
Limit rotation

### ISSUE THREAD

**Issue by mjpieters** [ish-app/ish#1035]
Please limit rotation to only 1 Portrait and 2 Landscape modes

I can't use the app when holding my phone sideways (lying on my side), which physically orients the top of the phone towards the ground. The vast majority of apps don't rotate past landscape mode in that case.

**Comment by nyuszika7h** [comment]
I can't reproduce your issue on iPhone XR, iOS 14.1 and iSH 1.0.2 (78) from:
* App Store
* TestFlight
* Manually sideloaded

It never rotates to "upside-down portrait" mode for me, only regular portrait and the two landscape modes.

**Comment by tbodt** [comment]
Phones with a notch apparently don't let you go into the upside down orientation.

The fix is probably just to uncheck the box, as long as iPad still lets you rotate upside down.
