### ISSUE TITLE
what do I cd to

### ISSUE THREAD

**Issue by arandomdos** [ish-app/ish#1042]
I don't know what to cd to, to run abuild

Arandomdos:~# cd ~
Arandomdos:~# abuild
>>> ERROR: : Do not run abuild as root

**Comment by saagarjha** [comment]
This doesn’t sound like an issue with iSH.

**Comment by 62f** [comment]
The ~ before the # means that the shell is already `chdir` into the admin's base folder, and the `#` portion of every prompt indicates that your currently logged in account `whoami` already executes all shell commands such as `abuild` with admin privileges. You will need to `adduser` to create a nonprivileged-account & then `login` with the username created, at which `~#` changes to `~?`.
You're welcome
