### ISSUE TITLE
Configuration settings gear icon not visible on 5s iPhone keypad

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#1049]
Enabling the Recovery menu setting only causes iSH to always crash when app is opened on 5s device
This is not related to the following bug-
_Originally posted by @62f in https://github.com/ish-app/ish/issues/1029_

**Comment by saagarjha** [comment]
This is probably the same issue as #1046, so closing.

**Comment by 62f** [comment]
No it is not the exact same bug, from within any version of iSH I still can pull up the info/secret menu just fine. I just can’t externally set recovery mode setting in iOS to directly show those same iSH configurations without causing iSH total crash at startup.
