### ISSUE TITLE
/proc/mounts infinite loop

### ISSUE THREAD

**Issue by skissane** [ish-app/ish#1050]
Installed latest version of iSH from App Store today. Ran `mount` command with no arguments, its output repeats in an infinite loop. `cat /proc/mounts` does the same thing.

Version:  4.20.69-ish iSH 1.0.2 (79) Nov 11 2020 23:59:13 i686 Linux

**Comment by skissane** [comment]
This seems to be a generic problem with `/proc`, not specific to `/proc/mounts`. Other files in `/proc`, for example `/proc/uptime`, exhibit the same infinite looping behaviour.

**Comment by tbodt** [comment]
This should be fixed in master. seek on all procfs files would just return EINVAL.

**Comment by skissane** [comment]
Just got version 82 installed by TestFlight. I confirm this is now fixed. Thanks
