### ISSUE TITLE
Phantom lines of text appear and disappear with orientation change😭

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#1051]
Feature request: to support Alpine v.3.12.1

**Comment by tbodt** [comment]
Would appreciate a screen recording for this

**Comment by 62f** [comment]
> https://discord.com/channels/508839261924229141/510581945638453269/777037729355268146

**Comment by 62f** [comment]
This bug appears only in bash 5.0 in Alpine 3.12.1 only; neither -ash nor zsh scramble up text, so I don't expect (Rel.82) is at fault. Since I am also now updating the 5s to a newer version of iOS, shall close this issue but reopen should either of the workarounds revert the behavior.
