### ISSUE TITLE
Infinate number of repeating mounts

### ISSUE THREAD

**Issue by zenarcher007** [ish-app/ish#1057]
Attached is a _**Small**_ snippet of the output of running "mount". (I ctrl-C'd it after a while). I tried it on multiple filesystems, and even tried deleting and reinstalling the app, but I still got the same result. I am on iSH 1.0.2 (Build 79), on iOS 14.2. Looking at /proc/mounts looks the same. Additionally, I cannot use the umount command to unmount anything, even filesystems mounted in iOS FileProvider, as it just hangs forever. 

[outputOfMount.gz](https://github.com/ish-app/ish/files/5541774/outputOfMount.gz)

**Comment by zenarcher007** [comment]
I can't think of what could have caused it, except that earlier I was playing around with mounting a FileProvider extension from an app named "ShellFish" within iSH.

**Comment by tbodt** [comment]
This is a bug accidentally introduced in the latest testflight beta, and is fixed for the next one.
