### ISSUE TITLE
node: illegal instruction (again)

### ISSUE THREAD

**Issue by Rexogamer** [ish-app/ish#1060]
I ran `node fruit.js` (if you want the file to look at lemme know) and it gave "illegal instruction". Here's what dmesg gave me:
![3C3F18E2-9A2C-4752-B628-AF8122133CB9](https://user-images.githubusercontent.com/42586271/99182712-80558800-272e-11eb-9f41-044b93b6e2a0.jpeg)
(for easy copying/screen readers, `illegal instruction at 0x56d6cf2f: 0f 72 f0 01 8b 00 66 0f`)

**Comment by saagarjha** [comment]
`pslld`. And text ≫ screenshots ;)

**Comment by Rexogamer** [comment]
I've edited to add the text.

**Comment by Rexogamer** [comment]
On further inspection, this looks a lot like #917 (I'm also using the edge repo).

**Comment by 62f** [comment]
I use the text when searching GH issues to identify duplicates and avoid double-posting bugs, because screenshot images aren't searchable. Screen readers often do weird things even with known words, no favors being done there, thank you very much.

**Comment by tbodt** [comment]
Yep looks like the same as #917
