### ISSUE TITLE
APK command not found

### ISSUE THREAD

**Issue by Broadcastre** [ish-app/ish#1063]
Whenever I try to run the apk command it says it is not found. There are various things I want to do using this so fixing this would be well appreciated.

**Comment by saagarjha** [comment]
The version of iSH on the App Store has had package management functionality removed. The ability to run Linux programs, as well as import files, has not been changed.

**Comment by Broadcastre** [comment]
I installed it from TestFlight

**Comment by Redecorating** [comment]
That's probably still got apple not allowing the inclusion of apk, if you don't know how to manually install it, see this wiki page: https://github.com/ish-app/ish/wiki/Installing-apk

**Comment by 62f** [comment]
I suggest not installing apk.

**Comment by ifuchs** [comment]
Because...?

**Comment by 62f** [comment]
Consider the workflow. It's ancillary.
