### ISSUE TITLE
...

### ISSUE THREAD

**Issue by mrnobody1111** [ish-app/ish#1065]

**Comment by Mnpn03** [comment]
Please, submit issues with actual content.

**Comment by mrnobody1111** [comment]
I'm tryin to figure out how to build on my iPhone se without a computer. Is this possible

**Comment by saagarjha** [comment]
Build iSH in iSH? No, it wouldn't be possible, because iSH only supports x86_64 and arm64. Unless you meant something else?

**Comment by mrnobody1111** [comment]
I was trying to see if possible to build thru working copy app and GitHub and a code editor... I’m a rookie of course and new to iOS and to be honest not very happy with the change from android

**Comment by mrnobody1111** [comment]
I’m looking to be able to use kali on my unjailbroken iPhone se or at least some metasploit tools

**Comment by saagarjha** [comment]
Kali Linux is unlikely to work in iSH, as are many Metasploit tools, unfortunately.

**Comment by 62f** [comment]
Since when is upconversion impossible in a cross-compile?

**Comment by saagarjha** [comment]
Forever since iSH has never supported the things necessary for those to run
