### ISSUE TITLE
Can't reach /proc/[pid]/fd

### ISSUE THREAD

**Issue by nimelehin** [ish-app/ish#1068]
Latest build.

<img width="639" alt="Screenshot 2020-11-17 at 18 22 08" src="https://user-images.githubusercontent.com/17456915/99408893-cf9fe200-2901-11eb-9fe1-dbac1be324a4.png">

**Comment by tbodt** [comment]
I can only reproduce on the simulator for some reason.

**Comment by tbodt** [comment]
Oh, this is because I was using bash (instead of busybox ash) on my device. Can now reproduce there.

**Comment by 62f** [comment]
> Oh, this is because I was using bash (instead of busybox ash) on my device. Can now reproduce there.

busybox works for -ash only, or you meant `busybox ash`?
