### ISSUE TITLE
Mounting file providers

### ISSUE THREAD

**Issue by ifuchs** [ish-app/ish#1070]
I would like to be able to access file providers that are shown in the files app; however, only "on My iPad", "iCloud Drive" and "JSBox" are accessible. (all others are grayed out). Is there a way to access the others (e.g., NextCloud)?

**Comment by 62f** [comment]
![image](https://user-images.githubusercontent.com/68332197/99665065-1e9b6380-2a37-11eb-97c7-cf41724cddf6.jpeg)
![image](https://user-images.githubusercontent.com/68332197/99665101-29ee8f00-2a37-11eb-9b8c-b8bf3b855f8b.jpeg)
![image](https://user-images.githubusercontent.com/68332197/99665114-2f4bd980-2a37-11eb-9818-fb3c397aaed6.jpeg)
![image](https://user-images.githubusercontent.com/68332197/99665129-34108d80-2a37-11eb-8186-6f27cc582b6f.jpeg)

**Comment by 62f** [comment]
![image](https://user-images.githubusercontent.com/68332197/99665065-1e9b6380-2a37-11eb-97c7-cf41724cddf6.jpeg)

![image](https://user-images.githubusercontent.com/68332197/99665129-34108d80-2a37-11eb-8186-6f27cc582b6f.jpeg)

![image](https://user-images.githubusercontent.com/68332197/99665114-2f4bd980-2a37-11eb-9818-fb3c397aaed6.jpeg)


![image](https://user-images.githubusercontent.com/68332197/99665101-29ee8f00-2a37-11eb-9b8c-b8bf3b855f8b.jpeg)

**Comment by ifuchs** [comment]
Thanks but are you getting to this interface from ish, gear->FileSystems->Import->Browse ? If so, I can see the various fileproviders that way but all files are grayed out.

**Comment by tbodt** [comment]
I think 62f misunderstands: this is about the `mount -t ios` popup, not the Files app.

iSH only supports opening directories from other file providers, and not all file providers support opening directories (since Apple forgot to write documentation on this).

**Comment by 62f** [comment]
> Thanks but are you getting to this interface from ish, gear->FileSystems->Import->Browse ? If so, I can see the various fileproviders that way but all files are grayed out.

Yes that's how I was getting to Files. My prior instructions are modified to apply only to yourself, not the OP of the issue, who is using an iPad.
-------//////-------//////-----
Help for the OP only is as follows:

https://apps.apple.com/us/app/mobile-memory/id1118842701

https://apps.apple.com/us/app/i-emory/id1041272431

https://apps.apple.com/us/app/i-flashdevice/id1100496131

**Comment by ifuchs** [comment]
Thanks very much but I'm not sure what this has to do with my original question. It would appear that the answer is that ish needs to be modified to deal with the nextcloud (or other) file provider APIs.￼

**Comment by 62f** [comment]
tbodt just explained why most of those complications don't exist and aren't expected to work, plus I disclosed probable alternatives for a pass-through type access to cloud-based file providers. I'm not dense and did realize you'd used e.g. instead of i.e. so 'ergo' that which you truly seek isΞΞΞonly a one-step solution for that one very specific, named-by-you, online/cloud-based, third-party file-host. Well i.e. you should try setting a OneDrive-Microsoft's product- as the automatic file backup location for Word, also-Microsoft, just to 'eXPerience' how many times that even a single-party combination spontaneously closes an opened document per hour so perhaps you'll better understand the intrinsic instability of the feature you've asked to materialize. No, Apple isn't going to permit the sales of their more capricious devices suffer on behalf of a niche supplication.

**Comment by tbodt** [comment]
It's not possible to mount a NextCloud folder, their file provider is implemented in a way that only allows opening one file at a time. It could be possible to use the share sheet or drag/drop or a file open box, but that's #337.

**Comment by ifuchs** [comment]
What about using webdav? (which is supported by Nextcloud)

**Comment by tbodt** [comment]
That could work, if the webdav file provider supports opening folders. Worth a try.

**Comment by ifuchs** [comment]
It seems to support opening folders, saving, etc.

**Comment by ifuchs** [comment]
apk add webdavfs2 installs but I haven't been able to get a mount to work. I am probably missing some steps.

**Comment by ifuchs** [comment]
I installed davfs2, created a mount point,  added userid/password to the /etc/davfs2/secrets file.
mount /mnt/dav gives:

Mounting failed.
Could not authenticate to server: rejected Basic challenge.

**Comment by tbodt** [comment]
I was thinking of a webdav file provider in the files app. davfs sounds like a FUSE which isn't supported.

**Comment by ifuchs** [comment]
If this was a FUSE, I would’ve expected a different error message than
“authentication rejected”.  But I defer to you.
