### ISSUE TITLE
iSH Build Fail on XCTest.h not found

### ISSUE THREAD

**Issue by emkey1** [ish-app/ish#1071]
I don't believe I changed anything but I was clicking around and managed to get myself into this mess...  My fault or actual issue?

<img width="278" alt="Screen Shot 2020-11-18 at 12 02 40 PM" src="https://user-images.githubusercontent.com/18100932/99562594-4d153200-2996-11eb-9672-64ea1dcedfd2.png">

**Comment by nimelehin** [comment]
Master builds fine. XCTest is a standard part of the SDK.

 This might help you: https://stackoverflow.com/questions/24275470/xctest-xctest-h-not-found-on-old-projects-built-in-xcode-6/24651704#24651704

**Comment by emkey1** [comment]
Thank you.  I just commented it out for now but I’ll check out the link.
