### ISSUE TITLE
2 Stub Syscalls 375 caused by #git clone https://github.com/oneapi-src/oneDNN.git

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#1073]
iSH build 80![image](https://user-images.githubusercontent.com/68332197/99641682-99a15180-2a18-11eb-9413-369ddff3b5df.png) will retry with iSH build 82(latest)

**Comment by saagarjha** [comment]
That’s `membarrier` and it’s stubbed because nothing really seems to care about it. Has it been an issue for you?

**Comment by 62f** [comment]
Confirmed in (82). The stubs were discovered by accident. There are worse issues, of course. As expected, the build-compile failed successfully at an unsatisfied prerequisite- so I don’t know if these membarriers occurring would have caused any trouble beyond that.

**Comment by tbodt** [comment]
membarrier isn't per se evidence of a bug.

**Comment by 62f** [comment]
Problem 'for me', per se, yes. I would have simply liked to know when these entries are being made, and thought I had found such answers to that prayer in fish/ but unfortunately that came with a price as due to its different handling of existing syslinks has just IMO resulted in a corruption of the busybox binary and unstartable iSH. Granted I didn't know THAT specifically would become a problem, and it's not an iSH problem, nor was my ineptitude to fix it properly, but my painstakingly-evolved philosophy keeps me from becoming the complete idiot especially when it comes to identifying sleeping giants which is now painfully apparent that nobody else cares enough about.
