### ISSUE TITLE
Installing python modules

### ISSUE THREAD

**Issue by ifuchs** [ish-app/ish#1074]
I would like to install numpy (as well as other python 2 and 3 modules). I tied the following:

pip3 install numpy
Traceback (most recent call last):
  File "/usr/bin/pip3", line 6, in <module>
    from pip._internal import main
  File "/usr/lib/python3.8/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 11, in <module>
    from pip._internal.commands import (
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 26, in <module>
    from pip._internal.index import PackageFinder
ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (/usr/lib/python3.8/site-packages/pip/_internal/index/__init__.py)

I know this issue has been raised before (year ago) but I have not found a solution. How to add python modules?

**Comment by 62f** [comment]
Python 2 is obsolete, though.

**Comment by anzhi0708** [comment]
$ apk search numpy

py3-numpy-1.18.4-r0
py3-numpy-doc-1.18.4-r0
py3-numpy-dev-1.18.4-r0
py3-numpy-f2py-1.18.4-r0

$ apk add py3-numpy

![274278EF-0387-406F-8F92-727B33E0D56E](https://user-images.githubusercontent.com/57821133/99897444-da30f180-2cdc-11eb-91b8-f1b692639d8b.png)

I guess it works at some level, dunno how to use numpy tho! I guess you need to install dependencies first if you want to install some python modules by using pip install. For example, libgfortran, openblas, etc.

**Comment by 62f** [comment]
I wouldn't use pip to install anything Alpine had already packaged into an apk anyway: Building wheels in iSH maybe takes forever, and then there's impending doom of duplicate binaries. In fact I've had very spotted success using pip beyond initially creating a (tutorial_env). Even pip installing updates to pip itself can be hit-&-miss, and seldom fixes anything. What's broken-pip usually stays pip-broken.
Now was never a better time to close this issue.

**Comment by ifuchs** [comment]
@anzhi0708 Thanks, that works!

**Comment by anzhi0708** [comment]
@ifuchs Yeah, maybe we can try to build pandas from source code or something ;) I'll try to build it when I got home

**Comment by 62f** [comment]
Attempting to install numpy using pip, a very very verbose output states:

    creating build/src.linux-i686-3.8/numpy/distutils
    building library "npymath" sources
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable ifort
    Could not locate executable ifc
    Could not locate executable lf95
    Could not locate executable pgfortran
    Could not locate executable nvfortran
    Could not locate executable f90
    Could not locate executable f77
    Could not locate executable fort
    Could not locate executable efort
    Could not locate executable efc
    Could not locate executable g77
    Could not locate executable g95
    Could not locate executable pathf95
    Could not locate executable nagfor
    don't know how to compile Fortran code on platform 'posix'

**Comment by were** [comment]
Follow up this thread. I installed bumpy, and run a simple matrix multiplication. I got this:
![image](https://user-images.githubusercontent.com/2356965/99929761-3eff4280-2d03-11eb-8b0e-bb5dae29aa37.jpeg)

**Comment by anzhi0708** [comment]
@were Same error here

**Comment by tbodt** [comment]
Original issue looks like a pip version mismatch or something. `apk fix py3-pip` may help.

Numpy does successfully install with `apk add py3-pip`.

For the error about not being able to compile fortran, try `apk add gfortran`.

@were This is #377.

**Comment by ifuchs** [comment]
@tbodt i tried the fix you suggested but the Original issue with running pip persists:

apk fix py3-pip
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86/APKINDEX.tar.gz
(1/1) Reinstalling python3 (3.8.2-r1)
Executing busybox-1.31.1-r9.trigger
OK: 653 MiB in 130 packages
Iras-iPad-Pro-2:~# pip3 install webdav3client
Traceback (most recent call last):
  File "/usr/bin/pip3", line 6, in <module>
    from pip._internal import main
  File "/usr/lib/python3.8/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 11, in <module>
    from pip._internal.commands import (
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 26, in <module>
    from pip._internal.index import PackageFinder
ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (/usr/lib/python3.8/site-packages/pip/_internal/index/__init__.py

**Comment by 62f** [comment]
pip and pip3 are different monsters.
