### ISSUE TITLE
resource#2

### ISSUE THREAD

**Issue by Khung-i11** [ish-app/ish#1079]
resource#2

__Originally posted by @Khung-i11 in https://github.com/ynkonghao/resource/issues/2#issuecomment-731239774__

**Comment by Khung-i11** [comment]
resource#2

**Comment by nimelehin** [comment]
What's that? I don't think it's connected with this project.

**Comment by Mnpn03** [comment]
Please stop creating issues like this. If you have an actual issue, please provide some actual information.
