### ISSUE TITLE
APK not work

### ISSUE THREAD

**Issue by OneParsec** [ish-app/ish#1098]
Package manager apk bot work![image](https://user-images.githubusercontent.com/65869620/101044519-7afe9700-3590-11eb-9eee-76960d08f44b.png)

**Comment by mr-antisecurity** [comment]
> Package manager apk bot work![image](https://user-images.githubusercontent.com/65869620/101044519-7afe9700-3590-11eb-9eee-76960d08f44b.png)

Yeep. I just downloaded iSH shell on my Iphone 6. But apk didn't work :(.

**Comment by mr-antisecurity** [comment]
> Package manager apk bot work![image](https://user-images.githubusercontent.com/65869620/101044519-7afe9700-3590-11eb-9eee-76960d08f44b.png)

Alright I just found out what to do. You have to install apk first. :) 
Try this :

wget -qO- http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86/apk-tools-static-2.10.5-r1.apk | tar -xz sbin/apk.static && ./sbin/apk.static add apk-tools && rm sbin/apk.static && rmdir sbin 2> /dev/null

**Comment by OneParsec** [comment]
Thanks for help! It works!

**Comment by mr-antisecurity** [comment]
> Thanks for help! It works!

Not at all !!!
