### ISSUE TITLE
R crash: illegal operation

### ISSUE THREAD

**Issue by ditestingr** [ish-app/ish#1100]
Hi there,

congrats to iSH! This is great great stuff.  Based on your efforts, iPads might turn into productive machines, running e.g. R. 
Unfortunately -- while loading libraries, importing data, estimating regressions... without any problems - R crashes when calling (e.g.) function 'summary' with message:

*** caught illegal operation ***
address 0xf6945796, cause 'unknown'

Traceback:
1: solve.default (-hessian...)
2: solve (-hessian....)
3 .........
 
To get R running in the iSH sandbox I followed guidance found in the net. Particularly, I managed to compile some required libraries on my notebook running linux (Ubuntu 18.04.5 LTS, Intel Core i7-2620M CPU) within a docker container running the same (as used in iSH) alpine linux 3.12 system.  Then I transfered these libraries onto the iPad and into the iSH box. When calling the summary() function in R running in this docker container everythin is fine.

Any clue, what goes wrong here? Does this issue seem solvable with justifiable effort? Anybody else stumbling over similar issues?

Thanks for feedback, Dieter

**Comment by Palmuser56** [comment]
Hi,

first of all: Congratulation to the developer. I love ish.

Unfortunately I also get an illegal operation error in R with an essential command. Everytime I use "qt" (quantile of the t destribution)  I get 

*** caught illegal operation ***
address 0xf7f94bec, cause 'unknown'

Traceback:
1: qt(0.7,12)


For I only need some basic set of commands I simply installed R with "app add R" which seemed to work fine.

Best regards
Michael

**Comment by SugarRayLua** [comment]
Hi, ditesting r and PalmUser56.

I love ish, too, and have been trying to use R with it and run into similar occasional problems with using some R commands.

If you didn't know already, there is one developer's program 'R analyst' on the app store that does run R successfully on my iPad. It's GUI is not optimum, the default font size needs to be much bigger, and there is no customer support that I can tell, but it does seem to work and consistently run 'R', come prepackaged with a good assortment of R libraries, and can import files into its file folder. 

I keep using and exploring iSH's capabilities but use 'R analyst' for my R work until iSH runs R consistently well.

Fyi.

Have a good week.

**Comment by Mnpn** [comment]
Hi! We've recently released iSH 1.3 which brings fixes for R. Please give it a try and let us know if you're still running into any unexpected behaviour - thanks!

**Comment by ditestingr** [comment]
dear martin,thanks for asking and sustaining efforts.mini tests (lm and glm) with the new version confirm that the summary command works as expected. anything more particular you want to be tested?best, dieterAm 26.04.2023 um 00:01 schrieb Martin Persson ***@***.***>:﻿
Hi! We've recently released iSH 1.3 which brings fixes for R. Please give it a try and let us know if you're still running into any unexpected behaviour - thanks!

**Comment by Mnpn** [comment]
Hi again, thanks for taking the time to try it! It seems there are unfortunately still some hiccups with certain operations in R, which we'll be tracking in #1780.
