### ISSUE TITLE
Race between execve and proc_pid_cmdline_show

### ISSUE THREAD

**Issue by emkey1** [ish-app/ish#1102]
See attached image for some context.  This is the script I'm running that causes the crash...

#!/bin/bash 
tmux new-session -s "My iPad" -d
tmux split-window -h
tmux split-window -v
tmux -2 attach-session -d 

Note that I can manually create the same layout after running tmux manually.

<img width="1635" alt="Screen Shot 2020-12-06 at 4 53 01 PM" src="https://user-images.githubusercontent.com/18100932/101294179-a3ca9a80-37e3-11eb-9341-fe674fdfeec5.png">

**Comment by emkey1** [comment]
I suspect this might be a race/locking condition since three windows are opening nearly at the same time in this scenario.

**Comment by tbodt** [comment]
I tried running this script and couldn't reproduce the problem

**Comment by emkey1** [comment]
This time in the right issue...

It might have to do with the speed of the iDevice. I was doing it on my iPad 7th gen. Opening only two panes makes it a LOT less likely to happen on that hardware. In fact, I can't seem to reproduce opening just two panes.

**Comment by emkey1** [comment]
Try adding several more window splits to the script.  It doesn't always crash on my iPad at two splits, but at four it's very consistent.

**Comment by emkey1** [comment]
I'm not sure it's useful, but I just submitted a crash dump via the popup.  I was attempting to open about a half dozen panes while ssh'd in.   Unfortunately, I think this bug might be in the JIT portion of the code.

**Comment by gitdev-bash** [comment]
Hello @emkey1 i have tried it out myself, i couldn’t reproduce it on my iPhone 6s.
It just did what it should have done without any crashes or slownes. When I remember right the iPad gen7 has more cpu power than the 6s. It’s probably not cpu limitations.
Hope I helped.
:-)

**Comment by emkey1** [comment]
Are you running iOS 14.2?  I'm able to reproduce this on several different devices, all running 14.2.  

I'll see if I can nail down a better description and reproducer.  For now, backgrounding tmux and running another with a different session name will almost certainly cause the error.

It's possible this is an iOS issue?

**Comment by gitdev-bash** [comment]
I am running iOS 14.2 and i did everything you Said:
![E0EC494C-23DA-454F-A744-7B9B8A09834E](https://user-images.githubusercontent.com/63194733/101785626-45602d80-3afd-11eb-8dd0-a3b6c74e72b5.jpeg)
![E2040D24-8447-4395-890C-5C75AE83068A](https://user-images.githubusercontent.com/63194733/101785631-4729f100-3afd-11eb-931f-9f330a223e9a.jpeg)
![FA8B744D-1DA9-412C-9C1C-9CC120FCD407](https://user-images.githubusercontent.com/63194733/101785777-72acdb80-3afd-11eb-9bab-7bb51f214d42.jpeg) (I exited myself)

**Comment by emkey1** [comment]
It's very dependant on the speed of the device and how many tasks are started over a short period of time.  My custom iSH root fs kicks off a number of processes each time a pane is opened.  Try the following.  You might have to up the max value of the variable i, but iSH will crash.

```
#!/bin/ash
for i in `seq 1 50`; do ps -eaf > /dev/null &2>1; done
```

**Comment by emkey1** [comment]
One other note, insert a sleep of a few seconds between each ps and odds are the crash won't occur which is why it feels like a locking/race condition to me.

**Comment by emkey1** [comment]
Here is a variation on what I think is the same issue.  This sometimes happens on iSH startup.

<img width="1792" alt="Screen Shot 2020-12-13 at 8 37 08 PM" src="https://user-images.githubusercontent.com/18100932/102031177-325e8f00-3d83-11eb-8fcb-275717c5a58d.png">

**Comment by gitdev-bash** [comment]
Hi @emkey1 i tried "for i in `seq 1 50`; do ps -eaf > /dev/null &2>1; done" and ish slowed down and crashed on me. I sent the crash logs to @tbodt he might post it here. And btw "for i in `seq 1 1000`; do ps -eaf > /dev/null &2>1; done" was enough to get my laptops 4 cpu cores to 100 so it might be a cpu overload issue where ish tries to use non-existing cpu power 
:)

**Comment by emkey1** [comment]
@gitdev-bash, this is essentially a fork bomb.  It's normal for an OS to become unresponsive if enough task creation requests are sent to it in a short period of time, but crashing is not good.

Depending on the iDevice that you have the numbers will vary, but there will be a lower range where iSH is almost always fine running the script, a middle range where it becomes increasingly likely to crash as you increase the number, and finally a point at which it will always crash.

While these crashes vary a bit in terms of where they occur in the code they all appear to be related to memory access.  Either attempts to access memory or attempts to free it.  This leads me to believe there is a locking issue that is allowing memory to be freed twice or accessed after it has been freed.

I'm going to spend some time today digging into this but I'm not optimistic about my chances.  iSH is both an emulated computer and a Linux kernel clone which is very cool, but extremely complex.  I'm an intermediate programmer at best and essentially a noob when it comes to C.

**Comment by gitdev-bash** [comment]
The Definition of fork bomb is a program which starts itself multiple times over and over again until the OS can't handle it (its non ending) but in your small one liner it just starts a specified program over and over again which is finite and non-recursive so you can't call it a fork bomb. Normally in modern OS' there are inbuilt protections against Fork bombs crashing the system (excluding Windows 10 :) (i programed a small fork bomb there and it crashed hilariously)) like prioritizing system tasks.

**Comment by gitdev-bash** [comment]
Here is the Forkbomb for windows in batch:`@echo off
start Runme.bat
start Runme.bat
:chrome
start chrome
goto chrome
`

**Comment by emkey1** [comment]
I did say "essentially".  :)

It's meant to have some of the same impact while still being finite.  

It would be possible to write a fork bomb with a recursion limit of course but this was simpler.

Nothing bad Windows related surprises me.

In regards to the crash issue, the following seems to help, but I suspect it's masking the issue rather than really helping it...

```
diff --git a/emu/memory.c b/emu/memory.c
index 25652ed..8f6610d 100644
--- a/emu/memory.c
+++ b/emu/memory.c
@@ -39,9 +39,10 @@ void mem_destroy(struct mem *mem) {
         if (mem->pgdir[i] != NULL)
             free(mem->pgdir[i]);
     }
-    free(mem->pgdir);
+    if(mem->pgdir != NULL) { //mke
+        free(mem->pgdir);
+    }
     write_wrunlock(&mem->lock);
-    wrlock_destroy(&mem->lock);
 }
 
 #define PGDIR_TOP(page) ((page) >> 10)
```

In particular, removing the call to 

wrlock_destroy(&mem->lock);

is likely bad but putting it back in greatly reduces stability.

**Comment by emkey1** [comment]
One last update and then I'm taking a break from this one.

Try the following script.  Provide it with an argument.  It doesn't matter much what, foo, bar, car, mars, whatever.

If iSH doesn't crash the first time it will almost certainly crash the second.  It pretty much always crashes in thread creation and somewhere where memory is being freed or checked.  

I've verified this with a fresh build of the current master branch.

#!/bin/bash
tmux new-session -s $1 -d
tmux split-window -h
tmux split-window -v
tmux split-window -v
tmux split-window -v
tmux split-window -v
tmux split-window -v
tmux split-window -v
tmux split-window -v
tmux split-window -v
tmux split-window -v

**Comment by 62f** [comment]
Is this a “Make iSH crash in one command” thread? Try 
curl file:///dev/zero --output -
that’s why I
rm /dev/zero
got rid of that. Wanna see the crash log?

**Comment by tbodt** [comment]
@62f Seems like dumping data on stdout too fast will cause a crash. `cat /dev/zero` also works. Feel free to file an issue for that if there isn't one already.

**Comment by tbodt** [comment]
Found a more effective repro, it crashes in under 100ms.
```
#!/bin/sh
echo 'exec $0' > /tmp/execloop.sh
chmod +x /tmp/execloop.sh
/tmp/execloop.sh &
pid=$!
while :; do
        cat /proc/$pid/cmdline >/dev/null
done
```

**Comment by tbodt** [comment]
<details>
<summary>TSAN report</summary>

```
WARNING: ThreadSanitizer: data race (pid=5521)
  Read of size 8 at 0x7b64000399c0 by thread T7 (mutexes: write M47):
    #0 proc_pid_cmdline_show <null> (ish:x86_64+0x1000272ee)
    #1 proc_pread <null> (ish:x86_64+0x10002567d)
    #2 sys_read <null> (ish:x86_64+0x1000179f3)
    #3 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #4 task_run_current <null> (ish:x86_64+0x100006781)
    #5 task_thread <null> (ish:x86_64+0x100006853)

  Previous write of size 8 at 0x7b64000399c0 by thread T6:
    [failed to restore the stack]

  Location is heap block of size 1248 at 0x7b6400039800 allocated by thread T4:
    #0 malloc <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x5239a)
    #1 task_create_ <null> (ish:x86_64+0x100006361)
    #2 sys_clone <null> (ish:x86_64+0x100007aef)
    #3 sys_fork <null> (ish:x86_64+0x1000083e1)
    #4 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #5 task_run_current <null> (ish:x86_64+0x100006781)
    #6 task_thread <null> (ish:x86_64+0x100006853)

  Mutex M47 (0x00010b2552d8) created at:
    #0 pthread_mutex_lock <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x3d65e)
    #1 task_create_ <null> (ish:x86_64+0x100006239)
    #2 construct_task <null> (ish:x86_64+0x100004021)
    #3 become_first_process <null> (ish:x86_64+0x100003fc1)
    #4 main <null> (ish:x86_64+0x100003b0b)

  Thread T7 (tid=62685, running) created by thread T4 at:
    #0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x2d8fd)
    #1 task_start <null> (ish:x86_64+0x1000067fe)
    #2 sys_clone <null> (ish:x86_64+0x10000822c)
    #3 sys_fork <null> (ish:x86_64+0x1000083e1)
    #4 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #5 task_run_current <null> (ish:x86_64+0x100006781)
    #6 task_thread <null> (ish:x86_64+0x100006853)

  Thread T6 (tid=62684, running) created by thread T4 at:
    #0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x2d8fd)
    #1 task_start <null> (ish:x86_64+0x1000067fe)
    #2 sys_clone <null> (ish:x86_64+0x10000822c)
    #3 sys_fork <null> (ish:x86_64+0x1000083e1)
    #4 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #5 task_run_current <null> (ish:x86_64+0x100006781)
    #6 task_thread <null> (ish:x86_64+0x100006853)

  Thread T4 (tid=62682, running) created by thread T3 at:
    #0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x2d8fd)
    #1 task_start <null> (ish:x86_64+0x1000067fe)
    #2 sys_clone <null> (ish:x86_64+0x10000822c)
    #3 sys_fork <null> (ish:x86_64+0x1000083e1)
    #4 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #5 task_run_current <null> (ish:x86_64+0x100006781)
    #6 task_thread <null> (ish:x86_64+0x100006853)

SUMMARY: ThreadSanitizer: data race (/Users/tbodt/Developer/projects/ish/crap/b/ish:x86_64+0x1000272ee) in proc_pid_cmdline_show+0x7e
==================
==================
WARNING: ThreadSanitizer: data race (pid=5521)
  Read of size 4 at 0x7b440023e980 by thread T7 (mutexes: write M47):
    #0 proc_pid_cmdline_show <null> (ish:x86_64+0x10002730d)
    #1 proc_pread <null> (ish:x86_64+0x10002567d)
    #2 sys_read <null> (ish:x86_64+0x1000179f3)
    #3 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #4 task_run_current <null> (ish:x86_64+0x100006781)
    #5 task_thread <null> (ish:x86_64+0x100006853)

  Previous write of size 4 at 0x7b440023e980 by thread T6:
    #0 format_exec <null> (ish:x86_64+0x100009d36)
    #1 __do_execve <null> (ish:x86_64+0x100008639)
    #2 sys_execve <null> (ish:x86_64+0x10000a9bf)
    #3 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #4 task_run_current <null> (ish:x86_64+0x100006781)
    #5 task_thread <null> (ish:x86_64+0x100006853)

  Location is heap block of size 288 at 0x7b440023e880 allocated by thread T6:
    #0 malloc <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x5239a)
    #1 mm_new <null> (ish:x86_64+0x10000d998)
    #2 format_exec <null> (ish:x86_64+0x100009328)
    #3 __do_execve <null> (ish:x86_64+0x100008639)
    #4 sys_execve <null> (ish:x86_64+0x10000a9bf)
    #5 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #6 task_run_current <null> (ish:x86_64+0x100006781)
    #7 task_thread <null> (ish:x86_64+0x100006853)

  Mutex M47 (0x00010b2552d8) created at:
    #0 pthread_mutex_lock <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x3d65e)
    #1 task_create_ <null> (ish:x86_64+0x100006239)
    #2 construct_task <null> (ish:x86_64+0x100004021)
    #3 become_first_process <null> (ish:x86_64+0x100003fc1)
    #4 main <null> (ish:x86_64+0x100003b0b)

  Thread T7 (tid=62685, running) created by thread T4 at:
    #0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x2d8fd)
    #1 task_start <null> (ish:x86_64+0x1000067fe)
    #2 sys_clone <null> (ish:x86_64+0x10000822c)
    #3 sys_fork <null> (ish:x86_64+0x1000083e1)
    #4 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #5 task_run_current <null> (ish:x86_64+0x100006781)
    #6 task_thread <null> (ish:x86_64+0x100006853)

  Thread T6 (tid=62684, running) created by thread T4 at:
    #0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x2d8fd)
    #1 task_start <null> (ish:x86_64+0x1000067fe)
    #2 sys_clone <null> (ish:x86_64+0x10000822c)
    #3 sys_fork <null> (ish:x86_64+0x1000083e1)
    #4 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #5 task_run_current <null> (ish:x86_64+0x100006781)
    #6 task_thread <null> (ish:x86_64+0x100006853)

SUMMARY: ThreadSanitizer: data race (/Users/tbodt/Developer/projects/ish/crap/b/ish:x86_64+0x10002730d) in proc_pid_cmdline_show+0x9d
==================
==================
WARNING: ThreadSanitizer: data race (pid=5521)
  Read of size 4 at 0x7b440023e97c by thread T7 (mutexes: write M47):
    #0 proc_pid_cmdline_show <null> (ish:x86_64+0x100027320)
    #1 proc_pread <null> (ish:x86_64+0x10002567d)
    #2 sys_read <null> (ish:x86_64+0x1000179f3)
    #3 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #4 task_run_current <null> (ish:x86_64+0x100006781)
    #5 task_thread <null> (ish:x86_64+0x100006853)

  Previous write of size 4 at 0x7b440023e97c by thread T6:
    [failed to restore the stack]

  Location is heap block of size 288 at 0x7b440023e880 allocated by thread T6:
    #0 malloc <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x5239a)
    #1 mm_new <null> (ish:x86_64+0x10000d998)
    #2 format_exec <null> (ish:x86_64+0x100009328)
    #3 __do_execve <null> (ish:x86_64+0x100008639)
    #4 sys_execve <null> (ish:x86_64+0x10000a9bf)
    #5 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #6 task_run_current <null> (ish:x86_64+0x100006781)
    #7 task_thread <null> (ish:x86_64+0x100006853)

  Mutex M47 (0x00010b2552d8) created at:
    #0 pthread_mutex_lock <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x3d65e)
    #1 task_create_ <null> (ish:x86_64+0x100006239)
    #2 construct_task <null> (ish:x86_64+0x100004021)
    #3 become_first_process <null> (ish:x86_64+0x100003fc1)
    #4 main <null> (ish:x86_64+0x100003b0b)

  Thread T7 (tid=62685, running) created by thread T4 at:
    #0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x2d8fd)
    #1 task_start <null> (ish:x86_64+0x1000067fe)
    #2 sys_clone <null> (ish:x86_64+0x10000822c)
    #3 sys_fork <null> (ish:x86_64+0x1000083e1)
    #4 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #5 task_run_current <null> (ish:x86_64+0x100006781)
    #6 task_thread <null> (ish:x86_64+0x100006853)

  Thread T6 (tid=62684, running) created by thread T4 at:
    #0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x2d8fd)
    #1 task_start <null> (ish:x86_64+0x1000067fe)
    #2 sys_clone <null> (ish:x86_64+0x10000822c)
    #3 sys_fork <null> (ish:x86_64+0x1000083e1)
    #4 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #5 task_run_current <null> (ish:x86_64+0x100006781)
    #6 task_thread <null> (ish:x86_64+0x100006853)

SUMMARY: ThreadSanitizer: data race (/Users/tbodt/Developer/projects/ish/crap/b/ish:x86_64+0x100027320) in proc_pid_cmdline_show+0xb0
==================
==================
WARNING: ThreadSanitizer: data race (pid=5521)
  Read of size 8 at 0x7b64000399c8 by thread T7 (mutexes: write M47):
    #0 user_read_task <null> (ish:x86_64+0x100005812)
    #1 proc_pid_cmdline_show <null> (ish:x86_64+0x10002736a)
    #2 proc_pread <null> (ish:x86_64+0x10002567d)
    #3 sys_read <null> (ish:x86_64+0x1000179f3)
    #4 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #5 task_run_current <null> (ish:x86_64+0x100006781)
    #6 task_thread <null> (ish:x86_64+0x100006853)

  Previous write of size 8 at 0x7b64000399c8 by thread T6:
    [failed to restore the stack]

  Location is heap block of size 1248 at 0x7b6400039800 allocated by thread T4:
    #0 malloc <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x5239a)
    #1 task_create_ <null> (ish:x86_64+0x100006361)
    #2 sys_clone <null> (ish:x86_64+0x100007aef)
    #3 sys_fork <null> (ish:x86_64+0x1000083e1)
    #4 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #5 task_run_current <null> (ish:x86_64+0x100006781)
    #6 task_thread <null> (ish:x86_64+0x100006853)

  Mutex M47 (0x00010b2552d8) created at:
    #0 pthread_mutex_lock <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x3d65e)
    #1 task_create_ <null> (ish:x86_64+0x100006239)
    #2 construct_task <null> (ish:x86_64+0x100004021)
    #3 become_first_process <null> (ish:x86_64+0x100003fc1)
    #4 main <null> (ish:x86_64+0x100003b0b)

  Thread T7 (tid=62685, running) created by thread T4 at:
    #0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x2d8fd)
    #1 task_start <null> (ish:x86_64+0x1000067fe)
    #2 sys_clone <null> (ish:x86_64+0x10000822c)
    #3 sys_fork <null> (ish:x86_64+0x1000083e1)
    #4 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #5 task_run_current <null> (ish:x86_64+0x100006781)
    #6 task_thread <null> (ish:x86_64+0x100006853)

  Thread T6 (tid=62684, running) created by thread T4 at:
    #0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x2d8fd)
    #1 task_start <null> (ish:x86_64+0x1000067fe)
    #2 sys_clone <null> (ish:x86_64+0x10000822c)
    #3 sys_fork <null> (ish:x86_64+0x1000083e1)
    #4 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #5 task_run_current <null> (ish:x86_64+0x100006781)
    #6 task_thread <null> (ish:x86_64+0x100006853)

  Thread T4 (tid=62682, running) created by thread T3 at:
    #0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x2d8fd)
    #1 task_start <null> (ish:x86_64+0x1000067fe)
    #2 sys_clone <null> (ish:x86_64+0x10000822c)
    #3 sys_fork <null> (ish:x86_64+0x1000083e1)
    #4 handle_interrupt <null> (ish:x86_64+0x100004fd5)
    #5 task_run_current <null> (ish:x86_64+0x100006781)
    #6 task_thread <null> (ish:x86_64+0x100006853)

SUMMARY: ThreadSanitizer: data race (/Users/tbodt/Developer/projects/ish/crap/b/ish:x86_64+0x100005812) in user_read_task+0x32
==================
```

</details>

**Comment by emkey1** [comment]
The fix looks good so far.  Thank you tbodt!
