### ISSUE TITLE
Can't run any of the linux commands. Thank you.

### ISSUE THREAD

**Issue by NxthanWasTaken** [ish-app/ish#1103]
![IMG_2902](https://user-images.githubusercontent.com/75347553/101300793-67576880-37fc-11eb-857f-ca7ad8ee5243.png)
Well play, Tbodt. iPad 7,3. I can't run 'Apk add Python3' or anything but whatever that command underneath. :)
![IMG_2903](https://user-images.githubusercontent.com/75347553/101300910-cc12c300-37fc-11eb-91b9-59fa98293bbd.png)

**Comment by saagarjha** [comment]
The version of iSH on the App Store has had package management functionality removed. The ability to run Linux programs, as well as import files, has not been changed.
