### ISSUE TITLE
fish-in-iSH breaks busybox

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#1108]
Failed to execute process '/usr/bin/less'. Reason:
exec: unknown error (errno was 8)
The file '/usr/bin/less' is marked as an executable but could not be run by the operating system.

__Originally posted by @62f in https://github.com/ish-app/ish/issues/1088__

Welcome to Alpine!

You can install packages with: apk add <package>

You may change this message by editing /etc/motd.

 Alpine systems.
See <http://wiki.alpinelinux.org/>.

You can setup the system with the command: setup-alpine

You may change this message by editing /etc/motd.

^C#                                                                                   iPhone0 user root@Tue 8_ 3:07AM~(/root)-zsh:fish
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
root@iPhone ~# ls /etc/r*dircolors: applet not found

/etc/rc.conf      /etc/rc.local*    /etc/rc.local~*   /etc/resolv.conf

/etc/raddb:
README.rst       hints@           mods-enabled/    radiusd.conf     trigger.conf
certs/           huntgroups@      panic.gdb        sites-available/ users@
clients.conf     mods-available/  policy.d/        sites-enabled/
dictionary       mods-config/     proxy.conf       templates.conf
root@iPhone ~# pip install--upgrade-pip
ERROR: unknown command "install--upgrade-pip"
root@iPhone ~ [1]# cp /usr/bin/less /usr/bin/less
cp: '/usr/bin/less' and '/usr/bin/less' are the same file
root@iPhone ~ [1]# rm /usr/bin/less
root@iPhone ~# ln -s /bin/busybox /usr/bin/less
root@iPhone ~# less
BusyBox v1.31.1 () multi-call binary.

Usage: less [-EFIMmNSRh~] [FILE]...

View FILE (or stdin) one screenful at a time

        -E      Quit once the end of a file is reached
        -F      Quit if entire file fits on first screen
        -I      Ignore case in all searches
        -M,-m   Display status line with line numbers
                and percentage through the file
        -N      Prefix line number to each line
        -S      Truncate long lines
        -R      Remove color escape codes in input
        -~      Suppress ~s displayed past EOF
root@iPhone ~ [1]# go list
can't load package: package .: no Go files in /root
root@iPhone ~ [1]# go build
can't load package: package .: no Go files in /root
root@iPhone ~ [1]# vi Failed to execute process '/usr/bin/vi'. Reason:
exec: unknown error (errno was 13)
vi |xxd
Failed to execute process '/usr/bin/vi'. Reason:
exec: unknown error (errno was 13)
Failed to execute process '/usr/bin/xxd'. Reason:
exec: unknown error (errno was 13)
root@iPhone ~ [125|125]# exit
iPhone0 user root@Tue 8_ 5:13PM~(/root)-zsh:cat /usr/bin/vi|xxd
zsh: permission denied: xxd
iPhone0 user root@Tue 8_ 5:14PM~(/root)-zsh:cat /usr/bin/vi|sudo xxd
sudo: xxd: command not found
iPhone0 user root@Tue 8_ 5:14PM~(/root)-zsh:sudo cat /usr/bin/vi|sudo
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u
            user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u
            user] file ...
iPhone0 user root@Tue 8_ 5:14PM~(/root)-zsh:sudo cat /usr/bin/vi|xxd 
zsh: permission denied: xxd
iPhone0 user root@Tue 8_ 5:15PM~(/root)-zsh:sudo cat /usr/bin/vi|sudo xxd
sudo: xxd: command not found
iPhone0 user root@Tue 8_ 5:15PM~(/root)-zsh:sudo fish                    
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
root@iPhone ~# cat /usr/bin/vi |xxd
Failed to execute process '/usr/bin/xxd'. Reason:
exec: unknown error (errno was 13)
root@iPhone ~ [SIGPIPE|125]# sudo cat /usr/bin/vi |xxd
Failed to execute process '/usr/bin/xxd'. Reason:
exec: unknown error (errno was 13)
root@iPhone ~ [SIGPIPE|125]# sudo cat /usr/bin/vi |sudo xxd
sudo: xxd: command not found
root@iPhone ~ [SIGPIPE|1]# which xxd
/usr/bin/xxd
root@iPhone ~# sudo cat /usr/bin/vi |sudo /usr/bin/xxd
sudo: /usr/bin/xxd: command not found
root@iPhone ~ [SIGPIPE|1]# sudo ls /usr/bin/xxd
/usr/bin/xxd
root@iPhone ~# sudo ls /usr/bin/xxd -la
-rw-rw-rw-    1 root     root            12 Jul 20 00:59 /usr/bin/xxd
root@iPhone ~# sudo cp /usr/bin/xxd /usr/bin/less
root@iPhone ~# which less
Failed to execute process '/usr/bin/which'. Reason:
exec: unknown error (errno was 8)
The file '/usr/bin/which' is marked as an executable but could not be run by the operating system.
root@iPhone ~ [125]# sudo cat /usr/bin/vi |sudo busybox /usr/bin/xxd
sudo: unable to execute /bin/busybox: Exec format error
root@iPhone ~ [SIGPIPE|1]# cat /usr/bin/vi |sudo busybox /usr/bin/xxd
sudo: unable to execute /bin/busybox: Exec format error
root@iPhone ~ [0|1]# cat /usr/bin/vi |sudo busybox xxd
sudo: unable to execute /bin/busybox: Exec format error
root@iPhone ~ [0|1]# cat /usr/bin/vi |busybox xxd
Failed to execute process '/bin/busybox'. Reason:
exec: unknown error (errno was 8)
The file '/bin/busybox' is marked as an executable but could not be run by the operating system.
root@iPhone ~ [SIGPIPE|125]# cat /usr/bin/vi |xxd
Failed to execute process '/usr/bin/xxd'. Reason:
exec: unknown error (errno was 13)
root@iPhone ~ [SIGPIPE|125]# sudo xxd
sudo: xxd: command not found
root@iPhone ~ [1]# sudo /usr/bin/xxd
sudo: /usr/bin/xxd: command not found
root@iPhone ~ [1]# sudo busybox /usr/bin/xxd
sudo: unable to execute /bin/busybox: Exec format error
root@iPhone ~ [1]# sudo busybox
sudo: unable to execute /bin/busybox: Exec format error
root@iPhone ~ [1]# busybox
Failed to execute process '/bin/busybox'. Reason:
exec: unknown error (errno was 8)
The file '/bin/busybox' is marked as an executable but could not be run by the operating system.
root@iPhone ~ [125]# which busybox
Failed to execute process '/usr/bin/which'. Reason:
exec: unknown error (errno was 8)
The file '/usr/bin/which' is marked as an executable but could not be run by the operating system.
root@iPhone ~ [125]# which which
Failed to execute process '/usr/bin/which'. Reason:
exec: unknown error (errno was 8)
The file '/usr/bin/which' is marked as an executable but could not be run by the operating system.
root@iPhone ~ [125]# ed /usr/bin/lesss
Failed to execute process '/bin/ed'. Reason:
exec: unknown error (errno was 8)
The file '/bin/ed' is marked as an executable but could not be run by the operating system.
root@iPhone ~ [125]# dmesg
[    0.000000] 34 stub syscall 375
               529 stub syscall 375
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               569 stub syscall 375
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32
               pollnval 71 flags 4 events 3 revents 32

               805 stub syscall 3

**Comment by 62f** [comment]
Now zsh is also complaining!

`root@iPhone ~ [125]# exit`
`iPhone0 user root@Tue 8_ 7:52PM~(/root)-zsh:reboot`
`zsh: exec format error: reboot`

**Comment by tbodt** [comment]
Could you export this filesystem and send it to me?

**Comment by 62f** [comment]
While attempting to `exit` from zsh as root, caused an immediate(eg. in an unprecedented fashion) popup to appear: ![image](https://user-images.githubusercontent.com/68332197/101535114-267b6300-3966-11eb-89c5-e5575aee0712.jpeg)

**Comment by 62f** [comment]
This is only another facet of issue #889.

**Comment by 62f** [comment]
#!/issue/close

**Comment by domvet-1zunru-Zozzov** [comment]
https://github.com/ish-app/ish/issues/1108#issuecomment-742722826

**Comment by domvet-1zunru-Zozzov** [comment]
<details><summary>Details</summary>
<p>

[]() 

</p>
</details>

**Comment by 62f** [comment]
Yeah
