### ISSUE TITLE
No Text Displayed on iOS 14.2

### ISSUE THREAD

**Issue by iamrecursion** [ish-app/ish#1112]
I just did a build from `0939889` and Im not seeing any text showing up in the terminal. A quick bisect shows that the issue seems to start with the hterm update in `c5c52d5b4e9e85f20e0cb47ceed540750298a092`.

**Comment by tbodt** [comment]
Can you check for errors in the JavaScript console? Enable settings > safari > advanced > web inspector, then follow the instructions there to inspect term.html. You may have to click reload to see the errors.

**Comment by iamrecursion** [comment]
I'm seeing the following.

```
[Error] Unhandled Promise Rejection: Error: Missing or invalid argument: onInit
	(anonymous function) (hterm_all.js:112)
	(anonymous function) (term.js:3)
	asyncFunctionResume
	(anonymous function) (term.js:2)
```

**Comment by iamrecursion** [comment]
Ah, it looks like this was my issue. I'd not run `git submodule update --recursive` on my branch after merging changes from `master`. All seems to work now. Sorry for the noise.
