### ISSUE TITLE
Incompatible with DNS from Huawei Router model HG658d

### ISSUE THREAD

**Issue by cypr3ss** [ish-app/ish#1113]
![the IO](https://i.imgur.com/dnCk9Qd.jpg)
same errors happen when using `apk upgrade` or `apk update`

might also be an error with the cdn, but I just checked & nothing out of the ordinary

**Comment by gitdev-bash** [comment]
Well from what I see here it could be that iSH does not have a internet connection or that the cdn Webserver of alpine linux is blocked in your environment. The reason can be that you have to use a proxy (that iSH does not use) , your internet connection is down or that your isp or your local network administrator blocked the cdn server.
Check by pinging the server: `ping dl-cdn.alpinelinux.org`
If the server answers it’s a local Problem with your Installation.
:-)

**Comment by cypr3ss** [comment]
`ping: bad address 'dl-cdn.alpinelinux.org`
i've no idea at this point.

checked router settings, nothing outta the usual. same with device settings; no proxy config, internet connection's good.

i doubt that my isp blocked the domain 'cause it worked last time i checked (two/three weeks ago)

i suppose it has to do with the installation or something; accessing the domain normally (as in through a browser) yields no odd results

**Comment by tbodt** [comment]
This could be a DNS configuration bug. Can you ping IP addresses? If so, what's the contents of /etc/resolv.conf? Try pointing it to some other nameserver such as 1.1.1.1.

**Comment by cypr3ss** [comment]
![image](https://user-images.githubusercontent.com/39476773/101732540-fbd2fc80-3a82-11eb-9fea-6930a265e8a6.jpeg)
pinging goes well

![image](https://user-images.githubusercontent.com/39476773/101732556-055c6480-3a83-11eb-8278-612409722a5f.jpeg)
gonna try doing the 1.1.1.1

![image](https://user-images.githubusercontent.com/39476773/101732957-a64b1f80-3a83-11eb-9733-ef26934433f2.jpeg)
well isn't that fun.... why tho..? anyway, i guess that's solved.

thanks!

**Comment by cypr3ss** [comment]
wait no

i closed the app, then opened it again cause i forgot something, then the issue returned
![image](https://user-images.githubusercontent.com/39476773/101735930-3ab78100-3a88-11eb-90ab-f8da4cd2aac6.jpeg)

apparently the file can't quite be permanently updated. cat'ing the file shows the old ip.s. ;-;

**Comment by gitdev-bash** [comment]
Try running this as root :`echo "1.1.1.1" > /etc/hostname && hostname -F /etc/hostname`
Should fix i:-)

**Comment by cypr3ss** [comment]
![image](https://user-images.githubusercontent.com/39476773/101806444-965e2a80-3ad9-11eb-939d-5b2584b1157c.jpeg)
not quite working :/

maybe it's just me not knowing how to run as root (i cd'd into "/root")

**Comment by saagarjha** [comment]
I suspect this is because we unconditionally write nameservers on app startup? @tbodt, ideas on what we should be doing in this situation?

**Comment by cypr3ss** [comment]
also, using .bashrc to do the job can't do the job exactly.
![image](https://user-images.githubusercontent.com/39476773/101844810-e4dbeb00-3b12-11eb-9210-e812e2fbaa44.jpeg)

though echo'ing the lines into the file normally does seem to work
![image](https://user-images.githubusercontent.com/39476773/101845041-51ef8080-3b13-11eb-94f1-f8e83fd52019.jpeg)

**Comment by gitdev-bash** [comment]
You know that to run as root you have to Type `su -`

**Comment by saagarjha** [comment]
You're already root by default when you start iSH.

**Comment by gitdev-bash** [comment]
And I found this online:

> You can solve the problem by installing the dhclient package. For the last time enable Google's DNS servers by runing for the last time:

> `sudo su "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"`

> Then run this cocktail of commands:

> `sudo apk update && sudo apk upgrade && sudo apk add dhclient`

> In order to get the fresh packages and install the dhclient. Then configure the /etc/dhcp/dhclient.conf and put the following:

option rfc3442-classless-static-routes code 121 = array of unsigned integer 8;

send host-name = gethostname();
request subnet-mask, broadcast-address, time-offset, routers,
        domain-name, domain-name-servers, domain-search, host-name,
        dhcp6.name-servers, dhcp6.domain-search, dhcp6.fqdn, dhcp6.sntp-servers,
        netbios-name-servers, netbios-scope, interface-mtu,
        rfc3442-classless-static-routes, ntp-servers;

prepend domain-name-servers 8.8.8.8, 8.8.4.4;

> And restart the networking:
`sudo rc-service networking restart`

> Optionally you can confirm that works if you run:

> `sudo reboot`

> In either case you can confirm that dns is resolved by pinging the google.

`ping google.com`

**Comment by gitdev-bash** [comment]
New title: DNS resolv.conf config broken

**Comment by tbodt** [comment]
@cypr3ss What ISP are you using? What type of connection (wireless, cellular, etc)?

**Comment by cypr3ss** [comment]
Provider' name's Telmex (I live in Mexico). Wireless connection, Huawei Router model HG658d

**Comment by tbodt** [comment]
My guess is this is an incompatibility between musl and your router. Unfortunately /etc/resolv.conf gets overwritten every time you start the app, so changing it is really only a temporary solution.

**Comment by cypr3ss** [comment]
huzzah! I managed to find the problem.

![image](https://user-images.githubusercontent.com/39476773/101872649-399b5800-3b4b-11eb-800b-dbb82cdcabbe.jpeg)
why ye little-!

![image](https://user-images.githubusercontent.com/39476773/101873228-318fe800-3b4c-11eb-8f94-652dbb8e78ec.jpeg)
that should do it...

![image](https://user-images.githubusercontent.com/39476773/101873248-38b6f600-3b4c-11eb-8fe2-42443e2bd49e.jpeg)
yup, that went better than expected!
#
fun.
anyway, i do think there's some funky business going on with the whole write-ins at startup, so that's a suggestion: don't force nameserver writes at startup, maybe a small config of those at first use

**Comment by tbodt** [comment]
It's necessary to overwrite /etc/resolv.conf, or DNS won't work at all. Not sure why I didn't think of changing system DNS settings here.

[Someone on reddit](https://www.reddit.com/r/ish/comments/k9yp00/offer_of_development_help_is_anybody_working_on) had the idea of writing a DNS proxy to run on localhost; this could fix any situations where DNS works with iOS and not musl, including mDNS. That would be a separate issue though.

**Comment by cypr3ss** [comment]
i think i know why the problem arose: 192.168.1.254 is the local pingback address to the router, which is then supposed to forward to an external dns ip (in this case: 189.233.13.5). The thing kinda crosswired somewhere between the request to the router & the request to the dns servo (or my 3rd world internet provider's dns is just very useless).
