### ISSUE TITLE
IPv6 network issues

### ISSUE THREAD

**Issue by bqrs01** [ish-app/ish#1124]
I'm not sure if this is the right place for this but the background is as follows.

On my local network, I have my router which provides access to IPv4 internet and also on the same network a Raspberry Pi which provides access to a local IPv6 intranet (no internet).

The Raspberry Pi acts as a router for the IPv6 network, and allocates addresses using radvd making it possible for devices on the network to connect to servers that are on this local IPv6 network.

The issue is that iSH takes this IPv6 network route to be the default route for internet requests therefore I experience that `ping` requests don't work unless I specify `-4` as well and tools like wget, curl and apk don't work at all (even when trying to force IPv4 only).

Is it possible to ignore the default IPv6 route in iSH?

What I'm looking for is for applications to recognize that there is no internet connectivity on IPv6 and to then fallback to IPv4. But it is clear that this is not happening.

**Comment by tbodt** [comment]
POSIX requires you to specify whether you want IPv4 or IPv6 every time you create a socket, and what programs do here is beyond my control. iSH always passes the IPv4/IPv6 preference directly to iOS. But here's what normally happens IIRC: musl sends simultaneous A and AAAA requests to DNS servers listed in /etc/resolv.conf. If the AAAA request returns an address, it uses IPv6, otherwise it uses IPv4.

I would expect pinging explicit IPv4 addresses to work fine. If the DNS is configured with only IPv6, that would be a problem. What's in your /etc/resolv.conf?

**Comment by bqrs01** [comment]
> POSIX requires you to specify whether you want IPv4 or IPv6 every time you create a socket, and what programs do here is beyond my control. iSH always passes the IPv4/IPv6 preference directly to iOS. But here's what normally happens IIRC: musl sends simultaneous A and AAAA requests to DNS servers listed in /etc/resolv.conf. If the AAAA request returns an address, it uses IPv6, otherwise it uses IPv4.
> 
> 
> 
> I would expect pinging explicit IPv4 addresses to work fine. If the DNS is configured with only IPv6, that would be a problem. What's in your /etc/resolv.conf?

In /etc/resolv.conf, I have `nameserver 2001:xxxx:xxxx:1::1`, which points to the Raspberry Pi's DNS server which returns both A and AAAA results.

If I were to make it so that the DNS server only returns A queries, would it then only prefer IPv4?

**Comment by tbodt** [comment]
Probably, but it seems weird to me that it would be returning both A and AAAA results for domains outside of your network. If it's doing that, then it could be a good idea to fix that instead, so it returns A for outside domains and AAAA for LAN domains.

**Comment by bqrs01** [comment]
Well, it seems that changing it so that the DNS server returns only A for outside domains indeed fixes the issue I was facing. Thank you @tbodt.
