### ISSUE TITLE
URLs in repositories

### ISSUE THREAD

**Issue by lijhello** [ish-app/ish#1127]
```
iPad:~# cat /etc/apk/repositories 
file:///ish/apk/main
iPad:~# 
```

- Can we still put URLs in repositories file?
- What version should we use? v3.xx, v3.11, v3.12

```
#example: alpine
http://dl-cdn.alpinelinux.org/alpine/v3.12/main
http://dl-cdn.alpinelinux.org/alpine/v3.12/community

#example: mirrors
http://mirrors.aliyun.com/alpine/v3.12/main
http://mirrors.aliyun.com/alpine/v3.12/community
```

**Comment by saagarjha** [comment]
iSH’s default filesystem has a modified repository list, but APK has not been modified. If you find that APK functionality is not working correctly, we would welcome any issues you find.
