### ISSUE TITLE
Missing packages for VNC server

### ISSUE THREAD

**Issue by YeaToast** [ish-app/ish#1131]
```

:~# apk add x11vnc x11vnc-doc xvfb xterm xorg-server xf86-video-dummy i3wm i3status i3l
ock xdpyinfo xdpyinfo-doc i3wm-doc i3lock-doc i3st
atus-doc ttf-dejavu
ERROR: unsatisfiable constraints:
  i3lock (missing):
    required by: world[i3lock]
  i3lock-doc (missing):
    required by: world[i3lock-doc]
  i3status (missing):
    required by: world[i3status]
  i3status-doc (missing):
    required by: world[i3status-doc]
  i3wm (missing):
    required by: world[i3wm]
  i3wm-doc (missing):
    required by: world[i3wm-doc]
  x11vnc (missing):
    required by: world[x11vnc]
  x11vnc-doc (missing):
    required by: world[x11vnc-doc]
  xdpyinfo (missing):
    required by: world[xdpyinfo]
  xdpyinfo-doc (missing):
    required by: world[xdpyinfo-doc]
  xterm (missing):
    required by: world[xterm]

```

**Comment by emkey1** [comment]
I'm assuming you are using a newer version that has /ish.  I'd recommend adding the web repositories to the end of /etc/apk/repositories.  

http://dl-cdn.alpinelinux.org/alpine/v3.12/main
http://dl-cdn.alpinelinux.org/alpine/v3.12/community

If the new mechanism fails for some reason then apk will be able to find the packages out on the web site.

To be clear you should end up with two lines that start 

file:...

With the two lines I specified above following.

**Comment by tbodt** [comment]
Yes, these packages are in the community repo. Next update will add the community repo back automatically.
