### ISSUE TITLE
No backpressure on terminal output leads to OOM

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#1134]
Repro: `cat /dev/zero`

**Comment by tbodt** [comment]
The pendingData queue is growing without bound, and takes about 10 seconds to exceed the available RAM. There should be some rate limit or something on terminal writes to prevent this.

**Comment by 62f** [comment]
iPhone:~# cat file:///dev/zero
cat: 'file:///dev/zero': No such file or directory
iPhone:~# cat file:///dev/zero
cat: 'file:///dev/zero': No such file or directory
iPhone:~# ls /dev/zero -la
crw-rw-rw- 1 root root 1, 5 Dec  9 02:02 /dev/zero

      So I had already tried cat. That’s why i asked in discord @accessing file:/// schemas and detailed the reproduction step using curl as I did, rm /dev/zero & retried accessing it in multiple ways: to be more thorough. I discover additional problems that way.
