### ISSUE TITLE
Workflow for discovery of #1134

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#1135]
I discover additional problems [this] way.

_Originally posted by @62f in https://github.com/ish-app/ish/issues/1134#issuecomment-745750939_
Yet another stub. Problems which occurred from attempts at making a gist using iSH.

iPhone:~# gh
-ash: gh: not found
iPhone:~# apk list git
git-2.26.2-r0 x86 {git} (GPL-2.0-or-later) [installed]

**Comment by tbodt** [comment]
What is the bug?

**Comment by 62f** [comment]
Starting with the fact that git's apk doesn't provide gh, hunting for that functionality is a bitch, "apk search man" is an incomprehensible-long ass list, and then life only gets better when adding man-db. If you'll just wait a while I can make this up. If I don't stub it right away, I'm likely to forget.

**Comment by 62f** [comment]
iPhone:~# apk add man-db
(1/5) Installing groff (1.22.4-r1)
(2/5) Installing less (551-r0)
(3/5) Installing libpipeline (1.5.2-r0)
(4/5) Installing libseccomp (2.4.3-r0)
(5/5) Installing man-db (2.9.1-r0)
Executing busybox-1.31.1-r19.trigger
Executing man-db-2.9.1-r0.trigger
Processing manual pages under /usr/share/man...
Updating index cache for path `/usr/share/man/man5'. Wait...mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man5/locale.5.gz: whatis parse for locale(5) failed
Updating index cache for path `/usr/share/man/man3'. Wait...mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man3/newlocale.3.gz: whatis parse for newlocale(3) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man3/mbstowcs.3.gz: whatis parse for mbstowcs(3) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man3/newlocale.3.gz: whatis parse for freelocale(3) failed
OK: 1488 MiB in 452 packages
Updating index cache for path `/usr/share/man/man8'. Wait...mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man8/iconvconfig.8.gz: whatis parse for iconvconfig(8) failed
Updating index cache for path `/usr/share/man/man1'. Wait...mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man1/iconv.1.gz: whatis parse for iconv(1) failed
Updating index cache for path `/usr/share/man/man7'. Wait...mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-15.7.gz: whatis parse for latin9(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-8.7.gz: whatis parse for iso-8859-8(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-10.7.gz: whatis parse for iso_8859_10(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-15.7.gz: whatis parse for iso-8859-15(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-7.7.gz: whatis parse for iso_8859-7(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-9.7.gz: whatis parse for latin5(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-16.7.gz: whatis parse for latin10(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-4.7.gz: whatis parse for iso-8859-4(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-2.7.gz: whatis parse for iso_8859_2(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-3.7.gz: whatis parse for iso_8859_3(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-5.7.gz: whatis parse for iso-8859-5(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-4.7.gz: whatis parse for latin4(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-6.7.gz: whatis parse for iso_8859-6(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-11.7.gz: whatis parse for iso_8859_11(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-14.7.gz: whatis parse for iso-8859-14(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/cp1251.7.gz: whatis parse for cp1251(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-9.7.gz: whatis parse for iso-8859-9(7) failed
mandb: warning: /usr/share/man/man7/iso_8859-16.7.gz: whatis parse for iso_8859-16(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-14.7.gz: whatis parse for latin8(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-3.7.gz: whatis parse for latin3(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-2.7.gz: whatis parse for iso-8859-2(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-4.7.gz: whatis parse for iso_8859_4(7) failed
mandb: warning: /usr/share/man/man7/iso_8859-11.7.gz: whatis parse for iso_8859-11(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-13.7.gz: whatis parse for iso-8859-13(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-16.7.gz: whatis parse for iso_8859_16(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-1.7.gz: whatis parse for iso_8859-1(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-8.7.gz: whatis parse for iso_8859_8(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-9.7.gz: whatis parse for iso_8859_9(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-11.7.gz: whatis parse for tis-620(7) failed
mandb: warning: /usr/share/man/man7/iso_8859-10.7.gz: whatis parse for iso_8859-10(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/charsets.7.gz: whatis parse for charsets(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-5.7.gz: whatis parse for iso_8859_5(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-3.7.gz: whatis parse for iso-8859-3(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-2.7.gz: whatis parse for latin2(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-6.7.gz: whatis parse for iso_8859_6(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/koi8-u.7.gz: whatis parse for koi8-u(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-1.7.gz: whatis parse for latin1(7) failed
mandb: warning: /usr/share/man/man7/iso_8859-3.7.gz: whatis parse for iso_8859-3(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-14.7.gz: whatis parse for iso_8859_14(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-11.7.gz: whatis parse for iso-8859-11(7) failed
mandb: warning: /usr/share/man/man7/iso_8859-13.7.gz: whatis parse for iso_8859-13(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-15.7.gz: whatis parse for iso_8859_15(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-10.7.gz: whatis parse for iso-8859-10(7) failed
mandb: warning: /usr/share/man/man7/iso_8859-2.7.gz: whatis parse for iso_8859-2(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-1.7.gz: whatis parse for iso-8859-1(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-7.7.gz: whatis parse for iso_8859_7(7) failed
mandb: warning: /usr/share/man/man7/iso_8859-5.7.gz: whatis parse for iso_8859-5(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/cp1252.7.gz: whatis parse for cp1252(7) failed
mandb: warning: /usr/share/man/man7/iso_8859-15.7.gz: whatis parse for iso_8859-15(7) failed
mandb: warning: /usr/share/man/man7/iso_8859-9.7.gz: whatis parse for iso_8859-9(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-6.7.gz: whatis parse for iso-8859-6(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-13.7.gz: whatis parse for latin7(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-10.7.gz: whatis parse for latin6(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/armscii-8.7.gz: whatis parse for armscii-8(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/koi8-r.7.gz: whatis parse for koi8-r(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-7.7.gz: whatis parse for iso-8859-7(7) failed
mandb: warning: /usr/share/man/man7/iso_8859-8.7.gz: whatis parse for iso_8859-8(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-1.7.gz: whatis parse for iso_8859_1(7) failed
mandb: warning: /usr/share/man/man7/iso_8859-14.7.gz: whatis parse for iso_8859-14(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-16.7.gz: whatis parse for iso-8859-16(7) failed
mandb: iconv_open ("UTF-8//IGNORE", "UTF-8"): Invalid argument
mandb: warning: /usr/share/man/man7/iso_8859-13.7.gz: whatis parse for iso_8859_13(7) failed
mandb: warning: /usr/share/man/man7/iso_8859-4.7.gz: whatis parse for iso_8859-4(7) failed
done.
Checking for stray cats under /usr/share/man...
Checking for stray cats under /var/cache/man...
Processing manual pages under /usr/share/man/it...
Updating index cache for path `/usr/share/man/it/man1'. Wait...done.
Checking for stray cats under /usr/share/man/it...
Checking for stray cats under /var/cache/man/it...
12 man subdirectories contained newer manual pages.
3280 manual pages were added.
0 stray cats were added.
0 old database entries were purged.

**Comment by 62f** [comment]
After an epidemic of updates, chicken wire bits and bailing twine, warnings and errors alike- became non reproducible.
