### ISSUE TITLE
how do i install the enlightenment window manager?

### ISSUE THREAD

**Issue by YeaToast** [ish-app/ish#1136]

**Comment by 62f** [comment]
To properly deliver such a request you would need a link to the GitHub docs for guidelines on how to fill out an issue with the iSH Wiki. This is GitHub’s site which is designed for contributors reporting bugs, not straightforward procedural details like stackoverflow-style assistance might provide. There should be links to two other more suitable iSH help forums in the config menus of iSH app: discord, twitter. Don’t expect too much of a straightforward fix here for personal tragedies such as your own.

**Comment by tbodt** [comment]
You may be interested in https://pkgs.alpinelinux.org/packages
