### ISSUE TITLE
OBCONF Missing

### ISSUE THREAD

**Issue by YeaToast** [ish-app/ish#1159]
Openbox' configurator is missing from alpine repos. Please help

**Comment by 62f** [comment]
Alpine’s contributions are made through gitlab, but don’t worry you’re already one step closer: openID will let you use the same login as here.

**Comment by tbodt** [comment]
Openbox can be found in the community repo. There's an iSH bug where these packages are not available; work around it with `echo file:///ish/apk/community >> /etc/apk/repositories`.
