### ISSUE TITLE
page fault on 0x8341be86 at 0x5655a345

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#1176]
```
# git clone git://git.openbox.org/dana/obconf

cd ./obconf

apk add gnome-session

chmod +x ./bootstrap

./bootstrap; ./configure; make

/usr/bin/msgmerge --update da.po obconf.pot
............make[2]: *** [Makefile:204: da.po] Segmentation fault
```

**Comment by Mnpn** [comment]
Hi, I've just ran these steps on iSH 1.3 (which we've recently released) and it appears to work, so I'll go ahead and mark this as resolved.

```
# /usr/bin/msgmerge --update po/da.po po/obconf.pot
.................................. done.
```

Please give it another try after updating, and if you're still running into problems with this, please let us know & feel free to re-open this issue!
