### ISSUE TITLE
fnstsw/fcmov needed by alpine glibc

### ISSUE THREAD

**Issue by econcz** [ish-app/ish#1182]
Good evening. I'm sorry to bring this topic up again but this is a **different question** compared to the ones posted. I exported the iSH "default" filesystem, successfully installed glibc 32-bit on it and tested it in Docker.
It seems to be working as a Docker container, here's a published version `docker pull econcz/x86-alpine-glibc:ish-glibc-3.12` (I successfully launched glibc-dpeendent software like miniconda or calibre in the image-based container) and you can download, tar.gz it and import it into iSH, it will work. However, iSH still produces **illegal instructions**. Does it mean the arm64 processor doesn't support glibc-based software in iSH at all?

**PS** Once again, I'm not looking forward to install glibc on iSH's Alpine Linux, I already did that and it works in Docker but not on iPad.

**Comment by tbodt** [comment]
Which illegal instruction? To quote the issue template:
> If this is a "Bad system call", "Illegal instruction", or "Segmentation fault", run `dmesg` to get a dump of the log messages and include the relevant output.

**Comment by econcz** [comment]
Just "Illegal instruction"

**Comment by tbodt** [comment]
Run `dmesg` and there will be more info.

**Comment by econcz** [comment]
For example,
iPad:~# stata
stata: /usr/lib/libstdc++.so.6: no version information available (required by stata)
stata: /usr/lib/libstdc++.so.6: no version information available (required by stata)
stata: /usr/lib/libstdc++.so.6: no version information available (required by stata)
stata: /usr/lib/libstdc++.so.6: no version information available (required by stata)
Illegal instruction
iPad:~# dmesg
4 illegal instruction at 0x9439b2b: dd 3c 24 0f b7 0c 24 23 

or
iPad:/opt/calibre# ./calibre-serve  
Illegal instruction
iPad:/opt/calibre# dmesg
4 illegal instruction at 0xf7c2dd56: db d1 dd d9 dd 1c 24 e8

**Comment by tbodt** [comment]
Thanks, looks like some unimplemented floating point instructions.
dd3c24: fnstsw [esp]
db d1: fcmovnbe st(0), st(1)

**Comment by econcz** [comment]
Also found 1 “Bad system call”
```
iPad :~# geckodriver
Bad system call
iPad:~# dmesg
5 missing syscall 403
7 missing syscall 403
```

**Comment by tbodt** [comment]
This issue is very broad (all possible things on glibc) so I'm going to narrow it to the floating point instructions. Please open a separate issue for each broken program.

**Comment by econcz** [comment]
Did it, thanks!

**Comment by tbodt** [comment]
Thanks! I'll close this issue now as it's now duplicated by #1183 and #1184.
