### ISSUE TITLE
IO Errors even after setting nameserver

### ISSUE THREAD

**Issue by 8thHalfHour** [ish-app/ish#1188]
I have just installed the TestFlight version of iSH, and I am getting `IO Error` on every `app add`(`apk update` works as expected, as does `app search`). I don’t have the `fetch command, either apparently, so I cannot try the `fetch` example in the Troubleshooting section of the wiki. I did, however, update the nameserver to Google’s `8.8.8.8`, as recommended, though it does not seem to have fixed anything. Any help is appreciated. Thank you.

**Comment by tbodt** [comment]
I/O error can mean many things. Does wget work for you?

**Comment by 8thHalfHour** [comment]
Hi, there. The command `wget` does function. Using the latest beta from Testflight, I can `apk update` and I can see packages when I search for them. I can ping all the things I try to ping with no loss. When I try to install something, though, with `apk add`, the packages and/or dependencies are downloaded and it tries to install. One-by-one, they all fail with IO ERROR. No packages are able to be installed. 

With the store version, `apk update` results in the app crashing -- every time. I have tried removing the app, restarting the iPad Pro, and reinstalling. But nothing changes. I'll switch to the iPad now and post the crash log.

**Comment by 8thHalfHour** [comment]
Okay, here is the crash log:

———

[https://gist.github.com/8thHalfHour/15cb718e516d0a1855b01cd476b46b22](url)

**Comment by 8thHalfHour** [comment]
An update: it appears to be related to other issues surrounding IO Errors. Turns out, I just had to follow the instructions here:

https://github.com/gliderlabs/docker-alpine/issues/386#issuecomment-376784936

I changed the version to 3.12, the version I am running. Now it's working fine. Hope this helps someone else.

**Comment by lakemike** [comment]
I also got „IO ERROR“ with apk even if resolv.conf was changed to 8.8.8.8
I could solve it with “wget -qO- http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86/apk-tools-static-2.10.6-r0.apk | tar -xz sbin/apk.static && ./sbin/apk.static add apk-tools && rm sbin/apk.static” (apk reinstallation)
