### ISSUE TITLE
> Repro steps: edit /usr/bin/pmap with nano to remove all the #commented-out features.

### ISSUE THREAD

**Issue by wachabaha** [ish-app/ish#1205]
> Repro steps: edit /usr/bin/with nano to remove all the #commented-out features.
> (write out) pmap && ./pmap
> on
> iSH 1.1.1(Build 91)

__Originally posted by @wachabaha in https://github.com/ish-app/ish/issues/1198#issuecomment-751314096__

**Comment by 62f** [comment]
![image](https://user-images.githubusercontent.com/68332197/104123169-7fe50200-5317-11eb-8c76-78b80d3a3af9.jpeg)Something's not quite right with this quote(see yellow hilight). Reference in New Issue automatically copies, so this was either an edited-in mistake or rare copying bug.
