### ISSUE TITLE
Disable screen turn off

### ISSUE THREAD

**Issue by JulianKahnert** [ish-app/ish#1212]
First of all: Thank you so much for this awesome project! This terminal app is awesome and the iOS FileProvider integration is a great fit 🙂 

While using the app, one thing could be improved (with relative less effort !?). When starting a long running process the screen of the device turns off after some time. This can be prevented by disabling the [idle timer](https://stackoverflow.com/a/28332647/10026834):
```objc
[[UIApplication sharedApplication] setIdleTimerDisabled: YES];
```

What do you think about this? Should I open a pull request for this?

**Comment by tbodt** [comment]
This already exists in the settings: "Disable Screen Dimming".i

**Comment by JulianKahnert** [comment]
Awesome! thx @tbodt

**Comment by StefanLobbenmeier** [comment]
@tbodt any chance this can be renamed to “Keep screen turned on”? That would make it a lot clearer, I actually did not understand what the option was going to do before I searched for it

**Comment by tbodt** [comment]
@StefanLobbenmeier Sounds like a good idea, please open a new issue so I don't forget
