### ISSUE TITLE
How to install php 7.4+?

### ISSUE THREAD

**Issue by felipereisdev** [ish-app/ish#1249]
I tried to install, but I have problems with the nomenclature (x86). The repository is x86_64.

**Comment by sdhoward** [comment]
This seems like an issue where alpine 3.12 has an older version but you want the [version that's only in alpine 3.13](https://pkgs.alpinelinux.org/packages?name=php7&branch=v3.13&repo=community&arch=x86).

Try the advice in [this comment](https://github.com/ish-app/ish/issues/1425#issuecomment-850969964), which is basically to download the [alpine 3.13 mini root filesystem](https://alpinelinux.org/downloads/) and open it in ish. Then use that to install newer php.

Hope to hear back if it's working or not.

**Comment by felipereisdev** [comment]
> This seems like an issue where alpine 3.12 has an older version but you want the [version that's only in alpine 3.13](https://pkgs.alpinelinux.org/packages?name=php7&branch=v3.13&repo=community&arch=x86).
> 
> Try the advice in [this comment](https://github.com/ish-app/ish/issues/1425#issuecomment-850969964), which is basically to download the [alpine 3.13 mini root filesystem](https://alpinelinux.org/downloads/) and open it in ish. Then use that to install newer php.
> 
> Hope to hear back if it's working or not.

Thank you for your help. It's working. Problem solved. Now I will try to install mysql.
