### ISSUE TITLE
Why does ish use i686 emulation rather than running native arm64 code directly?

### ISSUE THREAD

**Issue by rikka0w0** [ish-app/ish#1250]
Out of curiosity, why does ish use i686 emulation rather than allowing user to run native arm64 code directly?

`uname -a` in ish I get: "i686" but in native shell emulator I get "arm64".

Regards,

**Comment by saagarjha** [comment]
We have a FAQ entry for you: https://github.com/ish-app/ish/wiki/FAQ#q-why-does-ish-not-emulate-arm-or-some-other-architecture :)

**Comment by tbodt** [comment]
There's a bit in the wiki about this: https://github.com/ish-app/ish/wiki/FAQ#q-why-does-ish-not-emulate-arm-or-some-other-architecture
