### ISSUE TITLE
I/O Error for Apple Diagnostics Report

### ISSUE THREAD

**Issue by RowanKaag** [ish-app/ish#1266]
As requested in the latest 93 build.

I was seeing the I/O error yesterday (~20:00 CET @ 6th of February 2021) in iSH 1.1.2 (92). 

The dmesg output is no longer present (probably due to updating to build 93), but the error was showing: “Asset URL has expired”. According to search results it had something to do with the On-Demand Resources. By running the commands below, I was able to fix the message:

——————————————————

umount /ish/apk && rm -rf /ish

printf 'file:///ish/apk/main\nfile:///ish/apk/community\n' > /etc/apk/repositories && tar -xf /ish/apk/main/x86/apk-tools-static-2.10.5-r1.apk -C / && apk.static add apk-tools && rm /sbin/apk.static && apk upgrade

mkdir -p /ish/apk && printf 'file:///ish/apk/main\nfile:///ish/apk/community\n' > /etc/apk/repositories && mount -t apk apk /ish/apk && tar -xf /ish/apk/main/x86/apk-tools-static-2.10.5-r1.apk -C / && apk.static add apk-tools && rm /sbin/apk.static && apk upgrade

(Not working as of this moment, but included commands below to provide full context of steps tried - they may have some relevance)

echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/main/" > /etc/apk/repositories

echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/" >> /etc/apk/repositories 

apk update
apk upgrade

**Comment by tbodt** [comment]
Thanks for your help with this. Do you have a sysdiagnose captured immediately after the problem happens? If not, see if you can make the problem happen again and capture a sysdiagnose.

**Comment by RowanKaag** [comment]
No problem. Unfortunately I (manually) fixed it by pulling the latest APK. Deleted the TestFlight build and downloaded from the App Store: worked without any workaround. Then removed the App Store version and downloaded the TestFlight version: also worked without any workaround. 

In both cases it obviously had to pull the On-Demand Resource in first, but everything seemed to work like it was intended - could install new packages after APK was downloaded. Could the issue 've been temporary on Apple's CDN-side?

**Comment by tbodt** [comment]
Seems there are a lot of workarounds to make the problem go away, but I'd really like apple to fix whatever makes it happens in the first place. It's almost certainly not a temporary CDN problem.

**Comment by 62f** [comment]
Soon am posting decompressed bad/good sysdiagnoses for IOERROR into in a private GitHub project to attach to my new bug report; the tar.gz file is >200Mb & was accepted neither by discord nor GH (<25Mb).
