### ISSUE TITLE
APK I/O Error

### ISSUE THREAD

**Issue by q2r5** [ish-app/ish#1268]
dmesg output: `error fetching ODR main:x86:apk-tools-static-2.10.5-r1.apk: Error Domain=AssetErrorDomain Code=6 "Asset URL has expired" UserInfo={NSDebugDescription=Asset URL has expired}`

Timestamp: `2021-02-07 23:28:07.690223-0500`

[Sysdiagnose](https://www.dropbox.com/s/1wquyoyfwkl7ksu/sysdiagnose_2021.02.07_23-28-43-0500_iPhone-OS_iPhone_18E5140k.tar.gz?dl=0)

**Comment by tbodt** [comment]
Thanks! This is very helpful.

Closing since further updates will go on #1213
