### ISSUE TITLE
tcpdump doesnt work

### ISSUE THREAD

**Issue by mattwhaleyuk** [ish-app/ish#1270]
Really impressed with iSH. Not really much of a programmer, left IT industry a few years ago. Wanted to beable to analyse network packets with tcpdump but i guess doesnt work because of current limited network support etc. Is this something that will be added in future ?

**Comment by lxgr** [comment]
Unfortunately, this seems way out of reach: There is no iOS (userspace-accessible) API for packet capture, as far as I know.

If you're ok with using a Mac, there is `rvictl` which will let you dump all packets on all interfaces via USB.

**Comment by tbodt** [comment]
It may be possible to dump all packets going through your phone by making iSH a VPN app. But this is a bit far out.
