### ISSUE TITLE
Files app hides files/directories starting with .

### ISSUE THREAD

**Issue by repl-mike-roest** [ish-app/ish#1272]
I recently updated my apk packages to 3.13 and since ssh-agent hangs on start.  As part of debugging I wanted to remove my ssh keys to hopefully get past it and get into my shell.  I thought about using the Files app to move my keys out of .ssh.  Unfortunately it appears the Files provider (or Files itself) is not displaying files or folders that start with .  It would be nice to be able to access these.

**Comment by tbodt** [comment]
iSH doesn't filter out files that start with ., this seems to the Files app doing it on its own. Unfortunately there's nothing I can do about this.

**Comment by repl-mike-roest** [comment]
Would it be possible to feed the . files to Files with some kind of substitution ie . maps to something else like _ or __?

**Comment by 62f** [comment]
Yes. iPhone 5s displays all .files without reservation; although iOS 12.5.4 will not allow renames to begin with a period, it  renamed .them to anything else directly from the iSH file provider
