### ISSUE TITLE
Upgraded ISH using apk update / apk upgrade now FiSH no longer works

### ISSUE THREAD

**Issue by StewAlexander-com** [ish-app/ish#1273]
Hi 

I just ran apk update and apk upgrade and now the Friendly Interactive Shell (FiSH) no longer works, can't run ls or clear in it, it just dies

Running Alpine Linux 3.12.0

**Comment by YeaToast** [comment]
Maybe do this?
`echo “ http://dl-cdn.alpinelinux.org/alpine/v3.13/main
http://dl-cdn.alpinelinux.org/alpine/v3.13/community
http://dl-cdn.alpinelinux.org/alpine/edge/main
http://dl-cdn.alpinelinux.org/alpine/edge/community
http://dl-cdn.alpinelinux.org/alpine/edge/testing
http://dl-cdn.alpinelinux.org/alpine/latest-stable/main
http://dl-cdn.alpinelinux.org/alpine/latest-stable/community” > /etc/apk/repositories; apk update; apk upgrade`

**Comment by StewAlexander-com** [comment]
I'm getting a lot of "not found" errors by copying and pasting your answer into ish

**Comment by StewAlexander-com** [comment]
Maybe I'm missing keys or something?

**Comment by StewAlexander-com** [comment]
It's splitting your response by return character, hmm I'll need to take out the new lines

**Comment by tbodt** [comment]
> Maybe do this?
> 
> ```
> echo “http://dl-cdn.alpinelinux.org/alpine/v3.13/main
> http://dl-cdn.alpinelinux.org/alpine/v3.13/community
> http://dl-cdn.alpinelinux.org/alpine/edge/main
> http://dl-cdn.alpinelinux.org/alpine/edge/community
> http://dl-cdn.alpinelinux.org/alpine/edge/testing
> http://dl-cdn.alpinelinux.org/alpine/latest-stable/main
> http://dl-cdn.alpinelinux.org/alpine/latest-stable/community” > /etc/apk/repositories; apk update; apk upgrade
> ```

Having multiple versions of alpine is a bad idea; this is three. You should choose one.

**Comment by 62f** [comment]
I have a workaround. Downgrade ![image](https://user-images.githubusercontent.com/68332197/107835219-b672ca00-6d66-11eb-92f9-528dc25ca6b0.jpeg)to fish-2.6.0-r2 and ```apk add python2```.

**Comment by StewAlexander-com** [comment]
echo “http://dl-cdn.alpinelinux.org/alpine/v3.13/main" >

**Comment by StewAlexander-com** [comment]
Issue now redundant - cant upgrade so opened new ticket

**Comment by StewAlexander-com** [comment]
@62f 

apk add fish-2.6.0-r2 

Gives an error that the Aplinev3.13 main and community repos are unable to select the packages...

Any suggestions?

**Comment by 62f** [comment]
It seems that clear is not the only , after one or two entries of any sort, any of the newer fish versions locks iSH up even ^C, iSH cannot run any commands at all, although the web-based online ```help``` browser seems to work for extended periods. Despite the fact that I was using fish before, an update to musl seems to have nipped off that bud from a very low level, across the board. Even using another prebuilt Alpine mini-filesystems to take the major version of Alpine down to the lowest possible subversion hasn't helped, and I presuppose that htop's only salvation also lies in retrograding by several steps.

**Comment by 62f** [comment]
Just now it did seem as if I have found yet another workaround ```fish & fish``` which ran current versions of ```fish``` fairly well, until discovering any iOS task switch immediately freezes it. The latter versions log a 375 stub in dmesg with every command, while the working version of``` fish ```does not.

**Comment by 62f** [comment]
iSH (1.1.2 build 100) & fresh ```fish```:<details>
still flaky & fried!

**Comment by 62f** [comment]
Booting```fish``` as iSH v101(1.1.2)'s default shell visually registers input yet output-wise remains catatonic.

**Comment by 62f** [comment]
__Implicit example for a non-destructive app-regression : https://github.com/ish-app/ish/issues/1269#issuecomment-781817483__

**Comment by josteink** [comment]
> > Maybe do this?
> 
> > 
> 
> > ```
> 
> > echo “http://dl-cdn.alpinelinux.org/alpine/v3.13/main
> 
> > http://dl-cdn.alpinelinux.org/alpine/v3.13/community
> 
> > http://dl-cdn.alpinelinux.org/alpine/edge/main
> 
> > http://dl-cdn.alpinelinux.org/alpine/edge/community
> 
> > http://dl-cdn.alpinelinux.org/alpine/edge/testing
> 
> > http://dl-cdn.alpinelinux.org/alpine/latest-stable/main
> 
> > http://dl-cdn.alpinelinux.org/alpine/latest-stable/community” > /etc/apk/repositories; apk update; apk upgrade
> 
> > ```
> 
> 
> 
> Having multiple versions of alpine is a bad idea; this is three. You should choose one.

I went with v3.13 and that solved all IO ERROR issues for me.

**Comment by 62f** [comment]
@josteink except that the OP title isn’t simply about fixing apk repository I/O errors, it’s about fish ‘dying’. #1320 is #1213 , not this bug.

**Comment by kgsbowtie** [comment]
Any progress with this? I can confirm that this issue still exists quite frequently, to the point where FiSH is unusable in any normal capacity. 

I have it set as my default shell for the app and simply navigating around the file system with `cd` or checking running processes with `ps` will cause the described behavior. I can’t get it to happen consistently enough to determine a cause, but it definitely happens consistently enough to be unreliable. :(

**Comment by kgsbowtie** [comment]
iSH v1.2.2 (Build 178) and `fish` v3.1.2.
From my testing here’s what else I can determine about this issue:

1. _This error requires a command be run inside `fish`._ Spamming the <kbd>Return</kbd> key without running a command prior never causes `fish` to die/freeze up. Additionally, `fish` doesn’t care if it’s the default shell or if it’s called from another shell, this seems to be consistent regardless of how you enter the `fish` shell.
2. _This error seems to require *multi-line output* from `fish` to occur._ I cannot get this error to occur if I run a command or any series of commands that simply output a single line of text then output the prompt. But if the command outputs multiple lines of text, or if the command outputs text not in a regular output flow—i.e., uses tabs like with `ls`—it seems like that can help cause `fish` to die either soon after or upon execution of that command. The issue also can prop up if you use the tab suggestions and there’s multiple columns and rows of suggestions, but it doesn’t fail if there’s only a single row of suggestions.
3. _This appears possibly be related to how iSH renders outputs or handles text._ I don’t know if that’s true, but there is a difference in when commands are run in `ash` vs `fish`. The prompt in `fish` noticeably takes time to appear while the `ash` prompt is always instantly there with no delay, no matter how fast the <kbd>Return</kbd> key is spammed. I don’t even know if this observation is something noteworthy or not towards this issue, but this ‘delayed prompt’ doesn’t exist in `sh`, `bash`, `zsh`, `dash`, `csh` or `tcsh`. It’s exclusive to `fish`.

**Comment by 62f** [comment]
@kgsbowtie 
<details>Sounds like #1273. Unfortunately I don't know of any way to fix it.
</details>
__Originally posted by @tbodt in https://github.com/ish-app/ish/issues/1287#issuecomment-779505938__

**Comment by StewAlexander-com** [comment]
Any progress, how can I help?

**Comment by Practicalbutterfly5** [comment]
This problem still exists, any progress?

**Comment by Practicalbutterfly5** [comment]
> Still looking on any updates here - @Practicalbutterfly5 are you still seeing the problem?

Yes, s

> Still looking on any updates here - @Practicalbutterfly5 are you still seeing the problem?

Yes still same problem.

**Comment by StewAlexander-com** [comment]
@Practicalbutterfly5 😒, thanks for the update -- keeping this issue open until there's a fix or someone telling us that it can't be, and the reason

**Comment by Mnpn** [comment]
Hi! iSH 1.3 is out which might have resolved this problem (this sounds like the same issue described in #1764 and #2018). Could you please give it a try after updating, and let us know in the case you're still running into issues with fish? Thank you!

**Comment by alin23** [comment]
Tested this for a whole day, with all my fish plugins and customizations. Works perfect 👌 thanks!
