### ISSUE TITLE
apk: command not found

### ISSUE THREAD

**Issue by handlederror** [ish-app/ish#1279]
I installed iSH today, I executed "apk" command but it couldn't find the command. The reason why I executed apk command is I thought apk is the package manager for iSH. Because in some issues (on GitHub) people talk something called "apk"? I'm sure it's not Android's APK thing. Please help me I can't do anything with iSH except running some shell scripts which are even can't run because there is no BASH, there is only ASH.

**Comment by saagarjha** [comment]
How did you install iSH? Did you get any particular errors? iSH ships with apk so it should be available out of the box…

**Comment by handlederror** [comment]
I installed from the app store. I didn't get any errors while installing/after installing.

**Comment by handlederror** [comment]
I reinstall iSH and it somehow worked. Anyways thank you, you can close the issue. (I'm on GitHub mobile I can't close sorry. 🖐)
