### ISSUE TITLE
Cannot get homebrew to install

### ISSUE THREAD

**Issue by geekalert** [ish-app/ish#1281]
I am using the latest Testflight version of ISH (v1.1.2 build 98)

I have been attempting to try homebrew (linuxbrew) on iSH for the past month, with no joy. I have scoured hundreds of posts and  issues trykng to find solutions, including those in this repo. The most significant sources I have used are:

- [Install Linuxbrew on Alpine Linux](https://github.com/Linuxbrew/brew/wiki/Alpine-Linux)
- [Homebrew installation crashes ruby #715i](https://github.com/ish-app/ish/issues/715)
- [docker/alpine/Dockerfile](https://github.com/Linuxbrew/docker/blob/master/alpine/Dockerfile)
- [Installation on Alpine linux #839](https://github.com/Linuxbrew/brew/issues/839)
- [Homebrew on Linux](https://docs.brew.sh/Homebrew-on-Linux)
- [Dockerfile for alpine not working - docker](https://www.gitmemory.com/issue/Linuxbrew/docker/83/668884416)

The error:

```
iPadAir2:~# PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
iPadAir2:~# su - linuxbrew
iPadAir2:~$ whoami
linuxbrew
iPadAir2:~$ echo $SHELL
/bin/bash
iPadAir2:~$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
musl libc (i386)
Version 1.2.2
Dynamic Program Loader
Usage: /lib/ld-musl-i386.so.1 [options] [--] pathname
Homebrew requires Ruby 2.6 which was not found on your system.
Homebrew portable Ruby requires Glibc version 2.13 or newer,
and your Glibc version is too old.
See https://docs.brew.sh/Homebrew-on-Linux#requirements
Install Ruby 2.6 and add its location to your PATH.
iPadAir2:~$ which ruby
/usr/bin/ruby
iPadAir2:~$ ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [i586-linux-musl]
```

I have attempted putting the path to ruby in the linuxbrew user's `.profile` file as well in `/etc/profile.d` but nothing changes -- even when sourcing those files directly.

The list installed packages:

```
abuild
alpine-baselayout
alpine-conf
alpine-keys
alpine-sdk
apk-tools
attr
bash
bash-completion
bash-completion-doc
bash-doc
binutils
blkid
brotli-libs
build-base
busybox
ca-certificates
ca-certificates-bundle
cfdisk
coreutils
curl
eudev-libs
expat
fakeroot
file
findmnt
findutils
fortify-headers
g++
gcc
gdbm
git
git-bash-completion
gmp
gmp-dev
grep
gzip
hexdump
hwids-pci
hwids-usb
ifupdown-ng
isl22
less
libacl
libatomic
libattr
libblkid
libc-dev
libc-utils
libc6-compat
libcap-ng
libcrypto1.1
libcurl
libeconf
libfdisk
libffi
libgcc
libgmpxx
libgomp
libgphobos
libmagic
libmount
libsmartcols
libssl1.1
libstdc++
libtls-standalone
libucontext
libucontext-dev
libusb
libuuid
lsblk
lzip
make
mcookie
mpc1
mpfr4
musl
musl-dev
musl-utils
nano
nano-doc
ncurses
ncurses-libs
ncurses-terminfo-base
nghttp2-libs
openrc
openrc-bash-completion
openssl
partx
patch
pciutils
pciutils-libs
pcre
pcre2
pkgconf
readline
ruby
ruby-bigdecimal
ruby-bundler
ruby-dbg
ruby-dev
ruby-etc
ruby-fiddle
ruby-full
ruby-gdbm
ruby-io-console
ruby-irb
ruby-json
ruby-libs
ruby-minitest
ruby-net-telnet
ruby-power_assert
ruby-rake
ruby-rdoc
ruby-sdbm
ruby-test-unit
ruby-webrick
ruby-xmlrpc
s6-ipcserver
scanelf
setpriv
sfdisk
skalibs
ssl_client
sudo
sudo-doc
tar
usbutils
util-linux
util-linux-bash-completion
util-linux-openrc
utmps
utmps-openrc
yaml
zlib
```

**Comment by saagarjha** [comment]
As the error mentions, this seems to require glibc, which is unlikely to be supported anytime soon. So you're probably going to have to wait a bit :(

**Comment by geekalert** [comment]
I thought that might be it, but I had seen others seem to pull it off. If Alpine cannot support glibc, then wouldn't a Dockerfile with the exact same instructions also fail? They don't, though, and so the only thing I can conclude is that something is different with the iSH implementation of Alpine. The error also mentions Ruby not being in the path, but it is. (The Dockerfiles, btw, do not appear to install glibc, either.)

**Comment by emkey1** [comment]
I think it's less about Alpine not being able to support glibc and more about iSH not supporting glibc.  

iSH is not a complete emulation of a Linux kernel.  What it does support is the most important stuff to get musl linked binaries to work. 

When you containerize something in iSH you are not changing the fact that iSH is lacking some things needed to support glibc.

**Comment by geekalert** [comment]
Aha! Well, that makes more sense, and I appreciate the explanation. I can let this go now! 😜

**Comment by geekalert** [comment]
Aha! Well, that makes more sense, and I appreciate the explanation. I can let this go now! 😜
