### ISSUE TITLE
Alpine Linux not upgrading

### ISSUE THREAD

**Issue by StewAlexander-com** [ish-app/ish#1285]
I added the following to the repo file

iPhone:/etc# cat /etc/apk/repositories 
http://dl-cdn.alpinelinux.org/alpine/v3.13/main
http://dl-cdn.alpinelinux.org/alpine/v3.13/community

Ran apk update && apk upgrade && reboot 

And I still see this:

iPhone:/etc# cat alpine-release 
3.12.0

Now fish, & htop don't work

Ideas?

**Comment by tbodt** [comment]
/etc/alpine-release does not change with alpine upgrades, because it's in alpine-base instead of alpine-baselayout. This would be something for alpine to fix.

**Comment by 62f** [comment]
Yes, file an issue for htop's bug.
