### ISSUE TITLE
Fish hanging indefinitely 

### ISSUE THREAD

**Issue by workworksalot** [ish-app/ish#1287]
Every time I try to use “fish shell” it hangs up indefinitely and I have to restart the app. Please advise on a possible fix. I am very green at all of this. I have tried apk fix, reinstalling The app as well as updates, upgrades etc.

**Comment by tbodt** [comment]
Sounds like #1273. Unfortunately I don't know of any way to fix it.

**Comment by 62f** [comment]
iSH v1.2.2 (Build 178) and `fish` v3.1.2.
From my testing here’s what else I can determine about this issue:

1. _This error requires a command be run inside `fish`._ Spamming the <kbd>Return</kbd> key without running a command prior never causes `fish` to die/freeze up. Additionally, `fish` doesn’t care if it’s the default shell or if it’s called from another shell, this seems to be consistent regardless of how you enter the `fish` shell.
2. _This error seems to require *multi-line output* from `fish` to occur._ I cannot get this error to occur if I run a command or any series of commands that simply output a single line of text then output the prompt. But if the command outputs multiple lines of text, or if the command outputs text not in a regular output flow—i.e., uses tabs like with `ls`—it seems like that can help cause `fish` to die either soon after or upon execution of that command. The issue also can prop up if you use the tab suggestions and there’s multiple columns and rows of suggestions, but it doesn’t fail if there’s only a single row of suggestions.
3. _This appears possibly be related to how iSH renders outputs or handles text._ I don’t know if that’s true, but there is a difference in when commands are run in `ash` vs `fish`. The prompt in `fish` noticeably takes time to appear while the `ash` prompt is always instantly there with no delay, no matter how fast the <kbd>Return</kbd> key is spammed. I don’t even know if this observation is something noteworthy or not towards this issue, but this ‘delayed prompt’ doesn’t exist in `sh`, `bash`, `zsh`, `dash`, `csh` or `tcsh`. It’s exclusive to `fish`.

__Originally posted by @kgsbowtie in https://github.com/ish-app/ish/issues/1273#issuecomment-898829745__
