### ISSUE TITLE
Can someone please export the Default iSH file system?

### ISSUE THREAD

**Issue by The-Anonymous-Chicken** [ish-app/ish#1288]
I accidentally deleted it thinking it was another one, and now I always get an error code -2 or k.
And no, I cannot reinstall it. This would really help me out thx.

**Comment by saagarjha** [comment]
You can reinstall the app to get it back.

**Comment by The-Anonymous-Chicken** [comment]
I just said I can’t

**Comment by The-Anonymous-Chicken** [comment]
I can’t I tried that

**Comment by The-Anonymous-Chicken** [comment]
It just won’t install.

**Comment by Deloper2297** [comment]
Here You go man
[default.tar.gz](https://github.com/ish-app/ish/files/5991229/default.tar.gz)

**Comment by The-Anonymous-Chicken** [comment]
Thanks so much

**Comment by tbodt** [comment]
The link is here: https://github.com/ish-app/ish/blob/285cdc574e0909067ca44ba68441aa5a4f52731c/app/iSH.xcconfig#L13
