### ISSUE TITLE
Assembly code run: Permission Denied

### ISSUE THREAD

**Issue by Rishi5813** [ish-app/ish#1290]
I tried to execute assembly code on iSH, it gave a permission denied message -
![2B262430-3B6E-4C02-8A45-C516A749CC57](https://user-images.githubusercontent.com/74538195/108310199-fad3ef00-71d8-11eb-9fb7-8fa6998871be.png)

**Comment by tbodt** [comment]
What is the output of wc -l? You may have to chmod +x the output. Not sure why nasm wouldn't do that though.

**Comment by Rishi5813** [comment]
<img width="1024" alt="Screenshot 2021-02-18 at 11 33 07 AM" src="https://user-images.githubusercontent.com/74538195/108312650-18a35300-71dd-11eb-81a5-354facff5d08.png">
This was the output

**Comment by Rishi5813** [comment]
And the assembly code was:

section .text                   ;section declaration

                                ;we must export the entry point to the ELF linker or
    global  _start              ;loader. They conventionally recognize _start as their
			                          ;entry point. Use ld -e foo to override the default.

_start:

                                ;write our string to stdout

    mov     edx,len             ;third argument: message length
    mov     ecx,msg             ;second argument: pointer to message to write
    mov     ebx,1               ;first argument: file handle (stdout)
    mov     eax,4               ;system call number (sys_write)
    int     0x80                ;call kernel

                                ;and exit

  	mov     ebx,0               ;first syscall argument: exit code
    mov     eax,1               ;system call number (sys_exit)
    int     0x80                ;call kernel

section .data                   ;section declaration

msg db      "Hello, world!",0xa ;our string
len equ     $ - msg             ;length of our string

**Comment by tbodt** [comment]
Sounds like you need to link the program after you assemble it: https://stackoverflow.com/a/4241290
