### ISSUE TITLE
Congrats on being on the First Position on the App Store !

### ISSUE THREAD

**Issue by oudomskn** [ish-app/ish#1296]
Congrats on being on the First Position on the App Store !
![8BF55E9B-33C5-432E-A9FB-8F8813A2A435](https://user-images.githubusercontent.com/74538195/108602623-eeae8400-73c8-11eb-9975-d81ea734bf41.png)

_Originally posted by @Rishi5813 in https://github.com/ish-app/ish/discussions/1295_

**Comment by tbodt** [comment]
Thanks! This is not an issue, so closing.
