### ISSUE TITLE
Can’t perlbrew perl-5.32.1

### ISSUE THREAD

**Issue by mjgardner** [ish-app/ish#1297]
Using iSH 1.1.1 (Build 91) on iOS 14.4 on a iPad Pro (11-inch) (2nd generation).

I've installed bash, gcc, make, and [perlbrew](https://perlbrew.pl/), along with the requisite Perl modules via apk (list below). Trying to run `perlbrew install --verbose perl-5.32.1` via bash, I get at the end:

```
Use which C compiler? [cc]  
/usr/lib/gcc/i586-alpine-linux-musl/9.3.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/lib/gcc/i586-alpine-linux-musl/9.3.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
/usr/lib/gcc/i586-alpine-linux-musl/9.3.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find -lssp_nonshared
collect2: error: ld returned 1 exit status
Uh-oh, the C compiler 'cc' doesn't seem to be working.
 
You seem to have a working gcc, though.

*** However, any setting of the C compiler flags (e.g. for thread support)
*** will be lost.  It may be necessary for you to restart Configure and
*** add -Dcc=gcc to your Configure command line.

Would you like to go ahead and try gcc anyway? [n]  
/usr/lib/gcc/i586-alpine-linux-musl/9.3.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/lib/gcc/i586-alpine-linux-musl/9.3.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
/usr/lib/gcc/i586-alpine-linux-musl/9.3.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find -lssp_nonshared
collect2: error: ld returned 1 exit status
Uh-oh, the C compiler 'cc' doesn't seem to be working.
You need to find a working C compiler.
Either (purchase and) install the C compiler supplied by your OS vendor,
or for a free C compiler try http://gcc.gnu.org/
I cannot continue any further, aborting.
```

Here's a list of packages installed:

```
alpine-baselayout
alpine-conf
alpine-keys
apk-tools
bash
binutils
bison
blkid
busybox
ca-certificates
ca-certificates-bundle
cfdisk
curl
curl-doc
expat
findmnt
gcc
gcc-doc
gdbm
gdbm-dev
git
git-doc
git-perl
gmp
hexdump
isl
jq
libatomic
libblkid
libbz2
libc-utils
libcap-ng
libcrypto1.1
libcurl
libfdisk
libgcc
libgomp
libgphobos
libidn
libidn2
libmount
libsmartcols
libssl1.1
libstdc++
libtls-standalone
libunistring
libuuid
lsblk
m4
make
mandoc
mcookie
mpc1
mpfr4
musl
musl-utils
ncurses-libs
ncurses-terminfo-base
nghttp2-libs
oniguruma
openrc
patch
pcre2
perl
perl-app-cpanminus
perl-app-cpanminus-doc
perl-capture-tiny
perl-config-tiny
perl-cpanel-json-xs
perl-data-dump
perl-data-guid
perl-data-optlist
perl-data-uuid
perl-devel-symdump
perl-dist-checkconflicts
perl-encode-locale
perl-error
perl-exporter-tiny
perl-extutils-config
perl-extutils-helpers
perl-extutils-installpaths
perl-file-listing
perl-file-which
perl-git
perl-html-parser
perl-html-tagset
perl-http-cookies
perl-http-daemon
perl-http-date
perl-http-message
perl-http-negotiate
perl-io-html
perl-io-prompt-tiny
perl-io-socket-ssl
perl-json-maybexs
perl-libwww
perl-list-moreutils
perl-list-moreutils-xs
perl-lwp-mediatypes
perl-lwp-protocol-https
perl-module-build
perl-module-build-tiny
perl-module-implementation
perl-module-pluggable
perl-module-runtime
perl-mozilla-ca
perl-net-http
perl-net-libidn
perl-net-ssleay
perl-package-stash
perl-package-stash-xs
perl-params-util
perl-path-class
perl-pod-coverage
perl-probe-perl
perl-sub-exporter
perl-sub-install
perl-sub-uplevel
perl-test-deep
perl-test-exception
perl-test-fatal
perl-test-harness
perl-test-nowarnings
perl-test-output
perl-test-pod
perl-test-simple
perl-test-taint
perl-try-tiny
perl-uri
perl-utils
perl-www-robotrules
readline
scanelf
setpriv
setup-box
sfdisk
ssl_client
unzip
util-linux
wget
wget-doc
zip
zlib
```

**Comment by tbodt** [comment]
It's possible perlbrew doesn't support musl. Can you show the full compiler command line?

**Comment by mjgardner** [comment]
It's failing during the `Configure` script, trying to run this:

```
cc -o try -D_GNU_SOURCE try.c
```

`try.c` looks like this:

```
int main(int argc, char *argv[]) {
  return 0;
}
```

**Comment by tbodt** [comment]
Ah, looks like you need the libc headers, available from `apk add build-base`. On alpine, the `gcc` package literally only includes GCC.

**Comment by wachabaha** [comment]
> Using iSH 1.1.1 (Build 91) on iOS 14.4 on a iPad Pro (11-inch) (2nd generation).
> 
> I've installed bash, gcc, make, and [perlbrew](https://perlbrew.pl/), along with the requisite Perl modules via apk (list below). Trying to run `perlbrew install --verbose perl-5.32.1` via bash, I get at the end:
> 
> ```
> Use which C compiler? [cc]  
> /usr/lib/gcc/i586-alpine-linux-musl/9.3.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find Scrt1.o: No such file or directory
> /usr/lib/gcc/i586-alpine-linux-musl/9.3.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
> /usr/lib/gcc/i586-alpine-linux-musl/9.3.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find -lssp_nonshared
> collect2: error: ld returned 1 exit status
> Uh-oh, the C compiler 'cc' doesn't seem to be working.
>  
> You seem to have a working gcc, though.
> 
> *** However, any setting of the C compiler flags (e.g. for thread support)
> *** will be lost.  It may be necessary for you to restart Configure and
> *** add -Dcc=gcc to your Configure command line.
> 
> Would you like to go ahead and try gcc anyway? [n]  
> /usr/lib/gcc/i586-alpine-linux-musl/9.3.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find Scrt1.o: No such file or directory
> /usr/lib/gcc/i586-alpine-linux-musl/9.3.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find crti.o: No such file or directory
> /usr/lib/gcc/i586-alpine-linux-musl/9.3.0/../../../../i586-alpine-linux-musl/bin/ld: cannot find -lssp_nonshared
> collect2: error: ld returned 1 exit status
> Uh-oh, the C compiler 'cc' doesn't seem to be working.
> You need to find a working C compiler.
> Either (purchase and) install the C compiler supplied by your OS vendor,
> or for a free C compiler try http://gcc.gnu.org/
> I cannot continue any further, aborting.
> ```
> 
> Here's a list of packages installed:
> 
> ```
> alpine-baselayout
> alpine-conf
> alpine-keys
> apk-tools
> bash
> binutils
> bison
> blkid
> busybox
> ca-certificates
> ca-certificates-bundle
> cfdisk
> curl
> curl-doc
> expat
> findmnt
> gcc
> gcc-doc
> gdbm
> gdbm-dev
> git
> git-doc
> git-perl
> gmp
> hexdump
> isl
> jq
> libatomic
> libblkid
> libbz2
> libc-utils
> libcap-ng
> libcrypto1.1
> libcurl
> libfdisk
> libgcc
> libgomp
> libgphobos
> libidn
> libidn2
> libmount
> libsmartcols
> libssl1.1
> libstdc++
> libtls-standalone
> libunistring
> libuuid
> lsblk
> m4
> make
> mandoc
> mcookie
> mpc1
> mpfr4
> musl
> musl-utils
> ncurses-libs
> ncurses-terminfo-base
> nghttp2-libs
> oniguruma
> openrc
> patch
> pcre2
> perl
> perl-app-cpanminus
> perl-app-cpanminus-doc
> perl-capture-tiny
> perl-config-tiny
> perl-cpanel-json-xs
> perl-data-dump
> perl-data-guid
> perl-data-optlist
> perl-data-uuid
> perl-devel-symdump
> perl-dist-checkconflicts
> perl-encode-locale
> perl-error
> perl-exporter-tiny
> perl-extutils-config
> perl-extutils-helpers
> perl-extutils-installpaths
> perl-file-listing
> perl-file-which
> perl-git
> perl-html-parser
> perl-html-tagset
> perl-http-cookies
> perl-http-daemon
> perl-http-date
> perl-http-message
> perl-http-negotiate
> perl-io-html
> perl-io-prompt-tiny
> perl-io-socket-ssl
> perl-json-maybexs
> perl-libwww
> perl-list-moreutils
> perl-list-moreutils-xs
> perl-lwp-mediatypes
> perl-lwp-protocol-https
> perl-module-build
> perl-module-build-tiny
> perl-module-implementation
> perl-module-pluggable
> perl-module-runtime
> perl-mozilla-ca
> perl-net-http
> perl-net-libidn
> perl-net-ssleay
> perl-package-stash
> perl-package-stash-xs
> perl-params-util
> perl-path-class
> perl-pod-coverage
> perl-probe-perl
> perl-sub-exporter
> perl-sub-install
> perl-sub-uplevel
> perl-test-deep
> perl-test-exception
> perl-test-fatal
> perl-test-harness
> perl-test-nowarnings
> perl-test-output
> perl-test-pod
> perl-test-simple
> perl-test-taint
> perl-try-tiny
> perl-uri
> perl-utils
> perl-www-robotrules
> readline
> scanelf
> setpriv
> setup-box
> sfdisk
> ssl_client
> unzip
> util-linux
> wget
> wget-doc
> zip
> zlib
> ```



> Ah, looks like you need the libc headers, available from `apk add build-base`. On alpine, the `gcc` package literally only includes GCC.

**Comment by mjgardner** [comment]
> Ah, looks like you need the libc headers, available from `apk add build-base`. On alpine, the `gcc` package literally only includes GCC.

Thanks, that did it.
