### ISSUE TITLE
apk update - interrupted system call

### ISSUE THREAD

**Issue by SkysCrystal** [ish-app/ish#1299]
I want to use my iPhone 6 Plus to run docker. But I came across a problem.
Without changing `/etc/apk/repositories` file content, I can't get `apk update` on iPhone 6P. It showed that `WARNING: ... Interrupted system call`. Meanwhile, I can get `apt update` on iPad Pro. I also can add docker on iPad Pro.

Here is the warning on iPhone 6P:
```
AiPhone:~# apk update
WARNING: Ignoring file:///ish/apk/main/x86/APKINDEX.tar.gz: Interrupted system call
WARNING: Ignoring file:///ish/apk/community/x86/APKINDEX.tar.gz: Interrupted system call
OK: 14 distinct packages available
```

When I edited the `/etc/apk/repositories` file to the 'aliyun' alpine mirror, it could get `apk update`. But I can't get full `docker`.

It first showed I/O error. I made the directory in the name needed.
```
(1/1) Installing docker-cli (20.10.3-r0)
ERROR: Failed to create usr/bin/docker: I/O error
ERROR: docker-cli-20.10.3-r0: IO ERROR
```

Then it showed another error which was more complicated for me to solve.
```
ERROR: docker-cli-20.10.3-r0: failed to rename usr/bin/.apk.c3b1f6a8a8f27bcbd9b707e41fcfac57828b8f8f561e56f3 to usr/bin/docker.
Executing busybox-1.31.1-r19.trigger
1 error; 218 MiB in 26 packages
```

I want some help! Thanks a lot.

**Comment by tbodt** [comment]
The "interrupted system call" bug happens if you rotate your device or hide the keyboard while downloading a package. I don't know about the middle IO ERROR, but the last one is because you created a directory at /usr/bin/docker when you shouldn't have.

**Comment by SkysCrystal** [comment]
@tbodt Thanks a lot!!! 
After waiting for about 10mins, it finally ran correctly (`apk update`). 
I tried `apk del docker` then `apk add docker` and Docker can run in iSH.
