### ISSUE TITLE
I create a icon similar to terminal in Mac.

### ISSUE THREAD

**Issue by AAnas222222** [ish-app/ish#1301]
I create a icon similar to terminal in Mac. 

![IMG_0020](https://user-images.githubusercontent.com/55362783/103305005-0448a280-4a45-11eb-9add-43203a1bc691.jpeg)

__Originally posted by @PoonKinWang in https://github.com/ish-app/ish/issues/578#issuecomment-752191138__

**Comment by Mnpn03** [comment]
This looks like a quote of a comment, but please keep icon submissions to #578.
