### ISSUE TITLE
IO ERROR dmesg using provided fs

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#1320]
<details>The link is here: https://github.com/ish-app/ish/blob/master/app/iSH.xcconfig#L13
<details>
__Originally posted by @tbodt in https://github.com/ish-app/ish/issues/1288#issuecomment-780079957__
</details></details>

Reproduction: github.com/ish-app/roots/releases/download/g31251b2000a4378e65839b357dfc4dbf28a9dfb5/appstore-apk.tar.gz

```
iPhone:~# apk update
v3.12.4-5-gd7dba2fc46 [file:///ish/apk/main]
v3.12.3-121-gd18a91093f [file:///ish/apk/community]
OK: 12544 distinct packages available
iPhone:~# apk add py3-pip
(1/36) Installing libbz2 (1.0.8-r1)
ERROR: libbz2-1.0.8-r1: IO ERROR
(2/36) Installing expat (2.2.9-r1)
ERROR: expat-2.2.9-r1: IO ERROR
(3/36) Installing libffi (3.3-r2)
ERROR: libffi-3.3-r2: IO ERROR
(4/36) Installing gdbm (1.13-r1)
  0%                                             ^Z[1]+  Stopped                    apk add py3-pip
iPhone:~# dmesg
error fetching ODR main:x86:libbz2-1.0.8-r1.apk: Error Domain=AssetErrorDomain Code=6 "Asset URL has expired" UserInfo={NSDebugDescription=Asset URL has expired}
error fetching ODR main:x86:expat-2.2.9-r1.apk: Error Domain=AssetErrorDomain Code=6 "Asset URL has ```

**Comment by josteink** [comment]
Probably a duplicate of https://github.com/ish-app/ish/issues/1273

**Comment by 62f** [comment]
> Probably a duplicate of https://github.com/ish-app/ish/issues/1273

@josteink indeed it is, but as per the daily builds' preponderance of repititíous 1.1.2 TestFlight post-install-notes, I have captured two analytic sysdiagnose files: first before, and then another created within seconds, immediately following the incident. You're welcome; so now where do I upload them, they're both over 200Mb ?

**Comment by tbodt** [comment]
In #1268 someone used dropbox. I suppose you could also use mega.nz.

**Comment by 62f** [comment]
Closing since further updates will go on #1213

_Originally posted by @tbodt in https://github.com/ish-app/ish/issues/1268#issuecomment-774887191
