### ISSUE TITLE
Why can only one core of CPU be recognized (nproc command)

### ISSUE THREAD

**Issue by ZhangGaoxing** [ish-app/ish#1323]
```
ipad-air3:~# nproc
1
```

Using `make  -j1` command is also very slow

**Comment by 62f** [comment]
iSH is an i386 emulator. For hardware acceleraion, This class of Intel-compatible device mainly depended on multiple DRAM caching-level logic (L1, L2, L3), VPU instruction pipelining drivers, bus overclocking and in rare configurations, on software-transparent virtual hyperthreading optimization to improve performance.
The earliest multi-core 32-bit bus/64 bit instruction-capable CPUS were branded Core2Duo.
