### ISSUE TITLE
Adb error protocol fault

### ISSUE THREAD

**Issue by BlastBolt5** [ish-app/ish#1324]
Whenever I run the command adb devices I get this![image](https://user-images.githubusercontent.com/64578489/110138652-d0b52c00-7d97-11eb-8623-8fcc8caa2a43.jpeg)
I just need it for simple app installs so doesn't matter if it doesn't work fully

**Comment by PhamThiBexx** [comment]
A

**Comment by alexberry** [comment]
Ish cannot access usb, it is emulated inside a sandbox, so this will likely never work.

**Comment by BlastBolt5** [comment]
> Ish cannot access usb, it is emulated inside a sandbox, so this will likely never work.

I knew this I was talking about adb over the network

**Comment by guanzhangrtk** [comment]
@BlastBolt5 were you able to get this working? I loaded official alpinelinux v3.14 image and installed `android-tools`, then I pretty much get the exact error message as you when I tried to run `adb devices`. According to #498 it's supposed to be working, I wonder what changed in the last couple of months...? Thanks in advance for any help!
