### ISSUE TITLE
System call interrupted on rotate, keyboard show/hide, cog press

### ISSUE THREAD

**Issue by Aareon** [ish-app/ish#1330]
iSH TestFlight version 1.1.2 (build 112)
iPhone 11, iOS 13.5 (no jb)
After running `apk add nano bash curl zsh nvim`
and switching to a different app, I noticed when I came back that I received 2 errors. One was an IO error, and the other was an Interrupted system call error. Presumably the IO error is a result from switch apps during a download, and the Interrupted system call is from interacting in the app, i.e. rotating the screen, hiding/showing the keyboard, clicking the settings cog.
I’ve experienced this issue for a while (since at least build 91) on my iPhone 11 and iPhone 7.

No output from `dmesg`
Happy to help in any way I can!

**Comment by Aareon** [comment]
Just confirmed that this is also happening on a fresh iSH build 112 on iPhone 7 (jb). No sign of the IO error, but this sys call interrupt issue is bugging the hell out of me.

**Comment by Aareon** [comment]
The interrupt error during `apk add` is intermittent when switching applications. Keyboard hide/show and cog press consistently interrupt.

**Comment by ffffaaasl** [comment]
apk add <package>

**Comment by Mnpn03** [comment]
This should be resolved in iSH 1.2, if you're still experiencing problems, please reach out and we'll reopen the issue!
