### ISSUE TITLE
Unable to chroot Debian, “chroot: can't execute '/bin/ash': No such file or directory”

### ISSUE THREAD

**Issue by The-Anonymous-Chicken** [ish-app/ish#1336]
when i chroot Into Debian stretch it gives the error  `chroot: can't execute '/bin/ash': No such file or directory` using chroot ( `/srv/chroot/stretch/` ) and when I specify **bash** using `chroot /srv/chroot/stretch/ /bin/bash` it gives and error that it can’t execute bc it can’t find it same same, and now when try it just gives **illegal instruction**
I tried copying “ash” to “bin”, that didn’t work, i tried renaming **bin** to /bin that was the closest I ever got but then I got an error that it can’t find another folder, but I really didn’t want to risk destroying it by renaming all the root folders to begin with a “/“ bc it took so long to create the chroot with debootstrap. And now I have no idea what to do anymore, can someone please help me.
Thank you, I’ll give more details if needed!

**Comment by The-Anonymous-Chicken** [comment]
Also I am using an x64 Alpine minirootfs tarball as my rootfs.

**Comment by econcz** [comment]
Hi! Debian in chroot partly works (I tested it) but illegal instructions will arise for apt (apt won't work on amd64 unless you are using an amd-based Debian). ash is part of the busybox, I recommend chrooting using /bin/bash, it usually works.
How did you unpack Debian into iSH Linux?

**Comment by The-Anonymous-Chicken** [comment]
I actually used debootstrap to get the rootfs, and I used to use x86_64 alpine rootfs tarball, but then all of a sudden it stopped working because my arch switched from i386 to i686 just like that.
And then it stopped booting with error code -k

**Comment by The-Anonymous-Chicken** [comment]
![2357BEE3-E333-4103-A57D-2033D090B264](https://user-images.githubusercontent.com/77453663/111653838-7075af80-87c5-11eb-8f69-2db2eff20026.jpeg)

**Comment by The-Anonymous-Chicken** [comment]
![Uploading 87484608-B0B8-458D-9968-EA8ADF57BE71.png…]()

**Comment by econcz** [comment]
x86_64 (64-bit) Debian won’t run: iSH Linux emulates i386 (32-bit system).

**Comment by The-Anonymous-Chicken** [comment]
Oh, thanks. But for some reason after I created this file system it says my arch is i686, weird.

**Comment by asdfugil** [comment]
ish emulates i686 not i386
