### ISSUE TITLE
Error fetching ODR

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#1341]
error fetching ODR main:x86:APKINDEX.tar.gz: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service on pid 0 named com.apple.ondemandd.client" UserInfo={NSDebugDescription=connection to service on pid 0 named com.apple.ondemandd.client}
error fetching ODR community:x86:APKINDEX.tar.gz: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service on pid 0 named com.apple.ondemandd.client" UserInfo={NSDebugDescription=connection to service on pid 0 named com.apple.ondemandd.client}

<details>
Burak--iPhone:~# apk add python3
WARNING: Ignoring file:///ish/apk/main/x86/APKINDEX.tar.gz: IO ERROR
WARNING: Ignoring file:///ish/apk/community/x86/APKINDEX.tar.gz: Interrupted system call
ERROR: unsatisfiable constraints:
  python3 (missing):
    required by: world[python3]
Burak--iPhone:~# 
<details>
__Originally posted by @bizimburak in https://github.com/ish-app/ish/issues/123#issuecomment-761111553__
</details>

**Comment by Mnpn03** [comment]
This should be resolved in iSH 1.2. If you are still experiencing this problem on 1.2, please let us know so we can reopen this issue!
