### ISSUE TITLE
ctrl+c function issue

### ISSUE THREAD

**Issue by ni7ht** [ish-app/ish#1371]
Hi, I’m met a trouble when I want quit a option.
How could I get ctrl+c work without a shortcut and physical ctrl button? Thanks very much.
![F18A32F1-680E-4019-9D58-EF43BE586F47](https://user-images.githubusercontent.com/37174285/115426838-7979f680-a233-11eb-93e1-1377d8f82e1b.jpeg)

**Comment by Mnpn03** [comment]
Hi! You can press the `^` button, and then press the `C` key.

![](https://ish.app/assets/iphone-keyboard.png)

**Comment by ni7ht** [comment]
> Hi! You can press the `^` button, and then press the `C` key.
> 
> ![](https://camo.githubusercontent.com/0bb83b0f67d3bc5ee6329f219d65c1274d1f88d83843dd890c57ae1c7fcc764a/68747470733a2f2f6973682e6170702f6173736574732f6970686f6e652d6b6579626f6172642e706e67)

Thanks！
