### ISSUE TITLE
apk-tools-2.10.6-r0: IO Error

### ISSUE THREAD

**Issue by fuhaku** [ish-app/ish#1372]
![IMG_1BF9BFE7A96B-1](https://user-images.githubusercontent.com/6256248/115476147-17e76700-a1f6-11eb-9e84-4cf4451a1b79.jpeg)

can provide sysdiagnose file but size is 270 megs. Too large for Github. However, I don't have an email to send to. Can also provide a DropBox link for download, but don't want to make my sysdiagnose public.

Occurred at 4:26 PM Pacific time
iPad pro (11 inch) IOS - 14.4.2 / ISH 1.1.2 (142)

Does not occur on iPhone 12 Pro Max IOS - 14.4.2 updating and upgrading at same location

Was able to add curl just before errors started. Now cannot add anything.

**Comment by 62f** [comment]
https://tbodt.com/

**Comment by Mnpn03** [comment]
This should be resolved in iSH 1.2. If you are still experiencing this problem on 1.2, please let us know so we can reopen this issue!
