### ISSUE TITLE
"Downloading APKINDEX.Tar.gz (0%)" never starts.

### ISSUE THREAD

**Issue by antdude** [ish-app/ish#1373]
Hello.

I just downloaded and installed ish v1.1.1 into my old iPhone 6+ (iOS v12.5.2), but I can't seem to download APK stuff due to its "Downloading APKINDEX.Tar.gz (0%)". After a few minutes, it times out with:
"...
WARNING: Ignoring file:///ish/apk/main/x86/APKINDEX.tar.gz: IO ERROR
WARNING: Ignoring file:///ish/apk/community/x86/APKINDEX.tar.gz: No such
file or directory
..."

Why can't it download? Is it a bug? :( Thank you for reading and hopefully answering soon. :)

**Comment by Mnpn03** [comment]
This issue should be resolved in iSH 1.2. If you are still experiencing this issue on 1.2, please let us know so we can reopen this issue!

**Comment by antdude** [comment]
Thanks. It works. ;)
