### ISSUE TITLE
Is it possible to change the cursor’s color?

### ISSUE THREAD

**Issue by lifepillar** [ish-app/ish#1377]
The cursor is always black, which makes it difficult to spot it over a dark background.

![image](https://user-images.githubusercontent.com/1193314/116201717-19ef7f80-a73a-11eb-8d33-ca7ae6db3588.jpeg)

**Comment by sdhoward** [comment]
This looks like you used the light theme of iSH with a dark theme in your console text editor.

There's a dark theme available in the settings of iSH. Please try that first, in case you haven't.

**Comment by lifepillar** [comment]
>This looks like you used the light theme of iSH with a dark theme in your console text editor.

Correct. The dark theme is fine, the cursor is white then (and the latest release fixes the missing characters on screen as well)!

**Comment by sdhoward** [comment]
Great to hear, please self-close this issue
