### ISSUE TITLE
Need refresh feature.

### ISSUE THREAD

**Issue by mtsrp-dbychkrdhw** [ish-app/ish#1391]
Every time I need to refresh app. I have to delete and reinstall the app again and again. It's really annoying. Could you please make feature that I don't need to reinstall the app. Just switch or press some button and everything refreshed.

**Comment by mad-cs** [comment]
Make a copy of fresh system and save it in your iCloud or local disk. When ever you want to reset your Alpine, import the copy.

**Comment by tbodt** [comment]
> Make a copy of fresh system and save it in your iCloud or local disk. When ever you want to reset your Alpine, import the copy.

Can recommend this. That said you should not usually need to refresh the app. If you're running into some problem that requires you to frequently delete your data, please file an issue for that.
