### ISSUE TITLE
Non-ascii characters cannot be shown in ish terminal after IOS updated to 14.5.1

### ISSUE THREAD

**Issue by biao-biao** [ish-app/ish#1405]

**Comment by ferrmin** [comment]
+1

**Comment by SugarRayLua** [comment]
Similar concern to my UTF-8 comment in #1395?

**Comment by schabrolles** [comment]
may be related to this issue, but tmux split pane doesn't work anymore

**Comment by tbodt** [comment]
I believe this is a duplicate of #1423, which is now fixed
