### ISSUE TITLE
Opening files with vi / vim requires a tap to the screen in order for content to be displayed

### ISSUE THREAD

**Issue by Conanap** [ish-app/ish#1406]
iOS 14.5, App store version, iPad Pro 3rd gen

Create any file via vi / vim, the screen will be blanked but line number is available at the very bottom of the screen. Physically touching the screen will cause the content to show up.

Note that if you run `ash` or open another shell before you try to edit a file, this problem does not present itself. Once you’ve exited those shells you will once again encounter the problem.

**Comment by Conanap** [comment]
https://user-images.githubusercontent.com/15721264/118285843-dddd4e00-b49f-11eb-9175-52dca53fec64.MP4

I’ve attached a video for reproduction / demonstration purposes.

**Comment by personalizedrefrigerator** [comment]
This might be related to #1401?

**Comment by Conanap** [comment]
Looks like very much so. Should I close this as duplicate and you can link this issue in yours?

**Comment by Conanap** [comment]
Although I should note this is a consistent problem for me, while your issue seems to mention vim experiences this intermittently

**Comment by personalizedrefrigerator** [comment]
> mention vim experiences this intermittently

I think it always happens on Vim's startup, even when running within another shell (e.g. after launching bash).

**Comment by personalizedrefrigerator** [comment]
> Should I close this as duplicate and you can link this issue in yours?

I'm not sure... They are similar. They focus on different aspects of the problem, though.

**Comment by Conanap** [comment]
You're right; from my testing I saw that it only happens with the instance of shell when I boot it up. Any shell that is a child of that first shell does not exhibit this problem.  

I've only tested this with ash and bash though.

**Comment by 62f** [comment]
"1st* instance"

**Comment by sdhoward** [comment]
The parent issue was closed. Please try again with the updated version and advise if it was that or if it's something else.

**Comment by Conanap** [comment]
Appears to be fixed, thanks!
