### ISSUE TITLE
Are the udev and dbus’s daemons working in the latest AppStore iSH?

### ISSUE THREAD

**Issue by SugarRayLua** [ish-app/ish#1407]
As a novice Linux user, I'm only somewhat familiar with the functions of both udev and dbus. However, rc-status in my iSH (latest App Store build) says they are not running, and I can't restart them with rc-service ... restart:

iPad:~# rc-status
 * Caching service dependencies ...
grep: /proc/modules: No such file or directory                                                                                       [ ok ]
 * Clock skew detected with `(null)'
 * Adjusting mtime of `/run/openrc/deptree' to Sat May 15 10:56:40 2021
Runlevel: sysinit
 udev                                                                                                                         [  stopped  ]
 udev-trigger                                                                                                                 [  stopped  ]
 dbus                                                                                                                         [  stopped  ]
 sshd                                                                                                                         [  stopped  ]
Dynamic Runlevel: hotplugged
Dynamic Runlevel: needed/wanted
Dynamic Runlevel: manual

Yet, I can rc-service sshd restart and get the sshd daemon working. I was curious because I wanted to try and get the lightweight Midori web browser running but couldn't get it to run because it gave me a dbind error about "couldn't connect to accessibility bus". It seems that many of the desktop managers rely on dbus.

If there the udev and dbus daemons are supposed to be working on the latest App Store release of iSH and anyone has suggestions of how to get them running, I would appreciate it.

Thanks.

**Comment by SugarRayLua** [comment]
I apologize; I just saw on the iSH Wiki under openRC that dbus is not working. Please let me know if someone knows if udev working-- otherwise, since not listed on the Wiki as definitely working presume it probably is not. 

Thanks!

**Comment by tbodt** [comment]
udev is also not working, though it's not very useful for anything currently.

**Comment by SugarRayLua** [comment]
Thanks for the follow-up. :-)
