### ISSUE TITLE
cat in ish can’t output Chinese in IOS14.5.1

### ISSUE THREAD

**Issue by ubun222** [ish-app/ish#1412]
如题，升级系统后cat到中文就会卡住

**Comment by 62f** [comment]
While investigating this issue, another bug: at any point immediately after switching kb into Cyrillic(Русская) & typing ```Я``` outputs instead a ```Ð?``` 1x at the prompt of iSH(build 159)'s CLI instead of a backwards 'я', then resumes normal echos.

**Comment by sdhoward** [comment]
This might be the same as #1423, which is now fixed. Please check with the latest version from the app store.
