### ISSUE TITLE
SBCL support

### ISSUE THREAD

**Issue by xTriixrx** [ish-app/ish#1414]
SBCL is a compiler/interpreter for Common Lisp and currently does not work for iSH even though it is an apk package. Support for this would be greatly appreciated!

**Comment by 62f** [comment]
Although I'm 100% sure that it's a new bug,```apk search sbcl``` doesn't return any results.

**Comment by xTriixrx** [comment]
> Although I'm 100% sure that it's a new bug,```apk search sbcl``` doesn't return any results. 

Right, I had to do some digging through the alpine apk standard package repo online to find that sbcl is available as a standard apk package.

**Comment by 62f** [comment]
I had also dug up an .apk, which is precisely how I became "100% sure". It is my experience that any Alpine package's maintainer sometimes hides an apk's listing from the repository yet the file itself remains callable IF we correctly guess its URL. My guess is that those were found to be inop/defective or are being updated. There may in fact be several versions of these snakes-in-the-grass, so unless provided with a link to the exact .apk, there can be no way to investigate this specific issue with much certainty.

**Comment by xTriixrx** [comment]
I attempted to add one of the official alpine Linux repos to /etc/apk/repositories (after a restart iSH doesn't keep this edit not sure if this is a bug or nominal) and attempted to run "apk add sbcl". I was actually able to get sbcl downloaded however like you hinted in the comment above it appears to be defective (app gets hung up on startup). I could try a similar app with clisp if that application works.

**Comment by xTriixrx** [comment]
Just adding this for completeness, I have successfully installed ECL on iSH. I updated my /etc/apk/repositories to also include http://dl-cdn.alpinelinux.org/alpine/latest-stable/community/x86/. Once included I performed "apk add ecl" and so far the ECL shell appears to work as expected.

**Comment by 62f** [comment]
One simply cannot "include" another Alpine version's repository into the /etc/apk/repositories without serious consequences, especially of 'latest-stable' which is AKA 'Alpine 3.13', not only because every version of iSH ships equipped w/3.12 filesystem but also 3.13 is known for calling many many processor functions which iSH does not yet incorporate.
