### ISSUE TITLE
can't su root

### ISSUE THREAD

**Issue by soap-man** [ish-app/ish#1421]
i login to raspberry use pi user success,but can't su root,it's hold on when i su root,like this ![image](https://user-images.githubusercontent.com/33997593/119595416-1ec65280-be10-11eb-8f91-e8884b33da73.jpeg)

**Comment by soap-man** [comment]
i can login root by other ssh client,only iSH can't

**Comment by 62f** [comment]
try: ```sudo su root``` or ```exit```

**Comment by soap-man** [comment]
> try: ```sudo su root``` or ```exit```
can't ... I tried many times, i can use root login on other ssh client

**Comment by 62f** [comment]
What's the output of ```whoami```?

**Comment by sdhoward** [comment]
If your locale causes `su` to print non-ascii characters, then this might be the same as #1423 which was fixed. Would you please check again with the latest iSH from the app store?

**Comment by soap-man** [comment]
> If your locale causes `su` to print non-ascii characters, then this might be the same as #1423 which was fixed. Would you please check again with the latest iSH from the app store?

👏👏👏 its ok !

**Comment by saagarjha** [comment]
Closing as this appears to be resolved. Please let us know if this is not the case and you would like us to reopen this!
