### ISSUE TITLE
accented characters cause terminal glitches

### ISSUE THREAD

**Issue by sdhoward** [ish-app/ish#1423]
I've been using emacs inside of ish which is quite fun. But certain keyboard combinations which would work on macos cause the terminal to stop displaying the emacs window correctly. For example, option-`>` (option-shift-`.`) is a helpful shortcut in emacs on macos, but it generates `˘` in ios apps. If ish would just print the character as entered then I could remember that this type of shortcut is not supported.

Instead, in ish, entry of `˘` causes the terminal to stop printing the current line. 

You can even reproduce this with the software keyboard if you hold down a vowel like `i` and select some character like `ï`; it doesn't print in ish and then you have to hit return to get a new prompt that works.

Looking through known issues, it looks like ish used to support printing these characters: https://github.com/ish-app/ish/issues/510 https://github.com/ish-app/ish/issues/432

Is there some package I need to install inside of the system or can this be addressed as an ish bug?

Thanks!

**Comment by sdhoward** [comment]
#1395, #1401, #1405 describe this differently but they all say it was broken by an ios upgrade.

**Comment by tbodt** [comment]
Fixed by 928dfe0ce3a374fd85545fe04331efba426ab3cd

**Comment by miron** [comment]
> I've been using emacs inside of ish which is quite fun. But certain keyboard combinations which would work on macos cause the terminal to stop displaying the emacs window correctly. For example, option-`>` (option-shift-`.`) is a helpful shortcut in emacs on macos, but it generates `˘` in ios apps. If ish would just print the character as entered then I could remember that this type of shortcut is not supported.
> 
> Instead, in ish, entry of `˘` causes the terminal to stop printing the current line.
> 
> You can even reproduce this with the software keyboard if you hold down a vowel like `i` and select some character like `ï`; it doesn't print in ish and then you have to hit return to get a new prompt that works.
> 
> Looking through known issues, it looks like ish used to support printing these characters: #510 #432
> 
> Is there some package I need to install inside of the system or can this be addressed as an ish bug?
> 
> Thanks!

I use that character in my ascii art when editing files, not really a problem, but I do need to frequently redraw the buffer in vim with ctrl-L, as lines disappear randomly, or code artifacts get inserted in different locations. Also when clearing the screen in Python with os.system(‘cls’) sometimes new prints afterward show up, sometimes they don’t
