### ISSUE TITLE
[question/docs]: upgrade alpine version?

### ISSUE THREAD

**Issue by jsjoeio** [ish-app/ish#1425]
I looked through previous issues and discussions but didn't find anything.

Can I upgrade the version of Alpine to a newer version? (i.e. 3.13)

## Additional Context

![57C20764-BB09-4BFD-9AEC-871DA04A7684](https://user-images.githubusercontent.com/3806031/120091584-48f26b80-c0c1-11eb-9e75-f1fc6e96cb29.jpeg)

I've never used Alpine before (also new to ish). I'm running it on my iPad and trying to set up Doom Emacs, but it requires git v2.28 or newer, which means I need Alpine 3.13 AFAICT.

**Comment by tbodt** [comment]
It is possible to update by editing /etc/apk/repositories, but 3.13 is fairly untested and may break other things. If you try it please file issues for any bugs you find.

**Comment by jsjoeio** [comment]
Awesome! Will do. Thanks for the quick response.

**Comment by felipereisdev** [comment]
> Impressionante! Vai fazer. Obrigado pela resposta rápida.

Hi. Did you get to update?

**Comment by jsjoeio** [comment]
Not sure where that quote is from but here is how to do it: https://github.com/ish-app/ish/discussions/1428#discussioncomment-804269
