### ISSUE TITLE
support Colorful display on terminal?

### ISSUE THREAD

**Issue by baoyachi** [ish-app/ish#1430]

**Comment by 62f** [comment]
![image](https://user-images.githubusercontent.com/68332197/120587187-ea9bf480-c402-11eb-92ae-9b1faa0198e0.jpeg)💁🏿

**Comment by baoyachi** [comment]
So great.

**Comment by sdhoward** [comment]
ok to close?

**Comment by baoyachi** [comment]
how to setup

**Comment by 62f** [comment]
.

**Comment by baoyachi** [comment]
ipad Os:14.6.0

**Comment by baoyachi** [comment]
In iash app, I installed oy-my-zsh. It's solve.

**Comment by saagarjha** [comment]
Please reopen if this is still an issue.
