### ISSUE TITLE
when the ish app slide to background, ssh will connect pause at all time 

### ISSUE THREAD

**Issue by xingyugege** [ish-app/ish#1444]
Is it possible make ish still run at backend like a music player ?

**Comment by Mnpn** [comment]
Check out this wiki page on [running iSH in the background](https://github.com/ish-app/ish/wiki/Running-in-background)!

**Comment by SugarRayLua** [comment]
Sorry to add onto this closed issue, but Mnpn, could you provide an example of how you’ve gotten iSH to run in the background? I like to use VNC a lot and would really like it if iSH could run the background, and I could open the VNC viewer on my iPad to full screen. Usually, to use VNC, I have to keep the iSH app open to 1/3 of my screen running as a VNC headless server, and then open up the VNC viewer app to 2/3 of the screen to get this to work. Whenever I’ve tried “hiding” the ish VNC headless server (e.g. sliding the app screen dividing slider over to put iSH in the background and have the VNC viewer have the full iPad screen), the VNC viewer and my X window freezes, and I can’t enter any commands. I tried using the suggestions on the wiki page you mentioned by entering that shell set of instructions and then immediately after running the VNC server and opening up my VNC viewer app.

If you’ve found a way to get iSH to run in the background as a VNC headless server with a VNC viewer taking up 100% of the iPad screen in the foreground, I’d appreciate any tips you could pass on how you did that.

Thanks!

**Comment by asdfugil** [comment]
make sure you always allow ish to use your location

**Comment by SugarRayLua** [comment]
Thanks—I set settings to allow ish to use your location and that worked. However, when specifically trying to run iSH as a headless VNC server in the background and an X window in a VNC viewer in the foreground, I could only do a few commands before iSH crashed. It seems that the extra graphics requirements of generating an X window overloads iSH. I’ve noticed the same thing with iSH running a VNC server not in the background (e.g. as split screen)— iSH can display 2D graphics and images but seems limited to small images (4K or under); anything over that crashes iSH.

**Comment by saagarjha** [comment]
Even when running in the background, the OS enforces memory limits on the process. Going over that will get the app terminated (and you will see a Jetsam log show up detailing why the OS terminated the app).

**Comment by SugarRayLua** [comment]
That’s very helpful and interesting, saagarjha. As a very amateur programmer, I didn’t know anything about this. I suspect though that what you mentioned might explain a phenomenon I’m encountering in iSH—that it seems to frequently exceeds memory limits and terminate when it works with graphics. After reading your comment, I read online that iOS puts even stricter requirements on memory on apps running the background, and I also read that the usual memory page size allotment for 32bit ARM is appx 4000 bytes.  Thus, when I use ImageMagick to try and display images on iSH by having iSH operating as a headless VNC server and viewing those images on a simultaneously running VNC viewer app, I’ve found the maximum image size (.png) I can view is appx 4000 bytes—anything over that and the iSH VNC headless server connection gets terminated. Any image 4000 bytes or under it displays fine. However, when I try the same setup (VNC viewer of my iPad simultaneously running and connected to iSH running headless VNC server) and put iSH fully in the background, I’m able to use the X window on the VNC viewer for a short while but then it also suddenly terminates and terminates the server connection (before I even display a graphic image (.png)). I am therefore suspecting that iOS memory limits are being enforced even more stringently when iSH is running completely in the background and the ish running a headless VNC server and opening up and using an X window is somehow just too much memory requirements? Again, as an amateur programmer, it still seems a bit odd a new iPad Pro with 256GB wouldn’t have enough memory to allocate to iSH running a headless VNC server, a VNC viewer app and more than a 4000 byte image all at once? I’ve tried to also install some linux PDF viewers on iSH and run them through using iSH as also as a headless VNC server and viewing them simultaneously on a separate VNC viewer—the PDF viewers all crash when I try and view any PDF on screen larger than a small thumbnail in size. Could a process in iSH be leaking memory and causing graphic programs to terminate with anything bigger than a small image? // Last, interestingly, I can’t find any Jetsam logs on my iPad for these seemingly Jetsam related crashes under my Settings/General/Privacy/Analytics location (in fact, no crash logs of anytime when the VNC graphics processes terminate). Yet, if I run a VNC headless server on iSH and simultaneously use an X terminal on my VNC viewer app without trying to view larger graphic files, I have no problem nor crashes. I read online that sometimes apps can interfere with iOS’s auto crash/jetsam reports.  //Fyi, and have a good weekend.

**Comment by saagarjha** [comment]
I don't know the exact numbers and algorithm off the top of my head, but it's certainly much higher than 4000 even while running in the background. The Jetsam report will have all the details, here's instructions on how you can read those if you're not familiar with them: https://developer.apple.com/documentation/xcode/identifying-high-memory-use-with-jetsam-event-reports. I hope you have a great weekend as well!

**Comment by SugarRayLua** [comment]
Thank you! If you or others manage to figure out how to open and display graphic files larger than 4K on iSH, please post at your convenience.
