### ISSUE TITLE
Temporary error??

### ISSUE THREAD

**Issue by timstring** [ish-app/ish#1449]
I have been trying to install Python for the last three hours, and I keep getting "temporary error (try again later)". What's going on?

**Comment by timstring** [comment]
Ish is working now!  Thanks

**Comment by Mnpn** [comment]
Glad to hear!

**Comment by Bounceysteve99** [comment]
doesn’t work for me

**Comment by Bounceysteve99** [comment]
> Glad to hear!

doesn’t work for me
