### ISSUE TITLE
Problem with php

### ISSUE THREAD

**Issue by Xenobi97** [ish-app/ish#1452]
Hello so i'm kinda new to this world and i want some detailled infos and maybe some help please, so actually i downloaded Ish Shell on my ipad Pro and installed a bunch of packages after watching a bunch of videos on youtube like openssl,openssh,php,python3,git,pip and CamPhish i runned camphish and came up with a link to send to my friends so i can have a photo of their webcams they've clicked on it but i have no idea where to find those pictures. I could really use some help 😃

**Comment by saagarjha** [comment]
Hi @Xenobi97, and welcome! We're glad to hear that you're finding iSH useful :) Unfortunately, we can't really help you with software such as CamPhish, but if you have questions about the others please provide some more details and we can reopen this issue and try to help.
