### ISSUE TITLE
Expose hterm cursor styles in preferences

### ISSUE THREAD

**Issue by saagarjha** [ish-app/ish#1469]
Having the cursor show up as a vertical bar, etc. would be nice

**Comment by leo848** [comment]
I also think this should be configurable. Vim's insert mode looks way better with this type of cursor.

**Comment by 0x41c** [comment]
I have something kinda working for this in my theming PR. If someone could get it fixed up I would be super happy, kind of busy atm.

Pr: https://github.com/ish-app/ish/pull/1438
