### ISSUE TITLE
linker error at runtime of emacs missing time

### ISSUE THREAD

**Issue by ra-esmith** [ish-app/ish#1474]
This is fantastic, super excited by the thought of emacs and python on ipad.

I "think" at runtime the dynamic library related to time is not being found ... and thus I get lots of symbol not found.  But just speculating.  Ideas on how to fix this?

I did my apt get python3  and apt get emacs
which worked fine

when I run emacs or python however I get errors on "symbol not found" all of which involve time.

when i type emacs at shell and hit return I see

Error relocating /user/lib/libdbus-1.so.3:  __clock_getres_time64: symbol not found
Error relocating /user/lib/libdbus-1.so.3:  __pthread_cond_timedwait_time64: symbol not found
...
Error relocating /user/lib/libxml2.so.2: __time64: symbol not found
..
Error relocating /user/lib/libncurses2.so.6: __gettimeofday_time64: symbol not found
...
Error relocating /user/lib/emacs:  __pselect_time64: symbol not found

Thanks!

**Comment by tbodt** [comment]
These linker errors normally means some part of the system is out of date. Try running `apk upgrade` and see if that fixes it.

**Comment by ra-esmith** [comment]
yep I am about to try 
apk upgrade -a 
which i found in the wiki folks put up (thanks!)
