### ISSUE TITLE
Feature Request: Access to Camera Roll

### ISSUE THREAD

**Issue by whorfin** [ish-app/ish#1477]
Greetings

`ish` is fantastic, first off, many thanks for making and sharing this

It would be really excellent to be able to use the `Filesystems->Import` command to mount the camera roll, eg `/private/var/mobile/Media/DCIM`, after the user grants permissions of course.
If this is already possible, apologies - I could find no way to do this so far.

My immediate use case is to use `rsync` for photo backup, with secondary desire to have access for exif access and image resizing etc.  So close!

This app https://thephotobackup.com does this, with full access to all the camera roll folders, but it appears to be abandoned - it uses an old `libssh`, insists on deprecated key exchange, and if it goes away, there doesn't seem to be any other iOS photo rsync solution.

**Comment by whorfin** [comment]
Whoops, I see this is a duplicate of #89.  My search-fu failed...

I love the `$ mount -t dcim` idea

**Comment by souvikhaldar** [comment]
Can I access photos directory via ish?

**Comment by kxdkxd** [comment]
Hi, I tried your command however I failed to mount dcim. Can you please help me with it?

cd /root
mkdir dddd
mount -t dcim none /root/dddd

mount: mounting none on /root/dddd failed: Invalid argument
