### ISSUE TITLE
Has anyone gotten any lightweight graphic browser to work with iSH?

### ISSUE THREAD

**Issue by SugarRayLua** [ish-app/ish#1484]
Has anyone had success in getting any browser to work with iSH? I've not had full success with any browser I've tried. I know that iSH currently has limited graphics capabilities, and first tried running a browser with iSH as a VNC server and using a VNC client on my iPad Pro. However, iSH crashed (disconnected VNC) whenever I tried to open any of the graphical browser which I thought might be due to iSH's current limited graphical capabilities. Thus, I switched to trying to open graphical browsers in iSH using iSH as a ssh server and using the Mocha X11 iPad app as an ssh viewer with X11 forwarding. The nice thing about the Mocha X11 app is it takes over all the 2D graphic rending/resources from iSH so it eliminates difficulty with graphic rendering as a reason why apps like graphical web browser might not work (actually renders 2D graphics reasonably quickly). Using the Mocha X11 app as the ssh viewer, I can get the lightweight apps Dillo and Links 2 (using the -g graphical option) to open and graphically display Google's search page. However, when I then use Google to search for a webpage and try to connect to that webpage, iSH crashes giving me an "illegal instruction" error. Thus, I think there may still be some limitation in the iSH emulator preventing the graphical web-browsers from working not related to rendering graphics. I'm not able to try Midori since it requires dbus which I'm aware is not currently functioning in iSH. Has anyone else been successful? Thanks.

**Comment by saagarjha** [comment]
Since this isn't really an issue, I'm going to turn it into a discussion.
