### ISSUE TITLE
Keyboard edge calculation still broken on iPad 6th Gen (Build 190)

### ISSUE THREAD

**Issue by Fluzzlesnuff** [ish-app/ish#1489]
https://user-images.githubusercontent.com/65415889/125201453-1a20f680-e224-11eb-952d-1023fd0d5836.MOV
The terminal does not begin to scroll until text reaches the bottom of the screen, whether the keyboard is shown or not. To see all text, I have to dismiss the keyboard temporarily. I often find myself using `^L`, but that's not always convenient.

**Comment by 62f** [comment]
Same problem on the i5s
Yes. iPhone 5s displays all .files without reservation; although iOS 12.5.4 will not allow renames to begin with a period, it  renamed .them to anything else directly from the iSH file provider however there’s a problem with the (hterm)? display on 1.2.3 presently.

_Originally posted by @62f in https://github.com/ish-app/ish/issues/1272#issuecomment-873580916_

**Comment by Fluzzlesnuff** [comment]
Is there a workaround, or should I just keep using `^L`?

**Comment by tbodt** [comment]
I'd better just roll back the last change I made which seems to have broken more things than it fixed

**Comment by 62f** [comment]
@Fluzzlesnuff

**Comment by Fluzzlesnuff** [comment]
The rollback fixed it. Thanks for solving this inconvenient bug, even though it involved reverting some changes.
