### ISSUE TITLE
Screen doesnt scroll with current command line

### ISSUE THREAD

**Issue by nodomw** [ish-app/ish#1490]
Version: 1.2.3 TestFlight Beta

iOS version: 14.6, Iphone XS Max
Jailbroken: No

https://user-images.githubusercontent.com/47635446/125205925-c5619800-e284-11eb-9a88-021e5b591beb.MOV

**Comment by ChiefChippy2** [comment]
Same issue on iOS 14.6, iPad Air 2

**Comment by 62f** [comment]
Duplicate of #1489
