### ISSUE TITLE
Install new version of Emacs 27 or later

### ISSUE THREAD

**Issue by atanasj** [ish-app/ish#1493]
I’m wondering if it is possible to install a new new version of Emacs. The versions available are 26, and I would like to use 27. Is this possible somehow? If so, any advice about how to get this installed would be great. 

Do I need to building it form source perhaps?

**Comment by safre19** [comment]
Did you manage to install emacs 27?

**Comment by atanasj** [comment]
@safre19, I did via the beta version of the app. You need to install via the TestFlight app which you can download via the app store.
