### ISSUE TITLE
Invitation

### ISSUE THREAD

**Issue by wapes12** [ish-app/ish#1499]

**Comment by 62f** [comment]
If the beta is full, you have two options:
1. Use AltStore (https://altstore.io) with the source https://ish.app/altstore.json
2. Wait for @tbodt to remove some testers

**Comment by Mnpn** [comment]
Hi, [here's the link to the TestFlight beta](https://testflight.apple.com/join/97i7KM8O).
(If this isn't what you were looking for, please reply and add some more details to your issue, thanks!)
