### ISSUE TITLE
Where’s issue #1503?

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#1504]
Jan Brašna (1):
      Docs: Fix readme cli quoting (#1503)![image](https://user-images.githubusercontent.com/68332197/127074591-cf1c3f0d-596b-42c1-985a-06f0306cc0e6.jpeg)

**Comment by saagarjha** [comment]
It's literally linked in the comment you posted.

**Comment by tbodt** [comment]
It's not in the list onscreen because it's a pull request and not an issue.
