### ISSUE TITLE
Please idiot proof the app

### ISSUE THREAD

**Issue by Rukario** [ish-app/ish#1539]
So I don't need to reinstall the app e.g. because I executed "mount -t ios . /"

I know I shouldn't have done that for next time but, it would be good idea to have an emergency escape plan for evil commands that would require reinstalling the app.

**Comment by saagarjha** [comment]
We should probably add an option to skip mounting the iOS mount in recovery mode.

**Comment by 62f** [comment]
![Take another bite out of your apple<sic>](https://user-images.githubusercontent.com/68332197/130703945-f32ae1c4-57f6-4634-a5e4-d2ce73882f77.png)

**Comment by Mnpn** [comment]
Hi, a button to reset these mounts has been added to the debug screen in 8abbc2e which you can access through recovery mode under System Settings > iSH. This will be in the next release of iSH. Thanks for the report!

**Comment by upintheairsheep** [comment]
Had this same issue and now 10 gigabytes on my phone are unusable, I need to get them out without deleting the app entirely.

**Comment by upintheairsheep** [comment]
and yes, I did this same mistake, I wanted to have the root of my phone’s Files app appear on iSH and failed miserably.

**Comment by Petemir** [comment]
> Hi, a button to reset these mounts has been added to the debug screen in 8abbc2e which you can access through recovery mode under System Settings > iSH. This will be in the next release of iSH. Thanks for the report!

Is there some timeline for the new release? Or another way to solve this without reinstalling?
