### ISSUE TITLE
`rsync` Operation not permitted (1)

### ISSUE THREAD

**Issue by muammar** [ish-app/ish#1554]
First, thank you very much for this tool. It is fantastic. I was trying to use `rsync` to copy some files from my remote server to an iCloud directory, and I get these errors: 

```
rsync: chown "/mnt/GoogleDrive/." failed: Operation not permitted (1)
rsync: chown "/mnt/GoogleDrive/BackupsandConfigs" failed: Operation not permitted (1)
rsync: chown "/mnt/GoogleDrive/BackupsandConfigs/Backups" failed: Operation not permitted (1)
rsync: chown "/mnt/GoogleDrive/BackupsandConfigs/Backups/BrownU" failed: Operation not permitted (1)
```

After researching, I found that this is caused by the fact that the local user executing `rsync` does not have permission to change group and other attributes. Is the only way around this to use `--no-perms `? Although I would like to preserve permission and all attributes.

**Comment by esgie** [comment]
That is common behavior of misconfigured rsync operating on network remote folders. Local root doesn’t have any arbitral right to interfere with remote filesystem.
Mounting iOS filesystem in iSH works in a similiar manner.
What you expect to work is that rsync will be able to change the ownership of files at your mounted Google Drive directory. This is not something supported.

**Comment by muammar** [comment]
> That is common behavior of misconfigured rsync operating on network remote folders. Local root doesn’t have any arbitral right to interfere with remote filesystem.
> Mounting iOS filesystem in iSH works in a similiar manner.
> What you expect to work is that rsync will be able to change the ownership of files at your mounted Google Drive directory. This is not something supported by service provider as far as I know.

Thanks for your reply. I will proceed to close this report as there is no way around and this is the expected behavior. Still, I am very happy with iSH, a very cool idea. 

Best,
