### ISSUE TITLE
Question: why can't we use SF Mono?

### ISSUE THREAD

**Issue by shivaprsd** [ish-app/ish#1555]
iSH version: 1.2.2 (Build 178)
iOS version: 14.7.1

I searched for this everywhere, and only found a passing mention in the Discord server from more than two years ago.

SF Mono is now the default monospace font on iOS (& macOS). It still does not show up in the iSH font-picker though.
So why can't we make SF Mono the default font on iSH? Can't we add a 'Default' option into font-picker that selects it?

I'm not an iOS dev, but I am a web dev familiar with WKWebView on macOS. The Discord post mentioned SF Mono not
being exposed to webviews; but at least now it is, AFAIK the CSS `font-family: ui-monospace` selects SF Mono in both
Safari and webviews. I don't know if iSH selects fonts like that via CSS, but I do see 'Menlo' hard-coded into two files.

Loading it as a custom font is unfortunately not a solution now, due to the ongoing custom-font issue (#1485 & related).
It also feels rather stupid, seeing as it is shipped with iOS (and now *also the default*). I hope this would be easier to
solve than that issue.

Also, is there any licensing issues involved in using SF Mono in an iOS webview app?

**Comment by saagarjha** [comment]
The blocker for this mainly that the font picker is system-provided and does not expose SF Mono.

**Comment by shivaprsd** [comment]
Yes, I get that. Thanks for the quick reply.

That is why I asked about making SF Mono the *default* (at least for the relevant iOS versions).

I looked at the commit that added the font picker. In `UserPreferences.m` I see that "Menlo" is hard coded ([here](https://github.com/ish-app/ish/blob/4f705ce2de0999419a6a5d3910ba3b3e91a92c6b/app/UserPreferences.m#L40)) which I guess is setting the default. If we change that to "SF Mono" (or some variant of it), will it work?

**Comment by shivaprsd** [comment]
Apple provides an official API for this: UIFont method [monospacedSystemFontOfSize:weight:](https://developer.apple.com/documentation/uikit/uifont/3042484-monospacedsystemfontofsize?language=objc) returns SF Mono. Please see [this](https://stackoverflow.com/a/58284532) (similar things talked about [here](https://useyourloaf.com/blog/tweaking-the-ios-system-fonts/) also).

Seeing `FontPickerViewController` [builds](https://github.com/ish-app/ish/blob/4f705ce2de0999419a6a5d3910ba3b3e91a92c6b/app/FontPickerViewController.m#L22) the list of fonts from `UIFont.familyNames` (which apparently does not contain SF Mono), we could add an entry in that table titled 'Default' that maps to use the above API method instead of `UIFont fontWithName:`.

I'm guessing all this from the docs, sorry if it's dumb 🙃

**Comment by saagarjha** [comment]
Yeah, so the problem here is the code currently assumes that the font family has a name that can be used consistently across the web view that the code renders in and UIKit's font APIs. Unfortunately SF Mono has no public name in UIKit (just the API you showed) and it's available as ui-monospaced on the newer versions of iOS we support. So this makes adding it a bit complicated, although not insurmountably so. It's something that I've wanted for a while but just haven't gotten around to, unfortunately.

**Comment by shivaprsd** [comment]
Indeed, it would require some different logic compared to the way iSH is currently choosing fonts.
No problem, I see that there has been progress on the custom-fonts issue. Custom-installed SF Mono is rendering fine on the latest TestFlight beta, I can live with that for now.

I would have liked it to be natively available on iOS. Let's close this as "yet another quirk of Apple". 🤷🏼‍♂️
