### ISSUE TITLE
External keyboard: maybe misconfigured SHIFT key mapping

### ISSUE THREAD

**Issue by xiongnemo** [ish-app/ish#1561]
Key combination [SHIFT] + [1] (!) causes following terminal output (maybe /dev/tty)

![IMG_0339](https://user-images.githubusercontent.com/38759782/132209106-a82949af-356d-4764-9542-8074e5f0e95c.PNG)

I'm using an Apple Magic Keyboard (A1644), while the iDevice is iPad Pro 12.9' (First Generation) (A1584).

Soft keyboard works fine:

![IMG_0340](https://user-images.githubusercontent.com/38759782/132209464-c87bc258-9a6e-4fdd-926c-54882dff2f83.PNG)

iSH version: 1.2.3 (237)

**Comment by mthused** [comment]
I'm also seeing this with the Apple Magic Keyboard on a 2021 iPad Pro 12.9- either hardware shift key + number keys switches VTs rather than type shifted symbols.  Need a better hardware key combo for this since it breaks functionality- (tried typing an email address, but it just switched terms rather than the '@' symbol).

**Comment by tuxtof** [comment]
Same problem for me with v1.2.3 build 240
iPad Pro 11" 2021 + external keyboard

Shift + symbol stop working

**Comment by tmachielse** [comment]
I’m experiencing this issue too.

version 1.2.3 build 240 
iPad Pro 11” (gen1) 
Magic keyboard A2261 (Dutch layout).

**Comment by fer-c** [comment]
+1 Same experience with Shift + %/$/£

**Comment by mthused** [comment]
This was bothering me enough to track down a way to fix it- here's a source patch that changes the key modifier to switch terminals from <Shift> to <Cmd>:

diff --git a/app/TerminalViewController.m b/app/TerminalViewController.m
index 7d03892..a4ef2de 100644
--- a/app/TerminalViewController.m
+++ b/app/TerminalViewController.m
@@ -418,7 +418,7 @@
         for (unsigned i = 1; i <= 7; i++) {
             [commands addObject:
              [UIKeyCommand keyCommandWithInput:[NSString stringWithFormat:@"%d", i]
-                                 modifierFlags:UIKeyModifierShift
+                                 modifierFlags:UIKeyModifierCommand
                                         action:@selector(switchTerminal:)]];
         }
         [commands addObject:

**Comment by tbodt** [comment]
Sorry about this - this shortcut is a sort of debugging hack and was originally command+shift+option. Changed it by mistake, will revert.
