### ISSUE TITLE
illegal instruction at

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#1573]
0x565dac9e: 0f 0b fc 89 c7 f3 a4 8b <details>
```ed Anaconda3-2018.12-Linux-x86.sh```</details>

**Comment by grassjelly** [comment]
hi, did you manage to get miniconda working on your machine?

**Comment by saagarjha** [comment]
This is an illegal instruction. As there isn't enough information here to reproduce this (it's not even clear it's a bug in iSH…) I'm going to close this.
