### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Krw96** [ish-app/ish#1575]
[![image](https://user-images.githubusercontent.com/86090957/135234625-f4374a01-12a3-400d-af30-582588aa2c42.jpeg)]()

**Comment by Krw96** [comment]
I'm not filing an issue only providing feedback per instructions in Application Apple TestFlight. Also I need help understanding how to change etc/motd/ to a usable directory. Each time I install them try to run I get a "not found" error. What /which directory do I need to be in, create or cd to? Thank you!

**Comment by 62f** [comment]
/etc/motd is not a _usable directory_, it's a non-configuration file named motd in the /etc directory which is displayed on OS-init. ```chdir /etc```<details>
Simply "to comment" in any  'issues' section on any GitHub project is to have filed a bug report, and despite literal objection, this can only be interpreted as such. Hereby we can only reckon that iSH's written instructions are insufficiently self-explanatory, so to supplement your bug report, the following visuals aid in locating interactive teachers and indicate site links for  motivational contributions:![image](https://user-images.githubusercontent.com/68332197/138162714-e049d817-2253-4158-bb79-824281fdcafe.jpeg)![image](https://user-images.githubusercontent.com/68332197/138162757-d8cc094d-8805-4865-af49-6652396c9d20.jpeg)</details>

**Comment by Mnpn** [comment]
Hiya, this TestFlight screen tells you how you can go about leaving feedback, and doesn't itself have to be submitted. It seems like your question regarding the motd has been answered though (it's a file, not a directory), so I'll go ahead and close this issue :)
