### ISSUE TITLE
Apk repos are reset every time iSH is opened 

### ISSUE THREAD

**Issue by LuNeder** [ish-app/ish#1585]
Following the wiki instructions to use Alpine repositories work, however whenever you close iSH and open it again those repos go back to the default iSH ones. If you add any extra repos, those are removed as well. In addition to this, imported filesystems are set to iSH repos instead of the ones that were set manually before exporting.

**Comment by fakeronan2** [comment]
This is not actually a iSH issue, it could be a iSH storage error, but most likely it is a Alpine bug.

**Comment by LuNeder** [comment]
> This is not actually a iSH issue, it could be a iSH storage error, but most likely it is a Alpine bug.

On https://github.com/ish-app/ish/issues/1518#issuecomment-958065133 they say that changing profile.d fixes it. Unless profile.d is not edited by iSH, I’d say this is an iSH bug (or iSH intended behavior maybe, idk).

**Comment by saagarjha** [comment]
This behavior is intentional and part of iSH. The file has a comment it now that explains a bit more about what is happening and why.
