### ISSUE TITLE
When I use an external keyboard, the last line is blocked by the Accessory View.

### ISSUE THREAD

**Issue by XaoflySho** [ish-app/ish#1590]
When I use an external keyboard, the last line is blocked by the Accessory View.

I am using iPhone 12 mini and iOS 15.0.2

![](https://i.loli.net/2021/10/18/rzw6EaeL3stKIuG.png)
![](https://i.loli.net/2021/10/18/Ft3i7gydEYzwUlq.png)

**Comment by 40yostudent** [comment]
Same issue here

**Comment by langcloud** [comment]
same here - can use external keyboard

**Comment by rpopic2** [comment]
same issue still happening here

**Comment by lump** [comment]
So far, iSH is one of the best terminal emulators for iOS I've seen.  I just have one qualm, though.

I have searched the iSH Discord and I have seen this asked again and again, but there never is a satisfactory answer.  I did see one answer from last year that says it is being worked on.  Well?  It's a year later...

When I use a Bluetooth keyboard (which is way easier to type on), The bottom line is cut off.  If I hide the bottom menu, then it puts a line through the cursor and impedes me from typing.  I have to disconnect my Bluetooth keyboard for it to put a decent enough margin at the bottom. but then I have to use the clunky soft keyboard.  I, too have "Hide Extra Keys with external keyboard" checked.  It doesn't help.

![cannot-see](https://user-images.githubusercontent.com/280484/161400342-a0287374-4b86-4fbf-a75e-583d4b851ba8.png)
![cannot-type](https://user-images.githubusercontent.com/280484/161400347-36186c5e-df96-4fb8-bf7d-a9dfdd373bb4.png)

**Comment by lump** [comment]
I discovered one way around this is to run GNU Screen and turn on the bottom status bar.

**Comment by kamil-malinski** [comment]
is there anything new about this problem? it still isn't fixed

**Comment by saagarjha** [comment]
#1881 should improve the situation here.

**Comment by liushihao456** [comment]
> #1881 should improve the situation here.

When will the update be in AppStore pls?

**Comment by 3rand0m** [comment]
I want to like this app but not seeing what i'm typing when using a keyboard really makes it cumbersome.

**Comment by victordariovera** [comment]
Same situation no iPad Pro.

**Comment by wangchun** [comment]
I have to connect to iSH from Blink through SSH because of this bug.

**Comment by saagarjha** [comment]
iSH 1.3 is out, which has fixes for this issue. Please try it out and file new issues with what you encounter!
