### ISSUE TITLE
iSH keeps background running when not used

### ISSUE THREAD

**Issue by micturkey** [ish-app/ish#1606]
Hi developers,
iSH is really great and I love it because I can do things that could not be done when iSH didn't exist.

My issue is, recently, when I am not using iSH and I am sure iSH is closed completely by removing it in iOS's multitask-switching center, the iOS battery preference tells me that iSH is running in the background for nearly one hour a day. (You can see it in the picture and "后台" means run in the backgound).
![image](https://user-images.githubusercontent.com/1297392/139539919-ca753574-3b13-41de-a42e-8425058c310b.png)

I am really confused and cannot figure out the reason because I did not give location permission or background app refresh permission to iSH. I also try reinstalling but no difference.

Could you please answer me:
How does iSH do that?
Will this affect iOS device's battery life?

Thank you very much!

**Comment by saagarjha** [comment]
We recently identified an oversight in our file provider that might be causing this: #1591. We’re hoping to push it out in an update soon, so let us know if it helps when we do!

**Comment by micturkey** [comment]
> We recently identified an oversight in our file provider that might be causing this: #1591. We’re hoping to push it out in an update soon, so let us know if it helps when we do!

Thanks for your reply!
Looking forward to the update :)

**Comment by cetorres** [comment]
Hi, how's the status on this? I can confirm that iSH is still running on the background for no apparent reason and consuming battery.

**Comment by saagarjha** [comment]
This is improved in master, but it's not in a public build yet.

**Comment by saagarjha** [comment]
iSH 1.3 is out, which has fixes for this issue. Please try it out and file new issues with what you encounter!
