### ISSUE TITLE
Turn off find my iPhone

### ISSUE THREAD

**Issue by Livingfree111** [ish-app/ish#1614]

**Comment by 62f** [comment]
Why? Did turning off findMy iPhone stop iSH crashes?

**Comment by gitdev-bash** [comment]
Close?

**Comment by 62f** [comment]
@gitdev-bash did you have a condition of continual crashes which was not solved by the proposed action? You perhaps should file a separate bug report.

**Comment by Mnpn** [comment]
Hi! iSH can't turn off Find my iPhone. You'll have to do that through your device's settings. (If this isn't what you were suggesting, please reply and add more details to your issue. Thanks!)
