### ISSUE TITLE
‘/proc/filesystems‘  No such file

### ISSUE THREAD

**Issue by YiguiDing** [ish-app/ish#1616]
service samba start↙️
grep: /proc/filesystems: No such file or directory

**Comment by awesomelewis2007** [comment]
check if the folder exists

**Comment by YiguiDing** [comment]
![image](https://user-images.githubusercontent.com/50746494/141522787-1da70e4e-670f-4377-8404-4a512f737b23.jpeg)

**Comment by YiguiDing** [comment]
Do you have such file in your device?

**Comment by awesomelewis2007** [comment]
no

**Comment by awesomelewis2007** [comment]
> Do you have such file in your device?

It's probably not in the file system

**Comment by awesomelewis2007** [comment]
#1666

**Comment by awesomelewis2007** [comment]
The file has been added to ish

**Comment by YiguiDing** [comment]
👌
