### ISSUE TITLE
Add fn keys

### ISSUE THREAD

**Issue by awesomelewis2007** [ish-app/ish#1628]
I am finding it hard to use ish without function keys I would like to see the function keys on the keyboard where the arrow keys are at thanks

**Comment by awesomelewis2007** [comment]
It would be nice to see something like this

![image](https://user-images.githubusercontent.com/60709927/142723029-c9b56ffe-754d-46be-9386-e229eea7867d.jpeg)![image](https://user-images.githubusercontent.com/60709927/142723030-bb84d769-1235-436f-8c26-a510e2d68808.jpeg)

**Comment by awesomelewis2007** [comment]
I'm going to close this if this issue doesn't get any more activity

**Comment by Rexogamer** [comment]
Please do not make veiled threats like these. The iSH dev team is very small and has a lot to do.

**Comment by Mnpn** [comment]
Hi! Nice screenshots! This is already a part of #311, so let's continue this discussion over there.
