### ISSUE TITLE
Does running iSH in Windows is possible?

### ISSUE THREAD

**Issue by ClickNinYT** [ish-app/ish#1655]
I'm trying to get iSH running under Windows by compiling it from MSYS2-Clang64. I know WSL exists but I want to try something newer. If it possible can anyone guide me?

**Comment by leo848** [comment]
Why would you want to run iSH on Windows? It is a emulator for [Alpine Linux](https://www.alpinelinux.org/), a very lightweight Linux distro. You can either boot it or load it in a VM.

**Comment by ClickNinYT** [comment]
@leo848 I know, but iSH is not exactly a VM or anything like that. It's a x86 user space emulator and syscall translation. It run Linux by reimplementing syscalls and Linux-specific stuff. In my opinion it's like WSL1 more than a VM. Running it in Windows would be very great for me. Because WSL1 is a closed environment and Windows-specific. But iSH can be compiled and run in  both MacOS, Linux and iOS, so I think Windows is possible, just not now. I'm getting progress with trying to compile it under MSYS2 environment, but it current stuck at `meson build` part.
