### ISSUE TITLE
Conflicting packages when upgrading apk

### ISSUE THREAD

**Issue by NotAFedoraUser** [ish-app/ish#1658]
Tried upgrading apk, got an error about mandoc conflicting with man-db

```
/sbin/apk upgrade
ERROR: unable to select packages:
  mandoc-1.14.5-r5:
    breaks: man-db-2.9.4-r0[!mandoc]
    satisfies: world[mandoc]
```
I tried running in the app with whatever apk was in path,
it said mandoc was trying write into a directory or file that man-db ‘owned’.
IIRC it was trying to write into `/usr/bin/man`.
On build 298, iPadOS 15.1

**Comment by tbodt** [comment]
I believe the solution to this is to uninstall man-db (apk del man-db) and then retry the upgrade.

**Comment by NotAFedoraUser** [comment]
Okay I did that, but it got an error code 256.
Not sure what that means, but you probably do 👍 
![26D51F80-63C3-4734-8DFC-E439075D5AF6](https://user-images.githubusercontent.com/20476845/147019293-6548db27-5137-417b-b78e-f0482c17eef9.png)

**Comment by tbodt** [comment]
It should be possible to fix this by running "apk fix" and then restarting the upgrade.

**Comment by NotAFedoraUser** [comment]
That fixed it. Thanks man, both for helping, and creating this very cool app. 👍
