### ISSUE TITLE
My ish

### ISSUE THREAD

**Issue by Jerry787898** [ish-app/ish#1660]
Top

**Comment by awesomelewis2007** [comment]
> Top

?

**Comment by 62f** [comment]
@awesomelewis2007
Capitalisation of ```top```, the Linux binary which reports resource-usage to con:, was probably unintentional.

**Comment by Mnpn** [comment]
Hi! If you've run into a problem with `top` that you're reporting we'd like to ask you to provide some more information about what said problem is and how we could reproduce it. Please add some more details to your issue describing the problem you're facing, and we'd be more than happy to re-open this!
