### ISSUE TITLE
Terminal Driver wraps user input incorrectly

### ISSUE THREAD

**Issue by tjcaul** [ish-app/ish#1673]
When entering a long command in the shell, the command wraps before the right edge of the screen, but only on the first line. Some other issues regarding text entry stem from this bug, too. I've attached a video to illustrate the issue.

https://user-images.githubusercontent.com/65415889/147499270-a2c3febf-8257-4542-b2c1-12954fb5c54c.MOV

**Comment by montipls** [comment]
I have the same issue, please help...

https://github.com/ish-app/ish/assets/145486508/916b061a-60e2-4354-8644-087481a8440d

**Comment by montipls** [comment]
Could it be because of the custom promt message? It does have a new line character in it, which might be messing with the text wrapping...

**Comment by montipls** [comment]
Found another bug when I set the font size bigger. First it seems like the first line wraps correctly, but then it wraps again after a few characters, and I can't even go back to the first line with backspaces...

https://github.com/ish-app/ish/assets/145486508/8ee99ac3-3f0f-4ebc-83c8-64efa5d050d7

**Comment by montipls** [comment]
Also, in the previous video you can see that when I autocompleted with tab, the previous --- just disappeared, and it didn't just scroll down, it actually disappeared.https://github.com/ish-app/ish/assets/145486508/1749456f-2079-43b4-9371-cfe58a0de281

**Comment by montipls** [comment]
idk whats going on but something is definitely broken

**Comment by tjcaul** [comment]
In Ash (the default shell), you may be able to fix it by enclosing any non-printing parts of your prompt (such as ANSI colour sequences) in `\[` and `\]`. For example, my PS1 looks like this:
`PS1="\[\e[32;1m\]\W >\[\e[0m\] "`
