### ISSUE TITLE
Terminal sometimes misses output from the applications

### ISSUE THREAD

**Issue by YeonJi2** [ish-app/ish#1677]
The terminal emulator in iSH seems to miss some outputs from the application. For example, this is the expected output when using "lsmod" on iSH:
```
phone:~# lsmod
lsmod: /proc/modules: No such file or directory
Module                  Size  Used by    Not tainted
phone:~#
```
However, sometimes it does not show one of the lines like this:
```
phone:~# lsmod
lsmod: /proc/modules: No such file or directory
phone:~#
```
Or missing the next shell prompt(Pressing return does print the prompt though):
```
phone:~# lsmod
lsmod: /proc/modules: No such file or directory
Module                  Size  Used by    Not tainted
(There's no phone:~# prompt at the end)
```
...Or missing the output entirely:
```
phone:~# lsmod
(There's no phone:~# prompt at the end)
```

Running "ls" or "ls -l" also seems to produce similar bug. Sometimes it also doesn't show next shell prompt, and I have to press return to get the prompt.

And while I'm not 100% sure if this is related issue, but Vim sometimes does not draw the screen properly as well. Switching between different tabs occasionally draws only half of the next tab.

## Temporary workaround
Running the terminal inside tmux can be used as sort of workaround for now. This is because tmux remembers output coming from the application and redraw the output as needed.
And because these issues does not occur every time, redrawing the tmux often fixes the issue.
Redrawing can be triggered using one of these methods:
- Running `tmux refresh-client`
- Changing terminal size (by rotating the screen or hiding the keyboard for example)
- Switching to other window(Ctrl-B n for example)
- Detaching the session(Ctrl-B d) and reattaching it(`tmux attach-session`)

# Version
iOS version: 14.6
iSH version: 1.2.3(Build 298)

**Comment by tbodt** [comment]
It happens i just fixed this. Could you try the TestFlight build from 1 minute ago?

**Comment by YeonJi2** [comment]
> 

I tried using the most recent TF build, and it seems like it has been fixed. Vim is still a bit glitchy, but the issue I've mentioned(drawing only half of the tab) is gone.

**Comment by rdanter** [comment]
I am noticing this issue too and just wondering when the next official update will be with the fix? (I am running the App Store version, not TF).

**Comment by Mnpn** [comment]
Hi! It sounds like this issue has been fixed. I'm marking it as complete since we've just shipped a new App Store release - but feel free to re-open it if you're still running into issues! Thanks :)
