### ISSUE TITLE
Node illegal instruction

### ISSUE THREAD

**Issue by awesomelewis2007** [ish-app/ish#1687]
![image](https://user-images.githubusercontent.com/60709927/148660612-d7a48808-f253-4532-aae4-7c108b81b31d.jpeg)

Device: IPad Pro 11" 2021
CPU: Apple M1

**Comment by Patronics** [comment]
Running node (after installing it with `apk add nodejs`) works fine on an iPhone 12, running node 8.14.0

**Comment by Rhinozz** [comment]
This is a duplicate of #1482/#1473.
