### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [ish-app/ish#1704]
Hey there!

I belong to an open source security research community, and a member (@michaellrowley) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by tbodt** [comment]
Feel free to contact me via the email on my github profile. Please understand though that I don't really want to maintain a security boundary between iSH and the iOS sandbox. (Maybe it would be fun to add a /dev/mem for arbitrary memory access by design!)

**Comment by JamieSlome** [comment]
@tbodt - thanks for your response and update here! ❤️ 

If you would prefer, you can directly access the report here:
https://huntr.dev/bounties/43301686-ef08-40eb-8d86-1d50aeb17f81/

It is private and only accessible to maintainers with repository write permissions.

**Comment by tbodt** [comment]
We now have a SECURITY.md: https://github.com/ish-app/ish/blob/master/SECURITY.md
