### ISSUE TITLE
This code does not appear to be thread safe

### ISSUE THREAD

**Issue by emkey1** [ish-app/ish#1707]
I've only had this happen once, so it is rare, but iSH recently crashed on the first line of list_remove() which is in **util.h.**  I assume this was because another thread removed the list while the function was being called.  I'm not sure even "list_remove_safe()" is safe as I don't see any locking?  

item=NULL  when the crash occurred.

```
static inline void list_remove(struct list *item) {
    item->prev->next = item->next;
    item->next->prev = item->prev;
    item->next = item->prev = NULL;
}

static inline void list_remove_safe(struct list *item) {
    if (!list_null(item))
        list_remove(item);
}
```

**Comment by tbodt** [comment]
It's not supposed to be thread safe. The caller needs to do the appropriate locking.

**Comment by emkey1** [comment]
Got it.  Apparently there is some place in the code where that isn't happening?

**Comment by tbodt** [comment]
Guess so. Should look at the caller.

**Comment by emkey1** [comment]
If I were smarter I would have at least taken a screenshot.  As it is I have no additional information.  

Yes, I suck.
