### ISSUE TITLE
Arrow keys on external keyboard not recognised

### ISSUE THREAD

**Issue by rexx-org** [ish-app/ish#1708]
With a fresh build of the current version of iSH (commit e2d17ee), when run either in a simulator or on a device with an external hardware keyboard, the arrow keys when pressed in the default shell no longer work as they do on the App Store version. ie retrieve the previous command and move through the command line.  Nothing is returned when pressing the arrow keys when running cat.

The arrow keys are registered in app/TerminalView.m;  keyCommands() but are not being recognised in app/TerminalView.m; handleKeyCommand(). TAB key (\t) is registered in keyCommands() just like the arrow keys but is being recognised in handleKeyCommands()

It appears that the arrow keys are being intercepted before handleKeyCommands() but I need some assistance in trying to find where that is happening.

I am planning on adding support for most keys on an external keyboard; function, PgUp, PgDn, etc with and without modifiers. Initially the support will hard-code escape sequences for the default xterm-256color terminal type. Next phase of implementation will be to use terminfo. I'll make it as easy as possible to support a third phase (maybe by someone else) to add Function Keys to the virtual keyboard as requested in #311

I have a working version that implements some function keys, PgUp, PgDn, Home, End, Del but needs some cleanup and working arrow keys before contributing.

**Comment by tbodt** [comment]
I've looked into this and I have absolutely no clue where the arrow key events are going. It does seem to be related to the SDK version. The only difference between the app store version (with working arrow keys) and a version that you build yourself is the version of Xcode used to build it. If you can figure this out I will be eternally grateful.

I don't think we need or want terminfo involved here. The terminal type is hardcoded to xterm-256color, so just hardcode the escapes that correspond to that.

**Comment by emkey1** [comment]
I can confirm that building with Xcode 12.4 on a MacOS 10.15.6 system magically fixes the issue.

Would it be worth filing a bug report with Apple?

**Comment by tbodt** [comment]
Yes, if you can come up with a minimal reproducer. (Though you might figure out what iSH is doing wrong in the process.)

**Comment by rexx-org** [comment]
The arrow keys are recognised in pressesBegan() but "disappear" in the call to super pressesBegan()
Other keys, including the function keys are recognised by pressesBegan() but when super pressesBegan() is called it does pass the key onto handleKeyCommands()

I'll investigate a workaround to process the keys in pressesBegan()

**Comment by francoisvignon** [comment]
this one close also the issue #1617 (iSh build 08 jan 2022 with up to date tools work fine with external keyboard)

**Comment by francoisvignon** [comment]
and building iSh now (xcode 13.2.1 13C100) and at commit abb7a654e8f1ba81669da1b3cd9526896a2ae327 without any change except Team, etc. give a release with not longer functional external keyboard arrows :-/

**Comment by francoisvignon** [comment]
and with a fresh build (Version 13.2.1 (13C100), commit abb7a654e8f1ba81669da1b3cd9526896a2ae327), a lot of CTRL-key  give strange result, like ^D not longer working, ^O issue a CR ...

**Comment by rexx-org** [comment]
Progress update...
The good news is I have all arrow keys, function keys, pgup, pgdn, home, end, del, ins/help working with external keyboards. Unmodified, shifted and control modifiers for these keys also produce relevant escape sequences.  All other keys also respond in unmodified, shifted, control and meta. Have tested with a few external keyboards with mixed success (issues are with keyboards, not iSH).  Midnight Commander works fine (with a small (MC) config change for arrow keys), and various curses programs including my text editor (THE) which is my main motivation.

I also have all keys repeating when a key or key combination is held down.  Two new UI configuration items are needed; delay before a key repeats and time between repeating each key. I'll leave that implementation to someone else, but at the moment they are defined as constants in the code.

All keyboard behaviour is now handled by pressesbegan/pressesended. This means that the above functionality is only available on iOS 13.4 or above which is when the HID keyboard interfaces were introduced.

Given the inconsistency with the current keyboard behaviour under the latest Xcode then maybe there is no ability to support prior iOS versions.

As I don't use git/github much I'll be working out how to create a PR for this:-)
