### ISSUE TITLE
Filesystem screwed up after installation

### ISSUE THREAD

**Issue by mc3** [ish-app/ish#1711]
I uninstalled old ish installation from my iPhone (ios 15.3), rebooted it and installed recent ish to start over.
Unfortunately, the shell does not find any program:
`apt update
-ash: apt: not found
`
/usr/bin is empty or can't be accessed.
In recovery mode, I see
`default
mounted at /
`
If I browse files, Files app shows files with 'forbidden' sign and question mark.
No access to the filesystem on the Mac via finder.

**Comment by JacksonChen666** [comment]
`apt: not found` occurs because ish uses [alpine linux](https://en.wikipedia.org/wiki/Alpine_Linux), which uses [`apk`](https://wiki.alpinelinux.org/wiki/Package_management) as the package manager and not `apt`.

also, can you try something basic like, `echo`?

**Comment by mc3** [comment]
echo works as expected.
apk works. (-;

On my iPad uname -a gives empty string.

Thanks for your help and sorry for the noise.
