### ISSUE TITLE
NPM - Illegal Instruction

### ISSUE THREAD

**Issue by richryan1951** [ish-app/ish#1724]
New install of iSH on IPad Pro M1. Ran the following
1. apk update
2. apk update
3. apk add nodejs
4. node -v (returned v14.19.0)
5. npm -v (returned unknown)
6. apk add npm
7. npm -v (returns Illegal Instruction)
8. dmesg returns:
100 stub syscall  383
100 stub syscall 375
100 illegal instruction at 0x56fbfc4d: 66 0f c2 d1 02 66 0f 54

>

**Comment by emkey1** [comment]
A workaround is to downgrade to the Alpine 3.12.9 minirootfs.  Node does not have this issue there.

**Comment by saagarjha** [comment]
The fix for this is already merged and will ship with the next version of iSH.
