### ISSUE TITLE
How is created the file menu?

### ISSUE THREAD

**Issue by yap241986** [ish-app/ish#1730]
How is created this?
![BEDBC1B4-23CD-421C-82C4-B3312404D215](https://user-images.githubusercontent.com/65458792/155235598-3a961875-09c8-4a88-a9e2-e143f57ff5c9.jpeg)

**Comment by saagarjha** [comment]
Again, this would be better served elsewhere, but iSH uses the [File Provider](https://developer.apple.com/documentation/fileprovider) API.
