### ISSUE TITLE
The repository does not work

### ISSUE THREAD

**Issue by HeavySnowJakarta** [ish-app/ish#1733]
These days I wanted to install a package,but when I inputted "apk update" it told me IO ERROR.At first I thought there was something wrong with my network environment,but when I tried to visit apk.ish.app website,I found surprisedly that the website seemed not a repository but a blog site,and there was not any dictionaries like "v3.14" or "v3.13".I am doubtful whether there is something wrong with the official repository website.What's more,every time I restart iSH the repository file is reset. I really hope you can give us the ability to change the default repository to another one,for sometimes a user may prefer a local repository to the official one because of web conditions.

**Comment by tjim** [comment]
Looks like this got fixed.
