### ISSUE TITLE
Illegal instruction in jpegoptim

### ISSUE THREAD

**Issue by snicolai** [ish-app/ish#1744]
Installed jpegoptim-1.4.6-r1 with apk just now.

```
# apk add jpegoptim
(1/2) Installing libjpeg-turbo (2.1.0-r0)
(2/2) Installing jpegoptim (1.4.6-r1)
Executing busybox-1.33.1-r6.trigger
OK: 7 MiB in 16 packages
# jpegoptim
jpegoptim: file arguments missing
Try 'jpegoptim --help' for more information.

# jpegoptim -t ORG*.jpg
ORG_DSC00924.jpg 5184x3888 24bit N Exif XMP IPTC JFIF  [OK] Illegal instruction
```
From dmesg:

26 illegal instruction at 0xf7f11192: 66 0f c4 42 20 02 66 0f 
27 stub syscall 383
27 stub syscall 383
27 stub syscall 383
27 illegal instruction at 0xf7f11192: 66 0f c4 42 20 02 66 0f 
28 stub syscall 383
28 stub syscall 383
28 stub syscall 383
28 illegal instruction at 0xf7f11192: 66 0f c4 42 20 02 66 0f 
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383

I did run it three times testing various parameters.

The current directory is mounted from working copy.

**Comment by saagarjha** [comment]
`pinsrw`

**Comment by Mnpn** [comment]
Hi! This appears to be working in iSH 1.3, which is now released!

```
# jpegoptim -t *.jpeg
d479765f3dcebcf6364aaba72af8f5d4.jpeg 2672x3344 24bit N Exif  [OK] 8991414 --> 7942470 bytes (11.67%), optimized.
Average compression (1 files): 11.67% (1024k)
```

Please give it a try after updating, and let us know if you encounter any other issues with jpegoptim! :)
