### ISSUE TITLE
[Advice] It is time to switch arm version and need essential work of the procfs 

### ISSUE THREAD

**Issue by jakitliang** [ish-app/ish#1750]
### Need higher performance and efficiency 

Apple m1 shows the success of ARM architecture around the world.

More and more OS supports ARM, and windows 11 for arm has already can run x86 app just like Rosetta does.

So if the developer will take Rosetta into ish so can run faster. Or can just switch to the arm version to run natively.

I don’t think “x86 version of alpine has more choice of package” in such moments. Any ARM arch OSs are now highly developed and has fewer and fewer diff from x86 and it is more energy efficient.

Otherwise, many program runs really really slow in ish.

Rails bundle install takes more than half an hour.

Compile any c project maybe take long long long time.

So I just using cross compile for ish programs in an external VM.

When I attach my self into laptop or pc, I consider the reason why do I need iPad or iPhone, why need ish?

So the moment I use pc, I don’t want ish.

So, obviously the choices are:

1. Add Rosetta into ish
2. Switch to ARM arch

### Improvement of ProcFS is needed

As I see, procfs didn’t work so that makes many programs runs bad. You can see errors here and there when start any service.

Those can not work:
NFS
Mount
Samba
And many other services
Many ruby gems
Many python packages

Maybe the fakefs module should be improved. Hope it can be essentially work and no error prompts out.

### Ish is great but 75% unusable

ish is a great idea and it is helpful for many coders and server maintainers.

I agree with the idea and design.

Year by years, hope ish be better.

**Comment by emkey1** [comment]
It is my understanding that iSH would not be allowed on the App store if it were natively ARM.  

It is essentially an interpreter of 32 bit Intel code with an emulator built on top of that which implements a subset of the Linux kernel. 

As you note, this isn't a very efficient way of doing things, but it is one that Apple is willing to let live on the App store.

**Comment by saagarjha** [comment]
We are aware of both of these problems and are actively working on improvements here, but given the limitations of the environment we're in the task is extensive and we have no fixed schedule for delivering this. There's not much here that's actionable so I'm going to close this, but feel free to follow along with development and reopen this if you feel like you have more to add.
