### ISSUE TITLE
No app icon on iPhone XS (MT942VC/A), iOS 15.3.1 with iSH 1.2.3 build 298

### ISSUE THREAD

**Issue by pstimmons** [ish-app/ish#1751]
Hi.

I’m trying to install the current version of ish on my iPhone but there is no app icon on the iPhone Home Screen (or desktop?). I can find the app through a search though. Sometimes It shows in the App Library page (recently installed, productivity and finance) but sometimes not at all after I install it.

I removed the app and tried again with same result. I restarted the iPhone (raise volume button, lower volume button then hold power button until the Apple logo comes on), same result. A previous version of the app installed correctly on my iPad Air 4th generation (MYFT2VC/A) with iOS 15.3.1.

I tried changing the app icon from the settings inside the app but it didn’t solve the problem.

iPhone XS (MT942VC/A), iOS 15.3.1 with iSH 1.2.3 build 298

Thanks,
Patrick Timmons

**Comment by saagarjha** [comment]
Hi! Can you check that the app isn't just hanging out in your App Library? Try searching for it and adding it to the homescreen, like so: ![image](https://user-images.githubusercontent.com/13786931/158072376-9a848c7d-c795-4840-81aa-4b84eea28a55.png)

**Comment by pstimmons** [comment]
I could manually add it to the Home Screen. Just found out about that.

As for the App Library, each install would produce a different result. I could see the app in the “recently installed” folder after the first install, in a “productivity and finances” folder upon the second install, not at all after the third install and in Siri’s suggestions after the fourth.

**Comment by Mnpn** [comment]
Hi, as far as I can tell this isn't a problem with iSH. You can make iOS automatically create Home Screen icons instead of just placing new apps in the App Library by going to iOS Settings > Home Screen, which might ease the confusion. The App Library folders are managed & sorted by iOS.
