### ISSUE TITLE
[SUGGESTION] Add "tabs" to the app

### ISSUE THREAD

**Issue by fxrysh** [ish-app/ish#1755]
I've seen a lot of terminal emulator add tabs so maybe iSH should have them. Maybe something like this?
![IMG_2790](https://user-images.githubusercontent.com/99307966/159143408-a24ed361-c3fe-4564-a36b-e895edabb6fc.png)

> **NOTE**: The picture was taken from [here](https://github.com/IMcD23/TabView) so maybe we can use that.

**Comment by Mnpn** [comment]
Hi! This is a duplicate of #563, let's keep all of the discussion about this to there :)

**Comment by fxrysh** [comment]
I see, thanks
