### ISSUE TITLE
Need more keys

### ISSUE THREAD

**Issue by exyq** [ish-app/ish#1769]
![2AE90998-06C4-4605-9B5F-450891247EBD](https://user-images.githubusercontent.com/88557903/161866752-48184064-80f6-46ae-adbc-b2d73a3a0ee8.jpeg)

Need . / - ! % ……

**Comment by Rhinozz** [comment]
You can find those symbols on iOS by pressing the "123" key (on the English keyboard, at least). The top row is reserved for things not found on the iOS keyboard, like CTRL and TAB.

**Comment by exyq** [comment]
iOS's those keys to touch so tired

**Comment by awesomelewis2007** [comment]
What about function keys like f1

**Comment by Mnpn** [comment]
Hi! We're not currently looking into adding symbols that are already available on the iOS keyboard to iSH's extended row of keys, but we've already got an open issue regarding keyboard improvements at #311. Perhaps there are some third-party iOS keyboards out there with better placements for those keys that could help you out? (Also, iOS supports external bluetooth keyboards, if that's more your thing.)

@awesomelewis2007, we're tracking all keyboard improvements (including function keys) over at #311.
