### ISSUE TITLE
Illegal instruction from pynacl

### ISSUE THREAD

**Issue by aewens** [ish-app/ish#1770]
Steps to reproduce:
1. Install pynacl
    $ apk add py3-pynacl

2. Attempt to encrypt a string:
    $ python3
    > from nacl.public import PrivateKey, Box
    > sa = PrivateKey.generate()
    > sb = PrivateKey.generate()
    > pb = sb.public_key
    > box = Box(sa, pb)
    > box.encrypt(b"Hello, world!")

This causes Python to crash with "Illegal instruction"

Using iSH 1.2.3 (Build 298)

**Comment by saagarjha** [comment]
Can you run `dmesg` and post the output here so we can see what the failing instruction was?

**Comment by Mnpn** [comment]
Hi, thanks for the report! This instruction is `psrld`, and has been implemented by #1695. I ran your example on a recent TestFlight build and it appears to run correctly, so the fix for this will ship in the next release of iSH!

**Comment by jason-conway** [comment]
You can install it with `apk add py3-pynacl` but you'll need to be running the TestFlight beta for it to work 100%

**Comment by jason-conway** [comment]
I haven't used it myself, but [altstore](https://ish.app/altstore) could be an option
