### ISSUE TITLE
git clone get block when resolving deltas

### ISSUE THREAD

**Issue by zhouxingoddog312** [ish-app/ish#1798]
it’s like this
remote: Enumerating objects: 601, done.
remote: Counting objects: 100% (461/461), done.
remote: Compressing objects: 100% (456/456), done.
remote: Total 601 (delta 185), reused 0 (delta 0), pack-reused 140
Receiving objects: 100% (601/601), 140.55 KiB | 219.00 KiB/s, done.
^Csolving deltas:   4% (10/228)
then i have to enter ctrl+c

**Comment by saagarjha** [comment]
This is #943.
