### ISSUE TITLE
Support JIT

### ISSUE THREAD

**Issue by upintheairsheep** [ish-app/ish#1803]
JIT is the thing that makes UTM and 6th generation console emulators run on iOS fast. Can you support JIT via AltJIT or Jitterbug so iSH runs fast?

**Comment by saagarjha** [comment]
This is possible but iSH is not currently designed to support this, so it would require rewriting the emulator. The plans for that are pretty nebulous since nobody's really working on that at the moment. Ideas for making the emulator faster belong under #129, FWIW.
