### ISSUE TITLE
apt update

### ISSUE THREAD

**Issue by mybookers** [ish-app/ish#1807]

**Comment by AronkyDev** [comment]
I dont think that's the good way to report an error

**Comment by kpetrilli** [comment]
Alpine Linux doesn’t have apt. It has apk (check motd)

**Comment by Mnpn** [comment]
Hi! I'm closing this as your issue lacks a description. If you're running into issues with apt, please post some more information and potentially even some ways we can reproduce it! Though keep in mind what's been stated above, iSH already has a package manager!
