### ISSUE TITLE
Node illegal instruction

### ISSUE THREAD

**Issue by LukIsHere** [ish-app/ish#1808]
So i’ve instaled latest alpine linux and now when i try to use node js it says illegal instruction.
![image](https://user-images.githubusercontent.com/92756992/168972121-fb563f84-8c9f-4f45-81b8-b33d2d437c11.png)
![image](https://user-images.githubusercontent.com/92756992/168972179-542b5594-5620-49e7-83d4-4e72f2ea81f1.png)
![image](https://user-images.githubusercontent.com/92756992/169527485-db129e75-e3c9-4c11-9a68-d0d9707b73e5.png)
![image](https://user-images.githubusercontent.com/92756992/169527509-20023275-5bfa-4e9d-a999-1f1aa7a00d26.png)

**Comment by Alex4386** [comment]
According to `dmesg` provided by @luktvpl, This issue requires #1809 to be resolved beforehand.

**Comment by saagarjha** [comment]
iSH 1.3 is out, which has fixes for this issue. Please try it out and file new issues with what you encounter!
