### ISSUE TITLE
nodejs-current needs punpckhdq

### ISSUE THREAD

**Issue by saagarjha** [ish-app/ish#1809]
although this might be a different issue, 

dmesg output with `nodejs-current` on latest testflight build resulted in:  
`25 illegal instructions at 0x571a0ee6: 66 0f 6a d0 66 0f 7e d0`.  
(although this (`apk add nodejs-current`) installed node 16.11.1)  

which suggests that lack of `PUNPCKHDQ` instruction (part of SSE2) on iSH. <sup><a href="https://en.wikipedia.org/wiki/X86_instruction_listings#SSE2_MMX-like_instructions_extended_to_SSE_registers">Reference</a></sup>
And is also missing in [/emu/decode.h](https://github.com/ish-app/ish/blob/master/emu/decode.h#L294) file.  

@luktvpl Please include your `dmesg` output. you can get this by running `dmesg` after you executed `node`

_Originally posted by @Alex4386 in https://github.com/ish-app/ish/issues/1808#issuecomment-1131713071_

**Comment by luktvpl** [comment]
Here is dmesg
![image](https://user-images.githubusercontent.com/92756992/169494859-87dd956e-d8ba-40e0-be2b-4d915092c5fd.png)
![image](https://user-images.githubusercontent.com/92756992/169494888-513616ad-28f5-4980-8e43-946aea0b0205.png)

**Comment by Mnpn** [comment]
Marking this as complete as iSH 1.3 includes fixes for node and punpckhdq was added in #1872.
