### ISSUE TITLE
Opensource.com, то, вероятно, знаете на него ответ: пользователи Linux хотят иметь возможность работать

### ISSUE THREAD

**Issue by Gopnicheg** [ish-app/ish#1831]

**Comment by Mnpn** [comment]
Hi, I've ran the title of this issue through Google Translate:
> Opensource.com, you probably know the answer: Linux users want to be able to work

This doesn't seem quite right. It could be a translation fault, but if you've got a question or suggestion for iSH, or if you're reporting an issue, please further describe it. If this is an advertisement, please refrain from posting it.
