### ISSUE TITLE
ssh-keygen not found

### ISSUE THREAD

**Issue by kaelchan** [ish-app/ish#1842]
Hi, I saw in previous issues that people are using `ssh-keygen` but I couldn't seem to run it. Am I missing anything? Thanks!

```
~# ssh-keygen -t ed25519 -C "my@email.com"
-ash: ssh-keygen: not found
```

Context: I was trying to use iSH for git repository management and was trying to clone from GitHub.

**Comment by TheGhostboi64** [comment]
try `apk add openssh`

**Comment by kaelchan** [comment]
Thanks! That works for me!

**Comment by TheGhostboi64** [comment]
No problem
