### ISSUE TITLE
git clone hangs

### ISSUE THREAD

**Issue by Daniil-Gusev** [ish-app/ish#1854]
Good day.  Maybe I'm not writing to the right address, but I hope I can get an answer.  For a long time I used git with iSH, but then, I did not understand what was the reason, git clone in iSH began to hang at the "resolving deltas" stage.  Perhaps someone knows how to deal with this problem without reinstalling iSH?  I will be very grateful for the answer.

**Comment by Mnpn** [comment]
Hi! See #943, it also contains a workaround you can use until the next update of iSH is released.
