### ISSUE TITLE
npm（Illegal instruction）

### ISSUE THREAD

**Issue by Rmtdi** [ish-app/ish#1857]
I downloaded npm and nodejs through "apk add npm"
then：
![image](https://user-images.githubusercontent.com/89687872/182804549-cdc5e3ae-dca5-4790-8f10-2de3ca0ad93f.jpeg)
(but "node -v" is ok）
and dmesg：
![image](https://user-images.githubusercontent.com/89687872/182810774-3112fb99-38f8-48b6-8c59-8e78fe4ce13b.png)
So,what should I do?
Please help me  :-D

**Comment by saagarjha** [comment]
This is fixed in master already, and will ship in the next update, so I'll close this issue for now.

**Comment by Rmtdi** [comment]
I want nodejs14+ if possible, thanks

**Comment by Rmtdi** [comment]
> This is fixed in master already, and will ship in the next update, so I'll close this issue for now.

I want nodejs14+ if possible, thanks;-)
