### ISSUE TITLE
The last one I did it with dall-e :)

### ISSUE THREAD

**Issue by theangraffiti** [ish-app/ish#1862]
![EA2814EF-07C1-418C-B806-BE37B0D0E542](https://user-images.githubusercontent.com/110776431/183296280-9cdee0c6-98d1-4e7d-b051-eb2d6f847e8d.png)
![5958E468-EAF2-4D62-83B7-C9CD0A0E8372](https://user-images.githubusercontent.com/110776431/183296287-c9365f09-3f8a-436c-8307-50bbbce52b59.png)
![D0CFBBC6-0E9F-43E0-8E3E-1FA1ACE6C399](https://user-images.githubusercontent.com/110776431/183296288-a2f93437-27de-4b4a-b7a4-31005870a657.png)
![73714349-B37B-4F04-81DC-D12F04B4DA77](https://user-images.githubusercontent.com/110776431/183296291-ffbf8761-2e17-4b6e-b554-1f6aba50aadc.png)

**Comment by Mnpn** [comment]
Hi! Let’s keep all icon submissions to #578. Thank you!
