### ISSUE TITLE
GDB /proc file path does not exist

### ISSUE THREAD

**Issue by Trollyal** [ish-app/ish#1870]
So, i’m trying to open and run simple hello world compiled c filed.

After launching `gdb -q ./a.out/` i can set breakpoints and stuff, but once i hit `run` all goes down crashing with following line `warning: unable to open /proc file '/proc/<35>/task/<pid>/maps' `.
Now the weird thing is that after checking other /proc folders, the maps seem to be located in `/proc/<pid>/maps` and that may be the reason for the crash.

Now, i’m a noob in this so bare with me please. Is it a bug or is it something that can be configured and if so, how?

Thanks in advance.

**Comment by saagarjha** [comment]
iSH doesn't implement tasks in procfs yet, so the latest version of GDB is unfortunately no longer very functional. I have a patch that I'll put up soon that should fix this, though.

**Comment by saagarjha** [comment]
This is fixed by #1880.
