### ISSUE TITLE
Proposal:  Use Debian instead of Alpine Linux on iSH

### ISSUE THREAD

**Issue by brunochanrio** [ish-app/ish#1891]
Hello, it's possible to make iSH to use Debian instead of Alpine Linux?

**Comment by saagarjha** [comment]
You are welcome to try loading a Debian rootfs into the app, it's just very likely that things will not work.

**Comment by emkey1** [comment]
At the very least you would need to stub a few syscalls and add the **movntdq** and **fcmovbe** processor instructions to get it working.
