### ISSUE TITLE
Proposal: Add CTRL and ESC and down and up arrow keys to the on screen keyboard

### ISSUE THREAD

**Issue by fakeronan2** [ish-app/ish#1909]
If your someone who uses nano or Vim, you know that it is hard or impossiable to use it (if you don't have a external keyboard) as iSH does not currently have CTRL and ESC keys and arrow keys on the on screen keyboard. If you have used Termux before you know that it has all those features. I personally used the Alpine Linux rootfs instead of the built in iSH version as the iSH one has more limits than the offical Alpine Linux rootfs. It would also make it easier to change the repositories and many other things.

**Comment by saagarjha** [comment]
![image](https://user-images.githubusercontent.com/13786931/190883132-7c49e1e3-ee17-4310-a307-dceaf6dc4489.png)
