### ISSUE TITLE
Fix setup hostname

### ISSUE THREAD

**Issue by fakeronan2** [ish-app/ish#1914]
iSH info:
Running 1.24 (TestFlight version)
Running the offical Alpine Linux rootfs using edge version.

Error: hostname: sethostname: Operation not perm
Then openrc says hostname failed to start.
The issue with the hostname not able to start is that services like networking and chronyd can not run with out the hostname running.
![image](https://user-images.githubusercontent.com/111684799/192126236-296332d0-4ef3-42aa-bc4d-aa6a138f3a6a.png)
How to reproduce: First, download the offical Alpine rootfs and import it and switch the default iSH to the Alpine rootfs. Then run setup-alpine. Once you did that change the init system to openrc.
Restart the Alpine enviorment by typing in exit.
Run openrc and you will see that the hostname can't start.

If you think it is because the hostname wants to change the actual hostname on the host iOS device it is wrong as iSH runs in a sandboxed enviorment completly seperated from the iOS system.
And it would be able to make the hostname for the Alpine rootfs enviorment as the hostname could be virtualized to that virtualized system.

**Comment by rbreaves** [comment]
This prevents syslog, rsyslog and syslog-ng from working from all appearances. Really limits debug capabilities.

**Comment by Poocunt** [comment]
Is anybody working to fix this????
