### ISSUE TITLE
Consider switching the default rootfs to x64 by default and allow for x64 Alpine rootfs to be run

### ISSUE THREAD

**Issue by fakeronan2** [ish-app/ish#1915]
As the x86 architure is being phased out and more and more applications are starting to drop support for x86 it is only a matter of time before Alpine and most applications stop supporting it. Even though Alpine can run on very old systems due to its lightweight kernel and switching heavy weight packages like sudo and coreutils to doas and busybox and glibc to musl (But you can install compatablity layers to make programs that only work on glibc run on alpine). The removal of x86 will also be needed as the Linux kernel will eventually not support x86 causing security issues for older systems that use x86.

**Comment by saagarjha** [comment]
This is essentially a duplicate of #282.
