### ISSUE TITLE
movhpd

### ISSUE THREAD

**Issue by saagarjha** [ish-app/ish#1918]
from `npm i is-even`

```
illegal instruction at 0x57124d69: 66 0f 16 48 1c 0f 11 48
```

**Comment by jason-conway** [comment]
I've got movhpd and a test written for it that will be included in #1898

**Comment by saagarjha** [comment]
Ah, nice! I guess we should try to get that one merged, then.

**Comment by Mnpn** [comment]
Marking as complete; `movhpd` was added with #1926 and `npm i is-even` works in iSH 1.3.
