### ISSUE TITLE
Add guide for using other rootfs

### ISSUE THREAD

**Issue by fakeronan2** [ish-app/ish#1925]
A guide that tells you how to change the syscalls, to make operating systems like Debian, Ubuntu (older versions as it dropped i386 support in 18.04), Arch Linux 32. It would be useful, as you would have not to chroot into one which causes limitations due to how chroot works, or you have to spend hours finding out how to change a few syscalls around.

**Comment by saagarjha** [comment]
Are you asking for a guide, or planning on contributing one?

**Comment by fakeronan2** [comment]
> or

Asking for a guide

**Comment by saagarjha** [comment]
A very sort summary would be that the prerequisites are being familiar with C and how operating systems work. Our system call table is in [calls.c](https://github.com/ish-app/ish/blob/master/kernel/calls.c). To add a new one, or fix an existing one, look up the system call number for the one you care about and modify it as appropriate. System call numbers for x86 Linux are available [here](https://chromium.googlesource.com/chromiumos/docs/+/HEAD/constants/syscalls.md#x86-32_bit) for reference. Peek at the other implementations for idioms as to how we generally write these, for example when peeking at the pid (take `pids_lock`) or read/write memory (`user_read`, `user_write`). We take a number of liberties with fidelity, so if you have questions about a specific syscall feel free to ask and we might have advice for you :)

**Comment by fakeronan2** [comment]
> A very sort summary would be that the prerequisites are being familiar with C and how operating systems work. Our system call table is in [calls.c](https://github.com/ish-app/ish/blob/master/kernel/calls.c). To add a new one, or fix an existing one, look up the system call number for the one you care about and modify it as appropriate. System call numbers for x86 Linux are available [here](https://chromium.googlesource.com/chromiumos/docs/+/HEAD/constants/syscalls.md#x86-32_bit) for reference. Peek at the other implementations for idioms as to how we generally write these, for example when peeking at the pid (take `pids_lock`) or read/write memory (`user_read`, `user_write`). We take a number of liberties with fidelity, so if you have questions about a specific syscall feel free to ask and we might have advice for you :)

What I am asking for is a actual complete guide for the iSH wiki.

**Comment by saagarjha** [comment]
I believe you are significantly misunderstanding the process for improving iSH's system call compatibility. This is not something that can be automated nor would it be advisable to attempt it without the perquisites I mentioned above.

**Comment by fakeronan2** [comment]
I am making a proposal to add a guide to the iSH wiki, not asking for someone to tell me a guide.

**Comment by saagarjha** [comment]
I'm not entirely sure what you are suggesting but if you expect action from our side please let us know.

**Comment by Rexogamer** [comment]
I think they want someone else to write a guide on how to run other distros, but as you mention it's currently a lot harder than a guide could really help with due to the various missing system calls
