### ISSUE TITLE
Keyboard disappears on iOS 15.7

### ISSUE THREAD

**Issue by Daniil-Gusev** [ish-app/ish#1937]
I am a blind user using voiceover screen reader.  After updating my device to iOs 15.7, when using iSH, I very often hide the keyboard as if I pressed the "Hide Keyboard" button, but I did not.  Because of this, it became simply impossible to use the program, since the keyboard disappears almost instantly after it was displayed again.  With a bluetooth keyboard, this problem unfortunately persists.

**Comment by saagarjha** [comment]
Does this problem *only* occur when you're using a Bluetooth keyboard?

**Comment by Daniil-Gusev** [comment]
No, the problem also occurs if you use the on-screen keyboard.

**Comment by saagarjha** [comment]
Would it be possible for you to share a screen recording of this happening? I tried on my end and I didn't spot anything like this…

**Comment by saagarjha** [comment]
Also, do you happen to have "Full Keyboard Access" enabled?

**Comment by Daniil-Gusev** [comment]
No, I don't use this option.  The only thing I did was update the iOS version, after which the described problem arose.

**Comment by saagarjha** [comment]
I have reproduced and identified the bug, it's this change in WebKit: https://github.com/WebKit/WebKit/commit/3dc8889f1c0b63a64b3d5f7a255360074344c926. Now, to figure out how to fix it…
