### ISSUE TITLE
I have iPhone 7plus and iam using ish shell uname linux and i also face this problem resolving deltas stop in 0 

### ISSUE THREAD

**Issue by professor123456788** [ish-app/ish#1938]

**Comment by professor123456788** [comment]
I have iPhone 7plus and iam using ish shell uname linux and i also face this problem resolving deltas stop in 0

**Comment by Mnpn** [comment]
It sounds like you're talking about #943. This issue has already been resolved and a fix will ship in the next release of iSH. In the meantime, there's a workaround you can use mentioned [here](https://github.com/ish-app/ish/issues/943#issuecomment-783005151).
