### ISSUE TITLE
Date to show time 

### ISSUE THREAD

**Issue by MattIOSiSH** [ish-app/ish#1948]
Hi,
I currently get the time via:
#
date | awk '{print $4}'
  
For the life of me I can’t use the real date options to show me the time (hh:mm:ss)  ‘properly’ - that is, using the date options and format options.
  
  I’d simply like to get it more compatible with my Ubuntu and WSL implementations.
 
 Any help/examples would really be appreciated.

TIA, Matt

**Comment by saagarjha** [comment]
What did you try? Busybox's date is a bit minimalistic, but most of the strftime options should work.

**Comment by itskenny0** [comment]
What do you mean? Works just fine:
``` ajfon-kenni:~# date "+%Y-%m-%d %H:%m"
2022-11-03 08:11 ```

**Comment by MattIOSiSH** [comment]
> What did you try? Busybox's date is a bit minimalistic, but most of the strftime options should work.

Thanks for your reply. Here's the attempts I've made:

Usage: date [OPTIONS] [+FMT] [[-s] TIME]

Display time (using +FMT), or set time

        -u              Work in UTC (don't convert to local time)
        [-s] TIME       Set time to TIME
        -d TIME         Display TIME, not 'now'
        -D FMT          FMT (strptime format) for -s/-d TIME conversion
        -r FILE         Display last modification time of FILE
        -R              Output RFC-2822 date
        -I[SPEC]        Output ISO-8601 date
                        SPEC=date (default), hours, minutes, seconds or ns

Recognized TIME formats:
        @seconds_since_1970
        hh:mm[:ss]
        [YYYY.]MM.DD-hh:mm[:ss]
        YYYY-MM-DD hh:mm[:ss]
        [[[[[YY]YY]MM]DD]hh]mm[.ss]
        'date TIME' form accepts MMDDhhmm[[YY]YY][.ss] instead
 👎🏻

**Comment by MattIOSiSH** [comment]
> What do you mean? Works just fine:
> 
> ```
> 
> ajfon-kenni:~# date "+%Y-%m-%d %H:%m"
> 
> 2022-11-03 08:11
> 
>  ```

Thanks so much. You didn't have seconds (ss or SS) and that was tripping me up, but you *did* have mixed case and that was *also* tripping me up. Your format is just what I was looking for. I can't thank you enough.

**Comment by MattIOSiSH** [comment]
> date | awk '{print $4}'
 
Matt, 
Clearly that's the wrong way to do it.
Although it should be obvious to you, here's the correct way:

echo `date "+%H:%m:%s" | awk ' { printf("%s\n",substr($0,1,8)) } ' `

**Comment by MattIOSiSH** [comment]
One last comment. Here's a script that sums it up. (btw matt you forgot the double quotes. See below.)

#
echo " "
echo "This script shows 4 methods of displaying "
echo "the time in iSH. "
echo "It was a long, strange journey to get here. "
echo "Enjoy! "
echo " "
echo "(btw it sleeps for 1 second because iSH "
echo "doesn' like us to do things too quickly...)"
echo " "
#
echo "My time.sh (preferred):"
echo "date | awk '{print \$4}'"
date | awk '{print $4}'
echo " "
echo "Sleeping one second for poor widdle iSH..."
sleep 1
echo " "
echo "Like the above just more verbose:"
echo "date +\"%H:%m:%s\" | awk ' { printf("%s\\n",substr(\$0,1,8)) } ' \`"
date +"%H:%M:%s" | awk ' { printf("%s\n",substr($0,1,8)) } '
echo " "
echo "Sleeping one second for poor widdle iSH..."
sleep 1
echo " "
echo "And then, no seconds in ss format:"
echo "date +\"%H:%M\""
date +"%H:%M"
echo " "
echo "Sleeping one second for poor widdle iSH..."
sleep 1
echo " "
echo "And the best one (again - I - came up with):"
echo "date +\"%T\""
date +"%T"
echo " "
echo "That's all!"
echo " "

**Comment by Mnpn** [comment]
Hi, I'm closing this as it seems you found your answer!
