### ISSUE TITLE
Tkinter in iSH

### ISSUE THREAD

**Issue by techiebirb** [ish-app/ish#1957]
In iSH, I installed Python 3 and installed tkinter with apk add. However, when running a sample tkinter program (attached), it gave this error:
![656976FF-406C-4626-9EF9-7C8297FDD325](https://user-images.githubusercontent.com/73718824/201475837-d579c706-56e5-4a0d-b179-bbbe66efc745.jpeg)

By searching online, I tried entering `$ export DISPLAY=:0.0` and now I got a different error:
![E5210D9D-9CBE-4011-98FD-593108A5C950](https://user-images.githubusercontent.com/73718824/201475944-c575a978-a762-4144-a159-52d06354509a.jpeg)

Finally, I tried `$ export DISPLAY=unix$DISPLAY` and got
![A0F2FC5D-ECE0-4DFD-A16E-998939514DAF](https://user-images.githubusercontent.com/73718824/201476064-eae8e470-2cd5-46a8-b5dc-2a6883e311b7.jpeg)

Is this a problem on my side or were my hopes too high? The clock.py file I tested is
[https://drive.google.com/file/d/1ofe8xPVspayNRmZMea9bT25_MNI1Y97c/view?usp=drivesdk](here).

**Comment by saagarjha** [comment]
iSH does not have a framebuffer, so I'm unsure what you expect this code to do.
