### ISSUE TITLE
Qopotan

### ISSUE THREAD

**Issue by Qopotan** [ish-app/ish#1967]
Git Gi

**Comment by Mnpn** [comment]
Hi, this doesn't look quite right. If you meant to open an issue, please add more information to it. If you do, we'll reopen it.

**Comment by Qopotan** [comment]
> Git Gi

**Comment by Qopotan** [comment]
> Git Gi

exit

**Comment by Qopotan** [comment]
> Hi, this doesn't look quite right. If you meant to open an issue, please add more information to it. If you do, we'll reopen it.

exiting

**Comment by Qopotan** [comment]
> Hi, this doesn't look quite right. If you meant to open an issue, please add more information to it. If you do, we'll reopen it.

exiting
