### ISSUE TITLE
newest command line invisible when reaching the end of page

### ISSUE THREAD

**Issue by YYCCaa** [ish-app/ish#1972]

**Comment by andre-priebe** [comment]
I have the same issue with iPad Pro 11‘ (4th Generation) - screenshot attached. Any ideas on that? Thanks!
![A4CF1584-D04D-49B4-B2C6-BFADD29ECF62](https://user-images.githubusercontent.com/70572931/213800580-c74a6635-ba3b-421f-9fac-82d60cbbec65.png)

**Comment by saagarjha** [comment]
Should be fixed by #1881, which will ship in the next release.
