### ISSUE TITLE
Git clone freezes on resolving deltas iPhone 8 iOS 16.1.1 (A11)

### ISSUE THREAD

**Issue by JoshAtticus** [ish-app/ish#1975]
Been testing out iSH, and I reckon it's super cool, but I haven't really been able to test it to it's limits because I can't git clone anything.

![image](https://user-images.githubusercontent.com/72828296/205473408-442b151a-7364-4011-92f2-36d3af5049fe.png)

**Comment by kalitara** [comment]
I also experience this. The clone process stalls while resolving deltas.
I’m on a 6th Gen iPad Pro 12.9 with iOS 16.2.

**Comment by Hanibal911** [comment]
What's the solution in this? I'm also the same problem.

**Comment by JoshAtticus** [comment]
None yet

**Comment by object-Object** [comment]
From Yato on Discord: Setting `git config --global pack.threads "1"` seems to help.

**Comment by JoshAtticus** [comment]
> From Yato on Discord: Setting `git config --global pack.threads "1"` seems to help.

I will test that! I have an iPhone 12 now so I wonder if it just works normally on that.

**Comment by saagarjha** [comment]
iSH 1.3 is out, which has fixes for this issue. Please try it out and file new issues with what you encounter!
