### ISSUE TITLE
Support for GCC

### ISSUE THREAD

**Issue by fakeronan2** [ish-app/ish#1996]
It would make the process of building the source code for users who use GCC easier as Clang can be considered bloated for some.

**Comment by saagarjha** [comment]
We support builds with GCC, it's even tested by CI: https://github.com/ish-app/ish/blob/4eb18df76faa2120e94ed822ac455dd2a6fe0a2f/.github/workflows/ci.yml#L13. If you find that something's broken feel free to reopen this issue or file a new, more specific, one.
