### ISSUE TITLE
Git clone stuck at “resolving deltas” AND feature request

### ISSUE THREAD

**Issue by Pastlecry** [ish-app/ish#2003]
I tried to reinstall git but didn’t worked as well I’ve had this issue several times after last months update
Also it would be good if we had multiple terminals and I thing it’s a really good idea :)

**Comment by erauner12** [comment]
Yeah I am seeing the same thing here on the testflight version:

```bash
(05:38 ish /main_vault)-> git remote update
Fetching origin
fatal: unable to access 'https://github.com/erauner12/main_vault.git/': Failed to connect to github.com port 443 after 75040 ms: Operation timed out
```

but it connects fine on app store version of iSH:

```bash
iPad-2:~/obsidian/main_vault# git remote update
Fetching origin
Username for 'https://github.com': 
…
```

**Comment by Mnpn** [comment]
Hi! I think what you're running into is #943. This has already been resolved, and a fix for it will ship in the next release of iSH (in the meantime, there's a workaround mentioned in [this comment](https://github.com/ish-app/ish/issues/943#issuecomment-783005151)). You mentioned "last month's update", though, so I'm wondering if you're on the TestFlight beta? (The issue should be fixed there.)

Regarding multiple terminals, iSH supports multiwindow on iPadOS. There's an open issue for tab support you can track at #563, but I think it might be worth looking into using `tmux` or `screen` :)

**Comment by Pastlecry** [comment]
ok thanks a lot :)
