### ISSUE TITLE
testflight AOK version cannot connect to github.com

### ISSUE THREAD

**Issue by erauner12** [ish-app/ish#2004]
Comparing results of `git remote update` on both versions

iSH AOK testflight version (`1.2.4`)
```bash
(05:38 ish /main_vault)-> git remote update
Fetching origin
fatal: unable to access 'https://github.com/erauner12/main_vault.git/': Failed to connect to github.com port 443 after 75040 ms: Operation timed out
```
Seems it is having issues connecting to external hosts? DNS maybe?
- `Failed to connect to github.com port 443`

but it connects fine on app store version of iSH version (`1.2.3`):

```bash
iPad-2:~/obsidian/main_vault# git remote update
Fetching origin
Username for 'https://github.com': 
…
```

**Comment by erauner12** [comment]
anyone else having a similar issue?

**Comment by saagarjha** [comment]
Please file issues against iSH-AOK with the maintainers of that project.
