### ISSUE TITLE
Develop the application for iOS 9.3.5

### ISSUE THREAD

**Issue by ElectroFactory** [ish-app/ish#2008]
Hello, could you develop the application for iOS 9.3.5? I would like to install iPad Linux on it and I need this application to set it up, as my device is too old, the application available on the Apple store is not compatible and the 1.0.64 available on GitHub is also not compatible.

**Comment by tbodt** [comment]
If your device is too old to run iOS 11, that means it is a 32 bit device, which isn't supported.
