### ISSUE TITLE
Test Flight beta is full

### ISSUE THREAD

**Issue by martinorob** [ish-app/ish#2011]
Please @tbodt may you free up some Test Fligh slots?

Thanks

**Comment by miron** [comment]
Would love to join it too, when running vim in ish, the buffer gets messed up sometimes and I have to constantly hit ctrl-L to redraw it, sometimes I don’t and when I save the file, it messes up bits of it.

**Comment by bpsib** [comment]
Same problems with nano and Ctrl-L doesn’t fix it properly. I have ended up using it within tmux and just keep hitting Ctrl-b r to keep redrawing.

**Comment by Mnpn** [comment]
Hi! Letting you know that we've cleared up slots in the TestFlight beta after releasing 1.3. If you'd like to help beta-test iSH, [we'd love to have you on board](testflight.apple.com/join/97i7KM8O), and if you were looking for the improvements and fixes that've been on there, the latest [App Store release](https://apps.apple.com/us/app/ish-shell/id1436902243) is hot off the press! 😃 
Please give it a try, and let us know if you run into unexpected behaviour by filing new issues. Thank you!

**Comment by miron** [comment]
I randomly tried after the release and was in, now I know why :) Thank you!
