### ISSUE TITLE
Trying to run any rust programs results in a Invalid instruction

### ISSUE THREAD

**Issue by Luxvao** [ish-app/ish#2013]
If you install rust and cargo through apk, you wont be able to run any programs written in rust (if you run cargo run, it will output Invalid instruction)

Steps to reproduce:
1. apk add cargo
2. cargo new test
3. cd test
4. cargo run

**Comment by DuckyBlender** [comment]
Rust is unsupported, as stated in the wiki

**Comment by Mnpn** [comment]
Hi! See issue #67.
