### ISSUE TITLE
Fish doesn't respond

### ISSUE THREAD

**Issue by HeavySnowJakarta** [ish-app/ish#2018]
Each time running `fish`, it works at first, but soon the terminal would stop responding.

Info:
```
iPadOS 15.5
iSH 1.2.3, build 298
Alpine v3.14
Fish v3.2.2
```

**Comment by Mnpn** [comment]
Hi! We've recently released iSH 1.3 which seems to resolve this issue (fish appears to be running well for me). Please let us know if you're still running into this issue, and feel free to re-open this issue if so! Thank you!
