### ISSUE TITLE
abdulrahmanalkulaib11@gmail.com

### ISSUE THREAD

**Issue by Qopotan** [ish-app/ish#2029]
Qopo4tan

**Comment by Qopotan** [comment]
Debian
WIKI
ولوج
FrontPage
RecentChanges
FindPage
HelpContents
  
Debian
Wiki/
ولوجمعلوماتالمرفقات

coreutils

Translation(s): English - Italiano

For basic usage of a command line shell, it is good to know about programs provided by the coreutils package.

The GNU Core Utilities are the basic file, shell, and text manipulation utilities of the GNU operating system. These are the core utilities which are expected to exist on every operating system.

Commonly used tools provided by this package include:

chmod - changes file modes/permissions
chown - change file owner and group ownership
chroot - Changes the root directory.
cp - copy files and directories
dd - copies and converts a file
df - shows disk free space on filesystems
du - shows disk usage on filesystems
ln - creates file links
ls - list directory contents
mkdir - create directories
mv - move (rename) files
rm - remove (deletes) files
rmdir - remove empty directories
touch - changes file timestamps or create empty files
Text/shell utilities
Find, search, replace, compare, manipulate text, and basic shell scripting functions

[ ] or test - Check file types and compare values
basename - strip directory and suffix from filenames
cat - print (and concatenate) files to the standard output
comm - compare two sorted files line by line
cut - remove sections from each line of files
dirname - Removes the last level or filename from a given pathname.
echo - Prints a line of text.
expand, unexpand - convert tabs to/from spaces
false - Returns an unsuccessful exit status.
fmt - simple optimal text formatter
fold - wrap each input line to fit in specified width
head - output the first part of files
join - join lines of two files on a common field
md5sum - compute and check MD5 message digest
paste - merge lines of files
pr - convert text files for printing
seq - Print numeric sequences.
sleep - Suspends execution for a specified time.
sort - sort lines of text files
split - split a file into pieces
tail - output the last part of files
tee - Sends output to multiple files.
test or [ ] - Check file types and compare values
tr - translate or delete characters
true - Returns a successful exit status.
uniq - remove duplicate lines from a sorted file
wc - print the number of bytes, words, and lines in files
yes - Print a string repeatedly.
System utilities
date - Prints/sets the system date and time.
env - Displays/modifies the environment.
groups - Print the groups that the user is a member of.
hostname - Print or set the machine name.
id - Print real/effective uid/gid.
nice - Modify scheduling priority.
pwd - Print the current working directory.
su - Allows you to adopt the id of another user or superuser (see also sudo)
uname - Print system information.
who - Print a list of all users currently logged in.
whoami - Print effective user id.
Other coreutils commands include: chgrp, cksum, csplit, dir, dircolors, expr, factor, hostid, install, link, logname, mkfifo, mknod, nl, nohup, od, pathchk, pinky, printenv, printf, ptx, shred, stty, sum, sync, tac, tsort, tty, unlink, users, vdir

History

Previously these utilities were offered as three separate sets of GNU utilities: fileutils, shellutils, and textutils. Those sets have been combined into a single set of utilities called the coreutils.

Debian Woody shipped with the fileutils, shellutils, and textutils packages. Sarge shipped with coreutils. In Sarge and Etch the fileutils, shellutils, and textutils were dummy transition packages to facilitate upgrades. In Etch and later they may be safely removed.

CategoryCommandLineInterface | CategorySoftware | CategorySystemAdministration | CategoryRedundant: (work in progress) merge with ShellCommands

coreutils (آخدر تعديل 2020-05-07 13:50:21)
Debian privacy policy, Wiki team, bugs and config.Powered by MoinMoin and Python, with hosting provided by Metropolitan Area Network Darmstadt.

**Comment by Mnpn** [comment]
Hi again! Unfortunately I'm not quite sure what you mean here. :( Are you running into an issue with coreutils? If you're asking for help or reporting a problem, we'll need some more information to be able to help! If you add some, we'll reopen this issue.
