### ISSUE TITLE
Error code -8

### ISSUE THREAD

**Issue by tolikes** [ish-app/ish#2037]
The error appears when I try to import the aarch64 system file

Is it only x64 compatible for iOS?
![CFB38162-AB76-46D5-819C-C5BF14CC0788](https://user-images.githubusercontent.com/6198417/217283597-8e076182-b7b7-461a-a51b-4a86dd02c8a0.png)

**Comment by Mnpn** [comment]
Hi! iSH emulates x86 (not ARM, nor x86-64), so see if you can find that!
