### ISSUE TITLE
Alx

### ISSUE THREAD

**Issue by QwesiJay** [ish-app/ish#2053]

**Comment by Mnpn** [comment]
Hi! This doesn't look quite right. If you meant to open this issue, please add some more details describing your issue/report/request to it. We can reopen it if you do.

**Comment by QwesiJay** [comment]
please i dont get you

**Comment by Mnpn** [comment]
I'm sorry! To clarify, you did not provide a description in your issue, and we unfortunately can not understand what you mean by just "Alx". Is something not working in iSH, are you trying to request a feature, or are you asking for help? We can help if you explain it in further detail!

**Comment by QwesiJay** [comment]
I fixed it.
