### ISSUE TITLE
Why are there xfce packages installed and can I uninstall them?

### ISSUE THREAD

**Issue by R-Rothrock** [ish-app/ish#2054]
I just installed `ish` on my phone and I really like it. I was using `a-shell` before and this is so much better (and smaller). But I noticed, when running `apk list` that there are various xfce packages installed, yet I don't see why or how. Is that supposed to be there, and why?

Thanks in advance,

~Roan

**Comment by saagarjha** [comment]
`apk list` shows all available packages, rather than what is installed.

**Comment by saagarjha** [comment]
The list is generated from the index it maintains, rather than the internet.

**Comment by R-Rothrock** [comment]
Oh. Sorry, for the confusion and the dumb question.

**Comment by emkey1** [comment]
> I considered that, so I disconnected wifi, and it was still there. I apologize if this is a simple misuse.

The package manager has a local database that has entries for all the packages currently available.  You don't have to be connected to the Internet to use it.

The command you want is 

```apk info```

That will show only locally installed packages.

**Comment by R-Rothrock** [comment]
Sorry. I’m new to alpine.
