### ISSUE TITLE
![image](https://user-images.githubusercontent.com/59120512/204269184-c6db31c5-43d2-4b6a-8993-442038275c7a.jpeg)

### ISSUE THREAD

**Issue by ret708** [ish-app/ish#2072]
![image](https://user-images.githubusercontent.com/59120512/204269184-c6db31c5-43d2-4b6a-8993-442038275c7a.jpeg)

_Originally posted by @aassa1919 in https://github.com/ish-app/ish/issues/578#issuecomment-1328936646_

**Comment by ret708** [comment]
> ```
>           ![image](https://user-images.githubusercontent.com/59120512/204269184-c6db31c5-43d2-4b6a-8993-442038275c7a.jpeg)
> ```
> 
> 
>     
>  
>   
> 
> _Originally posted by @aassa1919 in [#578 (comment)](https://github.com/ish-app/ish/issues/578#issuecomment-1328936646)_

**Comment by ambratoor-1** [comment]
>               ![image](https://user-images.githubusercontent.com/59120512/204269184-c6db31c5-43d2-4b6a-8993-442038275c7a.jpeg)
> 
> 
> 
> _Originally posted by @aassa1919 in https://github.com/ish-app/ish/issues/578#issuecomment-1328936646_
> 
>
