### ISSUE TITLE
Use php 8 instead of php 7 to enable SSL

### ISSUE THREAD

**Issue by freebrowser1** [ish-app/ish#2078]
I found out that PHP functions like get_headers() did not work because of certificate errors, despite I set the correct paths to the certificate files in php.ini.
Then I upgraded PHP to PHP 8.0 (8.1 and 8.2 are not available ?) on iSH and evenything worked under PHP and Apache.
So on the PHP instruction page 
https://github.com/ish-app/ish/wiki/Installing-PHP-with-a-TLS-certificate-and-a-php-filemanager
the install command line should be:

`apk add openssl stunnel perl curl php8 php8-gd php8-json php8-session php8-fileinfo php8-iconv php8-zip php8-mbstring php8-ctype php8-phar php8-curl apache2 php8-apache2`

For me this works flawlessly.
I just updated that wiki page.

**Comment by Mnpn** [comment]
Looks good - thanks for contributing to the wiki!
