### ISSUE TITLE
Missing syscall 422

### ISSUE THREAD

**Issue by till213** [ish-app/ish#2097]
Hello,

With the just recently updated iSH app - thanks! - I did another attempt with compiling C++ code with Qt (yeah, I know… no graphics output, so what‘s the point ;)).

Steps:

* Remove iSH from my iPad
* Re-install from App Store („from scratch“)

Install Qt 6
* apk add qt6-qtbase-dev
* (This installs the older Qt 6.1 dev tools, including moc, qmake and uic etc.)

Upgrade Alpine Linux
* Edit /etc/apk/repositories

```
# overwriting the contents on boot.)
http://dl-3.alpinelinux.org/alpine/latest-stable/main
http://dl-3.alpinelinux.org/alpine/latest-stable/community
```

(According to https://wiki.alpinelinux.org/wiki/Upgrading_Alpine)

* apk update
* apk add --upgrade apk-tools
* apk upgrade —available
* sync
* reboot

Already during this upgrade some „Bad system call“ error messages showed up (mostly related to Gtk).

Then:

* /usr/lib/qt6/bin/qmake -v
* (This should print out the Qt version, something like „qmake 6.4.2“)
* ISSUE: „Bad system call“

DMESG:

```
Olis-Airbag:/usr/lib/qt6/bin# dmesg
63(gtk-query-immodu) missing syscall 422
64(gdk-pixbuf-query) missing syscall 422
90(glib-compile-sch) missing syscall 422
92(update-mime-data) missing syscall 422
94(gdk-pixbuf-query) missing syscall 422
96(gtk-update-icon-) missing syscall 422
101(qmake6) missing syscall 422
102(qmake) missing syscall 422
```

Other:

```
Olis-Airbag:/usr/lib/qt6/bin# uname -a
Linux Olis-Airbag 4.20.69-ish SUPER AWESOME Apr 23 2023 04:40:00 i686 Linux
```

**Comment by till213** [comment]
This is on an iPad Air Gen 3 with iPadOS 16.4.1 (20E252)

**Comment by till213** [comment]
```
Olis-Airbag:/usr/lib/qt6/bin# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.14.3
PRETTY_NAME="Alpine Linux v3.14"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Comment by till213** [comment]
By the way (not necessarily related to this issue, but perhaps helpful for others), I renamed the two files in directory /ish to *.orig, such that the /etc/apk/repositories file would (hopefully ;)) not be overwritten by iSH upon boot (according to the original comment in that file).

**Comment by till213** [comment]
Related issue: #1752

**Comment by till213** [comment]
For the record: with the „stock Alpine version“ (without upgrading) moc, uic and qmake seem to work!

E.g.

* Install iSH app
* apk add qt6-qtbase-dev
* /usr/lib/qt6/libexec/uic -v
* WORKS: „uic 6.1.1“

```
Olis-Airbag:/usr/lib/qt6/libexec# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.14.3
PRETTY_NAME="Alpine Linux v3.14"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
So it seems that the „missing system call 422“ is due to an upgraded Alpine Linux 3.17

**Comment by tbodt** [comment]
This appears to be fixed by stubbing the syscall
