### ISSUE TITLE
[Feature Request] Support Shortcuts

### ISSUE THREAD

**Issue by Zhou-Shilin** [ish-app/ish#2105]
_Google translated. Chinese->English Some words maybe strange._
I wish iSH can support iOS Shortcuts that allow users to write scripts (just like a-Shell does). This feature would be very useful, e.g:
```
git add -A
git commit -m "{shortcuts.user.input}"
git push
```

**Comment by Mnpn** [comment]
Hi! We have an open issue at #59 about this. Please track it for any updates on this topic!
