### ISSUE TITLE
adb from iSH app can't find my device

### ISSUE THREAD

**Issue by plia7** [ish-app/ish#2128]
Hello,

I have iPhone 12 Pro Max with iOS 14.4.1. I got iSH 1.3.2 app installed.

apk add android-tools --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing

I tried to run this command to install adb, looks like it got installed:

iPhone:~# apk add android-tools --repository=http://dl- cdn.alpinelinux.org/alpine/edge/testing 
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86/APKINDEX.tar.gz (1/8) Installing brotli-libs (1.0.9-r5) (2/8) 
Installing libgcc (10.3.1_git20210424-r2) (3/8) 
Installing lz4-libs (1.9.3-r1) (4/8) 
Installing libstdc++ (10.3.1_git20210424-r2) (5/8) 
Installing libprotobuf (3.15.7-r1) (6/8) 
Installing libusb (1.0.24-r2) (7/8) 
Installing zstd-libs (1.4.9-r1) (8/8) 
Installing android-tools (31.0.0p1-r2) 
Executing busybox-1.33.1-r6.trigger OK: 15 MiB in 22 packages 

iPhone:~# adb version Android Debug Bridge version 1.0.41 Version 31.0.0p1-android-tools Installed as /usr/bin/adb 
When I do adb version it says it's 1.0.41.

But when I try to connect to an ip (android device) that's on the local network that's already been paired with, it fails to connect:

Welcome to Alpine! 
You can install packages with: apk add <package> 
You may change this message by editing /etc/motd. 
iPhone:~# adb connect 192.168.X.X:YYYYY 
* daemon not running; starting now at tcp:5037 
* daemon started successfully failed to connect to 192.168.X.X:YYYYY 
iPhone:~# 

I tried to connect with another app that uses adb, and it has no problem to connect with the same ip:port. So it's only an issue when either running it from iSH Shell app and/or the specific package that I installed for adb. I tried to restart the Android phone but to no avail. Are you able to connect with it? Any other suggestions/repos to try?

Or maybe it looks like the issue is not being able to connect is because "adb devices" won't show the device, the adb vendor keys system variable is empty:

iPhone:~# adb kill-server 
iPhone:~# adb start-server 
* daemon not running; starting now at tcp:5037 
* daemon started successfully 
iPhone:~# adb devices 
List of devices attached 

iPhone:~#

Notes: 
1. I’m able to ping the android device ip from iSH. 
2. I was able to use scrcpy mobile app to pair and connect to my android phone, so this proves my iphone is able to communicate with the android phone through adb it just doesn’t work when it’s done through ish app/adb.
3. tbodt the app creator said: "it looks like a bug probably with ish".

UPDATE: Was able to get this to work, here is what I did:
I went to older ish versions
was getting some protocol error
then in version 1.3 I noticed it wouldn’t say that connection refused just wouldn’t connect, unlike other ports where it would say that it refused
so I paired it
since I remembered it’s like an emulated machine so pairing with other apps doesn’t count
was able to connect to it after pairing
and now after upgrading to 1.3.2 it works to connect

**Comment by doner005** [comment]
I’m a bit confused how you got it to work. I’m having the same issue. It’s saying connection refused and when I run adb devices, no devices show up. Could you explain a little more detail what you did? Thanks!

**Comment by plia7** [comment]
> I’m a bit confused how you got it to work. I’m having the same issue. It’s saying connection refused and when I run adb devices, no devices show up. Could you explain a little more detail what you did? Thanks!

try to install an older version of iSH first if you can (that's what I did it) or if you can't just use the version you have. Then run:
adb pair ip
type the pairing code
once paired just use
adb connect ip
And it should work. For me, the trick was to install an older version first (using my jailbreak on my iPhone).
