### ISSUE TITLE
[Question] Why use 386 instead of arm64?

### ISSUE THREAD

**Issue by kanrin** [ish-app/ish#2130]
Why use 386 instead of arm64？

Apple's product lines have all shifted to the arm64 architecture, and the alpine also has images.

Just want to know the idea of design, and if arm64 can be used to remove JIT?

**Comment by itskenny0** [comment]
https://github.com/ish-app/ish/wiki/FAQ#q-why-does-ish-not-emulate-arm-or-some-other-architecture
