### ISSUE TITLE
Run in background while screen is locked

### ISSUE THREAD

**Issue by JulyIghor** [ish-app/ish#2135]
Please add an option to allow the app to continue running in the background even when the screen is locked.
This would, for instance, enable us to start an SSH server and connect via other devices.
While there's an option to keep the screen on continuously, this isn't a sustainable solution and should be avoided.

**Comment by freebrowser1** [comment]
Make a startup script which contains `cat /dev/location > /dev/null &`. This allows running the app in the background and now it is possible to ssh into your iDevice asl long the client and the iDevice are in the same wifi network.
This is well documented on this page: https://github.com/ish-app/ish/wiki/Running-in-background
