### ISSUE TITLE
Alternative file browser

### ISSUE THREAD

**Issue by upintheairsheep** [ish-app/ish#2139]
Is it possible to make an alternate file browser that looks like iFile to export files, folders, and delete them if the files app does not work?

**Comment by freebrowser1** [comment]
Yes. Try this: https://github.com/ish-app/ish/wiki/View-iSH-files-in-Files-App and all iSH files are visible in the Files app.

Moreover, there is an alternative file browser : https://apps.apple.com/us/app/documents-file-manager-web/id364901807 which is free. And it can be mounted to the internal file system of iSH by `mount -t ios . /mnt` which opens a prompt on the iDevice allowing you to select an app, where you can select Documents as well.
I did mount /root/Documents to the Documents app which allows me to view its contents and files in iSH shell, even from remote when the iDevice screen is off, but connected to the same wifi as the ssh client.
And another option is Midnight Commander, a two pane file browser for a Linux terminal for almost all Linux distributions which also works in iSH by installing: `apk add mc`.

**Comment by upintheairsheep** [comment]
HELP! I ran mount -t ios . / and chose an empty iOS folder and iSH is practically bricked but the storage section still shows the apps storage as complete. How do I fix this???

**Comment by freebrowser1** [comment]
Do not mount the root folder, unless you are rooted / jailbroken.
`mount -t ios . /mnt` and select a valid folder in the prompt.

But iSH can be "bricked" (locked up) when running heavy tasks. E.g. running yt-dlp and some other heavy python scripts locks up iSH sometimes. But I have never had lockups when mounting e.g. the file system of the Readdie Documents app or the Downloads folder of the builtin Files app. And that mount works even persistently, i.e. after restarting iSH or even rebooting the iDevice the mount is still there. Until you explicitly unmount it.

**Comment by tbodt** [comment]
If the files app doesn't work we should fix the files app not make a replacement for the files app. Please report any issues you have with it.

We do have a backup for when the files app is hopelessly broken, which is the filesystem export feature.
