### ISSUE TITLE
Crash when installing python3

### ISSUE THREAD

**Issue by obfuscatedgenerated** [ish-app/ish#2154]
App version: 1.3.2 build 494
iOS version: 16.5.1
Device: iPhone 13

Following the web server tutorial, I tried to run `apk add python3`. It manages to install the dependencies of the package just fine, but when it gets around to acquiring python3, the app crashes when it reaches somewhere between 50% and 75% (seems to change each time). I have made sure to run `apk update` before. It is trying to install Python 3.9.16-r0.

**Comment by obfuscatedgenerated** [comment]
It should be noted that there is no problem installing python2.

**Comment by escapewindow** [comment]
I was able to install python3-3.9.16-r0 successfully today on iSH 1.3.2 build 494 on an 11" iPad Pro M2 running iPadOS 16.6.

**Comment by obfuscatedgenerated** [comment]
It now also works for me, very weird
