### ISSUE TITLE
ع

### ISSUE THREAD

**Issue by Drow120** [ish-app/ish#2155]

**Comment by ZlatislavZ** [comment]
Useless ahh issue

**Comment by Mnpn** [comment]
Hi, if you meant to open this issue, please edit its description and title. We can re-open it if you do.

**Comment by ZlatislavZ** [comment]
Why did i receive a notification about this

**Comment by Mnpn** [comment]
You have previously replied in this thread, so GitHub signed you up for notifications about updates to it. You can click the unsubscribe button to stop receiving them.
