### ISSUE TITLE
Could not logout from root

### ISSUE THREAD

**Issue by lyc-Lacewing** [ish-app/ish#2162]
As a normal user, the command `exit` will logout from the current user and login as root instead of waiting for a  username to login.

Additionally, when logged in as root, sometimes `exit` seems to be the same as `ash -i`, not logging out from root or quitting the app. It is not clear how to reproduce this bug at this point.

**Comment by saagarjha** [comment]
This is intentional behavior: https://github.com/ish-app/ish/blob/650c55526986b2eb37dab50c81f3b3fc6e73d3b7/app/TerminalViewController.m#L232.
