### ISSUE TITLE
man: not found

### ISSUE THREAD

**Issue by zizlog** [ish-app/ish#2166]
I installed the man-pages, because I thought they were not installed. A simple “man apk” resulted in -ash: man: not found.

So, I installed the man pages via “apk add man-pages” thinking that man was part of it and an “apk list man-pages shows:
man-pages-5.11-r0 x86 {man-pages} (GPL-2.0-or-later) [installed]

But they are still not accessible and I get -ash: man: not found. “which man” does not return anything.

Device is an iPadAir 1 with iOS12.5.7, apk-tools 2.12.7, compiled for x86, iSH v1.3.2

**Comment by tower-town** [comment]
`https://wiki.alpinelinux.org/wiki/Alpine_Linux:FAQ` maybe can help you.

**Comment by zizlog** [comment]
Thank @tower-town 
that was an easy fix hidden in plain sight.
I never had a distro before, where man and man-pages were not installed by default.
Would be good if apk points this out when printing “For more information: man 8 apk”
