### ISSUE TITLE
neomutt (and maybe glib) missing syscall 422

### ISSUE THREAD

**Issue by xyzzy314** [ish-app/ish#2168]
First off: I've been experimenting with newer mini root filesystems than iSH likely supports, so I did expect to run into issues and don't expect this to be an easy fix; more that I wanted to signal it now for visibility moving forward.

I am eager to get neomutt working on iSH.  Mutt works fine, but, neomutt is preferred.

However, neomutt was only ported to Alpine as of 3.17.

If I use a 3.17 miniroot file system (or the most recent 3.18), I can add neomutt, but, as soon as I launch, I get the Bad system call error.

Running it through gdb yields:

Program received signal SIGSYS, Bad system call.
0xf7f5d352 in __kernel_vsyscall ()
(gdb) bt
#0  0xf7f5d352 in __kernel_vsyscall ()
#1  0xf7f979f8 in syscall ()
   from /lib/ld-musl-i386.so.1

And according to dmesg:

26(neomutt) missing syscall 422

Which may be futex_time64, but I could be wrong.

**Comment by tbodt** [comment]
Appears to be resolved by stubbing the syscall
