### ISSUE TITLE
Will we ever have a 64bit version of iSH?

### ISSUE THREAD

**Issue by An-Unnamed-Developer** [ish-app/ish#2180]
I have a small problem. I need the latest versions of NodeJS but they only support 64bit Linux, not 32bit, like iSH.

**Comment by Collasperz** [comment]
you could change your file system to the official alpine linux 32 bit rootfs and use apk add nodejs

**Comment by An-Unnamed-Developer** [comment]
Problem is,  NodeJS no longer supports nor builds Linux 32-bit versions.

**Comment by Collasperz** [comment]
well the package manager cdn for the official alpine linux rootfs has node 18, and i used apk add nodejs and it works fine

**Comment by An-Unnamed-Developer** [comment]
How would I go about doing this?

**Comment by An-Unnamed-Developer** [comment]
Probably won’t happen, just use a different distro if needed.
