### ISSUE TITLE
Full arm64 container emulation support

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [ish-app/ish#2239]
It would be nice if we get support to run arm64 architecture binaries (including iphoneos arm64 in this case because that type of architecture is naturally connected to the arm64) and libraries in the terms of jailbreak because if we have rootless jailbroken device, we can easly mount real file system jb bootstrap location to an iSH folder and connect to it's shell (bootstrap shell) or just do chroot to that shell

In that way instead of architecture execution errors we will be able to run jailbreak terminal shell successfully

(Of course this requires an jailbreak user to use custom entitlements that allowing unsandbox and similar things so that jailbreak could be accessible for iSH - user just need to download iSH, resign it with custom entitlements and install it via TrollStore

After that all those commands above should work just fine because app is not sandbox protected anymore so it could be used as an real jailbreak terminal)

Most jailbreak terminal for rootless doesn't work properly and sometimes doesn't work at all. Nice UI, controls by iSH and stability of it's features can make us sure that it will run perfectly on jailbroken devices

And also, because of supporting not just i386 and amd64 but also arm64 (+ iphoneos-arm64 as part of the arm64 container emulation support), Apple App Store will not reject application so it will stay on the App Store and TestFlight but it will also give some support to us jailbroken users

Thanks in advance ✨✨✨

**Comment by saagarjha** [comment]
iSH will never support this. If your aim is to use iSH as a terminal on your jailbroken phone, I suggest connecting via SSH.
