### ISSUE TITLE
Add package: Bun

### ISSUE THREAD

**Issue by Bellisario** [ish-app/ish#2261]
Bun Runtime is a Node.js alternative. Would be great to use it as a replacer of Node.js inside Ish.

Bun website: https://bun.sh

**Comment by grepsploit** [comment]
bun doesn’t support ia32 architecture so even using npm to install it, it throws an error. This issue is not in scope of the iSH team, sorry. You’ll have to open a ticket with bun themselves.

**Comment by Bellisario** [comment]
Ok thanks, closing this issue
