### ISSUE TITLE
Getting error while building the project. Please help

### ISSUE THREAD

**Issue by raks8877** [ish-app/ish#2274]
ish git:(master) ✗ meson setup build
The Meson build system
Version: 1.2.3
Source dir: /Users/kurama/Downloads/Scripts/ish
Build dir: /Users/kurama/Downloads/Scripts/ish/build
Build type: native build
Project name: ish
Project version: undefined
C compiler for the host machine: cc (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.0.40.1)")
C linker for the host machine: cc ld64 1015.7
Host machine cpu family: x86_64
Host machine cpu: x86_64
Run-time dependency threads found: YES
Library rt found: NO
Library m found: YES
Library dl found: YES
Library sqlite3 found: YES
Program /usr/local/opt/llvm/bin/clang found: YES (/usr/local/opt/llvm/bin/clang)
Program check-cc.sh found: YES (/Users/kurama/Downloads/Scripts/ish/vdso/check-cc.sh)
Program tools/staticdefine.sh found: YES (/Users/kurama/Downloads/Scripts/ish/tools/staticdefine.sh)
Library unicorn found: NO
Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
Found CMake: /usr/local/bin/cmake (3.27.7)
Run-time dependency libarchive found: NO (tried pkgconfig, framework and cmake)
Library archive found: YES
Program tests/e2e/e2e.bash found: YES (/Users/kurama/Downloads/Scripts/ish/tests/e2e/e2e.bash)
Build targets in project: 10

Found ninja-1.11.1 at /usr/local/bin/ninja
➜  ish git:(master) ✗ cd build
 
 
 build git:(master) ✗ ninja
[78/93] Compiling C object libish.a.p/fs_tty.c.o
../fs/tty.c:675:22: warning: '&&' within '||' [-Wlogical-op-parentheses]
    if (tty == slave && !tty_is_current(slave) || slave->fg_group == 0) {
        ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~ ~~
../fs/tty.c:675:22: note: place parentheses around the '&&' expression to silence this warning
    if (tty == slave && !tty_is_current(slave) || slave->fg_group == 0) {
                     ^
        (                                     )
1 warning generated.
[86/93] Linking target tools/fakefsify
ld: warning: -undefined error is deprecated
[87/93] Linking target float80_test
ld: warning: -undefined error is deprecated
[93/93] Linking target ish
FAILED: ish
cc  -o ish ish.p/main.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error libish.a libish_emu.a libfakefs.a -lm -ldl -lsqlite3 -lsqlite3
ld: warning: -undefined error is deprecated
ld: warning: ignoring duplicate libraries: '-lsqlite3'
0  0x103243f43  __assert_rtn + 64
1  0x1031ebd4b  void dispatchForEach<mach_o::CompactUnwind::Diff24Fixup const, ld::LayoutExecutable::writeCompactUnwind(std::__1::span<unsigned char, 18446744073709551615ul>, unsigned long long, ld::SectionLayout const&) const::$_26>(std::__1::span<mach_o::CompactUnwind::Diff24Fixup const, 18446744073709551615ul>, unsigned long, ld::LayoutExecutable::writeCompactUnwind(std::__1::span<unsigned char, 18446744073709551615ul>, unsigned long long, ld::SectionLayout const&) const::$_26)::'lambda'(unsigned long)::operator()(unsigned long) const + 347
2  0x1031ec13b  ld::LayoutExecutable::writeContentWithoutLinkEdit(std::__1::span<unsigned char, 18446744073709551615ul>, unsigned long long) + 987
3  0x1031f39fa  ld::LayoutExecutable::writeToFile(char const*) + 21546
4  0x103192f9f  main + 12831
ld: Assertion failed: (false && "compact unwind compressed function offset doesn't fit in 24 bits"), function operator(), file Layout.cpp, line 5758.
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by saagarjha** [comment]
Do you already have a file with that name?

**Comment by raks8877** [comment]
Opsie! 
I created the output directory and then tried to run fakefsify

Thanks, it got compiled!
