### ISSUE TITLE
Run Selenium in iSH

### ISSUE THREAD

**Issue by Ivan2Hsu** [ish-app/ish#2304]
As the subject, is there any person can run python + selenium successfully in iSH?
When I run some script, the warning said can't find some files etc.

**Comment by AutomationD** [comment]
What are you trying to achieve? Please provide a brief scenario you have in mind.

**Comment by Ivan2Hsu** [comment]
> What are you trying to achieve? Please provide a brief scenario you have in mind.

I want to run the auotmation in IOS but I have done the research. It looks there can't run the automation program in iPAD or iPhone.

**Comment by AutomationD** [comment]
Maybe you could get more luck with ios-driver? http://ios-driver.github.io/ios-driver/?page=setup
