### ISSUE TITLE
Add package

### ISSUE THREAD

**Issue by Treata11** [ish-app/ish#2312]
The [obfs4proxy](https://github.com/Yawning/obfs4) package isn't made available by the package manager.

**Comment by Mnpn** [comment]
Hi, iSH runs Alpine Linux and as such uses Alpine packages, though with pinned repositories. This package does not appear to exist in Alpine's repositories. Consider contacting the developer of the package in question to see if they would be interested in [packaging releases for Alpine](https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package). Though, it appears that [this project was forked](https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird/-/issues/40010), and is [available on Alpine testing](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/testing/lyrebird/APKBUILD) under the name [lyrebird](https://pkgs.alpinelinux.org/packages?name=*lyrebird*&branch=edge&repo=&arch=x86&maintainer=).
