### ISSUE TITLE
Apperance - color scheme - Can not be changed from the command line

### ISSUE THREAD

**Issue by jaclu** [ish-app/ish#2331]
All the other defaults I use I can now change from the command line. It is still not possible to change the color scheme from the command line.

[ Set it to 1 via Settings]

cat proc/ish/defaults/color_scheme
1
echo 2 > /proc/ish/defaults/color_scheme
cat proc/ish/defaults/color_scheme
1

**Comment by saagarjha** [comment]
Looks like I forgot some preference keys in #1941

**Comment by jaclu** [comment]
thx for quick fix!
