### ISSUE TITLE
Directory

### ISSUE THREAD

**Issue by gitstudent-000** [ish-app/ish#2346]
Please explain how to add a .c file to the ish directory. I am not able to use files app on iOS to add a .c file or folder to the ish directory. If you can please explain how to open a file in ish from the files app.

**Comment by gitstudent-000** [comment]
Solved

I resolved my question by creating a folder & mounting the folder to the files app.
I installed apk and I can now run files.

**Comment by Mnpn** [comment]
Hi, I'm closing this issue as you have resolved it :)
