### ISSUE TITLE
Compile Java

### ISSUE THREAD

**Issue by gitstudent-000** [ish-app/ish#2360]
Is it possible to compile .java file using iSH on apple iOS. If it is please explain how to.

Also is there a list of all languages that can be compiled on apple iOS using iSH.

**Comment by Sadasak** [comment]
@Ari-RERA-43 ,

It's not working with me:

```

ERROR: unable to select packages:
  openjdk8-jdk (no such package):
    required by: world[openjdk8-jdk]

```

**Comment by LukeIvan** [comment]
@Sadasak 
> 
> It's not working with me:
> 
> ```
> ERROR: unable to select packages:
>   openjdk8-jdk (no such package):
>     required by: world[openjdk8-jdk]
> ```

Check your /etc/apk/repositories file, the line containing the community repo ('http://apk.ish.app/v(VERSION)/community') may be commented out. Use whichever editor to remove the comment and try again.
