### ISSUE TITLE
mounting a folder isn't working 

### ISSUE THREAD

**Issue by hsarji** [ish-app/ish#2361]
`mount -t ios . /mnt` isn't working as expected. The dialog to choose a directory opens and allows me to navigate to a directory and click on `Open`, but iSh remains at `localhost:~#`.

**Comment by lewhfree** [comment]
The command you have included mounts the chosen folder at /mnt

another way to do it would be 
'localhost:~%23 mkdir mountedFolder'
<br>
'localhost:~%23 cd mountedFolder'
<br>
'localhost:~/mountedFolder%23 mount -t ios . .'

That should work.

**Comment by lewhfree** [comment]
The command you have included mounts the chosen folder at /mnt
​
another way to do it would be 
<br>
localhost:~# mkdir mountedFolder
localhost:~# cd mountedFolder
localhost:~/mountedFolder# mount -t ios . .
​
That should work.
The command you have included mounts the chosen folder at /mnt

another way to do it would be


localhost:~# mkdir mountedFolder
localhost:~# cd mountedFolder
localhost:~/mountedFolder# mount -t ios . .

That should work.

**Comment by lewhfree** [comment]
The command you have included mounts the chosen folder at /mnt
​
another way to do it would be 
<br>
localhost:~ # mkdir mountedFolder
localhost:~ # cd mountedFolder
localhost:~/mountedFolder # mount -t ios . .
​
That should work.

**Comment by Mnpn** [comment]
Hi! As mentioned above, you have mounted it to the folder `/mnt`, which is not where you are (your home folder, `~`). You'll find the files in `/mnt`. If you want to go there, `cd /mnt`.
