### ISSUE TITLE
SSH Server

### ISSUE THREAD

**Issue by nonphiksion** [ish-app/ish#2385]
Hi, please how do I change my username from root to any name of my choice?

Also I would like to change my hostname too to something simpler so I can login easily. My hostname currently is the ip address of either my iPad or iPhone if I am ssh from any one of them to the other.

**Comment by nikeedev** [comment]
I believe you can't use anything else than `root`, as it is the default username for root 
user in Linux.

**Comment by nonphiksion** [comment]
I understand that the ssh server username for my Ubuntu machine is not root, but rather dell, and the hostname is the name of the machine itself. I was hoping that I could change the server username using the ish app on my iPhone.

**Comment by Mnpn** [comment]
You can create a new user by using `adduser` and then switch to this user by holding down the settings button in iSH for a few seconds, scrolling down, and changing the `root` in the launch command. You'll probably also want to install `sudo`, and add your new users to the sudoers file.

You [cannot currently](https://github.com/ish-app/ish/wiki/Hostname-always-localhost) change your hostname in iSH, but you can use your device's name when SSHing, like `user@iphone-name.local`, e.g. `martin@Martins-iPhone.local`.

**Comment by nonphiksion** [comment]
Wow, thank you. Please, how do I add the new user to the sudo file?

**Comment by Mnpn** [comment]
Easiest way would probably be to add a `usernamehere ALL=(ALL) ALL` line to `/etc/sudoers`

**Comment by Mnpn** [comment]
Cheers, no problem!

**Comment by nikeedev** [comment]
> Easiest way would probably be to add a `usernamehere ALL=(ALL) ALL` line to `/etc/sudoers`

Based on this website: https://wiki.alpinelinux.org/wiki/Setting_up_a_new_user, alpine uses something else called `doas` instead of sudo.
