### ISSUE TITLE
Why is it not updated in the App Store ?

### ISSUE THREAD

**Issue by freebrowser1** [ish-app/ish#2404]
The App Store version is more than a year old. But I see here that this app appears to be well-maintained with all the recent updates from at most a week ago.
Why are these not published on the App Store ? I understand that you don't want to apply every week, but more than a year is somewhat long.
And when I set the repos to 3.17 and do `apk update` and `apk upgrade`, it is soon reverted to 3.14.

**Comment by IbrahimSiddiqui007** [comment]
So to fix that just install the mini root filesystem x86 alpine linux image. Then open the settings ->  Filesystems -> Import on the top right hand corner -> Select the linux image -> select the Newly added filesystem -> Boot from this filesystem.

The link to the Linux Image: https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/x86/alpine-minirootfs-3.20.0-x86.tar.gz

**Comment by iGherghe** [comment]
@IbrahimSiddiqui007 
Hi, I followed your advice, but some programs like nano or python3 throw a "Bad command" when I use the new file system. Any idea why this behaviour ?
Thanks.

**Comment by iGherghe** [comment]
If I do:

```
nano test.txt | dmesg
```

I get missing syscall 215. I guess 3.20 is too new for the kernel included with the actual iSH application. I got a similar error with 3.19.

**Comment by iGherghe** [comment]
This version seems to work:

```
https://dl-cdn.alpinelinux.org/alpine/v3.18/releases/x86/alpine-minirootfs-3.18.6-x86.tar.gz
```

**Comment by freebrowser1** [comment]
I tried this, but still not working.
When I start `mc` (Midnight commander) I get `Bad system call`.
The I invoked dmesg:
```
localhost:~# dmesg
121(httpd) stub syscall 364
FIXME socketcall 18
122(httpd) stub syscall 364
FIXME socketcall 18
122(httpd) stub syscall 364
121(httpd) stub syscall 364
120(httpd) stub syscall 364
FIXME socketcall 18
120(httpd) stub syscall 364
118(httpd) stub syscall 364
FIXME socketcall 18
119(httpd) stub syscall 364
118(httpd) stub syscall 364
FIXME socketcall 18
119(httpd) stub syscall 364
128(mc) missing syscall 422
135(mc) missing syscall 422
102(sshd) stub syscall 364
102(sshd) stub syscall 364
141(mc) missing syscall 422
```
So some libraries are missing.

**Comment by jauderho** [comment]
I am using https://dl-cdn.alpinelinux.org/alpine/v3.20/releases/x86/alpine-minirootfs-3.20.3-x86.tar.gz . This seems to work for me with basic testing.

**Comment by tbodt** [comment]
The mentioned syscall errors appear to be resolved by stubbing the syscall.
