### ISSUE TITLE
3.20 repository SQLite and Lynx terminate with "bad system call" error

### ISSUE THREAD

**Issue by amusingimpala75** [ish-app/ish#2406]
I needed to use the latest neovim, which is available on the latest Alpine releases, but, if I upgrade, then both lynx and sqlite3 terminate due to a "bad system call". 

Re-adding the 3.14 repositories and downgrading sqlite still doesn't work.

**Comment by amusingimpala75** [comment]
3.19 has the same error, whereas 3.18 works fine

**Comment by ethanaobrien** [comment]
I think exemptions are dumped into dmesg iirc, might help the devs to check that.

**Comment by Mnpn** [comment]
Hi, thanks for the report! It appears that lynx and sqlite crashing has been resolved in master, the fixes will be available in the next release of iSH.

**Comment by ethanaobrien** [comment]
Hey @Mnpn, is it possible `nano` is also included in this bug fix using the 3.20 alpine repos?

![image](https://github.com/user-attachments/assets/abf3c80d-8034-4e75-928f-126619e0bd95)

**Comment by Mnpn** [comment]
Yep, from my testing both nano and vim also don’t exhibit these crashes on newer builds of iSH

**Comment by cornwithbutter** [comment]
What’s changed on the newer versions of iSH? I want to fix the issue without having to build the new version

**Comment by saagarjha** [comment]
You’re going to need a new version of iSH to pull in https://github.com/ish-app/ish/commit/f8a7e44ccf2d94192a15ca319ca7112e69a38a7c

**Comment by ethanaobrien** [comment]
Is there any sort of eta on when a new release will be dropped?
