### ISSUE TITLE
zpty: can't open pseudo terminal: no such file or directory

### ISSUE THREAD

**Issue by wzxu** [ish-app/ish#263]
Was pretty excited to try out zsh with my prezto configs. Unfortunately there seems to be some problem causing zpty not working properly so I keep seeing errors of "can't open pseudo terminal" and "no such pty command":

![img_0014](https://user-images.githubusercontent.com/5619348/50850643-65d55980-13b5-11e9-8bff-6bfe6e702b31.PNG)

After some Googling I think it might be the same cause as this issue: https://github.com/sindresorhus/pure/issues/117
As you can see there are also no /dev/ptyXX in ish but /dev/pts.

Any possibility this could be fixed? Or any workaround?

**Comment by tbodt** [comment]
This makes 5 issues that will be solved once I implement ptys 😛

**Comment by SConaway** [comment]
Done?

**Comment by tbodt** [comment]
You wouldn't get the same error, though I don't know if it would work.

**Comment by rcdailey** [comment]
I'm following [this guide](https://medium.com/@borekb/zsh-via-msys2-on-windows-3964a943b1ce) for using ZSH on Windows via MINGW64. My `.zshrc` looks like this:

```sh
source ~/antigen.zsh
antigen use oh-my-zsh
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure
antigen bundle zsh-users/zsh-completions
antigen apply
```

I get these errors:

```
(zpty):zpty:12: can't open pseudo terminal: bad file descriptor
async_init:zpty:14: no such pty command: _async_test
/c/Users/robert/Nextcloud/Development/Home/Robert/.antigen/bundles/sindresorhus/pure/pure.zsh: line 566: prompt${^prompt_opts[@]}: bad substitution
```

Is it related to this issue?

**Comment by tbodt** [comment]
@rcdailey I would recommend WSL for running zsh on windows
