### ISSUE TITLE
Freezes Files App After Use

### ISSUE THREAD

**Issue by Shock9616** [ish-app/ish#360]
I have been noticing all of the same issues with editing files with the files app that everyone else has been having as well, but sometimes later after I have successfully managed to add files with the files app, the files app just freezes on whatever directory I was in last. I can’t open files, I can’t change directories, I can’t do anything with the files app until I completely restart my iPad. It doesn’t happen all the time but it does happen not infrequently so I’m not exactly sure what’s going on.

![D77DE6DB-6943-47AE-A5DD-C66A60089B4E](https://user-images.githubusercontent.com/28808006/55901722-c58efc80-5b7e-11e9-9cd6-1d1b2c64e881.jpeg)

Ex. There are supposed to be 4 folders and 4 files here but it only shows a blank screen where the files should be, the back button in the top doesn’t work, and none of the locations buttons in the sidebar work either. I can open the recents tab but I can’t do anything from there either.

**Comment by leeramsay** [comment]
Hi @Shock9616, I’m trying to reproduce this and can’t. Can you confirm if it’s still occurring?

If YES, iOS 12 or 13? Current iSH build?

**Comment by Shock9616** [comment]
It seems to be fixed now. The only thing that is similar is that when a I try to copy large numbers of files  from other places on my iPad I get an error saying `Operation could not be completed: Could not communicate with helper application` This did happen before but it is a different issue. Sorry about that I completely forgot that I opened this issue.

**Comment by sh4338** [comment]
I experienced the same thing for a few months recently, but chalked it up to a bug in iOS.  It started around when I installed the ish beta in March.  I recently got a new device and haven't installed the beta and have not had this issue.  I have no idea whether it was related or not.  Furthermore, it was happening in all files providers, seemingly randomly.

**Comment by tbodt** [comment]
Closing for lack of repro
