### ISSUE TITLE
git clone: inflate: data stream error (incorrect header check)

### ISSUE THREAD

**Issue by tbodt** [ish-app/ish#373]
https://twitter.com/BlazeDSanders/status/1121997033210961920

https://github.com/ROBO-BEV/CafeBeep

**Comment by plaurent** [comment]
Oddly enough git clone just seems to hang now with Version 1.0 (50).

**Comment by tbodt** [comment]
ah yes I broke that, fix on the way

**Comment by plaurent** [comment]
Confirmed v 1.0 (51) fixes the git clone not running. Thank you!

**Comment by JonasGessner** [comment]
I'm getting this error when fetching on build 62 now. I was able to clone and pull a few times already but now I'm getting this error when pulling/fetching. One of the commits I'm fetching adds a bunch of new files (~30). Not sure if that has to do anything with it.

**Comment by JonasGessner** [comment]
To add more details, the commit that broke it for me added a .svn directory to the repo. Having removed that commit on the remote everything is back to normal when pulling.

**Comment by tbodt** [comment]
@JonasGessner I haven't been able to fix this because I've never gotten it to happen to me. Any chance you'd be able to make a copy of the repo that has the problem available to me?

**Comment by JonasGessner** [comment]
No I unfortunately can't give you a copy of the repo. It might be worth a try to just add an svn repo to a git repo and try to clone it, this is what caused it to fail for me.

**Comment by JonasGessner** [comment]
I just tried updating oh my zsh and got the same error. Maybe you can reproduce it by cloning that repo.

**Comment by Atem18** [comment]
Hi same error here pulling one of my personal repository.
Ish 62 and git 2.22.2

**Comment by plaurent** [comment]
If you want this bug to even be looked at, please post a url to a public failing repo so we can clone and replicate the problem.

**Comment by Atem18** [comment]
@plaurent https://github.com/Atem18/kmdotnet

**Comment by Rexogamer** [comment]
No issues here, iSH 62 + git 2.23

**Comment by Atem18** [comment]
Still have the issue even after updating the alone Linux version to 3.11 so Git 2.34.

/etc/os-release still shows 3.10 but all softwares have been updated, so...

@plaurent An idea?

**Comment by tbodt** [comment]
Here's where the issue stands: it has never happened to me, and until I can get it to happen to me in a repeatable way, I won't be able to fix it. Any details you can provide, such as a repository that consistently fails when you try to clone it, would be much appreciated.

**Comment by Atem18** [comment]
@tbodt I deleted my local copy of repo and cloned it again and now it works again...

Maybe there was a bug but it probably has been fixed. Btw is it right to update the alpine Linux like any regular alpine Linux ? Because as I said the file os-release is not changed after the upgrade.

Thanks a lot in advance and for your great software it’s so amazing !

**Comment by tbodt** [comment]
It seems the version of alpine in iSH is so minimal it doesn't include /etc/os-release. But yeah that's how you're supposed to upgrade it.

**Comment by Atem18** [comment]
Ok then subject is closed for me.

**Comment by tommycusick** [comment]
[git-pull-error.tar.gz](https://github.com/tbodt/ish/files/4177812/git-pull-error.tar.gz)

In case it helps debug further, here’s an oh-my-zsh install that fails with this error when running `git pull`.  As others have said, moving it aside and creating a new clone of the repo with the latest iSH works fine.

**Comment by saagarjha** [comment]
Might be #613.

**Comment by tbodt** [comment]
Here's a docker container that reproduces either this problem or something like it...except it only seems to reproduce on Linode VMs, and works fine elsewhere. [git-repro-standalone.tar.gz](https://github.com/tbodt/ish/files/4302916/git-repro-standalone.tar.gz)

```
Cloning into '/root/dotfiles2'...
remote: Enumerating objects: 437, done.
remote: Counting objects: 100% (437/437), done.
remote: Compressing objects: 100% (174/174), done.
remote: Total 437 (delta 256), reused 437 (delta 256)
Receiving objects: 100% (437/437), 78.14 KiB | 169.00 KiB/s, done.
Resolving deltas: 100% (256/256), done.
error: packfile /root/dotfiles2/.git/objects/pack/pack-3851fe41132df85631c7230112adb773561bbb36.pack does not match index
error: packfile /root/dotfiles2/.git/objects/pack/pack-3851fe41132df85631c7230112adb773561bbb36.pack does not match index
error: packfile /root/dotfiles2/.git/objects/pack/pack-3851fe41132df85631c7230112adb773561bbb36.pack does not match index
error: packfile /root/dotfiles2/.git/objects/pack/pack-3851fe41132df85631c7230112adb773561bbb36.pack does not match index
fatal: update_ref failed for ref 'HEAD': cannot update ref 'refs/heads/master': trying to write ref 'refs/heads/master' with nonexistent object 5bd43f8d8797089b7599e11ae1e2081f2738e1cd
```

**Comment by tbodt** [comment]
Latest build has a potential fix for this. If no one reports this again for a month I'll close it.

**Comment by tbodt** [comment]
It's been 2 months so I guess it's fixed
