### ISSUE TITLE
Option to hide extra row of keys

### ISSUE THREAD

**Issue by tommythorn** [ish-app/ish#518]
When you connect an external bluetooth keyboard, there's no need for the onscreen keyboard.  Unfortunately tapping the keyboard icon makes the cursor turn from solid to hollow and keyboard input correspondingly no longer have an effect.

This was observed on release 1.0 (59) and still happens on 1.0 (60), both portrait and landscape orientation.

Ideally iSH should be able to use the full screen real-estate when using a bluetooth keyboard.

**Comment by tbodt** [comment]
There's no "hide keyboard" button on iPad for this reason.

**Comment by tommythorn** [comment]
I only using an iPhone.  I note that Terminus doesn’t have this problem so it can’t be inherently impossible.

**Comment by tbodt** [comment]
"Hide keyboard" unfocuses the terminal view. Hiding the extra row of keys is an entirely separate thing which should have a different control.

**Comment by GraemeElrod** [comment]
+1 to this, though the settings button would have to move somewhere.

**Comment by markbraggmusic** [comment]
It’s more than just for aesthetics, it also affects functionality. The extra row of keys hides the bottom of my vim instance for example, so I can’t see what I’m doing on the bottom row

**Comment by tbodt** [comment]
@markbraggmusic That's a different bug: #469. It seems to be a UIKit bug so I can't directly fix it. You can work around it by rotating your device.

**Comment by tommythorn** [comment]
FWIW, the apparently standard behavior in iOS is to not display a soft keyboard when an external keyboard  is detect.  This should apply to the controls too which are redundant (we have tab, control, escape, and arrow keys).

**Comment by tbodt** [comment]
Hiding the bar while an external keyboard is connected is a good idea, but it's impossible to know whether an external keyboard is connected.

**Comment by yury** [comment]
@tbodt possible

**Comment by tbodt** [comment]
How do you do that?

**Comment by yury** [comment]
KBFrame.height is smaller or zero (if no extra accessory or bar) when hardware kb is attached.
