### ISSUE TITLE
BadSystemCall in building Haskell

### ISSUE THREAD

**Issue by watosar** [ish-app/ish#523]
https://github.com/redneb/ghc-alt-libc/releases/download/ghc-8.8.1-musl/ghc-8.8.1-i386-unknown-linux-musl.tar.xz
I installed this and tried to build.
It said “Bad system call”.
dmesg returned 
```
[    0.000000] 9 stub syscall 375
               436 missing syscall 259
```

**Comment by tbodt** [comment]
timer_create

**Comment by tbodt** [comment]
timer_create is now implemented. I tried running the installer and now it fails because alpine's terminfo is apparently not compatible.
