### ISSUE TITLE
iOS 10 compatibility

### ISSUE THREAD

**Issue by ann0see** [ish-app/ish#55]
Is it possible to make this project compatible with iOS 10?

**Comment by Mnpn03** [comment]
iOS 10 support could technically happen, but it does not support updating file timestamps (utimensat).
Also the JIT only supports 64-bit devices as of now

**Comment by tbodt** [comment]
utimes doesn't support passing a file descriptor as the directory for resolving relative paths. I suppose it would be possible to fchdir, but that seems inelegant.

**Comment by ann0see** [comment]
Thanks for the answers!
For my understanding: the function utimensat is not available on iOS 10. Therefore we need an other one (utimes), which can't handle relative paths -> we need something to generate an absolute path which will be passed to utimes. You suggest fchdir, but that's just a workaround? 

So basically iOS 10 would add complexity, we don't need.

**Comment by indicolite** [comment]
my ios is 9.3.5, also want this app -_-

**Comment by Mnpn03** [comment]
Quoting @tbodt: “turns out I’m using various APIs that only exist on iOS 10”

**Comment by ann0see** [comment]
Since iOS 14 is around the corner probably we must close this issue.

**Comment by Rexogamer** [comment]
Yeah I doubt this is realistically gonna happen. Most people are on 12 or 13 at this point.

**Comment by ann0see** [comment]
Closed the issue
