### ISSUE TITLE
Custom fonts not show accurately

### ISSUE THREAD

**Issue by onewayticket255** [ish-app/ish#553]
I use this method [adding_a_custom_font_to_your_app](https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app)

add this powerline font [Hack](https://github.com/powerline/fonts/tree/master/Hack)

and change Terminal.m     themeInfo      @"fontFamily": prefs.fontFamily,  to @"Hack"

The font indeed changes, but not work accurately.

![](https://i.loli.net/2019/11/04/ZpBEw7LSfniy86e.png)

-------
powerline font in my computer
![](https://i.loli.net/2019/11/04/IscHWdhBrNvlxTU.png)

**Comment by alessaba** [comment]
It's a bit complicated: it's difficult to install fonts systemwide on iOS. You could try with configuration profiles, but that works only with font pickers, i think 🤔

**Comment by saagarjha** [comment]
You can install fonts without configuration profiles in iOS 13 and later.

**Comment by alessaba** [comment]
This is only partially true.
As far as I understand, for an app to use fonts installed with the iOS 13 method, it has to explicitly request those fonts. It's not like on macOS, where ttf installed fonts work system wide. In iOS every app needs to support them.

**Comment by saagarjha** [comment]
Well, applications need to opt in with an entitlement, but aside from that using an installed font is relatively straightforward. Also note that the issue that @onewayticket255 is having here does not have to do with fonts installed systemwide.

**Comment by tbodt** [comment]
Duping this into #621 so we can just have one issue about fonts
