### ISSUE TITLE
Feature request color theme support

### ISSUE THREAD

**Issue by jason-green-io** [ish-app/ish#575]
It'd be great if we could customize the color theme. Pretty sure I've seen this requested on the Discord, here's an issue to track it.

**Comment by jasonboukheir** [comment]
I know this is an older issue, but I'm definitely interested in adding a custom color theme here.

If I wanted to hack a color theme, where would I do it?

**Comment by c0dine** [comment]
You can create your own on https://github.com/ish-app/ish/pull/1438
From there you can export it and put it onto other devices running that build.

Still kinda wip but all the main features are there

**Comment by saagarjha** [comment]
This has been merged into master as part of #1740.
