### ISSUE TITLE
git annex standalone not working

### ISSUE THREAD

**Issue by jacobshapiro** [ish-app/ish#591]
When trying to execute the standalone version of git annex (for linux i386) I get the following error in the included image

![image](https://user-images.githubusercontent.com/51758916/71382016-12e3ba80-25a4-11ea-8f3d-809ea7cba3ab.png)

**Comment by jacobshapiro** [comment]
If this issue could please be re-opened for build 64 it would be great. git annex standalone runs but this is what happens when one tries to init a repo (see attachment). 
<img width="1194" alt="Screenshot 2020-01-29 at 1 05 29 AM" src="https://user-images.githubusercontent.com/51758916/73333383-a0679980-4237-11ea-8c0d-fd17b72afcd6.png">

**Comment by tbodt** [comment]
Just got it working

**Comment by tbodt** [comment]
Apparently still has trouble running git annex init in a repo with one file in it

**Comment by tbodt** [comment]
I hear it's working now
