### ISSUE TITLE
Hiding and showing the keyboard can get the scroll view out of sync

### ISSUE THREAD

**Issue by tbodt** [ish-app/ish#596]
https://cdn.discordapp.com/attachments/510581945638453269/659858373327585280/video0.mp4
https://cdn.discordapp.com/attachments/510581945638453269/659859089584685066/video0.mp4

**Comment by tbodt** [comment]
Reproduced on iOS 12 iPod touch, could not reproduce on iOS 13 iPad pro. Seems like the touches are going to the f***ing webview.

**Comment by 62f** [comment]
Hiding and showing the touch-keyboard interrupts wget but not curl downloads. Also, I have had a problem with lowering the keyboard, selecting webview text and then the keyboard won't come up again. Scrollback works fine, no blank spot where the keyboard should be like before, however there's just no way to enter any more text from the screen. I have simply been avoiding doing that as a quasi-workaround, but if it deserves its own complaint, I can also do that .
