### ISSUE TITLE
Space not freed on removal from iSH’s “Documents & Data” when content is copied out of iSH

### ISSUE THREAD

**Issue by sn0crash** [ish-app/ish#603]
Space not freed on removal from iSH’s “Documents & Data” when content is copied out of iSH. This is on iOS 13.3.

Steps to reproduce:
1. Create a large file in iSH. I used `dd if=/dev/zero of=bigfile bs=10240 count=102400` for testing.
2. Go to iSH’s storage in the Settings app and record the size of the "Documents & Data".
3. Copy the large file from iSH via the Files app to another location local to the device (i.e. in On My iPad / On My iPhone).
4. Delete file in iSH (I used Files app to do this, but rm should also work)
5. Delete newly copied file and empty the trash
(Steps 4 and 5 can be reversed as well)
6. Go back to the main screen in the settings app and then go back into iSH’s storage (to refresh).

Space is not freed even though there are no references to the file. I think this may have to do with APFS cloning the file and not all references getting cleaned up.

Only workaround to free up space is to delete iSH and re-install. Rebooting doesn’t help.

**Comment by sn0crash** [comment]
Looks like it is keeping a copy of the deleted data in the “File Provider Storage".

**Comment by relikd** [comment]
I'm wondering, how did you manage to connect iSH to the Files app? Because thats something I want to accomplish. Do you mount it somehow in alpine? Files does not show an iSH folder for me unfortunatelly

**Comment by ntindle** [comment]
@relikd https://github.com/tbodt/ish/wiki/View-iSH-files-in-Files-App

**Comment by talalife** [comment]
> I'm wondering, how did you manage to connect iSH to the Files app? Because thats something I want to accomplish. Do you mount it somehow in alpine? Files does not show an iSH folder for me unfortunatelly

I was using youtube-dl and found downloaded files in iSH/root.

**Comment by tbodt** [comment]
No idea how I'm supposed to fix this. Apple's documentation says that it will call stopProvidingItemAtURL: when it's OK to delete the copy, but that never actually happens. Do I just need to periodically delete old files?

**Comment by sn0crash** [comment]
@tbodt It looks like that method is deprecated in iOS 13:
https://developer.apple.com/documentation/fileprovider/nsfileproviderextension

**Comment by tbodt** [comment]
Yeah but apple has not bothered to document a replacement, so...

**Comment by erikhermesman** [comment]
Please keep us updated, hopefully something from WWDC tomorrow and the sessions following will allow for a fix.

**Comment by tbodt** [comment]
I asked about this in a WWDC lab and they said that -stopProvidingItemAtURL: never being called is a known issue, and apparently they do that because of a buggy app that would lose user data if the method was called or something. New plan: delete the entire file provider storage periodically and let the system re-request anything it was using.

**Comment by erikhermesman** [comment]
Thanks for the update!

**Comment by tbodt** [comment]
Plan for fixing this:
- When a file is deleted, delete its copy from file provider storage
- Populate file provider storage with hardlinks instead of copies. Needs further research to determine whether this is sane.

**Comment by markpanado** [comment]
Experiencing same issue, I'm mostly using youtube-dl and extracting big .rar and .7z files. After deleting the files, the storage is still consumed

**Comment by davestgermain** [comment]
This is still a problem in 1.3.3:

`du -sh /` reports 315MB, but iSH is using 4.4GB.

**Comment by bijoy26** [comment]
Seems like the issue is still present.

> This is still a problem in 1.3.3:
> 
> `du -sh /` reports 315MB, but iSH is using 4.4GB.

**Comment by Eireman** [comment]
Issue is still present, but easy to correct, no FS export and app removal needed. Run the following command:

`fsck -a -p`

This will free “lost” sectors in under a minute, even on huge file systems. In my case, I am using an M1 iPad Pro with 512GB internal storage, as well as a mounted 2TB SSD on a lightning hub. The 512GB took under 15 seconds to free almost 300GB sectors, and the SSD took around a minute to free 1.8TB sectors. iOS shows this immediately.

Suggestion, run `fsck -a -p` in the background when ever starting a terminal window?

**Comment by pretubedongit** [comment]
Mine just returned the version and no space released. Could you suggest?


`fsck (busybox 1.33.1)`

> Issue is still present, but easy to correct, no FS export and app removal needed. Run the following command:
> 
> `fsck -a -p`
> 
> This will free “lost” sectors in under a minute, even on huge file systems. In my case, I am using an M1 iPad Pro with 512GB internal storage, as well as a mounted 2TB SSD on a lightning hub. The 512GB took under 15 seconds to free almost 300GB sectors, and the SSD took around a minute to free 1.8TB sectors. iOS shows this immediately.
> 
> Suggestion, run `fsck -a -p` in the background when ever starting a terminal window?
