### ISSUE TITLE
Option to show status bar with the terminal

### ISSUE THREAD

**Issue by tbodt** [ish-app/ish#620]

**Comment by dullbananas** [comment]
still waiting

**Comment by tbodt** [comment]
Yeah now would be a good time to do this since the window controls are now in the middle of it. And also enable it by default.

**Comment by c0dine** [comment]
I can pick this one up for ya if you want ;)

**Comment by tbodt** [comment]
> I can pick this one up for ya if you want ;)

Why not!

**Comment by Mnpn** [comment]
This was merged and resolved long ago :)
