### ISSUE TITLE
Ability to use custom fonts

### ISSUE THREAD

**Issue by rrroyal** [ish-app/ish#621]
iOS 13 added ability to install custom fonts ([related stackoverflow question](https://stackoverflow.com/questions/57653398/ios-13-custom-fonts-download-and-installation)). Maybe we can add ability to use those fonts in terminal?

**Comment by Chew** [comment]
Partially related to #553, apparently they aren't shown very well as of yet

**Comment by rrroyal** [comment]
#553 doesn't look like wrong font rendering, more like a "no font selected - falling back to default web font". You'll achieve the same effect when you will select a non-existing font in HTML webpage.

**Comment by bensleveritt** [comment]
Is it possible to side load a font directly into the app, say into app documents?

**Comment by nyuszika7h** [comment]
Yes, this would be nice. As an example, Secure ShellFish can use custom fonts installed via configuration profiles using Fontcase.

**Comment by SamHep0803** [comment]
Would be really nice to have this - any update if this is being developed on?

**Comment by tbodt** [comment]
An update: iSH can now use fonts installed via configuration profile or other apps on iOS 14. It filters out non-monospace fonts though, and some monospace fonts are missing the flag that says they are monospaced. I should build some UI to allow you to choose non-monospace fonts if you really want, but that's a bit more work.

**Comment by NyaMisty** [comment]
@tbodt I'm sorry but is it the version from git or from TestFlight?

**Comment by SamHep0803** [comment]
Git afaik

**Comment by tbodt** [comment]
Yes, git. Unfortunately the entitlement requires a paid developer account. I guess Apple doesn't want people using fonts for free?

**Comment by NyaMisty** [comment]
Well I'll wait for the testflight :) You're really my god!

**Comment by rrroyal** [comment]
Live on TestFlight v.1.1.1 (88)
