### ISSUE TITLE
Fish shell error

### ISSUE THREAD

**Issue by thedimas3007** [ish-app/ish#631]
When I type command in fish shell after command it returns: `Could not send own process 401, 'sed' in job 3, 'commandline | sed 's|\s\+|\x1e|g'' from group 400 to group 400 setpgid: unknown error (errno was 1)` but command runs. After some commands fish shell stops responding. How can I fix it? Help please

**Comment by tbodt** [comment]
Just pushed something which helps a bit with this

**Comment by creepinson** [comment]
I also get this when trying to install oh my fish
Installation aborted: /bin/busybox is not a sane environment

**Comment by tbodt** [comment]
Can't reproduce anymore, feel free to open a new issue if something turns up

**Comment by kkk669** [comment]
I reproduced on App Store version of iSH 1.0.1 (77).

It looks caused by race condition or something like that.

![566A0268-F417-43F5-9A9C-21E04B7C6128](https://user-images.githubusercontent.com/601636/97101229-fe4de280-16de-11eb-8adf-a6ce6f07453a.png)

**Comment by vichaos** [comment]
It seems like fish shell is working perfectly now
![01B91FD3-CDF2-4ABC-946A-F75EECB435AF](https://user-images.githubusercontent.com/724055/160199618-8418fcc9-d517-4cab-82b3-65678adcbd71.png)
