### ISSUE TITLE
UTM uses QEMU TCG to achieve almost 70% speed of QEMU

### ISSUE THREAD

**Issue by jcampbell05** [ish-app/ish#645]
https://getutm.app/faq/

I'm interested to see how this compares to techniques used here

**Comment by saagarjha** [comment]
iSH is faster at the moment, interestingly. Unfortunately the trick used there precludes it from being distributed via TestFlight.

**Comment by tbodt** [comment]
This project has motivated me to work on a prototype of using QEMU in iSH. It's a bit difficult because I can't just compile QEMU, I have to pick out the parts I want to use. We'll see how far I get this weekend.

**Comment by tbodt** [comment]
Also the 70% refers to the fact that it's 30% slower than QEMU normally is.

**Comment by jcampbell05** [comment]
> Also the 70% refers to the fact that it's 30% slower than QEMU normally is.

Good to know - supposedly latest release manages to improve on this https://github.com/utmapp/qemu/commit/552be7a9d61ee7955c70591ca8bebf14aa15f871

**Comment by tbodt** [comment]
Going to close this as duplicate of #129
