### ISSUE TITLE
Feature Request: Interface gestures

### ISSUE THREAD

**Issue by bderiso** [ish-app/ish#651]
* Double tap to insert tab.
* Swipe anywhere in window to send up, down, left, right

**Comment by s-clerc** [comment]
I just want compatibility with the two finger cursor movement.

**Comment by bderiso** [comment]
The new space-bar long-press is much easier to grab, thanks!

**Comment by tbodt** [comment]
Should this be closed?

**Comment by bderiso** [comment]
Yes, although i might open a separate one for the double-tap tab-complete request if you don’t mind.
