### ISSUE TITLE
Can't select text on iOS 13.4

### ISSUE THREAD

**Issue by akbarnia71** [ish-app/ish#667]
I can't select or copy text in terminal via mouse on ios 13.4

**Comment by lpiot** [comment]
Hi @akbarnia71.
Can you do it by touching screen with your finger and/or the `Apple Pencil`?
I haven’t observed the behavior since I have no mouse, but I can’t select text by any usual _touch_ capabilities.

**Comment by tbodt** [comment]
Looks like all text selection is broken on iOS 13.4.

**Comment by lpiot** [comment]
Well, I made some tests those last days.  
Text selection behaves very unsmoothly now. But there are some real differences between apps.

* Most text editors are OK.
* Using `termius` (native iOS _ssh_ client) is OK too.
* Using `Google Cloud Shell` from `Safari` is… weird: you have to touch *after* the typing cursor to trigger text selection, and then you can move text selection handles where you want.
* iSH doesn’t trigger any selection *wherever* you touch the screen.
