### ISSUE TITLE
Metasploit error

### ISSUE THREAD

**Issue by thedimas3007** [ish-app/ish#669]
When I trying to run `./msfconsole` I got this error: 
```
Traceback (most recent call last):
        9: from ./msfconsole:48:in `<main>'
        8: from ./msfconsole:48:in `require'
        7: from /opt/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        6: from /opt/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        5: from /opt/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        4: from /opt/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        3: from /opt/metasploit-framework/lib/msf/core.rb:44:in `<top (required)>'
        2: from /opt/metasploit-framework/lib/msf/core.rb:44:in `require'
        1: from /opt/metasploit-framework/lib/msf/core/db_manager.rb:24:in `<top (required)>'
/opt/metasploit-framework/lib/msf/core/db_manager.rb:66:in `<class:DBManager>': undefined local variable or method `optionally_include_metasploit_credential_creation' for Msf::DBManager:Class (NameError)
```

But I have already installed *metasploit-credential* (`gem install metasploit-credential`). How can I solve this error? Thank you in advance

**Comment by tbodt** [comment]
Why was this closed?

**Comment by Assfugil** [comment]
msfconsole now launches

**Comment by Assfugil** [comment]
![3A09223E-8E17-4DE4-A598-5066EF0BFE4A](https://user-images.githubusercontent.com/42699250/98558833-dd8dab80-22e0-11eb-9826-72c25b8d3c73.png)
![B14474E4-4969-45E0-9CA7-BA497057D002](https://user-images.githubusercontent.com/42699250/98558961-04e47880-22e1-11eb-85aa-f59f61587642.png)
![D903AFAF-5FF2-4ECC-BEA7-DB4E8B9D654E](https://user-images.githubusercontent.com/42699250/98558818-d8306100-22e0-11eb-9f74-6e27c30cae95.png)
The following messages appeared in dmesg during launch , but it does launch.
```
[    0.000000] 494 stub syscall 375
               516 stub syscall 375
               568 stub syscall 375
```

**Comment by Assfugil** [comment]
start with `msfconsole -n`
I used the commands form https://github.com/fcolista/alpine-metasploit to setup everything.
