### ISSUE TITLE
Crash on VNC installation as on wiki

### ISSUE THREAD

**Issue by lujo777** [ish-app/ish#670]
Hello,

there is a problem in installing packages for VNC usage. After I execute command as in instruction I got crash every time.

Here is a crash trace from Analytics.
[cloudd-2020-03-29-233035.txt](https://github.com/ish-app/ish/files/4399731/cloudd-2020-03-29-233035.txt)

Device on iPad OS 13.3.1

**Comment by tbodt** [comment]
That's a crash report for cloudd, not iSH. Can you find one whose name starts with iSH?

**Comment by lujo777** [comment]
[iSH-2020-03-29-233102.txt](https://github.com/ish-app/ish/files/4399748/iSH-2020-03-29-233102.txt)

**Comment by tbodt** [comment]
Seems like it probably has something to with the syscall logging I accidentally left enabled. That'll be fixed in the next release.
