### ISSUE TITLE
SSHD Can't bind to 0.0.0.0

### ISSUE THREAD

**Issue by kyelewis** [ish-app/ish#678]
Setting up sshd as per wiki instructions, sshd fails with a cannot bind to 0.0.0.0 error. Tried on both port 22 and on another port 2222.

Binding to 127.0.0.1 works fine- which is my use case anyway, but thought it was worth putting here.

iPadOS 13.4 Beta (17E255)

**Comment by tbodt** [comment]
Works for me, on the same iOS version. Not sure what's up. Let me know if you have more info.
