### ISSUE TITLE
/proc/sys: No such file or directory

### ISSUE THREAD

**Issue by nguyenhuyblyat** [ish-app/ish#680]
I ran `sysctl -p` but it returns `/proc/sys: No such file or directory`.

**Comment by tbodt** [comment]
What specifically would you like to do with sysctl or /proc/sys? /proc/sys isn't really interesting in and of itself, so I wouldn't want to implement it until I find something that needs it.

**Comment by nguyenhuyblyat** [comment]
https://www.linux.com/topic/desktop/setting-vpn-linux/
I’m following this guide

**Comment by tbodt** [comment]
Closing this, can open new issues for specific sysctl commands that should work. net.ipv4.ip_forward is not really one of those.
