### ISSUE TITLE
Haw to code hack Facebook app ish

### ISSUE THREAD

**Issue by saman1111111** [ish-app/ish#684]
Link for site

**Comment by tbodt** [comment]
What the fuck

**Comment by CottonTheButton** [comment]
Uh... sure.

**Comment by nguyenhuyblyat** [comment]
bruh

**Comment by Rexogamer** [comment]
Hey, can someone teach me how to hack Facebook via iSH? I’m thinking the Notes app might be useful in this leet hax.

Okay but seriously wtf
