### ISSUE TITLE
Permission denied while importing GPG Key

### ISSUE THREAD

**Issue by mkapra** [ish-app/ish#685]
When I try to import a GPG private key I get `Permission denied` errors. The command is executed by a created user. The `.gnupg` directory is read- and writeable for this user.
When I call `gpg —list-keys` I see the key that I tried to (`/home/user/.gnupg/pubring.kbx`).

I am not sure what I can post here to help so I attached a screenshot of the problem.

![13E19EFD-F231-46FD-8990-640AE4D480B2](https://user-images.githubusercontent.com/34742358/79691507-47206c80-8260-11ea-8042-4b9174c8330d.jpeg)

**Comment by tbodt** [comment]
Weird. Can you run `dmesg > log.txt`

**Comment by tbodt** [comment]
Weird. Can you run `dmesg > log.txt` right after reproducing the problem and send it to me?

**Comment by tbodt** [comment]
Just got the log email. Thanks for sending, that was very helpful. Looks like the permission problem was on /dev/pty/0. The permissions on that are set so it's only accessible to root. Ideally it should be set to be only readable by the user you logged in as, but I have no way of knowing what that is. So I'll add a hack to make it accessible to all users.

It's possible to have this problem on actual Linux, so in the meantime there are some suggestions here:
https://askubuntu.com/questions/1080204/gpg-problem-with-the-agent-permission-denied

**Comment by tbodt** [comment]
Update: looks like the `login` command automatically changes the owner of the pty and overwrites the default. Can you tell me how you're logging into your user account? If you're using `su` the real solution is probably to just use `login`.

**Comment by mkapra** [comment]
Because there is no option to set the default user of `ish` to something else than `root` I call `su` in the `.profile` file of the `root` user.
Looks like I am switching to `login`. The only thing of `login` is, that I need the password of the user now. With `su` I don‘t have this „problem“.

**Comment by tbodt** [comment]
That's pretty easy to fix, use `login -f user` instead of `login user`.

**Comment by mkapra** [comment]
ah thanks!
