### ISSUE TITLE
Missing SSE Instruction

### ISSUE THREAD

**Issue by yobson** [ish-app/ish#688]
I found a temporary work around for my last bug, but I have found a new one!
`illegal instruction at 0xf66df8b9: f3 0f 2a c1 f3 0f 5e 46`

`decode.h` is missing as SSE instruction (around line 913). It should be decoded:
```
0:  f3 0f 2a c1             cvtsi2ss xmm0,ecx
4:  f3                      repz
5:  0f                      .byte 0xf
6:  5e                      pop    esi
7:  46                      inc    esi
```
Sadly, I cannot work out how to modify the code to get it to work!
[`CVTSI2SS`](https://www.felixcloutier.com/x86/cvtsi2ss) converts a doubleword integer to scalar single-precision floating-point value

**Comment by tbodt** [comment]
@MatthewMerrill has done a bit of work on SSE

**Comment by yobson** [comment]
Fantastic! Anything I can help test?

**Comment by tbodt** [comment]
This instruction is now implemented, along with a few more. I tried running the installer and now it fails because alpine's terminfo is apparently not compatible.
