### ISSUE TITLE
apk update doesn’t work on my iPad 

### ISSUE THREAD

**Issue by writersglen** [ish-app/ish#693]

**Comment by tbodt** [comment]
What does it do instead of working?

**Comment by writersglen** [comment]
$ apk update
apk: command not found
$ apk update
apk: command not found
$ sudo apk update
sudo: command not found

Thanks for looking into this. I was almost ready to abandon my iPad but now,
with iSH, it fits more smoothly into my workflow.

LRP

**Comment by nguyenhuyblyat** [comment]
bruh reinstall iSH. problem solved

**Comment by writersglen** [comment]
Many thanks to an amazing community.

LRP

**Comment by writersglen** [comment]
Argh! Deleted iSH from my iPad. Went to store to be told TestFlight beta was filled.

Makes me want to cry.

LRP

**Comment by tbodt** [comment]
Reinstalling should fix it. I'm pretty sure this is #625 in disguise.

Sorry about the full beta. I'll remove some testers in a bit, in the meantime you can install using AltStore.
