### ISSUE TITLE
ISh hangs when trying to read file from mounted folder

### ISSUE THREAD

**Issue by valentinJonev** [ish-app/ish#699]
When trying to read a file from a mounted folder (either from On My Ipad or from iCloud Drive) the terminal just hangs and becomes unresponsive. I’ve tried using vim and cat to read from a file, but they both act the same. Trying to stop the process with Ctrl+C or Ctrl+Z or anything doesn’t work. So far the only solution for stopping the process is to exit the app and launch it again.

**Comment by larrykollar** [comment]
Seeing the same issue on an iPhone 6s, running iOS 13.3.1. Left alone long enough, it looks it gave a couple messages and crashed, but it came up to a fresh shell.
