### ISSUE TITLE
Mounting not working on iOS 12

### ISSUE THREAD

**Issue by larrykollar** [ish-app/ish#700]
iPad Air, running iOS 12.4.6. Looks like the file picker is coming up instead of the directory picker. 

![iPad picker](https://user-images.githubusercontent.com/16429595/81035080-5bbb5200-8e67-11ea-84fc-5eeb97356502.PNG)

Working as expected on an iPhone 6s, iOS 13.3.1.

**Comment by kkk669** [comment]
It works on my 2nd generation 11" iPad Pro running iOS 13.5 beta 3.

![image](https://user-images.githubusercontent.com/601636/81060016-9925eb00-8f0c-11ea-9800-9a0d3ee2740c.png)

**Comment by larrykollar** [comment]
So maybe this only works in iOS 13+ ?

**Comment by tbodt** [comment]
Sounds likely. I never tested on iOS 12.

**Comment by larrykollar** [comment]
So does iOS 12 not support a directory picker?

**Comment by tbodt** [comment]
Not sure, haven't looked into it. If that turns out to be the case, I'll disable the feature on iOS 12.

**Comment by kkk669** [comment]
@larrykollar @tbodt It is possible to open a directory on iOS 12, but the UI is different from iOS 13. For example, Textastic and Pythonista has supported that feature since iOS 12.

**Comment by kkk669** [comment]
@tbodt If [`UIDocumentPickerViewController.allowsMultipleSelection`](https://developer.apple.com/documentation/uikit/uidocumentpickerviewcontroller/2902365-allowsmultipleselection?language=objc) is set to `YES`, mounting will work even on iOS 11 and 12. But it requires a little more work for multiple selection. For example, ignore folders other than the first one.

![C01680E7-2511-4954-A2F9-FC6C85A7FE9A](https://user-images.githubusercontent.com/601636/82158014-013ae080-98c0-11ea-82f4-858dda9f079a.png)
