### ISSUE TITLE
Terminate mount command automatically after cancelling the document picker

### ISSUE THREAD

**Issue by kkk669** [ish-app/ish#703]
When I tap or click the outside of the document picker, it will be closed with the `mount` command still running. So, I have to press Ctrl+C to terminate it.

Please see the following video.

https://youtu.be/MTSSxKa6qgk

Is it possible to terminate the `mount` command automatically after cancelling the document picker?

**Comment by tbodt** [comment]
It does work if you tap Cancel. For some reason documentPickerWasCancelled isn't called if you just tap outside.

**Comment by kkk669** [comment]
@tbodt I understand. It may be a workaround to insert `picker.modalPresentationStyle = .fullScreen` into [here](https://github.com/ish-app/ish/blob/2b2fc7ac688dd41e7fdfe6aaf5e419e76e000e29/app/iOSFS.m#L55).

**Comment by kkk669** [comment]
@tbodt This issue can be solved by https://developer.apple.com/documentation/uikit/uiadaptivepresentationcontrollerdelegate/3229889-presentationcontrollerdiddismiss, so I submitted a PR #724. Please check it out.
