### ISSUE TITLE
SplitView issue

### ISSUE THREAD

**Issue by suliveevil** [ish-app/ish#704]
![splitview issue](https://user-images.githubusercontent.com/35763237/81075766-59b3ca80-8f1d-11ea-8691-5c534448ee6a.png)

iSH 1.0（67）
iPadOS 13.5 public beta 2
iPad Pro 11（2018）

**Comment by tbodt** [comment]
Is the cursor position the issue?

**Comment by suliveevil** [comment]
When enter the splitview，the screen will be a mess.
Not only cursor，the whole layout will be a mess.
Sometimes it happens after rotating screen too.
