### ISSUE TITLE
Can't access go web server

### ISSUE THREAD

**Issue by abasse** [ish-app/ish#705]
I can't access a local go web server on 127.0.0.1:8080
Code:

```
package main

import (
    "fmt"
    "net/http"
)

func main() {
    http.HandleFunc("/", HelloServer)
    http.ListenAndServe(":8080", nil)
}

func HelloServer(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Hello, %s!", r.URL.Path[1:])
}
```

Any suggestions?

**Comment by jankais3r** [comment]
Have you look at [How to run iSH in the background](https://github.com/ish-app/ish/wiki/Running-in-background)? In my experience web servers don't work well if you background iSH without using the location trick.

**Comment by abasse** [comment]
@jankais3r Thanks! The trick works great.
