### ISSUE TITLE
Can't build for simulator with Meson 0.54

### ISSUE THREAD

**Issue by Jewsh-S** [ish-app/ish#706]
I wanted to put some work in to developing a feature I wanted ish to have (and possibly fix a bug you might already be fixing [iPad Pro12.9 in mouse causes major UI issues in iSH]).  But when I try to build the app, meson makes an exe file on macos catalina.  I am not familiar with meson what so ever, so I don't know where the build flag is that is making it build a windows executable on MacOS.  Was hoping you could give me a quick pointer.

I am sure the core dev(s) are busy, so if this is a waste of your time feel free to just close it and move on.  Thanks!  (side note, this is a very great application of a shell on MacOS if you ask me.  By far the best I have touched).

====================
What I am doing:
   - Cloning the root repository 
   - opening iSH.xcodeproj in xCode
   - changing the root project identifier
   - setting target to iPad Pro (12.9)
   - pressing build
What OS: MacOS Catalina 10.15.4 (19E287)
What version of xCode: Version 11.4.1 (11E503a)

**Comment by Jewsh-S** [comment]
I got a successful build to run when I built directly to my iPad. I just can't get it to build in a simulator.  I forgot to mention that.

**Comment by tbodt** [comment]
The latest version of Meson seems to have a lot of bugs. Downgrade to 0.53.1 and it will work. `pip3 install meson==0.53.1`

**Comment by tbodt** [comment]
https://github.com/mesonbuild/meson/pull/6933 fixes it

**Comment by tbodt** [comment]
Meson 0.55 is out and includes the fix.
