### ISSUE TITLE
Ruby uses timer_settime in ctrl-c handler

### ISSUE THREAD

**Issue by NightMachinary** [ish-app/ish#707]
I was trying to get homebrew to work. I roughly followed this [dockerfile](https://hub.docker.com/r/linuxbrew/alpine/dockerfile). I also installed util-linux. But the installed ruby interpreter doesn’t work:

```
iPad:~# ruby
^C[ASYNC BUG] timer_settime (arm)
ENOTTY

ruby 2.6.6p146 (2020-03-31 revision 67876) [i586-linux-musl]

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: https://www.ruby-lang.org/bugreport.html

Aborted
```

I have just installed iSH this evening.

**Comment by tbodt** [comment]
It works, until it took too long and you got impatient and pressed ctrl-c.

**Comment by NightMachinary** [comment]
@tbodt I didn’t press ctrl-c in installing Homebrew, and it still exited with the same error.

**Comment by tbodt** [comment]
Ah ok.

**Comment by tbodt** [comment]
#715
