### ISSUE TITLE
Shell formatting support (xterm)

### ISSUE THREAD

**Issue by GalacticLion7** [ish-app/ish#708]
Can there be support for formatting like xterm?

**Comment by tbodt** [comment]
This has been in since the very first release, is it not working?

**Comment by tbodt** [comment]
Closing due to lack of response

**Comment by GalacticLion7** [comment]
> This has been in since the very first release, is it not working?

For example, there isn't any syntax highlighting in vim or nano. It's all black and white. I think it's on iSH's end since there is syntax highlighting on a real Alpine chroot.

**Comment by tbodt** [comment]
I just tried vim and the syntax highlighting worked. The default `vi` program is not vim, it's busybox vi which has no support for highlighting. nano syntax highlighting has to be enabled.

If it still doesn't work for you: what's your $TERM?
