### ISSUE TITLE
Emacs broke

### ISSUE THREAD

**Issue by tbodt** [ish-app/ish#711]
https://discord.com/channels/508839261924229141/510973900209913857/708708134398459905

> Help me! I installed ish on my ipad air3, after ran freshly installed emacs I got this error “Failed select: Invalid argument”. I have tried  ‘emacs —no—init-file’ , ‘apk upgrade & apk update’, reinstall emacs, reinstall ish, but with no success. After some googling I found this [https://github.com/termux/termux-packages/issues/952] and this [https://github.com/termux/termux-packages/pull/956]. Somebody encountered a bug in emacs under termux, and it looks like the same bug which ish happens to have?

**Comment by glyph** [comment]
I saw this same issue on “1.0 (67)” via testflight. Emacs was the first thing I tried to use after installing, and this was a bit sad. So close!!

**Comment by tbodt** [comment]
The good news is this is fixed if you build from source, and is also a regression in just the latest version, so you can try installing the one before that.

**Comment by glyph** [comment]
Wow, thanks for the instant feedback! Now the only problem is that control-space doesn’t seem to be accessible on the iPad keyboard, and that’s a pretty important key binding in Emacs :).

**Comment by tbodt** [comment]
That would be good to file a new issue for, in the meantime you can probably fake it with ctrl-2
