### ISSUE TITLE
AltStore Source Version Number Mismatch

### ISSUE THREAD

**Issue by JoelStickney** [ish-app/ish#713]
The source you use for AltStore (https://ish.app/altstore.json) doesn't match your IPAs version number.

JSON Source Version: `1.0.67`
IPA Short Bundle Version: `1.0`

AltStore parses out all characters when comparing version numbers to know when an app has been updated (and will notify the user).

So basically, your IPA says it's 1.0. Your JSON says it's 1.0.67. AltStore parses version numbers by removing all character except numbers and so the iSH IPA looks like Version 10, while your JSON source looks like it's Version 1067. 1067 > 10 so AltStore constantly bugs people to update, but if you do, it just updates to the same `1.0` version.

**Comment by tbodt** [comment]
The CFBundleVersion is 67. AltStore really should be looking at that.

**Comment by JoelStickney** [comment]
I agree, but shouldn't the Short Bundle Version **match** the "marketing" version (how it's presented in the iSH JSON source) anyway.

I'll talk to Riley about it, but he's been using the `CFShortBundleVersion` since the beginning and iSH is the only app to ever have this issue. I'm unsure if he'll reconsider.

**Comment by tbodt** [comment]
I've been using Fastlane's increment_build_number action, which doesn't affect CFBundleShortVersionString. I just discovered there's also an increment_version_number action, so next time I release I'll spend some time trying to get things to work better.

**Comment by tbodt** [comment]
(I won't necessarily always want to increment the version number though. TestFlight sort of expects you to only increment the build number most of the time.)

**Comment by JoelStickney** [comment]
> (I won't necessarily always want to increment the version number though. TestFlight sort of expects you to only increment the build number most of the time.)

I think that AltStore users would take more infrequent updates over an update that never actually updates.

**Comment by JoelStickney** [comment]
Thought I’d update with Riley’s response. 

![897FC911-9CFB-45DD-8571-5EA87CACDD5B](https://user-images.githubusercontent.com/5572600/81490307-e7115a80-924e-11ea-8c51-b2e77f1c99e0.jpeg)

**Comment by JoelStickney** [comment]
Closing this issue since, in the end, it'll have to be fixed on Riley's end.
