### ISSUE TITLE
Can’t use Docker

### ISSUE THREAD

**Issue by rluvaton** [ish-app/ish#717]
I’m trying to use Docker and it’s giving me this error:
```
h-iPhone-sl-Name:~# docker pull hello-world
Using default tag: latest
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
I’m trying to run
```
service docker start
```
But I get this error:
```
h-iPhone-sl-Raz:~# service docker start
ash: service: not found

```
I’ve also tried another command, `docker create` and it result with the same error

**Comment by jankais3r** [comment]
Services don't work yet

**Comment by GalacticLion7** [comment]
Also, I don't think `service` exists on Alpine. Install OpenRC (`app add openrc`) if you want something similar.

**Comment by tbodt** [comment]
Duping to #63. Talking to a docker daemon on another computer should work, at least.
