### ISSUE TITLE
Support ngrok error illegal instruction

### ISSUE THREAD

**Issue by professorIsaac** [ish-app/ish#719]

**Comment by tbodt** [comment]
Please read the issue template and provide more information.

**Comment by professorIsaac** [comment]
22 stub syscall 375

**Comment by professorIsaac** [comment]
Is that what you are looking for

**Comment by tbodt** [comment]
That doesn't mention the illegal instruction, can you try running dmesg after running ngrok?

**Comment by professorIsaac** [comment]
Ok I will try

**Comment by professorIsaac** [comment]
/ngrok: line 1: can't create E@@8@?@@@@@@@dd@@: Illegal byte sequence
./ngrok: line 1: : not found
./ngrok: line 1: ELF: not found
./ngrok: line 1: A: not found
./ngrok: line 1: : not found
./ngrok: line 1: 
                 +
                  +,ll@Qte@: not found
./ngrok: line 1: }: not found
./ngrok: line 1: : not found
./ngrok: line 1: R: not found
./ngrok: line 2: X: not found
./ngrok: line 2: : not found
./ngrok: line 4: g: not found
./ngrok: line 5: syntax error: unexpected "("

**Comment by professorIsaac** [comment]
38 stub syscall 375

**Comment by tbodt** [comment]
It sounds like you downloaded the 64 bit version. Download the 32. it version and try again.

**Comment by professorIsaac** [comment]
#
# Fatal error in , line 0
# Check failed: cpu.has_sse2().
#
#
#
#FailureMessage Object: 0xffffd754Illegal instruction

**Comment by professorIsaac** [comment]
Dmesg result is 16 illegal instruction at 0x8096ee7: f2 0f 59 c1 f2 0f 58 44

**Comment by tbodt** [comment]
That's the error you get from node, which is weird because ngrok is written in go. Where did you download from?

**Comment by professorIsaac** [comment]
Npm but dmesg result is more important

**Comment by tbodt** [comment]
Did the dmesg result come from ngrok or npm? What was the output of ngrok?

**Comment by professorIsaac** [comment]
Yeah I tried installing the real ngrok so the dmesg result comes from the real ngrok

**Comment by jankais3r** [comment]
Can confirm, this is a dmesg from ngrok, no node involved.
```
Jans-iPhone:~# ./ngrok
Illegal instruction
Jans-iPhone:~# dmesg
14 illegal instruction at 0x8096ee7: f2 0f 59 c1 f2 0f 58 44 
```

**Comment by professorIsaac** [comment]
Thanks for confirming my case

**Comment by professorIsaac** [comment]
@tbodt what is your opinion on this is it fixable or not?

**Comment by tbodt** [comment]
yes

**Comment by tbodt** [comment]
ngrok works now

**Comment by Jalal2003** [comment]
any solutions ??
