### ISSUE TITLE
Is “scrcpy” possible one I-SH ?

### ISSUE THREAD

**Issue by F3000** [ish-app/ish#725]
More infos here :
https://github.com/Genymobile/scrcpy

**Comment by tbodt** [comment]
It would probably work with ADB over TCP.

Feel free to open a new issue if you try that and it doesn't work.

**Comment by F3000** [comment]
Great . But ADB works in general in your app ? Only wireless ?

**Comment by tbodt** [comment]
It does work (see #498) but not over USB.
