### ISSUE TITLE
Emacs 26.2 “Failed select: Invalid argument”

### ISSUE THREAD

**Issue by DeepakTivari** [ish-app/ish#727]
Fresh install of emacs gives this error:
Failed select: Invalid argument

![D45EB311-651B-47FA-8ED6-C6B13EEB9E39](https://user-images.githubusercontent.com/8651699/82333899-e0869e00-9a19-11ea-91be-1ca6efb3183c.png)

**Comment by tbodt** [comment]
Duplicate of #711
