### ISSUE TITLE
terraform 0.12.24 throws illegal instruction

### ISSUE THREAD

**Issue by repl-mike-roest** [ish-app/ish#729]
Trying to use terraform on ish throws illegal instruction even after #57 

744 illegal instruction at 0x8093db7: f2 0f 59 c1 f2 0f 58 44

Thanks

**Comment by tbodt** [comment]
Works on master

**Comment by repl-mike-roest** [comment]
Awesome great thanks @tbodt wasn't sure if that fix was yet into the testflight or not.

**Comment by tbodt** [comment]
Not in testflight, but hopefully it'll be soon
