### ISSUE TITLE
Ish won’t start after re-install - Could not start session - Error Code 2

### ISSUE THREAD

**Issue by idvorkin** [ish-app/ish#735]
I uninstalled the iSH beta, and then re-installed it.  Now when I launch iSH, I get the below error message and there is no shell after I hit OK

![IMG_0345](https://user-images.githubusercontent.com/280981/82814636-5f317000-9e4c-11ea-89e5-9e072135daee.png)

**Comment by tbodt** [comment]
This is a bug that happens occasionally on install, if you uninstall and reinstall that should fix it.

~Theodore

**Comment by idvorkin** [comment]
Right you are. Closing but out of curiosity what is the problem?

**Comment by tbodt** [comment]
I have no idea... it looks like it gives up halfway through a database migration. It's quite rare and once the problem becomes visible any opportunity to get diagnostics is gone.

**Comment by tbodt** [comment]
Duplicate of #625
