### ISSUE TITLE
Adding python modules 

### ISSUE THREAD

**Issue by ifuchs** [ish-app/ish#741]
How does one go about adding python modules for use with python2 or python3? Is there a PIP command or equivalent that can be used?

**Comment by emkey1** [comment]
pip3 can be used exactly the same as pip for python3 I believe.  You'll likely have to do something like...

apk add python python3

I believe pip and pip3 are included with the main packages but I'm not sure.

**Comment by ifuchs** [comment]
﻿
Thanks. I installed python and there is no pip. However, if I  install python3, there is a pip3.

**Comment by tbodt** [comment]
You might be interested in py2-pip
