### ISSUE TITLE
e2e tests produce div by zero error message when test isn't found

### ISSUE THREAD

**Issue by MatthewMerrill** [ish-app/ish#744]
```
ish (master) $ bash tests/e2e/e2e.bash -e foobar
Runtime error (func=(main), adr=15): Divide by zero
### Passed: 0/0 (%)                ###
```

**Comment by MatthewMerrill** [comment]
Changed: assignee=matthewmerrill
Changed: priority=P4

**Comment by MatthewMerrill** [comment]
+LABEL=Great first issue

**Comment by OrangeFran** [comment]
The error probably appears because there aren't any tests called 'foobar'. So no test ran. But in the end, we divide with NUM_TOTAL. The simplest solution would probably be to check if NUM_TOTAL is 0 and then echo something and exit. I don't know if it should exit with 0.

**Comment by OrangeFran** [comment]
```
if [ "$NUM_TOTAL -eq 0 ]; then
    printf "### No tests found"
    exit 0
```

**Comment by OrangeFran** [comment]
#804
