### ISSUE TITLE
Emacs 

### ISSUE THREAD

**Issue by rf23** [ish-app/ish#749]
Thanks for ish and it works great. I mainly to get Emacs to work with ish which it did with ish 1.0 (65). (with 66 and 67 I saw the failed select error message just like others have reported. BTW, when will a new build release? I understand the issue has been fixed but not rleased yet). 

I am able to get my usual Emacs setup working for most parts. However, I had an issue of some feature not working. I tracked it down and found Emacs was not able to handle substraction properly in lisp. 

If the following code is evaluated, it works fine (if first number is > than 2nd):
 (- 0.5 0.3)
=> it returns 0.2 as a correct answer

However, if I do 

(- 0.3 0.5)  it returns -0.0e+NaN. 

in fact, (- 0.2), which should return -0.2 (negation operator) but under ish Emacs it returns -0.0e+NaN. 

Hope someone also spotted this issue and knows of a fix. Thanks.

**Comment by tbodt** [comment]
Looks like the issue is not with subtraction but with printing negative floats.
```
linux-vm:~# emacs -batch --eval="(print -823908123.2123)"
-0.0e+NaN
```

**Comment by rf23** [comment]
> Looks like the issue is not with subtraction but with printing negative floats.
> 
> ```
> linux-vm:~# emacs -batch --eval="(print -823908123.2123)"
> -0.0e+NaN
> ```

awesome. thanks for the quick fix.
