### ISSUE TITLE
Adding ngrok

### ISSUE THREAD

**Issue by ifuchs** [ish-app/ish#751]
How does one add ngrok?

**Comment by tbodt** [comment]
See ngrok.com

**Comment by ifuchs** [comment]
Thanks but how exactly do you add ngrok to the available binaries?

**Comment by tbodt** [comment]
Same way you would on linux

**Comment by ifuchs** [comment]
Which binary?

**Comment by tbodt** [comment]
The 32 bit linux one, duh

**Comment by ifuchs** [comment]
Evidently you are averse to actually providing instruction on how to do
this. Sorry for bothering you.

**Comment by tbodt** [comment]
Yeah, I feel like that since it works the same way as a normal linux system, this isn't the best place to find out how to do it.

**Comment by ifuchs** [comment]
Yes, Pip install ngrok runs but does not result in being able to simply run
ngrok so obviously there must be another step on the iPhone.

**Comment by tbodt** [comment]
https://pypi.org/project/ngrok/ is completely unrelated to ngrok.com and I suspect might be malware. TBH ngrok.com needs better install instructions, but it's not my job to do that.

**Comment by ifuchs** [comment]
Thanks, I have figured it out. I agree that you need not provide ngrok install instructions but this thread would be have been a lot shorter if you had simply said, "use apk add to get wget, copy the file and unzip it.

**Comment by ifuchs** [comment]
actually wget was probably already in /usr/bin.

**Comment by tbodt** [comment]
I agree I wasn't communicating very well, sorry about that. I should have said something like [this](https://github.com/ish-app/ish/issues/751#issuecomment-636566361) up front.
