### ISSUE TITLE
Keyboard hiding/rotation broken by extra key hiding

### ISSUE THREAD

**Issue by tbodt** [ish-app/ish#753]
Various reports from discord:
https://discord.com/channels/508839261924229141/508839261924229143/716818832370696233
https://cdn.discordapp.com/attachments/508839261924229143/716819380549451796/video0.mp4
https://cdn.discordapp.com/attachments/508839261924229143/716824325440798720/video0.mp4

The keyboard doesn't go away when the terminal resigns first responder. On iPhone (6s, 13.3.1), rotation is broken.

**Comment by yu90nusTr** [comment]
Me too (ios 13.3.1 ipad 7)

**Comment by tbodt** [comment]
Revert is in, this issue is now tracking fixing the actual problem

**Comment by tbodt** [comment]
Should be fixed by 3c186de2bc3101e19430ca1c91f2189ea2b3fe9b
