### ISSUE TITLE
Advanced debugging menu not accessible

### ISSUE THREAD

**Issue by 0507spc** [ish-app/ish#757]
iPhone 11 Pro Max: when accessing the advanced menu, the scrolling is not working, so unable to access the options.

Tried killing and still the same.

**Comment by tbodt** [comment]
Can you post a screenshot or screen recording?

**Comment by 0507spc** [comment]
[Video](https://imgur.com/a/gTxexIm)

I seem to have a workaround by clicking the hide keyboard icon (that does nothing on phone). Though that allows scrolling to work.

**Comment by tbodt** [comment]
Looks like an extension of #753
