### ISSUE TITLE
Is there a way to run node.js scripts in ISH ?

### ISSUE THREAD

**Issue by obrassard** [ish-app/ish#760]
Hi ! I was wondering if there is a way to execute nodeJS in ISH ?
I was able to install node flawlessly with apk, however there is an error when I try to run it :

![image](https://user-images.githubusercontent.com/17227551/83479342-4e918300-a466-11ea-8d5a-b565db10923a.jpeg)

Whatever the answer I wanted to tell you that I think this project is very cool and has a lot of potential.
Keep up the good work! ✌️

**Comment by tbodt** [comment]
Not yet. There's already an issue: #90

**Comment by obrassard** [comment]
I hadn't seen the other issue, should have searched a little more, my bad. Thanks 🙏

**Comment by eason204646-droid** [comment]
<img width="1170" height="2532" alt="Image" src="https://github.com/user-attachments/assets/2a2891cb-19c0-4c5d-a5c8-69adabc7d8c5" />
I just ran the version 14.21.3 on ish.
