### ISSUE TITLE
Ping complains about old kernel

### ISSUE THREAD

**Issue by thislooksfun** [ish-app/ish#763]
Running `ping -4 google.com` works, but is preceded by the messages
```
ping: WARNING: your kernel is veeery old. No problems.
ping: WARNING: setsockopt(IP_RETOPTS): Protocol not available
```

`ping` was installed from `iputils-20190709-r0`

**Comment by tbodt** [comment]
Gonna dupe this to #762 because one is about IP_RECVERR and the other is about IPV6_RECVERR which are basically the same

**Comment by thislooksfun** [comment]
This issue has nothing to do with IP_RECVERR or IPV6_RECVERR, which is why I opened it as a separate issue. As I said, running `ping -4 google.com` works just fine, but it has a warning beforehand which could speak to some underlying issue.

**Comment by tbodt** [comment]
Actually it does, the "old kernel" message is printed when your kernel doesn't support IP_RECVERR.

https://github.com/iputils/iputils/blob/d6e1d77dd27f8beba0f35f71427da6df33cb38f9/ping/ping.c#L832

**Comment by thislooksfun** [comment]
Ah, I stand corrected. Very well then.
