### ISSUE TITLE
Change category for iOS screen time stats

### ISSUE THREAD

**Issue by lpiot** [ish-app/ish#764]
Of course, it’s just a _« nice to have »_ enhancement…
Right now, `iSH` screen time is gathered in a category that is _other_. It might be changed to _productivity_ that is more accurate, I suppose.

My2cents.

**Comment by saagarjha** [comment]
I think this is based on App Store categories; not sure if those apply to TestFlight apps.

**Comment by Rexogamer** [comment]
Seemingly untrue, Discord here is the TestFlight version (although it is published on the App Store so dio)

![Uploading 4DB083D8-9D35-4C21-BDE3-78353650EC07.jpeg…]()

**Comment by tbodt** [comment]
@Rexogamer Looks like you clicked submit before it finished uploading

**Comment by Rexogamer** [comment]
fixed

**Comment by tbodt** [comment]
The app store category is set to "Developer Tools", which I understand only exists because the Mac app store has it. I'll change it to "Productivity" so it shows up in that screen time category.
