### ISSUE TITLE
Persisting data after re-installation

### ISSUE THREAD

**Issue by sassanh** [ish-app/ish#769]
Thanks for this wonderful app, I built it and have been playing around with it for a while and I already setup most of my dot-files repository. Now I want to do some minor changes to the code. I'm wondering what happens if I rebuild and run from Xcode, will it persist my data? Or should I install everything from scratch? Is there anyway I can create a backup from my data?

**Comment by tbodt** [comment]
It will install a second copy of the app with its own sandbox. There's currently no way to back up and restore the data, but that's planned, and might even come in the next version (#695).
