### ISSUE TITLE
procmail not working - missing syscall 204 (setregid32)

### ISSUE THREAD

**Issue by rf23** [ish-app/ish#770]
fetchmail seems to be working well; however, I am using procmail as mda to deliver the mail to mail spool. procmail is not working  and dmesg show missing system call 204, which I looked up is setregid32. 

will this system call be added anytime soon? thanks.

**Comment by tbodt** [comment]
I'm not familiar with procmail or fetchmail, could you give me some steps to reproduce this bug?

**Comment by rf23** [comment]
> I'm not familiar with procmail or fetchmail, could you give me some steps to reproduce this bug?

sure. first get procmail package installed:
# apk add procmail

then create a test file with random text (it does not matter even it's not an email message)
iPad [~]# echo "test" > foobar

run procmail and here is the sample result:

iPad [~]# procmail < foobar
Bad system call
iPad [~]# dmesg
46 missing syscall 204
50 missing syscall 204
iPad [~]# 

204 is also used in another program that is used by Emacs when reading mail. I was able to get them all going and working by re-compile them with 204 calls commented out. 

Thanks again for the great work. It's amazing that I can run Emacs on an iPad with almost the same setup I have on my desktop (windows and macos).

**Comment by tbodt** [comment]
Just added an implementation of setregid and setreuid (204 and 203). Let me know if there are any other problems in the next version.

**Comment by rf23** [comment]
awesome. thanks for the quick fix. look forward to the next version.

**Comment by rf23** [comment]
I upgraded to build 72 and can confirm the problem has been fixed. procmail is working fully. thanks.
