### ISSUE TITLE
Ligatures Aren’t Working

### ISSUE THREAD

**Issue by CRKatri** [ish-app/ish#788]
![image](https://user-images.githubusercontent.com/48231187/85185235-27f28b00-b261-11ea-956d-3ce2528447ba.png)
![image](https://user-images.githubusercontent.com/48231187/85185240-2de86c00-b261-11ea-9192-4b8bebf7e8a0.png)
As you can see the ligatures aren’t displaying despite using a font that supports them.

**Comment by tbodt** [comment]
Fixed by #790
