### ISSUE TITLE
console input not working properly

### ISSUE THREAD

**Issue by ifuchs** [ish-app/ish#789]
I tried this program:
```
#include <stdio.h>
int main () {
char str1[20];
printf("Enter name: ");
scanf("%s", str1);
printf("Entered Name: %s\n", str1);
return(0);
```
This results in a wait for input with no prompt. After entering input, the prompt and the printf value are printed together.

**Comment by nguyenhuyblyat** [comment]
where is the last curly boi `}`?

**Comment by ifuchs** [comment]
Sorry, it’s there but for my bad cut/paste.

**Comment by nguyenhuyblyat** [comment]
lmao but did gcc work in iSH? mine doesn’t

**Comment by ifuchs** [comment]
Haha, imho, yes it does after a couple of apk  installs

**Comment by tbodt** [comment]
It seems like glibc is unique in flushing stdout when you call scanf. You'll need to flush manually on musl. This isn't an iSH problem in any case, the same thing happens on a real Alpine system.

**Comment by ifuchs** [comment]
Did not know of the need to flush the buffer. fflush(stdout) fixes the problem.  Thanks.
