### ISSUE TITLE
gpg decrypt failing with missing syscall 352

### ISSUE THREAD

**Issue by bolapara** [ish-app/ish#798]
disclosure: I upgraded alpine to 3.12 to get the ‘pass’ package that is available starting on that version.  I upgraded by changing the /etc/apk/repositories file and running ‘apk upgrade --update-cache --available‘ and then exiting iSH and restarting.  I didn’t try and use gpg before the upgrade to 3.12 so unsure if that is what broke it.

gpg -d fails with:

gpg: public key decryption failed: End of file

dmesg shows:

missing syscall 352

**Comment by tbodt** [comment]
sched_getattr

**Comment by tbodt** [comment]
Pretty sure this is https://github.com/GNOME/glib/blob/ff44c490d48c6056d27b5d2a042d7d85b185ffd6/glib/gthread-posix.c#L1187

**Comment by bolapara** [comment]
Confirmed this fixed it.  Thank you!
