### ISSUE TITLE
App crashes on import of Ubuntu Base tarball, becomes unusable afterwards

### ISSUE THREAD

**Issue by jankais3r** [ish-app/ish#808]
Used tarball: http://cdimage.ubuntu.com/ubuntu-base/releases/18.04/release/ubuntu-base-18.04.4-base-i386.tar.gz

IPS of import crash: [iSH-2020-06-28-214821.zip](https://github.com/ish-app/ish/files/4842917/iSH-2020-06-28-214821.zip)

IPS of post-import launch crash: [iSH-2020-06-28-214905.zip](https://github.com/ish-app/ish/files/4842920/iSH-2020-06-28-214905.zip)

**Comment by PusheenMaster5** [comment]
Have had the same problem with every Ubuntu mini x86 and Debian small cd i386 tarball I make/try
