### ISSUE TITLE
The “open” command needs support.

### ISSUE THREAD

**Issue by Lathryx** [ish-app/ish#814]
I attempted to use “open” to open my browser, however it wasn’t installed. So, I tried installing it, no luck. 

I get the following error message: 

`ERROR: unsatisfiable constraints:
  open (missing):
    required by: world[open]`

Also, is this a the wrong way to ask for such a feature?

**Comment by nguyenhuyblyat** [comment]
iSH is in a sandbox, it can’t be used to open external apps

**Comment by tbodt** [comment]
Dupe of #471
