### ISSUE TITLE
Shortcuts integration

### ISSUE THREAD

**Issue by ifuchs** [ish-app/ish#820]
I know that this has been requested before (18 months ago?) but does any integration from shortcuts to ish exist? For example, is it possible to invoke ish with cli parameters from shortcuts with the result available to an action?

**Comment by tbodt** [comment]
There's nothing new. iOS 14 added the ability to run shortcuts in the main app process, so maybe I'll implement that at some point.

**Comment by ifuchs** [comment]
Given how many things ish can run that are impossible (or at least difficult) to run any other way, please consider adding Shortcuts support. The ability to execute a command and get/put a file would be very useful (much the same as a-shell permits).

**Comment by tbodt** [comment]
#59
