### ISSUE TITLE
rbenv install ruby version compile error

### ISSUE THREAD

**Issue by Equilibri0** [ish-app/ish#826]
Hey, I’ve got the ruby version manager rbenv successfully running on my IPad. If i am going to install any ruby version with rbenv install 2.6.5 as an example, i am running in an compile error, looks like rbenv is downloading the source code of the ruby version and trying to compile it with GCC.

DMESG:

[    0.000000] 616 stub syscall 375
               7939 stub syscall 375
               9058 page fault on 0x4 at 0x56781bc5
               9059 page fault on 0x4 at 0x56781bc5
               9061 page fault on 0x4 at 0x56781bc5

I’ve put the rbenv version install log in the attachment, maybe there is something helpful.

[rbenv.log](https://github.com/ish-app/ish/files/4927013/rbenv.log)

**Comment by Equilibri0** [comment]
PING

**Comment by tbodt** [comment]
![2014 06 12_friendly_ping](https://user-images.githubusercontent.com/5678977/91404628-8b1b1380-e7f6-11ea-8ad4-17d26e4e206b.png)
