### ISSUE TITLE
Wine does not work

### ISSUE THREAD

**Issue by asdfugil** [ish-app/ish#830]
Running `wine cmd` causes illegal instruction

`dmesg` output:
```
[    0.000000] 36 stub syscall 375
               36 illegal instruction at 0x7c40001d: 8e e0 89 e0 8d a4 24 78 
```

**Comment by CrCrate** [comment]
same here, [dmesg output](https://pastebin.com/21jSgM68)

**Comment by canandlamp** [comment]
5th of July of 2023, wine in alpine in iSH cause the same error . . .
