### ISSUE TITLE
Late query for Local Network Permissions on iOS 14 Beta

### ISSUE THREAD

**Issue by boguscoder** [ish-app/ish#831]
On fresh install of iSH (TestFlight) on iOS 14 Beta there's new permission for 'Local network access'. 
The app would ask for it on the first run of smth like 'apk add' but would NOT ask for it if first thing you try is "ping" , it would look like network is just broken

So the ask here is basically to ask for network permissions ealier ¯\\_(ツ)_/¯

**Comment by Mnpn03** [comment]
I can only get the prompt show up when I run `ping localhost`, and local network access is blocked before it has been approved.

https://developer.apple.com/videos/play/wwdc2020/10110/

**Comment by Nicceboy** [comment]
I'm not sure if this should be possible, but I cannot connect/find devices of local WiFi network, even though this permission has been granted.

**Comment by tbodt** [comment]
The app doesn't really have control over when the system prompts for permissions. If anything is blocked without a prompt, that's arguably an iOS bug. Hopefully it's been fixed since the beta period ended.
