### ISSUE TITLE
Running clang 

### ISSUE THREAD

**Issue by ifuchs** [ish-app/ish#832]
clang test.c creates a.out executable file (as expected) but./a.out gives file not found. How to run it?

**Comment by saagarjha** [comment]
Watch https://reviews.llvm.org/D36809.

**Comment by ifuchs** [comment]
Sorry if it should be obvious but how to run the a.out executable?

**Comment by tbodt** [comment]
There is a clang bug where the a.out executable cannot be run when compiled for musl. Saagar linked to a clang patch that would fix it.

**Comment by saagarjha** [comment]
Well, not fully, as even after that clang makes binaries that ld.so will refuse to load. But that patch going in would be a start.

**Comment by ifuchs** [comment]
Thanks although I have no clue as to how to apply that patch in ish to
permit a.out out to be executable.

**Comment by saagarjha** [comment]
Can you do me a favor and run `sed -i s/i586/i386/g` on a simple program compiled with clang and posting your results after running the binary?

**Comment by ifuchs** [comment]
sed -i s/i586/i386/g a.out gives null result.

**Comment by saagarjha** [comment]
What happens when you run a.out? Did it change the binary? (I can't remember how Busybox sed works off the top of my head, sorry…)

**Comment by ifuchs** [comment]
That did it! Thanks for your help!
