### ISSUE TITLE
Impossible to input non-ascii (á, ß, ö...) in apps such as vi(m), mg, emacs

### ISSUE THREAD

**Issue by ashtophet** [ish-app/ish#837]
Hello,

While those characters work fine on ash ("echo Fuß") if I try to input then on vi(m), mg or emacs it doesn't work.
 
Any hint? Tried to setup LANG and LC_* variables to en_US.UTF-8 without better results.

The only text editor I’ve found which supports inputing those characters is https://github.com/antirez/kilo which compiles and runs flawlessly. 

TIA

PS.: video here https://streamable.com/x89d0v

**Comment by rf23** [comment]
Emacs actually supports input and display of unicode characters. add these lines to your .emacs:

       (set-terminal-coding-system 'utf-8)                                                                 
       (set-keyboard-coding-system 'utf-8)

**Comment by ashtophet** [comment]
OMG, how could I have missed that!!

Thank you very much.

Marking it as closed. Sorry for the noise.
