### ISSUE TITLE
feature request: create /var/log/boot.log

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#851]
The effect is equivalent to a cls, although the worst occasion occurred within a few seconds after task-switching from Safari to iSH, when ash spontaneously burped up a few lines of something before the reinit, rebooted (which reset the activeB directory to ~/root) despite the current directory formerly having been set as an iOS system folder(yes it’s now a straw man) It has also been difficult for iSH to run tasks such as apk which maintain their handles open to the file system/network durning background periods, along with the unspoken overall difficulty for other binaries to open handles which ‘do not exist’. The workaround is to touch the file explicitly by name, then recommence the blocked operation. These problems are both unrelentingly-persistent.

**Comment by 62f** [comment]
This may or may not be relevant: stub syscall 375

**Comment by tbodt** [comment]
I've seen this "cls" bug you described before.

In the situation you described where it "rebooted" after opening the app, what most likely happened is: app goes into the background, iOS takes a screenshot to show in the app switcher, then kills the app for whatever reason, then when you open the app again it shows the screenshot and fades it away once the app starts. So that's not a bug, that's how iOS handles killing background apps.

#600 is a known issue where the app is likely to crash if it's using the filesystem while entering the background. I have a hard time understanding the other bugs you're talking about.

**Comment by phatlnga2** [comment]
Vào Th 7, 8 thg 8, 2020 lúc 12:20 Theodore Dubois <notifications@github.com>
đã viết:

**Comment by phatlnga2** [comment]
Vào Th 7, 8 thg 8, 2020 lúc 12:28 pham phat <phatlnga2@gmail.com> đã viết:

**Comment by 62f** [comment]
Until I’ve got the normal means (vat/log/boot.log) for determining whether a blanked screen was indeed as you suggest, a full app restart or a simple cls, all I shall have are “opinions”. But the condition which prompted(🎭) me to start an issue is from just one time after experiencing a cls, after which I resumed to use iSH for a few seconds but iSH spontaneously did what appeared to be a warm reboot: ctrl-alt-del restart. No error, no full app crash, just double resets for no obvious reason. That’s why I included the dmesg report. All of the other simpler cls-only-like events could be written off as the already-infamous fault w/ accesses to /dev/location & iOS task switching, but this dejavu-reset could be its own show.

**Comment by 62f** [comment]
Until I’ve got the normal means (var/log/boot.log) for determining whether a blanked screen was indeed as you suggest, a full app restart or only a simple cls, all I shall be able to provide will be “opinions”.
    The condition which prompted(🎭) me to start a new issue is from just one time, soon after experiencing a cls, on when I had resumed to use iSH for a very few seconds, iSH spontaneously did what appeared to be a warm reboot: ctrl-alt-del restart. No error, no full app crash, just double CLI resets for no obvious reason. That’s why I included the dmesg in this report... a full reboot( after displaying the motd) usually takes away the dmesg entries, but this second warm-reboot had not.
 All of the other simpler cls-only-like events I have been experiencing over and again I have been writing-off as the already-infamous fault concerning simultaneous accesses to /dev/location & iOS task switching, and wasn’t reporting as they weren’t accompanying a bug-app closure- but this dejavu-reset must be its own show, and led me to discover that iSH is also creating no boot log. You wished to know its importance, and here it is.

**Comment by 62f** [comment]
Until I’ve got the normal means (var/log/boot.log) for determining whether a blanked screen was indeed as you suggest, a full app restart or only a simple cls, all I shall be able to provide will be “opinions”.
    The condition which prompted(🎭) me to start a new issue is from just one time, soon after experiencing a cls, on when I had resumed to use iSH for a very few seconds, iSH spontaneously did what appeared to be a warm reboot: ctrl-alt-del restart. No error, no full app crash, just double CLI resets for no obvious reason. That’s why I included the dmesg in this report... a full reboot( after displaying the motd) usually takes away the dmesg entries, but this second warm-reboot had not.
 All of the other simpler cls-only-like events I have been experiencing over and again I have been writing-off as the already-infamous fault concerning simultaneous accesses to /dev/location & iOS task switching, and wasn’t reporting as they weren’t accompanying a bug-app closure- but this dejavu-reset must be its own show, and led me to discover that iSH is also creating no boot log. You wished to know its importance, and here it is.

**Comment by 62f** [comment]
Until I’ve got the normal means (var/log/boot.log) for determining whether a blanked screen was indeed as you suggest, a full app restart or only a simple cls, all I shall be able to provide will be “opinions”.
    The condition which prompted(🎭) me to start a new issue is from just one time, soon after experiencing a cls, on when I had resumed to use iSH for a very few seconds, iSH spontaneously did what appeared to be a warm reboot: ctrl-alt-del restart. No error, no full app crash, just double CLI resets for no obvious reason. That’s why I included the dmesg in this report... a full reboot( after displaying the motd) usually takes away the dmesg entries, but this second warm-reboot had not.
 All of the other simpler cls-only-like events I have been experiencing over and again I have been writing-off as the already-infamous fault concerning simultaneous accesses to /dev/location & iOS task switching, and wasn’t reporting as they weren’t accompanying a bug-app closure- but this dejavu-reset must be its own show, and led me to discover that iSH is also creating no boot log.

**Comment by tbodt** [comment]
I have a theory for the cls bug: the WebView reloaded (all the scrollback is stored in JS). I have no idea what would cause that though.

**Comment by 62f** [comment]
No unexpected iSH warm-reboot after task switching has occurred since doing a major flush of Alpine 3.12 (see #896) reloading and upgrading the packaged binaries with apk... Could be able to close this bug myself, soon.

**Comment by 62f** [comment]
Thinking that I was unable to get ```touch /var/log/boot.log``` to create a file that would survive, I will create the stub and hope one day that a RAM-based OS such as Alpine will one day see fit to populate it. This feature request has been upstaged so brutally by bug #1613 that #851 said: "I need a vacation", so I'm putting it to bed.
