### ISSUE TITLE
/var/log/boot.log neither exists nor is /var usable from file manager in iOS.

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#856]
cat /var/log/boot.log should look something like the following, but more importantly, a boot.log should be accessible from within the iOS file manager for view when iSH does not boot. Currently the /var directory only is accessible after a fully-successful boot, although there is created no boot.log; and alternatively (though not as useful), /foo/var directory already appears as accessible from iOS file manager as ready to be ( or already is populated by ) files for every chroot directory created. k?
ie:
iPhone:# cat /var/log/boot.log
View Linux Boot Logs
[  OK  ] Started Load/Save RF Kill Switch Status.
 [ TIME ] Timed out waiting for device dev-disk-by\x2duuid
-53e41ce9\x2ddc18\x2d458c\x2dbc08\x2d584c208ed615.device.

[DEPEND] Dependency failed for /dev/disk/by-uuid/53e41ce9
-dc18-458c-bc08-584c208ed615.

[DEPEND] Dependency failed for Swap.

 [  OK  ] Reached target System Initialization.

[  OK  ] Listening on UUID daemon activation socket.

[  OK  ] Started Daily Cleanup of Temporary Directories.

[  OK  ] Listening on CUPS Scheduler.

[  OK  ] Started Daily apt activities.

[  OK  ] Reached target Timers.

[  OK  ] Listening on Avahi mDNS/DNS-SD Stack Activation Socket.

[  OK  ] Started ACPI Events Check.

[  OK  ] Started Trigger resolvconf update for networkd DNS.

[  OK  ] Started CUPS Scheduler.

[  OK  ] Reached target Paths.

[  OK  ] Listening on D-Bus System Message Bus Socket.

[  OK  ] Listening on ACPID Listen Socket.

         Starting Console System Startup Logging...

[  OK  ] Listening on Cockpit Web Service Socket.

[  OK  ] Reached target Sockets.

[  OK  ] Reached target Basic System.

          Starting LSB: Set the CPU Frequency Scaling governor to "ondemand"...

[  OK  ] Started ACPI event daemon.

**Comment by tbodt** [comment]
Why should this file exist?

**Comment by tbodt** [comment]
I think I see: this is the default destination of syslog output during boot on Alpine. iSH doesn't by default have syslog or openrc though, so that's not going to work.

**Comment by 62f** [comment]
-also useful ‘for view after a (successful) boot’, to determine whether or not Alpine had indeed been rebooted, as per https://github.com/ish-app/ish/issues/851 Even though the concept of system-on-a-disc is similar to Puppy-linux which tries to run itself totally from within a RAM drive, which philosophy makes little or no use of nonvolatile storage.
