### ISSUE TITLE
Sumbitting icon

### ISSUE THREAD

**Issue by zxc929961112** [ish-app/ish#861]
![未标题-1](https://user-images.githubusercontent.com/32637692/90602670-b7e68e00-e22c-11ea-87e2-45da4c565049.png)

**Comment by tbodt** [comment]
Icon submissions are this way -> #578

I'll go ahead and veto this one though:
1. The alpine logo doesn't have enough contrast
2. The iSH logo is scaled badly
3. The corners will be rounded which will probably cut off the alpine logo
4. The alpine logo is probably protected by trademark and/or copyright
5. Apple's HIG advises not to use text in icons
6. This is really not that original of an idea in the first place
