### ISSUE TITLE
inaccessible iOS keyboard iSH v1(74) after apk executes busybox-1.31.1-r19.trigger (FORTRAN)

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#862]
![9D1A615F-A94B-4FE0-93ED-D9CAE78E9645](https://user-images.githubusercontent.com/68332197/90673731-270cb400-e226-11ea-9714-2b9a77eeffeb.png)

**Comment by tbodt** [comment]
I'm not sure what the problem is that is being reported
