### ISSUE TITLE
Downgrading iSH in TestFlight causes boot fs switch from later versions not to occur.

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#870]
“As a test I will downgrade iSH as far as possible to see if the bug will fix itself,...“

_Originally posted by @62f in https://github.com/ish-app/ish/issues/839#issuecomment-674422669_

Unfortunately I was unable to perform the required test since switching the fs then downgrading iSH only causes a revert to boot the original file system, which attempt is unsuccessful due to the currently ‘borked’-state, and probably will remain so (unbootable) until there’s a method provided to either rename or repair it, besides deleting and replacement. Since I choose not to.
My theory is that iSH v<(1.73) are expecting to find a directory to be named with a specific resource name, and don’t understand whatever the new flag is that has been created especially for them to use: which causes (1.73) & (1.74) to switch and restart into the user’s selected fs. Clearly the directory names of all fs are being kept static for the purpose of these database links to function.

**Comment by tbodt** [comment]
Downgrading is not really supported and may break things in unfixable ways. The only thing that is guaranteed to work is uninstalling the app, thus deleting its data, and then installing an older version.

**Comment by 62f** [comment]
Since I had ‘chosen’ to defer any action on the original Alpine fs what I’ll perform next is a technique called a sideload: expand an old unbootable Alpine fs into a freshly-loaded working minimal fs in order to create the needed pseudo-test environment. Call me Dr. Frankenstein.
