### ISSUE TITLE
‘Calling Dr. Bombay’ (side-loading with tar) has not “broken iSH in unfixable ways.” The iSH thing still boots fine.

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#871]
Frankenstein’s creator says: I do realize that some of these directories <don’t exist> because they belonged to former usernames which weren’t recreated before untarring, but such is how sideloading is done; alpine and Alpine also (were originally chroot-dirs) had trouble. But the only purpose here is imparting the 2 error-types, prefixed below by *, which occurred during the untarring.

_Originally posted by @62f in https://github.com/ish-app/ish/issues/870#issuecomment-678842983_

iPhone# tar -C / -xf /sys/alpine/alpine.tar.gz --skip-old-files

tar: ./dev/pts: Cannot mkdir: Operation not permitted
tar: ./proc: Cannot mkdir: Operation not permitted
* tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: ./root/python-gcc/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/__init__.py: Cannot utime: Operation not permitted
tar: ./root/python-gcc/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/__init__.py: Cannot utime: Operation not permitted
tar: ./root/python-gcc/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/gcc_root/gcc7/gcc7/__init__.py: Cannot utime: Operation not permitted
tar: ./root/homebrew/Library/Homebrew/os/mac/pkgconfig/fuse/osxfuse.pc: Cannot open: No such file or directory
tar: ./root/homebrew/Library/Homebrew/os/mac/pkgconfig/fuse/fuse.pc: Cannot open: No such file or directory
tar: ./usr/bin/go~: Cannot open: No such file or directory
tar: ./openpkg: Cannot open: Is a directory
tar: ./root/nvdimm/scripts/dtc/include-prefixes/arc: Cannot open: Is a directory
tar: ./root/nvdimm/scripts/dtc/include-prefixes/arm: Cannot open: Is a directory
tar: ./root/nvdimm/scripts/dtc/include-prefixes/arm64: Cannot open: Is a directory
tar: ./root/nvdimm/scripts/dtc/include-prefixes/c6x: Cannot open: Is a directory
tar: ./root/nvdimm/scripts/dtc/include-prefixes/dt-bindings: Cannot open: Is a directory
tar: ./root/nvdimm/scripts/dtc/include-prefixes/h8300: Cannot open: Is a directory
tar: ./root/nvdimm/scripts/dtc/include-prefixes/microblaze: Cannot open: Is a directory
tar: ./root/nvdimm/scripts/dtc/include-prefixes/mips: Cannot open: Is a directory
tar: ./root/nvdimm/scripts/dtc/include-prefixes/nios2: Cannot open: Is a directory
tar: ./root/nvdimm/scripts/dtc/include-prefixes/openrisc: Cannot open: Is a directory
tar: ./root/nvdimm/scripts/dtc/include-prefixes/powerpc: Cannot open: Is a directory
tar: ./root/nvdimm/scripts/dtc/include-prefixes/sh: Cannot open: Is a directory
tar: ./root/nvdimm/scripts/dtc/include-prefixes/xtensa: Cannot open: Is a directory
tar: ./storage/openpkg/openpkg: Cannot open: Is a directory
tar: ./home/Songoku/var/run: Cannot open: Is a directory
tar: ./home/Songoku/var/spool/cron/crontabs: Cannot open: Is a directory
tar: ./home/Songoku/var/spool/mail: Cannot open: Is a directory
tar: ./home/Songoku/etc/init.d/functions.sh: Cannot open: No such file or directory
tar: ./home/Songoku/sbin/rc-sstat: Cannot open: No such file or directory
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: ./Alpine/var/run: Cannot open: Is a directory
tar: ./Alpine/var/spool/cron/crontabs: Cannot open: Is a directory
tar: ./Alpine/var/spool/mail: Cannot open: Is a directory
tar: ./Alpine/etc/init.d/functions.sh: Cannot open: No such file or directory
tar: ./Alpine/sbin/rc-sstat: Cannot open: No such file or directory
tar: ./alpine/var/run: Cannot open: Is a directory
tar: ./alpine/var/spool/cron/crontabs: Cannot open: Is a directory
tar: ./alpine/etc/init.d/functions.sh: Cannot open: No such file or directory
tar: ./alpine/sbin/rc-sstat: Cannot open: No such file or directory
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: ./alpine/usr/lib/terminfo: Cannot open: Is a directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/var/spool/mail: Cannot open: Is a directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/var/run: Cannot open: Is a directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/usr/sbin/rmt: Cannot open: No such file or directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/usr/bin/w: Cannot open: No such file or directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/usr/bin/pager: Cannot open: No such file or directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/usr/bin/nawk: Cannot open: No such file or directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/usr/bin/awk: Cannot open: No such file or directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/etc/systemd/system/timers.target.wants/motd-news.timer: Cannot open: No such file or directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/etc/systemd/system/timers.target.wants/fstrim.timer: Cannot open: No such file or directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/etc/systemd/system/timers.target.wants/e2scrub_all.timer: Cannot open: No such file or directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/etc/systemd/system/timers.target.wants/apt-daily.timer: Cannot open: No such file or directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer: Cannot open: No such file or directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/etc/systemd/system/default.target.wants/e2scrub_reap.service: Cannot open: No such file or directory
tar: ./alpine/home/ubuntu-in-ish/ubuntu-fs/var/run: Cannot open: Is a directory
tar: ./alpine/home/ubuntu-in-ish/ubuntu-fs/var/spool/mail: Cannot open: Is a directory
tar: ./alpine/home/ubuntu-in-ish/ubuntu-fs/usr/sbin/rmt: Cannot open: No such file or directory
tar: ./alpine/home/ubuntu-in-ish/ubuntu-fs/usr/bin/pager: Cannot open: No such file or directory
tar: ./alpine/home/ubuntu-in-ish/ubuntu-fs/usr/bin/awk: Cannot open: No such file or directory
tar: ./alpine/home/ubuntu-in-ish/ubuntu-fs/usr/bin/nawk: Cannot open: No such file or directory
tar: ./alpine/home/ubuntu-in-ish/ubuntu-fs/usr/bin/w: Cannot open: No such file or directory
tar: ./alpine/home/ubuntu-in-ish/ubuntu-fs/etc/systemd/system/timers.target.wants/motd-news.timer: Cannot open: No such file or directory
tar: ./alpine/home/ubuntu-in-ish/ubuntu-fs/etc/systemd/system/timers.target.wants/fstrim.timer: Cannot open: No such file or directory
tar: ./alpine/home/ubuntu-in-ish/ubuntu-fs/etc/systemd/system/timers.target.wants/apt-daily.timer: Cannot open: No such file or directory
tar: ./alpine/home/ubuntu-in-ish/ubuntu-fs/etc/systemd/system/timers.target.wants/apt-daily-upgrade.timer: Cannot open: No such file or directory
tar: ./alpine/dev/dev: Cannot open: Is a directory
tar: ./alpine/bin/dev: Cannot open: Is a directory
tar: ./dev/dev: Cannot open: Is a directory
tar: ./root/dev: Cannot open: Is a directory
tar: ./alpine/home/ubuntu-in-ish/ubuntu-fs/sys: Cannot open: Is a directory
tar: ./alpine/home/ubuntu-in-ish/ubuntu-fs/dev: Cannot open: Is a directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/musl/objdir/dev: Cannot open: Is a directory
tar: ./alpine/alpine/var/run: Cannot open: Is a directory
tar: ./alpine/alpine/var/spool/cron/crontabs: Cannot open: Is a directory
tar: ./alpine/alpine/var/spool/mail: Cannot open: Is a directory
tar: ./alpine/alpine/etc/init.d/functions.sh: Cannot open: No such file or directory
tar: ./alpine/alpine/sbin/rc-sstat: Cannot open: No such file or directory
tar: ./alpine/alpine/root: Cannot open: Is a directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/root/dev: Cannot open: Is a directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/sys: Cannot open: Is a directory
tar: ./alpine/root/ubuntu-in-ish/ubuntu-fs/dev: Cannot open: Is a directory
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
tar: Ignoring unknown extended header keyword 'hdrcharset'
*tar: Exiting with failure status due to previous errors

**Comment by tbodt** [comment]
I have no idea what the bug is that you are reporting

**Comment by 62f** [comment]
It seems that tar from Alpine 3.12 has gone ahead and overwritten the Alpine binaries despite being instructed by the above command NOT to do so. Look at the tar —help, and note that —skip-old-files is no longer a feature.
Also the last line: which is an attempt to use tar, has been unable to finish for some hours.
* Text from screenshot in case it doesn’t load
. /lib/firmware/tigon/
./lib/firmware/tigon/tg3_tso5.bin
./lib/firmware/tigon/tg357766.bin
./lib/firmware/tigon/tg3.bin
./lib/firmware/tigon/tg3_tso.bin
./lib/firmware/ti-keystone/
./lib/firmware/ti-keystone/ks2_qmss_pdsp_acc48_k2_le_1_0_0_9.bin
./lib/firmware/ti-connectivity/
./lib/firmware/ti-connectivity/wl12xx-nvs.bin
tar: can't create symlink './lib/firmware/ti-connectivity/wl12xx-nvs.bin' to 'wl127x-nvs.bin': File exists
iPhone# tar -C / -xf alpine.tar.gz -k -t   
BusyBox v1.31.1 () multi-call binary.

Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [--exclude PATTERN]... [FILE]...

Create, extract, or list files from a tar file

        c       Create
        x       Extract
        t       List
        -f FILE Name of TARFILE ('-' for stdin/out)
        -C DIR  Change to DIR before operation
        -v      Verbose
        -O      Extract to stdout
        -m      Don't restore mtime
        -o      Don't restore user:group
        -k      Don't replace existing files
        -Z      (De)compress using compress
        -z      (De)compress using gzip
        -J      (De)compress using xz
        -j      (De)compress using bzip2
        -a      (De)compress using lzma
        -h      Follow symlinks
        -T FILE File with names to include
        -X FILE File with glob patterns to exclude
        --exclude PATTERN       Glob pattern to exclude
iPhone# tar -t alpine.tar.gz -k   
 
*   This version of tar appears unable to finish.
*  so I’m asking for anyone’s opinion if it’s now warranted to file an Alpine bug for the above hijack caused by tar, or if the above documented destruction is somehow iSH’s fault ( unless the alpine.tar.gz itself was somehow at fault then it doesn’t seem to be).
