### ISSUE TITLE
TAR from busybox also disregards instruction not to overwrite.

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#876]
It seems that tar from Alpine 3.12 has gone ahead and overwritten the Alpine binaries despite being instructed by the above command NOT to do so. Look at the tar —help, and note that —skip-old-files is no longer a feature.
Also the last line: which is an attempt to use tar, has been unable to finish for some hours.
* Text from screenshot in case it doesn’t load
```
. /lib/firmware/tigon/
./lib/firmware/tigon/tg3_tso5.bin
./lib/firmware/tigon/tg357766.bin
./lib/firmware/tigon/tg3.bin
./lib/firmware/tigon/tg3_tso.bin
./lib/firmware/ti-keystone/
./lib/firmware/ti-keystone/ks2_qmss_pdsp_acc48_k2_le_1_0_0_9.bin
./lib/firmware/ti-connectivity/
./lib/firmware/ti-connectivity/wl12xx-nvs.bin
tar: can't create symlink './lib/firmware/ti-connectivity/wl12xx-nvs.bin' to 'wl127x-nvs.bin': File exists
iPhone# tar -C / -xf alpine.tar.gz -k -t   
BusyBox v1.31.1 () multi-call binary.

Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [--exclude PATTERN]... [FILE]...

Create, extract, or list files from a tar file

        c       Create
        x       Extract
        t       List
        -f FILE Name of TARFILE ('-' for stdin/out)
        -C DIR  Change to DIR before operation
        -v      Verbose
        -O      Extract to stdout
        -m      Don't restore mtime
        -o      Don't restore user:group
        -k      Don't replace existing files
        -Z      (De)compress using compress
        -z      (De)compress using gzip
        -J      (De)compress using xz
        -j      (De)compress using bzip2
        -a      (De)compress using lzma
        -h      Follow symlinks
        -T FILE File with names to include
        -X FILE File with glob patterns to exclude
        --exclude PATTERN       Glob pattern to exclude
iPhone# tar -t alpine.tar.gz -k   
```` 

*   This version of tar appears unable to finish.
*  so I’m asking for anyone’s opinion if it’s now warranted to file an Alpine bug for the above hijack caused by tar, or if the above documented destruction is somehow iSH’s fault ( unless the alpine.tar.gz itself was somehow at fault then it doesn’t seem to be).

_Originally posted by @62f in https://github.com/ish-app/ish/issues/871#issuecomment-679009248_

Cause of above problem is fixed and screenshot from successfully completed untar is being attached in a comment below:

**Comment by 62f** [comment]
![5027EEBE-DFD1-4B5C-8685-6EC52223270F](https://user-images.githubusercontent.com/68332197/91322332-9d149c00-e78d-11ea-88fc-e6946cc2f2b2.jpeg)

**Comment by 62f** [comment]
What’s not immediately obvious is that the image above is barely the beginning of creating an enormous exclude file for tar line-by-line. Eventually while building that, tar -k gets ahold of some file access permission system registry and garbles it, causing an iSH error -13 whereby iSH can’t successfully boot using files which are otherwise present and valid because Alpine no longer lets root user execute them. Then after some further tar offenses, tar overwrites busybox’s bin executable with the one from the tar.gz which causes “iSH unable to boot -2”. It might work better to pipe the whole blasted directory tree straight into an exclude file...

**Comment by tbodt** [comment]
From my read of busybox tar, -k just disables the behavior where it deletes files before extracting them. You're supposed to get errors if the file exists.
