### ISSUE TITLE
![AE766374-8270-4331-BF23-2E9AF7DA7282](https://user-images.githubusercontent.com/8845353/72582475-85e10800-38a8-11ea-86b0-096d1c0275c8.png)

### ISSUE THREAD

**Issue by alyzidi222** [ish-app/ish#878]
![AE766374-8270-4331-BF23-2E9AF7DA7282](https://user-images.githubusercontent.com/8845353/72582475-85e10800-38a8-11ea-86b0-096d1c0275c8.png)
Examples of a few on black

_Originally posted by @ntindle in https://github.com/ish-app/ish/issues/578#issuecomment-575450539_

**Comment by Mnpn03** [comment]
I'm not quite sure what you mean to say with this issue, that's just ntindle's comment
