### ISSUE TITLE
Using ngrok

### ISSUE THREAD

**Issue by ifuchs** [ish-app/ish#883]
I am running a webserver using JSBox on port 4000 and I would like to use ngrok under ish to access this port from outside. ngrok runs fine and seems to create a tunnel. The server is running ( I can access it on the local network). Is what I am trying to do workable or is there some restriction that I am bumping against?

**Comment by ifuchs** [comment]
I managed to get this working on an iPad as long as the app running the server and ish were sharing the screen. I can access the webserver from off the local network Perhaps this will not work on ios due to the inability to run the 2 apps simultaneously? Or is there something else I am missing?

**Comment by tbodt** [comment]
iOS won't usually let apps run in the background. I think you'll just have to use split screen, unless you can find a way to make JSBox run in the background. Or maybe you could run iSH in the background (https://github.com/ish-app/ish/wiki/Running-in-background) and JSBox in the foreground.

**Comment by ifuchs** [comment]
Running iSH in the background allowed it to work. Thanks.
