### ISSUE TITLE
Reopen ed to check length of file results in subsequent line deletion of target file

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#884]
ed caused 2-line file to lose half of its contents presumably after being opened. Better cat any file opened by ed to check it until the cause of this is fixed.
![C4BDFC88-CA2A-451A-A488-80304B8D6FAB](https://user-images.githubusercontent.com/68332197/91876000-363e2980-ec4a-11ea-82ef-40b34c7042f7.jpeg)

**Comment by 62f** [comment]
Just by looking it could appear that there’s also a chance that gcc, zsh, ^z or another I/O operation is chewing up these files, but ed on its own behaves erratically enough already in 3.12 to warrant downgrading http://dl-cdn.alpinelinux.org/alpine/v3.9/releases/x86/alpine-netboot-3.9.6-x86.tar.gz for doing anything serious. gcc also seems to be unable to finish compiling a C-language program, but this bane is a legacy of anything Ubuntu-derived.

**Comment by tbodt** [comment]
I can reproduce this on a real linux system, so it must be a bug in busybox ed.
