### ISSUE TITLE
`dig` Doesn't Work

### ISSUE THREAD

**Issue by iamrecursion** [ish-app/ish#891]
Running `dig` results in the following on Alpine Edge:

```
> dig google.com
time.c:118: Invalid argument
timer.c:634: fatal error: RUNTIME_CHECK(isc_time_now((&now)) == 0) failed
Aborted
```

**Comment by 62f** [comment]
I also get the same error on 3.12 after install
{
> apk add nagios-plugins-dig
}
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86/APKINDEX.tar.gz
(1/14) Installing nagios-plugins (2.3.2-r0)
(2/14) Installing fstrm (0.6.0-r1)
(3/14) Installing krb5-conf (1.0-r2)
(4/14) Installing libcom_err (1.45.6-r0)
(5/14) Installing keyutils-libs (1.6.1-r1)
(6/14) Installing libverto (0.3.1-r1)
(7/14) Installing krb5-libs (1.18.2-r0)
(8/14) Installing json-c (0.14-r1)
(9/14) Installing libprotobuf (3.12.2-r0)
(10/14) Installing libprotoc (3.12.2-r0)
(11/14) Installing protobuf-c (1.3.3-r1)
(12/14) Installing bind-libs (9.16.6-r0)
(13/14) Installing bind-tools (9.16.6-r0)
(14/14) Installing nagios-plugins-dig (2.3.2-r0)
Executing busybox-1.31.1-r19.trigger
https://nagios-plugins.org/

**Comment by ankushnarula** [comment]
Just tested `dig` with App Store release version and it appears to work now.

`iPad:~# dig google.com

; <<>> DiG 9.12.4-P2 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52813
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             250     IN      A       172.217.15.78

;; Query time: 19 msec
;; SERVER: 10.0.0.242#53(10.0.0.242)
;; WHEN: Thu Oct 22 19:54:58 UTC 2020
;; MSG SIZE  rcvd: 55

ipad:~# uname -a
Linux ipad 4.20.69-ish iSH 1.0 (76.2) Oct 20 2020 09:48:32 i686 Linux`

**Comment by iamrecursion** [comment]
This is specifically for `dig` on alpine edge. You're likely on the latest stable release of alpine on the app store version, which works fine last I checked!

**Comment by mbaierl** [comment]
I just tested about 10 minutes ago with the latest app store version - it does not work.

**Comment by tbodt** [comment]
Still makes noise about unsupported socket options, but at least it works.

**Comment by iamrecursion** [comment]
Can confirm it works on `master`.

**Comment by Equilibri0** [comment]
i've installed the bind-tools to test it aswell and i am also getting an error. 

dig google.com

ERROR: 
timer.c:118: invalid argument 

dmesg:
653 stub syscall 375

**Comment by atefsaleh** [comment]
Installed bind-tools on appstore version getting the same error

**Comment by 62f** [comment]
socket.c:2294: setsockopt(20, IPV6_RECVPKTINFO) failed: Invalid argument
socket.c:2405: setsockopt(20, IPV6_RECVTCLASS) failed: Invalid argument

; <<>> DiG 9.16.6 <<>> google.com
