### ISSUE TITLE
phpMyAdmin with php7 crashes

### ISSUE THREAD

**Issue by x-magic** [ish-app/ish#892]
When serving phpMyAdmin with PHP7 on alpine in iSH, PHP crashes with Illegal instructions. 

```root@BHGsID-iPad:~/phpMyAdmin-5.0.2-english# php -S localhost:8080
PHP 7.3.22 Development Server started at Thu Sep 10 16:49:09 2020
Listening on http://localhost:8080
Document root is /root/phpMyAdmin-5.0.2-english
Press Ctrl-C to quit.
Illegal instruction
```

dmesg message: 
```root@BHGsID-iPad:~/phpMyAdmin-5.0.2-english# dmesg
3774 stub syscall 375
FIXME unimplemented setitimer 2
FIXME unimplemented setitimer 2
3774 illegal instruction at 0xf54e9eed: 0f 73 f9 01 83 e1 0f 66 
3796 stub syscall 375
FIXME unimplemented setitimer 2
FIXME unimplemented setitimer 2
3796 illegal instruction at 0xf54e9eed: 0f 73 f9 01 83 e1 0f 66
```

Not sure if it has anything to do with #597 as I’m not really running MySQL server within iSH. 

Cheers

**Comment by mtarek** [comment]
Getting the same instruction error trying to run composer or `php composer-setup.php`

illegal instruction at 0xf6a9fb65: 0f 73 f9 01 83 e1 0f 66

**Comment by x-magic** [comment]
Tested with iSH 1.0.1 (77) App Store version. Now it works as expected. 

Weird that cmpxchg8b was implemented quite a while ago, but PMA only work until now.
