### ISSUE TITLE
Testflight is full

### ISSUE THREAD

**Issue by behnammodi** [ish-app/ish#893]
<img width="209" alt="Screen Shot 2020-09-10 at 23 53 38" src="https://user-images.githubusercontent.com/1549069/92790260-dde0f780-f3c0-11ea-8808-71d815cc858c.png">

**Comment by tbodt** [comment]
You'll have to either use AltStore or wait for me to remove some testers.

I'm curious how you found out about this beta? There seems to have been a big spike recently and I'm not sure where it's coming from.

**Comment by ntindle** [comment]
Is iSH listed in Airport?

**Comment by tbodt** [comment]
Hmm yeah that could be it. I submitted it recently.

**Comment by Jsn2win** [comment]
I heard about it from a buddy of mine I went to school with.

**Comment by abdullah0sedeq** [comment]
Nsns

**Comment by behnammodi** [comment]
@tbodt from here https://testflight.apple.com/join/97i7KM8O

**Comment by tbodt** [comment]
Testflight is no longer full.

**Comment by pipecc** [comment]
﻿from the Internet, I do not remember what site, please do not delete me




Отправлено с iPhone

10 сент. 2020 г., в 23:56, Theodore Dubois <notifications@github.com> написал(а):

You'll have to either use AltStore or wait for me to remove some testers.

I'm curious how you found out about this beta? There seems to have been a big spike recently and I'm not sure where it's coming from.



Отправлено с iPhone
