### ISSUE TITLE
Can’t build on MacOS Big Sur / iOS 14

### ISSUE THREAD

**Issue by TinQ0** [ish-app/ish#894]
I'm trying to build this app for my iPhone on iOS 14 while on MacOS Big Sur using the Xcode beta and the build fails:

No account for team "CK5SXRTBR7". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.

No profiles for 'com.twix.iSH' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.twix.iSH'.

Anything I could do or should I try the standard Xcode on Catalina?

**Comment by tbodt** [comment]
You have to change the team on the xcode project in the signing tab, or it will try to sign the app as me. Not sure why this isn't in the readme.
