### ISSUE TITLE
The new icon

### ISSUE THREAD

**Issue by loloco22** [ish-app/ish#898]
The new icon
![C14BC579-0E2F-47D1-874F-82AD5CB4562D](https://user-images.githubusercontent.com/46279716/93008378-99af4c00-f5a6-11ea-9051-41300e3dd5a1.jpeg)

_Originally posted by @stc2001 in https://github.com/ish-app/ish/issues/578#issuecomment-691590729_

**Comment by saagarjha** [comment]
Please post icon suggestions in #578 rather than making new issues.

**Comment by Mnpn03** [comment]
Duplicate from the App icon submissions thread (you can react with a thumbs up if you like it, you don't need to open another issue)
