### ISSUE TITLE
node/npm needs SSE

### ISSUE THREAD

**Issue by philipamour** [ish-app/ish#90]
Running npm or node returns 'Bad system call'

**Comment by Mnpn03** [comment]
Node is on the list. https://github.com/tbodt/ish/projects/7

**Comment by mattapperson** [comment]
If someone (me) wanted to push this forward. Is there a recommended place to start debugging what’s needed here?

**Comment by tbodt** [comment]
You can try to run the program with strace logging enabled (on by default in Xcode, `meson configure -Dlog=strace` if you're running ish standalone), and find out what system call it's attempting to use. My hunch is that you'll find it's trying to call `epoll_create`, which is the entry point to an entire unimplemented subsystem that will have to be implemented before node can get anywhere at all. If you're feeling up to the task, a decent starting point would be the implementations of `select` and `poll`.

**Comment by philipamour** [comment]
Wish I could help anyhow; however, my expertise is limited to software design (iXD, UI, UX, PM, ...)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mnpn03** [comment]
No longer a bad system call:
```
Device:~# node
Illegal instruction
Device:~# dmesg
FIXME socketcall 16
13 page fault on 0x50 at 0x567336fd
unknown ioctl 5451
unknown ioctl 5451
unknown ioctl 5451
19 illegal instruction at 0x56cc250f: f2 0f 10 02 b2 00 66 0f ```

**Comment by kaleocheng** [comment]
what's the next for this?

**Comment by zerkotin** [comment]
is it a priority? it would be amazing to be able to run node so I can build my project and run it

**Comment by Envo** [comment]
Any update on this?

**Comment by tbodt** [comment]
no

**Comment by pburtchaell** [comment]
Hi all, lurker here. To all of the folks replying with "Any update? What's next? What's the priority?", please don't. It's disrespectful to the community and the owner of this project to hammer issues with rhetorical questions.

This is an open source project and the issue is clearly up for grabs (see "No one assigned" on the assignees space). If you're interested in seeing node support added, subscribe to the issue and either (a) do it yourself or (b) wait for someone else to do it.

**Comment by zerkotin** [comment]
A. No one means any disrespect, if anything we cared enough to search for the repo and look for bugs... 
B. If I or anyone had a clue how to do that we probably would, but we don’t,
C. It’s important to be able to run JavaScript on iPad because it will open a whole ne world, and as you can see from the poll you made on the main page, most people use JavaScript html and so on

Please see it as a plea to push it up the priority ladder instead of a disrespectful comment.

**Comment by tbodt** [comment]
What's the poll I made on the main page?

**Comment by zerkotin** [comment]
Got it mixed with another page sorry...

**Comment by Envo** [comment]
I'm sorry if i was disrespectful, it wasn't my intention.

**Comment by Macmee** [comment]
to get node to work, don't we need to implement SSE2 which is pretty big?

**Comment by tbodt** [comment]
Yeah

**Comment by Inukinator** [comment]
Would it make sense to abuse JavaScriptCore somehow (not that I know how) to add node support for those who wants it?

I see how this can be problematic for those who doesn't care about nodes at all in iOS (such as myself)

**Comment by tbodt** [comment]
No, JavaScriptCore isn't a good substitute for Node. They're completely different programs, with different supported features.

**Comment by jusdepatate** [comment]
btw Rescript (free on Apple's App Store) has a full and working environment in NodeJS

**Comment by tbodt** [comment]
That's pretty cool, I haven't seen it before. I bet it's really slow though.

**Comment by jusdepatate** [comment]
i tried it one time on my iPad (6th) it was pretty good, don't know if it's what he wants

**Comment by Inukinator** [comment]
Their sample project is super fast!

**Comment by templarundead** [comment]
> > is it a priority? it would be amazing to be able to run node so I can build my project and run it
> 
> btw Rescript (free on Apple's App Store) has a full and working environment in NodeJS

Also Play.js but is paid.

**Comment by mattapperson** [comment]
I don’t know enough to know how much work getting support for node would be. But is there a bounty amount that would make it worth someone’s time?

**Comment by Envo** [comment]
Rescript looks nice, but what I really need is Gulp, which can be installed as a node module via npm.

**Comment by filfat** [comment]
Howdy,

I have created a bounty for this issue https://www.bountysource.com/issues/66159647-npm-node-support

**Comment by Rexogamer** [comment]
Would https://github.com/janeasystems/nodejs-mobile be of any use?

**Comment by tbodt** [comment]
@Rexogamer no not really

**Comment by k16blfurm** [comment]
Apparently, there is hope for this if you want to run a really old version of node.

[https://github.com/nodejs/node/issues/8926](url)

Although, compiling from source in iSH for really big programs crashes, so take it with a grain of salt.

**Comment by tbodt** [comment]
Crashing when compiling large programs is something I've noticed too, I suspect it's because of memory leaks. Filed issue #464 for that.

**Comment by mrbrianhinton** [comment]
The lack of Dev tools anywhere in iOS is what led me to a Surface Go. I'm still watching this issue with hope in my heart. A real dev env is the only thing missing on iPad. I suspect multithreading and memory issues will crush Node truly coming to iPad. Not to mention all the various package compatibility issues. Just Node isn't going to suddenly open all possibilities. A lot of packages require build pipelines that could involve Make, Python and any number of additional libraries. Much appreciation to all the Ish devs!

**Comment by brandonros** [comment]
Couldn’t somebody just recompile node.js to not use SSE2 instructions in the compiler flags?

Is it node.js, V8, or both that would need the compiler flags changed?

**Comment by tbodt** [comment]
The V8 JIT made SSE2 mandatory 6 years ago. https://github.com/v8/v8/blame/4b9b23521e6fd42373ebbcb20ebe03bf445494f9/src/ia32/assembler-ia32.cc#L129

As mentioned above, you could try compiling node 0.10.x, which uses a version of V8 from before this requirement.

**Comment by brandonros** [comment]
Gotcha. Fabrice Bellard’s QuickJS may almost be an alternative.

Does Linux’s epoll work with iSH yet or no?

**Comment by tbodt** [comment]
Yes. quickjs is in the alpine testing repo, it probably works fine.

**Comment by brandonros** [comment]
Is there a list of what SSE2 instructions the V8 JIT requires? We could compare them to what is already implemented to break this ticket into “actionable items”.

**Comment by tbodt** [comment]
https://github.com/v8/v8/blob/61dd16ade0695310787267740609094d61048862/src/codegen/ia32/assembler-ia32.h#L833

**Comment by tbodt** [comment]
Not all of those are used, but they're all available. There's no list of which ones are actually used.

**Comment by brandonros** [comment]
Do we have a list of what SSE/SSE2 is already implemented in iSH?

Regards,

Brandon

________________________________

**Comment by tbodt** [comment]
cc @MatthewMerrill

**Comment by MatthewMerrill** [comment]
I don't have a canonical list (I should make one though). If you search for " V" (including the space) in https://github.com/tbodt/ish/blob/master/emu/decode.h that includes all the SSE stuff.

There's also https://github.com/tbodt/ish/tree/master/tests/e2e/sse2 but that's lagging behind quite a bit.

**Comment by MatthewMerrill** [comment]
Those V__() macros are defined in https://github.com/tbodt/ish/blob/master/jit/gen.c
and those indirectly call https://github.com/tbodt/ish/blob/master/emu/sse.h

**Comment by brandonros** [comment]
Is there any way to capitalize on the TCG portions of QEMU for these instructions?

**Comment by tbodt** [comment]
No

**Comment by texasbruce** [comment]
can we make this priority?

**Comment by tbodt** [comment]
@texasbruce in open source, if you want something done, you do it yourself

**Comment by texasbruce** [comment]
> @texasbruce in open source, if you want something done, you do it yourself

So sponsors don’t get anything?

**Comment by tbodt** [comment]
Sorry didn't see you were a sponsor. But not in this case, my sponsor page is just a way for you to express your appreciation.

**Comment by GalacticLion7** [comment]
Could SpiderNode

https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey

**Comment by GalacticLion7** [comment]
Could [SpiderNode](https://github.com/mozilla/spidernode) be a workaround to this issue? SpiderNode is basically Node.js decoupled from V8 to SpiderMonkey.

**Comment by itsmepetrov** [comment]
I've tried to run `nodejs` using https://github.com/ish-app/ish/commit/55816c8be60b85f650772a2ce0e6721ec4e8feab changes.

Now it's able to run `nodejs` but it can't close the process.

How to reproduce:

```bash
apk add nodejs
echo "console.log(123); > index.js"
node index.js
```

It prints `123` and gets stuck after that.

**Comment by tbodt** [comment]
That's for the same reason as #472 AFAICT

**Comment by tbodt** [comment]
I think this is pretty much done now.

**Comment by Rexogamer** [comment]
Do you get the bounty?

**Comment by tbodt** [comment]
I think so

**Comment by saagarjha** [comment]
what are you going to do with your newfound wealth

**Comment by mattapperson** [comment]
@tbodt if so, I missed there was a bounty. Happy to contribute to the windfall from this

**Comment by tbodt** [comment]
@mattapperson You may do so at https://www.bountysource.com/issues/66159647-node-npm-needs-sse

**Comment by mattapperson** [comment]
Yea it's closed now, won't let me add to the bounty. Before you claim the next one let me know? ill just back that one
