### ISSUE TITLE
Hey team! I actually love the simplicity of the original icon, but I’m of the 1337 crowd, so I just did a quick color swap.

### ISSUE THREAD

**Issue by loloco22** [ish-app/ish#900]
Hey team! I actually love the simplicity of the original icon, but I’m of the 1337 crowd, so I just did a quick color swap.

1337_icon.png
![IMG_0267](https://user-images.githubusercontent.com/69870988/90557011-af1f8a80-e14e-11ea-8415-c46accd9b11d.png)

_Originally posted by @AudioBr4in in https://github.com/ish-app/ish/issues/578#issuecomment-675671406_

**Comment by Mnpn03** [comment]
You don't have to create several new issues quoting comments, if you like an icon submission you can react with a thumbs up.
