### ISSUE TITLE
Just Found something interesting, that aligns with App Interface. (24KB w/ ImageOptim)

### ISSUE THREAD

**Issue by loloco22** [ish-app/ish#901]
Just Found something interesting, that aligns with App Interface. (24KB w/ ImageOptim)

![iSH@1024x1024](https://user-images.githubusercontent.com/11737680/71036132-0c100000-20eb-11ea-8a28-04cbc7b75f0f.png)

_Originally posted by @TechUpdateGuy in https://github.com/ish-app/ish/issues/578#issuecomment-566759722_

**Comment by Mnpn03** [comment]
Please stop creating new issues that are just quotes of another thread. Once again, you can react to comments to show your approval. You may be restricted from opening further issues if this continues, and I don't think either one of us wants that!
