### ISSUE TITLE
Random thought

### ISSUE THREAD

**Issue by loloco22** [ish-app/ish#902]
Random thought

![图片](https://user-images.githubusercontent.com/10259119/70389509-14857e00-19fb-11ea-94e3-03323a707771.png)

![图片](https://user-images.githubusercontent.com/10259119/70389548-cb81f980-19fb-11ea-84e7-a5b65754359e.png)

CC-BY

_Originally posted by @01010101lzy in https://github.com/ish-app/ish/issues/578#issuecomment-562944000_

**Comment by Mnpn03** [comment]
Please see the comments I've posted on your other issues.
