### ISSUE TITLE
Build issue undeclared identifier 'UIKey'

### ISSUE THREAD

**Issue by Nanoc-ice** [ish-app/ish#904]
I am trying to build the latest code for iSH with Xcode 11.3.1 Mojave and getting this for Terminal.m:

.../dev/iSH/ish/app/TerminalView.m:518:9: error: use of undeclared identifier 'UIKey'
        UIKey *key = presses.anyObject.key;
        ^
.../dev/iSH/ish/app/TerminalView.m:518:16: error: use of undeclared identifier 'key'
        UIKey *key = presses.anyObject.key;
               ^
.../dev/iSH/ish/app/TerminalView.m:518:40: error: property 'key' not found on object of type 'UIPress *'
        UIKey *key = presses.anyObject.key;
                                       ^
.../dev/iSH/ish/app/TerminalView.m:520:13: error: use of undeclared identifier 'key'
            key.keyCode == UIKeyboardHIDUsageKeyboardSpacebar &&
            ^
.../dev/iSH/ish/app/TerminalView.m:520:28: error: use of undeclared identifier 'UIKeyboardHIDUsageKeyboardSpacebar'
            key.keyCode == UIKeyboardHIDUsageKeyboardSpacebar &&
                           ^
.../dev/iSH/ish/app/TerminalView.m:521:13: error: use of undeclared identifier 'key'
            key.modifierFlags & UIKeyModifierControl) {
            ^
6 errors generated

**Comment by saagarjha** [comment]
Your Xcode is too old, `UIKey` was introduced in iOS 13.4, which Xcode 11.3.1 doesn't have an SDK for.

**Comment by Nanoc-ice** [comment]
OK, thanks.
