### ISSUE TITLE
micro editor doesn't run (golang runtime error)

### ISSUE THREAD

**Issue by dullbananas** [ish-app/ish#909]
I tried installing the micro code editor https://github.com/zyedidia/micro/releases/tag/v2.0.7 but it won't run. I tried 32 bit, 64 bit, and static 64 bit binaries. 32 bit version was able to start up and modify terminal settings but it crashed with a Go runtime error. 64 bit versions show a syntax error in the elf file since 32 bit is the correct one

**Comment by saagarjha** [comment]
What were you trying to do, and what issues did you run into? I was able to start it and do basic things:

<img width="697" alt="Screen Shot 2020-09-17 at 21 19 44" src="https://user-images.githubusercontent.com/13786931/93555669-82b48500-f92b-11ea-8523-f4c766ed4345.png">

**Comment by tbodt** [comment]
Works on my machine

**Comment by dullbananas** [comment]
not working on my ipad

**Comment by tbodt** [comment]
Works on my iPad. Are you on the latest version?

**Comment by 0xknown** [comment]
How do I install it again? 
`apk add micro` Doesn’t seem to work. 
```
ERROR: unsatisfiable constraints:
  micro (missing):
    required by: world[micro]
```
Debian file from micro’s release page doesn’t work either.
```
dpkg-deb: error: 'micro-2.0.8-amd64.deb' is not a Debian format archive
dpkg: error processing archive micro-2.0.8-amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 micro-2.0.8-amd64.deb
```

**Comment by saagarjha** [comment]
You should be able to download and use a linux32 binary from [the releases page](https://github.com/zyedidia/micro/releases).
