### ISSUE TITLE
“World”

### ISSUE THREAD

**Issue by franzbloom** [ish-app/ish#910]
When I try to install something it says world missing "world" why?

**Comment by Mnpn03** [comment]
Are you sure that the name of the program you're installing is correct (or even exists in Alpine's repositories)?

**Comment by franzbloom** [comment]
Where can I find the repo of alpyne?

**Comment by Mnpn03** [comment]
I think you can browse the list and search at https://pkgs.alpinelinux.org/packages?name=&branch=v3.11&arch=x86, otherwise you can use `apk list <package name>` in iSH

**Comment by 62f** [comment]
apk doesn’t take the whole package name including the version number as the parameter for input, only the textual portion. There’s a list of repos on every mirror, ie. http://alpine.42.fr/MIRRORS.txt

**Comment by 62f** [comment]
apk doesn’t accept the whole package name (including the version number or gl*bs) as the input parameter for add/del, just the textual portion functions as an apk argument. There’s a list of repos on every mirror, ie. http://alpine.42.fr/MIRRORS.txt
