### ISSUE TITLE
Command ExternalBuildToolExecution failed with a nonzero exit code (library not found)

### ISSUE THREAD

**Issue by fiddleyowl** [ish-app/ish#913]
I tried building iSH with Xcode 12(12A7209) and macOS Big Sur (20A5374g), but Xcode build failed with error Command ExternalBuildToolExecution failed with a nonzero exit code. The full log indicated that a library was not found.

Sanity check compile stdout:
-----
Sanity check compile stderr:
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)
-----
meson.build:1:0: ERROR: Compiler env -u SDKROOT -u IPHONEOS_DEPLOYMENT_TARGET clang can not compile programs.

I'm using meson 0.53.0. Does anyone have a clue on how to solve this?

**Comment by tbodt** [comment]
Are you using a DTK? I've gotten this error when I try to use it to build for the simulator.
