### ISSUE TITLE
Cannot install oh-my-fish

### ISSUE THREAD

**Issue by jarvisluong** [ish-app/ish#916]
curl -L https://get.oh-my.fish | fish
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0       0     0    0     0    0     0      0     100   194  100   194    0     0    219      0 --:--:-- --:--:-- --:--:--   219
  0     0    0     0    0     0      0     100 19035  100 19035    0     0   9781      0  0:00:01  0:00:01 --:--:-- 43758
Checking for a sane environment...
Failed to execute process '/usr/bin/env'. Reason:
exec: unknown error (errno was 22)
Install aborted: /bin/busybox is not a sane 'head' implementation

When I run dmesg I got this:

dmesg | tail
8 stub syscall 375
51 stub syscall 375

**Comment by tbodt** [comment]
Can't reproduce this error, my environment seems sane. It hangs though

**Comment by jarvisluong** [comment]
Now I can install using latest version. Hence closed
