### ISSUE TITLE
Illegal Instruction in NodeJS

### ISSUE THREAD

**Issue by iamrecursion** [ish-app/ish#917]
It seems that sticking around alpine edge is turning up all sorts of bugs! This one is quite simple to reproduce, but I can provide a rootfs if necessary.

1. Set your repositories to alpine edge.
2. `apk add nodejs`
3. Run `node`.

It will crash with an illegal instruction that boils down to the following:

```
50 illegal instruction at 0x56d4d529: 0f 72 f0 01 8b 00 66 0f
```

<details>
  <summary>Output from `dmesg` for the crash</summary>
  
```plain
[    0.000000] 50 stub syscall 383
               50 stub syscall 383
               50 stub syscall 383
               50 stub syscall 383
               50 stub syscall 383
               50 stub syscall 383
               50 stub syscall 383
               50 stub syscall 383
               50 stub syscall 383
               50 stub syscall 383
               50 stub syscall 383
               50 stub syscall 383
               50 stub syscall 383
               50 stub syscall 383
               50 stub syscall 375
               50 illegal instruction at 0x56d4d529: 0f 72 f0 01 8b 00 66 0f 
               56 stub syscall 383
               56 stub syscall 383
               56 stub syscall 383
               56 stub syscall 383
               56 stub syscall 383
               56 stub syscall 383
```
</details>

**Comment by 62f** [comment]
I expect that using a more bleeding-edge repo than the iSH-provided 3.12 fs will produce more errors, especially if the steps don’t include upgrading after switch of repos. I’ve ‘seen’ no problem <v3.12> running node except for hidden(issue).

**Comment by zerkotin** [comment]
All i get is “illegal instruction” when running either node or npm

**Comment by Askovia** [comment]
In case you haven't fixed it, I manage to fix it in my phone by also installing npm along with nodejs, since they are codependent

**Comment by zerkotin** [comment]
I have both installed on my iPad and it doesn’t work, when calling both npm or node i get Illegal Instruction

**Comment by zerkotin** [comment]
Update:
I updated and upgraded apk like so:
`apk update`
`apk upgrade`
Then removed node and npm
`apk del nodejs`
`apk del npm`
Then reinstalled them
`apk add nodejs`
`apk add npm`
Now it works - seems like the new apk updates adds and installs dependent libraries necessary to run it

**Comment by Askovia** [comment]
Also noticed that the error comes when you aren't running the AppStore Repos

**Comment by specious** [comment]
None of these proposed solutions are helping. Any advice on how to investigate what is causing this crash?

**Comment by specious** [comment]
iSH needs SSE2 instruction support: https://github.com/ish-app/ish/issues/90#issuecomment-458797267

**Comment by specious** [comment]
This is the problem: #1473

**Comment by Ivan0x17** [comment]
"Node and npm" return 
illegal instruction 

Probably the problem is nodejs why npm It depends on nodejs and v8 javascript engine

**Comment by iamrecursion** [comment]
Wait until the next AppStore release.

**Comment by Ivan0x17** [comment]
> Wait until the next AppStore release.

Ok 👍🏻, thank you so much for fast response about my question, good project!! , I hope to use node-red soon

**Comment by Diluka** [comment]
any updates?

**Comment by mfyz** [comment]
+1

**Comment by pro-gamer007** [comment]
+2

**Comment by saagarjha** [comment]
We don't really need votes for this issue, it's already been fixed and will ship in the next release.

**Comment by pro-gamer007** [comment]
When will the next release be?

**Comment by remino** [comment]
When is the next release?

**Comment by rhea-so** [comment]
When is the next release?

**Comment by Lukas-Batema** [comment]
I’m getting the same issue on the most recent edge branch of Alpine, and after updating and upgrading, and installing the pkgs with —-no-cache, it broke it. None of the solutions said to work above, worked on my local device.

**Comment by vkhv** [comment]
+1

**Comment by famiclone** [comment]
Any updates?

**Comment by TheGhostboi64** [comment]
I’m also getting the same problem

**Comment by vkhv** [comment]
Does anyone know how to run node.js on ipad?

**Comment by specious** [comment]
Look at #1482.

**Comment by Fonysony** [comment]
#1482 Actually works, just had to use vim to switch the repo into 1.12 and download node 12.22.12-r0.

**Comment by saagarjha** [comment]
iSH 1.3 is out, which has fixes for this issue. Please try it out and file new issues with what you encounter!

**Comment by dishanaik** [comment]
> iSH 1.3 is out, which has fixes for this issue. Please try it out and file new issues with what you encounter!

Whoa! Finally. Thanks
