### ISSUE TITLE
Clipboard usage from terminal (eg: emulate pbcopy/pbpaste from osx)

### ISSUE THREAD

**Issue by AndrewFarley** [ish-app/ish#920]
**Feature Request**

Fidgeting with trying to find the text to highlight with your finger is annoying, I'm recently making the transition to using my iPad on the road, and am very used to using pbcopy in OS-X to put things into the clipboard.  This would greatly simplify common workflows, such as grabbing a block of text to google for, or grab a URL from the console.  Especially with the "handoff" feature of Apple devices, this makes something like pbcopy/pbpaste very valuable.

A few simple examples...

```bash
# Lets say I just generated a new SSH key I want to go put into my cloud provider
cat ~/.ssh/id_rsa.pub | pbcopy
# Then I can instantly CMD-Tab to switch over to my browser and paste this into their web console
# Or alternatively, if I have my laptop around I could just instantly take that pub key from my iPad and paste it into the authorized hosts on a remote host that I am managing
```

```bash
# Lets say I am working on something that crashes or has some issues in Node or Python, and perhaps throws some crazy error
echo "This is a crazy error: Code 1234"
# Instead of having to try to select it very fiddly with my finger, I can just...
echo "This is a crazy error: Code 1234" | pbcopy
# And then CMD-Tab into safari, CMD-V, and hit return.  Instant gratification.
```

I use these above workflows so regularly, I'd love to have a similar experience on the iPad.  I haven't dived into this code, but I imagine to make something like this work you'd need some hooks to read and write to the pasteboard/clipboard on iOS, and then you'd need some scripts (binary or even some simple shell script) which can read/write.  I imagine if some of the /proc or /dev filesystem is emulated somewhat, could easily be a matter of making an alias for pbcopy to echo the contents into a /dev or /proc device, and pbpaste to cat that same device.

Apologies if this is already possible and I missed it?

Thoughts?

**Comment by saagarjha** [comment]
Perhaps the device file /dev/clipboard might serve your needs?

**Comment by AndrewFarley** [comment]
> Perhaps the device file /dev/clipboard might serve your needs?

OMG yes, yep.  :P  Just tried copy and paste with it, works fantastically.  I'll just make some aliases and be golden.  :P  Glad it already exists, thanks @saagarjha
