### ISSUE TITLE
Unable to get IP address for interface: eth0

### ISSUE THREAD

**Issue by markpanado** [ish-app/ish#927]
When executing `iftop` in iSH, I’m getting the response below:
```
interface: eth0
Error getting hardware address for interface: eth0
ioctl(SIOCGIFHWADDR): Not a tty
Unable to get IP address for interface: eth0
ioctl(SIOCGIFADDR): Not a tty
pcap_open_live(eth0): socket for SIOCETHTOOL(ETHTOOL_GET_TS_INFO): Invalid argument
```

**Comment by nguyenhuyblyat** [comment]
iSH dont have ifconfig, because iOS restrictions

**Comment by ifuchs** [comment]
If you want the external IP address and you don't mind using an external service, you could use something like this:
`import urllib.request

external_ip = urllib.request.urlopen('https://ident.me').read().decode('utf8')

print(external_ip)`￼

**Comment by tbodt** [comment]
`iftop` isn't going to work anytime soon, it's quite hard to capture packets from an iOS app.

**Comment by 62f** [comment]
But we aren’t trying to capture packets FROM an iOS app, we are trying to capture packets IN* an iOS app. Is it going to be impossible for curl to generate pcap files? If so then why is everyone on discord pretending to be so worried about requests @ ie. Wireshark?
