### ISSUE TITLE
Look at how many times this happens & I had no idea

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#928]
pollnval 265 flags 4 events 3 revents 32

**Comment by tbodt** [comment]
What were you doing at the time?

**Comment by 62f** [comment]
Most of iSH’s time is used to compile libraries and various code from git. AtM I’m working on developing curl with quiche/quic(http3) since many of my curl downloads are often being (56) aborted by the remote host. So those dmesg’d failures could have happened either while using my bear/boringssl- modified curl w/git(unmodified)or less likely: from dozens of apks loaded/used for building ie. curl dependencies (c, gcc/c++, python)

**Comment by tbodt** [comment]
Without repro steps, this isn't really actionable

**Comment by 62f** [comment]
That's precisely the problem; I was doing a ton of things during that session, mostly building and linking code, but none of those activities had indicated between start, run, and stop that they might have triggered a dmesg event.
