### ISSUE TITLE
can support 64bit linux?

### ISSUE THREAD

**Issue by astronaut1712** [ish-app/ish#937]

**Comment by Assfugil** [comment]
no

**Comment by astronaut1712** [comment]
do you have any plan to support 64bit?

**Comment by tbodt** [comment]
No plans currently. Why?

**Comment by 62f** [comment]
32-bit i386 isn’t even fully supported yet; https://github.com/ish-app/ish/issues/923#issuecomment-701038583

**Comment by Assfugil** [comment]
i686 is definitely not fully supported, but how about i386-i586?

**Comment by 62f** [comment]
‘i686’ is a generic nomenclature used for all 32-bit instruction sets. Unfortunately unix kernel coders saw no use for distinguishing between SX (coprocessor-less) and DX(+math coprocessored) versions of CPUs, and sometimes configure flags will not recognize cross compile (porting) is being requested when a configure has different —build=ix86 and —target=ix86 switches, so you may also have to specify =i386 and other steps to turn off use of SSE# when building software intended for use in the scientific realm. Any apps, especially those using matrix algebra libs, will still need to be forked and compiled if possible to not use iSH’s unsupported instructions or you will find unexpected items in the dmesg log- or crashes- when those apps execute.

**Comment by 62f** [comment]
PPS: if anyone wished to pursue the matter, Alpine developers may be contacted on their IRC channel or its discord chat mirror and ask them why their 'i386' apk repositories actually contain software packages which are often compiled for >486/DX-class processors requiring SSEx Seems as a bit of false advertisement.

**Comment by vcgato29** [comment]
![Image](https://github.com/user-attachments/assets/8b5e61a5-d51c-4063-8a33-0ad7ff0527cf)
