### ISSUE TITLE
dmesg item(s) deleted from list after iSH upgrade to rel.76

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#939]
I’ve ‘seen’ no problem <v3.12> running node except for hidden(issue).

_Originally posted by @62f in https://github.com/ish-app/ish/issues/917#issuecomment-707447849_

Before upgrade to iSH I had 2 dmesg errors which are no longer logged after upgrade:
[    0.000000] 127 stub syscall 375
               127 stub syscall 383

**Comment by tbodt** [comment]
Not sure why this is a bug

**Comment by 62f** [comment]
It's a bug because it reappeared  during iSH's TestFlight update. I had an instance of iSH running and started an update. Right away I switched back to iSH, long before the iSH update had a chance to finish downloading, then iSH crashed straight to the launcher (Home Screen without putting up the feedback form) before even reopening iSH, I went to analytics and read the sole report on that crash, which named (as having been responsible) the version of iSH which I had not even had a chance to use. Sure, it's a bad analysis, but it took some data along for the ride which it shouldn't have. It's also been acting suspiciously after I had to switch from TF to AppStore versions, the change itself is resetting permissions on files I have installed myself, ergo files which weren't part of the OEM filesystem, which has caused multiple issues that I am choosing to present elsewhere in GitHub one at a time. No clear relation to ed eating whole and parts of opened files despite permission set to read only, but then again- perhaps so.

**Comment by 62f** [comment]
The problem is that nobody expects to have the door shut on their foot while still using the app, which TF does without mercy; I had to turn off automatic updates because the new policy of daily builds randomly inject themselves while ignoring that I've started a multi-day configure session, inconveniently breaking the unmonitored-process, while never leaving any trace in the analytics, and its restart always begins from step # 1: leaving me with only a guess that what closed iSH was the update and not an illegal instruction/segfault/panic.
