### ISSUE TITLE
I have a stupid question, please help me.

### ISSUE THREAD

**Issue by Kiarimo** [ish-app/ish#951]
I very much hope that I can run adb commands on iPadOS, even adblogcat is very good, but I have found a lot of software that can’t be achieved, is this possible?

**Comment by Kiarimo** [comment]
By finding issues that have been closed.
I ran the command
1. apk add android-tools --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
2. apk upgrade all --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
But executing the command adb connect, an error occurs

Error relocating /usr/bin/adb: __gmtime64_r: symbol not found
Error relocating /usr/bin/adb: __stat_time64: symbol not found
Error relocating /usr/bin/adb: __localtime64_r: symbol not found
Error relocating /usr/bin/adb: __lstat_time64: symbol not found
Error relocating /usr/bin/adb: __time64: symbol not found
Error relocating /usr/bin/adb: __pthread_cond_timedwait_time64: symbol not found
Error relocating /usr/bin/adb: __utime64: symbol not found
Error relocating /usr/bin/adb: __fstat_time64: symbol not found
Error relocating /usr/bin/adb: __nanosleep_time64: symbol not found
Error relocating /usr/bin/adb: __select_time64: symbol not found

What should i do next

**Comment by tbodt** [comment]
You will probably need to upgrade everything to edge at once. See https://wiki.alpinelinux.org/wiki/Edge#Upgrading_to_Edge

**Comment by 62f** [comment]
Same solution for mdevd, I expect.
Error relocating /bin/mdevd: __stat_time64: symbol not found
