### ISSUE TITLE
-ash: apk: not found

### ISSUE THREAD

**Issue by travis-mark** [ish-app/ish#956]
Attempting to follow instructions on several pages results in the following error:

    -ash: apk: not found

Pages impacted:

https://github.com/ish-app/ish/wiki/Installing-PHP-with-a-TLS-certificate-and-a-php-filemanager
https://github.com/ish-app/ish/wiki/Installing-R-and-any-package-from-the-CRAN
https://github.com/ish-app/ish/wiki/Running-an-SSH-server
https://github.com/ish-app/ish/wiki/Running-a-VNC-Server
https://github.com/ish-app/ish/wiki/Running-a-Python-Web-Server

Recommend re-adding apk.

**Comment by saagarjha** [comment]
Unfortunately those pages refer to the TestFlight version of iSH. The version of iSH on the App Store has had package management functionality removed. The ability to run Linux programs, as well as import files, has not been changed.

**Comment by jarvisluong** [comment]
Is there a way that we can add apk back ourselves after downloading the app?

**Comment by miwagner1** [comment]
> Is there a way that we can add apk back ourselves after downloading the app?

https://github.com/ish-app/ish/wiki/Installing-apk-on-the-App-Store-Version

**Comment by travis-mark** [comment]
Can this be added an option on initial startup? Should the referenced wiki pages link to this page since the App Store version should quickly become the primary version.

**Comment by saagarjha** [comment]
There are no plans to offer this option in the App Store version at this time. The referenced wiki pages should probably be updated to mention that they depend on the existence of a specific program that is shipped in the TestFlight build but not in the App Store build, and simply state that on the App Store version these steps will not work out-of-the-box.
