### ISSUE TITLE
APK is not found

### ISSUE THREAD

**Issue by phmx** [ish-app/ish#958]
Seems like package manager is not installed with App Store app

```
Maksims-iPad-2:~# apk
-ash: apk: not found
```

**Comment by saagarjha** [comment]
The version of iSH on the App Store has had package management functionality removed. The ability to run Linux programs, as well as import files, has not been changed.

**Comment by GaarMark** [comment]
It happens to me the same

**Comment by phmx** [comment]
Thanks! Sorry, I didn’t search for recently closed issues

**Comment by Jsn2win** [comment]
P

**Comment by kecinzer** [comment]
How can I install SSH client?

**Comment by matti** [comment]
Install apk from the wiki and then ssh
