### ISSUE TITLE
ip address and timezone

### ISSUE THREAD

**Issue by lijhello** [ish-app/ish#960]
Hi,

Is it possible to set ip address and timezone inside iSH, or use the ip address and timezone on iPhone or iPad?

I can compile with GCC 9 on iSH. It is amazing. Thanks!

**Comment by tbodt** [comment]
IP address can't be changed, it's just the IP of your device. Info on how to change the timezone is here (just ignore the warning about them being oudated): https://wiki.alpinelinux.org/wiki/Setting_the_timezone

**Comment by lijhello** [comment]
I followed that link and tried on both iPhone XS and iPad Mini 4, but the timezone didn't change. I'll try it again later.

When will iSH be make public on App Store?

**Comment by ket000** [comment]
Same here. Tried this on ipad 14.1 and it does not work.

**Comment by lijhello** [comment]
On alpinelinux, there's /etc/localtime link to /etc/zoneinfo

# ls -l /etc/localtime 
lrwxrwxrwx    1 root     root            27 Oct 25 05:20 /etc/localtime -> /etc/zoneinfo/Asia/Shanghai
# 
 
On iSH, there's no zoneinfo

# find /usr -name zoneinfo
# find /etc -name zoneinfo
# 

I copied zoneinfo file from alpinelinux to iSH and made link to it. The date output only removed the timezone name "UTC", the time didn't change.

# date
Sun Oct 25 04:37:49 UTC 2020
# ln -s /etc/zoneinfo/Asia/Shanghai /etc/localtime# ls -l /etc/localtime
lrwxrwxrwx    1 root     root            27 Oct 25 04:37 /etc/localtime -> /etc/zoneinfo/Asia/Shanghai
# ls -l /etc/zoneinfo/Asia/Shanghai
-rw-r--r--    1 root     root           393 Oct 25 04:07 /etc/zoneinfo/Asia/Shanghai
# date
Sun Oct 25 04:38:07  2020
#

**Comment by lijhello** [comment]
Still trying.. the shown localtime is 8 hours behind.

```
# apk add alpine-conf tzdata
# date
Thu Oct 29 14:12:11  2020
# setup-timezone
Which timezone are you in? ('?' for list) [UTC] Asia
What sub-timezone of 'Asia' are you in? ('?' for list) Shanghai
# date
Thu Oct 29 14:12:44  2020
# cat /etc/timezone 
Asia/Shanghai
# 
```
