### ISSUE TITLE
apk: not found

### ISSUE THREAD

**Issue by DarkestSky** [ish-app/ish#962]
I've just downloaded the app from App Store, apk seems not working. How should I fix this problem?

**Comment by taeuscherpferd** [comment]
https://github.com/ish-app/ish/wiki/Installing-apk-on-the-App-Store-Version

**Comment by DarkestSky** [comment]
> https://github.com/ish-app/ish/wiki/Installing-apk-on-the-App-Store-Version

Thanks!
