### ISSUE TITLE
Default to non-root login

### ISSUE THREAD

**Issue by lijhello** [ish-app/ish#972]
Can iSH default to non-root login, or require login before use it.

**Comment by kkk669** [comment]
You can do it now.

1. Open Settings app
1. Go to iSH settings
1. Enable "Recovery Mode"
1. Open iSH app
1. Then, rewrite "Launch cmd"

![image](https://user-images.githubusercontent.com/601636/97101014-03aa2d80-16dd-11eb-94cd-d11d6935ed27.jpeg)

**Comment by lijhello** [comment]
@kkk669 thanks. Is your version from the Test Flight. I don't find the settings to enable Recovery Mode on App Store release version

**Comment by kkk669** [comment]
@lijhello I'm using the latest App Store version, but TestFlight one also has. You can find it here.

![F3711C8B-18CD-45FB-9B61-897B16F65C3D](https://user-images.githubusercontent.com/601636/97102090-fa718e80-16e5-11eb-97d3-23014e2b454c.png)

**Comment by lijhello** [comment]
waiting for the picture to show up... the network connection in China is not stable very much.

**Comment by lijhello** [comment]
I did the following but the changes can not be saved. 
1. iPad / iPhone: Settings / iSH / Recovery Mode: *
2. iSH Shell: Launch cmd: /bin/login -f user123

**Comment by kkk669** [comment]
Did iSH crash when you pressed a return key or moved the cursor into another text field? If iSH crashes, you need to try again until it stops crashing. I'm not sure why iSH crashes so often.

**Comment by lijhello** [comment]
Yes, if I select the "Boot cmd" field field first, then select "Launch cmd" field, it exits.
It's not big problem, I can live with default root login for now.
