### ISSUE TITLE
Getting weird error when attempting to use apk.static

### ISSUE THREAD

**Issue by StewAlexander-com** [ish-app/ish#975]
Whenever I try to download something using APK after installing the apk.static package I get this weird error …

```sbin/apk.static: line 1: can't create /1@?@8@??: nonexistent directory```

**Comment by tbodt** [comment]
I suspect you tried to execute a binary built for the wrong architecture. Where did you get it?

**Comment by StewAlexander-com** [comment]
APK? From

http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/apk-tools-static-2.6.10-r0.apk

Using wget

**Comment by saagarjha** [comment]
iSH only supports 32-bit executables at the moment, that's a 64-bit one.

**Comment by StewAlexander-com** [comment]
I see, so I need to get the x86 version, thanks   
  

  

  
  
  
  

  
Best Regards,
  

  Stew Alexander   
  stew@stewalexander.com (mailto:stew@stewalexander.com)
  
M:   (919) 697-8591 (tel:(919)%20697-8591)
  

  
 - Sent via mobile -
  
  
  
  
  

  
  
>

**Comment by StewAlexander-com** [comment]
32bit apk.static works fine
