### ISSUE TITLE
File permissions changed to -x of many preexisting Alpine-3.12.0-fs binaries after switch from TestFlight to AppStore version.

### ISSUE THREAD

**Issue by 62f** [ish-app/ish#977]
(tutorial_env) ~ # whoami
-ash: whoami: Permission denied

(tutorial_env) ~ # ls -la /bin/busybox
-rwxr-xr-x 1 root root 799836 Aug 28 12:11 /bin/busybox

(tutorial_env) ~ # ls -la /usr/bin|grep Jul
-rwxr-xr-x   1 root root       95 Jul 20 23:11 2to3-3.8
-rw-rw-rw-   1 root root       12 Jul 20 00:59 awk
-rwxr-xr-x   1 root root       12 Jul 20 00:59 basename
-rw-rw-rw-   1 root root       12 Jul 20 00:59 bc
-rw-rw-rw-   1 root root       12 Jul 20 00:59 beep
-rw-rw-rw-   1 root root       12 Jul 20 00:59 bunzip2
-rw-rw-rw-   1 root root       12 Jul 20 00:59 bzcat
-rw-rw-rw-   1 root root       12 Jul 20 00:59 cal
-rw-rw-rw-   1 root root       12 Jul 20 00:59 chvt
-rw-rw-rw-   1 root root       12 Jul 20 00:59 cksum
-rw-rw-rw-   1 root root       12 Jul 20 00:59 clear
-rw-rw-rw-   1 root root       12 Jul 20 00:59 cmp
-rw-rw-rw-   1 root root       12 Jul 20 00:59 comm
-rw-rw-rw-   1 root root       11 Jul 20 01:02 crontab
-rw-rw-rw-   1 root root       12 Jul 20 00:59 cut
-rw-rw-rw-   1 root root       12 Jul 20 00:59 dc
-rw-rw-rw-   1 root root       12 Jul 20 00:59 deallocvt
-rw-rw-rw-   1 root root       12 Jul 20 00:59 diff
-rw-rw-rw-   1 root root       12 Jul 20 00:59 du
-rw-rw-rw-   1 root root       12 Jul 20 00:59 eject
-rw-rw-rw-   1 root root       12 Jul 20 00:59 env
-rw-rw-rw-   1 root root       12 Jul 20 00:59 expand
-rw-rw-rw-   1 root root       12 Jul 20 00:59 expr
-rw-rw-rw-   1 root root       12 Jul 20 00:59 factor
-rw-rw-rw-   1 root root       12 Jul 20 00:59 free
-rwxr-xr-x   1 root root    13516 Jul 14  2019 gkbd-keyboard-display
-rw-rw-rw-   1 root root       12 Jul 20 00:59 groups
-rw-rw-rw-   1 root root       12 Jul 20 00:59 hd
-rw-rw-rw-   1 root root       12 Jul 20 00:59 head
-rw-rw-rw-   1 root root       12 Jul 20 00:59 hexdump
-rw-rw-rw-   1 root root       12 Jul 20 00:59 install
-rw-rw-rw-   1 root root       12 Jul 20 00:59 ipcrm
-rw-rw-rw-   1 root root       12 Jul 20 00:59 killall
-rw-rw-rw-   1 root root       12 Jul 20 00:59 less
-rw-rw-rw-   1 root root       12 Jul 20 00:59 logger
-rw-rw-rw-   1 root root       12 Jul 20 00:59 lsof
-rw-rw-rw-   1 root root       12 Jul 20 00:59 lsusb
-rw-rw-rw-   1 root root       12 Jul 20 00:59 md5sum
-rw-rw-rw-   1 root root       12 Jul 20 00:59 mesg
-rw-rw-rw-   1 root root       12 Jul 20 00:59 microcom
-rw-rw-rw-   1 root root       12 Jul 20 00:59 mkfifo
-rw-rw-rw-   1 root root       12 Jul 20 00:59 mkpasswd
-rw-rw-rw-   1 root root       12 Jul 20 00:59 nc
-rw-rw-rw-   1 root root       12 Jul 20 00:59 nproc
-rw-rw-rw-   1 root root       12 Jul 20 00:59 nslookup
-rw-rw-rw-   1 root root       12 Jul 20 00:59 od
-rw-rw-rw-   1 root root       12 Jul 20 00:59 openvt
-rw-rw-rw-   1 root root       12 Jul 20 00:59 pkill
-rw-rw-rw-   1 root root       12 Jul 20 00:59 pmap
-rw-rw-rw-   1 root root       12 Jul 20 00:59 printf
-rw-rw-rw-   1 root root       12 Jul 20 00:59 pwdx
-rwxr-xr-x   1 root root       78 Jul 20 23:11 pydoc3.8
-rwxr-xr-x   1 root root    13432 Jul 20 23:11 python3.8
-rw-rw-rw-   1 root root       12 Jul 20 00:59 readlink
-rw-rw-rw-   1 root root       12 Jul 20 00:59 realpath
-rw-rw-rw-   1 root root       12 Jul 20 00:59 renice
-rw-rw-rw-   1 root root       12 Jul 20 00:59 reset
-rw-rw-rw-   1 root root       12 Jul 20 00:59 seq
-rw-rw-rw-   1 root root       12 Jul 20 00:59 setkeycodes
-rw-rw-rw-   1 root root       12 Jul 20 00:59 setsid
-rw-rw-rw-   1 root root       12 Jul 20 00:59 sha1sum
-rw-rw-rw-   1 root root       12 Jul 20 00:59 sha256sum
-rw-rw-rw-   1 root root       12 Jul 20 00:59 sha3sum
-rw-rw-rw-   1 root root       12 Jul 20 00:59 showkey
-rw-rw-rw-   1 root root       12 Jul 20 00:59 shuf
-rw-rw-rw-   1 root root       12 Jul 20 00:59 smemcap
-rw-rw-rw-   1 root root       12 Jul 20 00:59 sort
-rw-rw-rw-   1 root root       12 Jul 20 00:59 split
-rw-rw-rw-   1 root root       12 Jul 20 00:59 strings
-rw-rw-rw-   1 root root       12 Jul 20 00:59 sum
-rw-rw-rw-   1 root root       12 Jul 20 00:59 tac
-rwxr-xr-x   1 root root       12 Jul 20 00:59 tail
-rw-rw-rw-   1 root root       12 Jul 20 00:59 tee
-rw-rw-rw-   1 root root       12 Jul 20 00:59 test
-rw-rw-rw-   1 root root       12 Jul 20 00:59 time
-rw-rw-rw-   1 root root       12 Jul 20 00:59 timeout
-rw-rw-rw-   1 root root       12 Jul 20 00:59 top
-rw-rw-rw-   1 root root       11 Jul 20 01:02 traceroute6
-rw-rw-rw-   1 root root       12 Jul 20 00:59 truncate
-rw-rw-rw-   1 root root       12 Jul 20 00:59 tty
-rw-rw-rw-   1 root root       12 Jul 20 00:59 ttysize
-rw-rw-rw-   1 root root       12 Jul 20 00:59 uniq
-rw-rw-rw-   1 root root       12 Jul 20 00:59 unlink
-rw-rw-rw-   1 root root       12 Jul 20 00:59 unlzma
-rw-rw-rw-   1 root root       12 Jul 20 00:59 unlzop
-rw-rw-rw-   1 root root       12 Jul 20 00:59 unxz
-rw-rw-rw-   1 root root       12 Jul 20 00:59 unzip
-rw-rw-rw-   1 root root       12 Jul 20 00:59 uudecode
-rw-rw-rw-   1 root root       12 Jul 20 00:59 uuencode
-rw-rw-rw-   1 root root       12 Jul 20 00:59 vi
-rw-rw-rw-   1 root root       12 Jul 20 00:59 wc
-rw-rw-rw-   1 root root       12 Jul 20 00:59 wget.old
-rw-rw-rw-   1 root root       12 Jul 20 00:59 whoami
-rw-rw-rw-   1 root root       12 Jul 20 00:59 whois
-rw-rw-rw-   1 root root       12 Jul 20 00:59 xxd
-rw-rw-rw-   1 root root       12 Jul 20 00:59 xz
-rw-rw-rw-   1 root root       12 Jul 20 00:59 xzcat

**Comment by 62f** [comment]
https://gist.github.com/62f/83dbf1483043c65b039691f5dbc0024b

**Comment by tbodt** [comment]
This crash dump is unrelated, will file a new issue for it

**Comment by 62f** [comment]
iPhone0 user root@Sat 21_ 7:07AM~(/root)-zsh:login Songoku
Welcome to Alpine!

You can install packages with: apk add <package>

You may change this message by editing /etc/motd.

 Alpine systems.
See <http://wiki.alpinelinux.org/>.

You can setup the system with the command: setup-alpine

You may change this message by editing /etc/motd.

Error loading shared library libreadline.so.8: Permission denied (needed by /bin/bash)
Error relocating /bin/bash: unstifle_history: symbol not found
Error relocating /bin/bash: rl_make_bare_keymap: symbol not found
Error relocating /bin/bash: rl_bind_key_if_unbound_in_map: symbol not found
Error relocating /bin/bash: rl_macro_dumper: symbol not found
Error relocating /bin/bash: previous_history: symbol not found
Error relocating /bin/bash: rl_vi_end_word: symbol not found
Error relocating /bin/bash: rl_parse_and_bind: symbol not found
Error relocating /bin/bash: rl_redisplay: symbol not found
Error relocating /bin/bash: rl_push_macro_input: symbol not found
Error relocating /bin/bash: rl_bind_key_in_map: symbol not found
Error relocating /bin/bash: clear_history: symbol not found
Error relocating /bin/bash: add_history: symbol not found
Error relocating /bin/bash: rl_redraw_prompt_last_line: symbol not found
Error relocating /bin/bash: rl_function_of_keyseq_len: symbol not found
Error relocating /bin/bash: history_get: symbol not found
Error relocating /bin/bash: rl_get_keymap: symbol not found
Error relocating /bin/bash: rl_kill_text: symbol not found
Error relocating /bin/bash: remove_history: symbol not found
Error relocating /bin/bash: history_truncate_file: symbol not found
Error relocating /bin/bash: rl_generic_bind: symbol not found
Error relocating /bin/bash: rl_read_key: symbol not found
Error relocating /bin/bash: read_history: symbol not found
Error relocating /bin/bash: rl_add_defun: symbol not found
Error relocating /bin/bash: history_expand: symbol not found
Error relocating /bin/bash: rl_translate_keyseq: symbol not found
Error relocating /bin/bash: rl_get_previous_history: symbol not found
Error relocating /bin/bash: rl_forced_update_display: symbol not found
Error relocating /bin/bash: rl_read_init_file: symbol not found
Error relocating /bin/bash: rl_invoking_keyseqs: symbol not found
Error relocating /bin/bash: append_history: symbol not found
Error relocating /bin/bash: free_history_entry: symbol not found
Error relocating /bin/bash: rl_unbind_key_in_map: symbol not found
Error relocating /bin/bash: readline: symbol not found
Error relocating /bin/bash: rl_variable_value: symbol not found
Error relocating /bin/bash: history_set_pos: symbol not found
Error relocating /bin/bash: rl_unbind_function_in_map: symbol not found
Error relocating /bin/bash: read_history_range: symbol not found
Error relocating /bin/bash: history_is_stifled: symbol not found
Error relocating /bin/bash: stifle_history: symbol not found
Error relocating /bin/bash: replace_history_entry: symbol not found
Error relocating /bin/bash: rl_insert_text: symbol not found
Error relocating /bin/bash: rl_get_keymap_by_name: symbol not found
Error relocating /bin/bash: rl_set_screen_size: symbol not found
Error relocating /bin/bash: rl_vi_bWord: symbol not found
Error relocating /bin/bash: rl_get_termcap: symbol not found
Error relocating /bin/bash: rl_ding: symbol not found
Error relocating /bin/bash: where_history: symbol not found
Error relocating /bin/bash: rl_delete_text: symbol not found
Error relocating /bin/bash: rl_function_of_keyseq: symbol not found
Error relocating /bin/bash: rl_bind_keyseq: symbol not found
Error relocating /bin/bash: rl_reset_terminal: symbol not found
Error relocating /bin/bash: history_tokenize: symbol not found
Error relocating /bin/bash: rl_forward_word: symbol not found
Error relocating /bin/bash: rl_function_dumper: symbol not found
Error relocating /bin/bash: _rl_find_next_mbchar: symbol not found
Error relocating /bin/bash: rl_vi_insertion_mode: symbol not found
Error relocating /bin/bash: rl_variable_bind: symbol not found
Error relocating /bin/bash: rl_named_function: symbol not found
Error relocating /bin/bash: rl_initialize: symbol not found
Error relocating /bin/bash: rl_vi_start_inserting: symbol not found
Error relocating /bin/bash: rl_complete_internal: symbol not found
Error relocating /bin/bash: history_list: symbol not found
Error relocating /bin/bash: tilde_expand: symbol not found
Error relocating /bin/bash: rl_funmap_names: symbol not found
Error relocating /bin/bash: rl_set_keymap: symbol not found
Error relocating /bin/bash: rl_variable_dumper: symbol not found
Error relocating /bin/bash: rl_bind_keyseq_in_map: symbol not found
Error relocating /bin/bash: write_history: symbol not found
Error relocating /bin/bash: rl_on_new_line: symbol not found
Error relocating /bin/bash: rl_clear_visible_line: symbol not found
Error relocating /bin/bash: rl_completion_matches: symbol not found
Error relocating /bin/bash: rl_completion_mode: symbol not found
Error relocating /bin/bash: rl_add_undo: symbol not found
Error relocating /bin/bash: rl_cleanup_after_signal: symbol not found
Error relocating /bin/bash: rl_list_funmap_names: symbol not found
Error relocating /bin/bash: using_history: symbol not found
Error relocating /bin/bash: history_get_time: symbol not found
Error relocating /bin/bash: remove_history_range: symbol not found
Error relocating /bin/bash: rl_crlf: symbol not found
Error relocating /bin/bash: history_length: symbol not found
Error relocating /bin/bash: rl_completion_found_quote: symbol not found
Error relocating /bin/bash: rl_completion_type: symbol not found
Error relocating /bin/bash: rl_point: symbol not found
Error relocating /bin/bash: history_lines_written_to_file: symbol not found
Error relocating /bin/bash: history_max_entries: symbol not found
Error relocating /bin/bash: history_write_timestamps: symbol not found
Error relocating /bin/bash: rl_completion_suppress_quote: symbol not found
Error relocating /bin/bash: rl_basic_word_break_characters: symbol not found
Error relocating /bin/bash: rl_mark: symbol not found
Error relocating /bin/bash: rl_directory_rewrite_hook: symbol not found
Error relocating /bin/bash: rl_end: symbol not found
Error relocating /bin/bash: rl_directory_completion_hook: symbol not found
Error relocating /bin/bash: rl_completer_word_break_characters: symbol not found
Error relocating /bin/bash: rl_dispatching: symbol not found
Error relocating /bin/bash: rl_filename_completion_function: symbol not found
Error relocating /bin/bash: rl_filename_quoting_desired: symbol not found
Error relocating /bin/bash: history_search_delimiter_chars: symbol not found
Error relocating /bin/bash: rl_executing_keyseq: symbol not found
Error relocating /bin/bash: rl_key_sequence_length: symbol not found
Error relocating /bin/bash: rl_filename_dequoting_function: symbol not found
Error relocating /bin/bash: rl_filename_rewrite_hook: symbol not found
Error relocating /bin/bash: rl_filename_stat_hook: symbol not found
Error relocating /bin/bash: rl_tilde_expand: symbol not found
Error relocating /bin/bash: vi_insertion_keymap: symbol not found
Error relocating /bin/bash: rl_newline: symbol not found
Error relocating /bin/bash: rl_vi_editing_mode: symbol not found
Error relocating /bin/bash: rl_prep_term_function: symbol not found
Error relocating /bin/bash: rl_menu_completion_entry_function: symbol not found
Error relocating /bin/bash: rl_attempted_completion_function: symbol not found
Error relocating /bin/bash: history_comment_char: symbol not found
Error relocating /bin/bash: rl_username_completion_function: symbol not found
Error relocating /bin/bash: rl_insert: symbol not found
Error relocating /bin/bash: rl_filename_completion_desired: symbol not found
Error relocating /bin/bash: rl_done: symbol not found
Error relocating /bin/bash: rl_tab_insert: symbol not found
Error relocating /bin/bash: rl_completion_append_character: symbol not found
Error relocating /bin/bash: rl_sort_completion_matches: symbol not found
Error relocating /bin/bash: history_lines_read_from_file: symbol not found
Error relocating /bin/bash: emacs_ctlx_keymap: symbol not found
Error relocating /bin/bash: rl_deprep_term_function: symbol not found
Error relocating /bin/bash: rl_editing_mode: symbol not found
Error relocating /bin/bash: tilde_additional_prefixes: symbol not found
Error relocating /bin/bash: rl_menu_complete: symbol not found
Error relocating /bin/bash: history_subst_char: symbol not found
Error relocating /bin/bash: rl_readline_state: symbol not found
Error relocating /bin/bash: rl_attempted_completion_over: symbol not found
Error relocating /bin/bash: vi_movement_keymap: symbol not found
Error relocating /bin/bash: rl_filename_quote_characters: symbol not found
Error relocating /bin/bash: rl_filename_quoting_function: symbol not found
Error relocating /bin/bash: history_quotes_inhibit_expansion: symbol not found
Error relocating /bin/bash: rl_readline_name: symbol not found
Error relocating /bin/bash: rl_line_buffer: symbol not found
Error relocating /bin/bash: emacs_meta_keymap: symbol not found
Error relocating /bin/bash: rl_char_is_quoted_p: symbol not found
Error relocating /bin/bash: rl_completion_entry_function: symbol not found
Error relocating /bin/bash: rl_last_func: symbol not found
Error relocating /bin/bash: rl_ignore_some_completions_function: symbol not found
Error relocating /bin/bash: rl_completion_invoking_key: symbol not found
Error relocating /bin/bash: rl_instream: symbol not found
Error relocating /bin/bash: tilde_expansion_preexpansion_hook: symbol not found
Error relocating /bin/bash: rl_yank_last_arg: symbol not found
Error relocating /bin/bash: tilde_additional_suffixes: symbol not found
Error relocating /bin/bash: rl_completion_suppress_append: symbol not found
Error relocating /bin/bash: history_inhibit_expansion_function: symbol not found
Error relocating /bin/bash: rl_completer_quote_characters: symbol not found
Error relocating /bin/bash: rl_completion_quote_character: symbol not found
Error relocating /bin/bash: rl_complete: symbol not found
Error relocating /bin/bash: history_base: symbol not found
Error relocating /bin/bash: rl_terminal_name: symbol not found
Error relocating /bin/bash: history_expansion_char: symbol not found
Error relocating /bin/bash: rl_outstream: symbol not found
Error relocating /bin/bash: emacs_standard_keymap: symbol not found
Error relocating /bin/bash: rl_startup_hook: symbol not found
Error relocating /bin/bash: history_quoting_state: symbol not found
Error relocating /bin/bash: rl_signal_event_hook: symbol not found
Error relocating /bin/bash: rl_special_prefixes: symbol not found
Error relocating /bin/bash: rl_explicit_arg: symbol not found
Error relocating /bin/bash: rl_num_chars_to_read: symbol not found
Error relocating /bin/bash: rl_completion_mark_symlink_dirs: symbol not found
iPhone0 user root@Sat 21_ 7:11AM~(/root)-zsh:why am I still root?

**Comment by padroid** [comment]
62f ya sonna bitch

**Comment by 62f** [comment]
Since ```sudo``` can be used to execute all binaries in a fake-fs even despite -x, which besides the ios-fs interface is the only type being used by iSH,...
