### ISSUE TITLE
Commands doesn’t work after I reinstalled ISH

### ISSUE THREAD

**Issue by IvanTheBrains** [ish-app/ish#987]
# Issue after reinstalling the app
After I downloaded an app from AppStore I tried to _apk update_. However nothing works! Basic commands like "cd" or "ls" does not work. When I try to apk something I get an error
`-ash: apk: not found`
Does it mean, that I deleted the Alpine Sowtware?

**Comment by ntindle** [comment]
apk is not allowed when distributed in the app store. Check the wiki for more details.

**Comment by IvanTheBrains** [comment]
@ntindle I have fixed that. Also thx for the reply.

**Comment by IvanTheBrains** [comment]
I have fixed that by downloading **Alpine Linux** on my iPhone. Then I went to settings of ISH

> Settings > Filesystems > name of the downloaded linux system > Click on it and then tap Boot from this Filesystem
