### ISSUE TITLE
Fd command error, illegal instruction 

### ISSUE THREAD

**Issue by the0demiurge** [ish-app/ish#990]
![BE69F41E-E1C0-4E17-B9AD-8F5E05D317C2](https://user-images.githubusercontent.com/11363529/97260395-d5049200-1857-11eb-897d-a44274954686.png)
![A146A541-E6C1-4872-8001-F8AF00C5DD26](https://user-images.githubusercontent.com/11363529/97260399-da61dc80-1857-11eb-97e8-a005c6232995.png)

**Comment by saagarjha** [comment]
This looks like `paddd`, which means it's the same as #923?

**Comment by the0demiurge** [comment]
What is paddd?

**Comment by saagarjha** [comment]
It's an x86 MMX instruction: https://www.felixcloutier.com/x86/paddb:paddw:paddd:paddq

**Comment by the0demiurge** [comment]
I see, thank you:)
This instruction seems the same with that mentioned issue

**Comment by tbodt** [comment]
Will dupe to #805, seems to affect a number of rust programs
