### ISSUE TITLE
inittab: gettys are not needed

### ISSUE THREAD

**Issue by docwhat** [ish-app/ish#996]
The `getty` lines in `/etc/inittab` can be commented out; they aren't being used to provide consoles.

I tested it just to be sure. :smiley:

**Comment by tbodt** [comment]
No real reason to change this

**Comment by docwhat** [comment]
Removing unneeded processes that clutter up `ps`?

Fair enough.  At least anyone searching will see this and see that they are harmless (they use very little memory and no CPU) and that you can remove them by commenting them out of `/etc/inittab` and doing a `kill -HUP 1`.
